### ISSUE TITLE
JIT ARM64-SVE: Assertion failed '(varDsc->lvIsParam && !varDsc->lvIsRegArg) || isPrespilledArg' when running SVE unit tests

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#100101]
When running SVE unit tests, `theEmitter->emitIns_R_S(INS_sve_ldr_mask, EA_8BYTE, REG_P0, 1, 0);` fails with the above assert. This seems to have been introduced by #99608.

cc @dotnet/arm64-contrib @a74nh @kunalspathak.

**Comment by JulieLeeMSFT** [comment]
@a74nh PTAL.

**Comment by a74nh** [comment]
This assert doesn't fire for me. But it's clearly due to there being no stack variables in the current method. @amanasifkhalid and myself are testing by attaching to different C# methods, so that explains the differences.

#100132 removes the tests. We might want to think about properly testing `emitIns_R_S/emitIns_S_R` in a new PR, including general purpose load/stores. But that's a task for a later date.

**Comment by kunalspathak** [comment]
Fixed by https://github.com/dotnet/runtime/pull/100132

**Comment by amanasifkhalid** [comment]
I'm still seeing this assert hit for the SVE unit tests that call `emitIns_R_S/S_R`. Here's how I'm using SPMI to repro this:
```
C:\runtime\artifacts\bin\coreclr\windows.x64.Checked\superpmi.exe C:\runtime\artifacts\bin\coreclr\windows.x64.Checked\clrjit_universal_arm64_x64.dll C:\runtime\artifacts\spmi\mch\3c216494-65f8-49e2-b69a-7f272193bcc6.windows.arm64\benchmarks.run.windows.arm64.checked.mch -c 1 -jitoption JitEmitUnitTests="*" -jitoption JitEmitUnitTestsSections="sve"
```

**Comment by kunalspathak** [comment]
@a74nh - can you take a look?

**Comment by a74nh** [comment]
>I'm still seeing this assert hit for the SVE unit tests that call emitIns_R_S/S_R. Here's how I'm using SPMI to repro this:

That's because I missed some. I'll remove all of them....

**Comment by kunalspathak** [comment]
This is fixed in https://github.com/dotnet/runtime/pull/100153
