### ISSUE TITLE
Failing test due to no detected IO events in 'System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents'

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#103584]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=709665
Build error leg or test failing: System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink
Pull request: https://github.com/dotnet/runtime/pull/103528

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Deleted event did not occur as expected",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=709665
**Error message validated:** `[Deleted event did not occur as expected`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/17/2024 3:57:06 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[1308498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1308498)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1308498&view=ms.vss-test-web.build-test-results-tab&runId=36551942&resultId=144016)|dotnet/runtime#121906|
|[1308424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1308424)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1308424&view=ms.vss-test-web.build-test-results-tab&runId=36550730&resultId=120225)|dotnet/runtime#124760|
|[1305436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1305436)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1305436&view=ms.vss-test-web.build-test-results-tab&runId=36461528&resultId=120485)|dotnet/runtime#124641|
|[1301782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1301782)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1301782&view=ms.vss-test-web.build-test-results-tab&runId=36355392&resultId=116826)|dotnet/runtime#123614|
|[1298856](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1298856)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1298856&view=ms.vss-test-web.build-test-results-tab&runId=36281214&resultId=116874)|dotnet/runtime#124347|
|[1297576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1297576)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_InNestedDirectory](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1297576&view=ms.vss-test-web.build-test-results-tab&runId=36240666&resultId=118103)|dotnet/runtime#124202|
|[1297009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1297009)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1297009&view=ms.vss-test-web.build-test-results-tab&runId=36228574&resultId=135184)||
|[1293826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1293826)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1293826&view=ms.vss-test-web.build-test-results-tab&runId=36128798&resultId=129322)|dotnet/runtime#124393|
|[1293405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1293405)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1293405&view=ms.vss-test-web.build-test-results-tab&runId=36117878&resultId=129730)|dotnet/runtime#124380|
|[1291897](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1291897)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1291897&view=ms.vss-test-web.build-test-results-tab&runId=36071612&resultId=121760)|dotnet/runtime#124309|
|[1291332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1291332)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1291332&view=ms.vss-test-web.build-test-results-tab&runId=36059130&resultId=113452)|dotnet/runtime#123819|
|[1290749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1290749)|dotnet/runtime|[System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_DataModification](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1290749&view=ms.vss-test-web.build-test-results-tab&runId=36038228&resultId=124716)|dotnet/runtime#124296|
|[1283654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1283654)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1283654&view=ms.vss-test-web.build-test-results-tab&runId=35841474&resultId=118227)|dotnet/runtime#124065|
|[1283352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1283352)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1283352&view=ms.vss-test-web.build-test-results-tab&runId=35835272&resultId=121619)|dotnet/runtime#123958|
|[1281397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1281397)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_InNestedDirectory](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1281397&view=ms.vss-test-web.build-test-results-tab&runId=35777860&resultId=121955)|dotnet/runtime#123138|
|[1278967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1278967)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1278967&view=ms.vss-test-web.build-test-results-tab&runId=35706482&resultId=119861)|dotnet/runtime#123160|
|[1276222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1276222)|dotnet/runtime|[System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1276222&view=ms.vss-test-web.build-test-results-tab&runId=35626284&resultId=120269)|dotnet/runtime#123818|
|[1272941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1272941)|dotnet/runtime|[System.IO.Tests.File_Delete_Tests.FileSystemWatcher_File_Delete_ForcedRestart](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1272941&view=ms.vss-test-web.build-test-results-tab&runId=35515634&resultId=120704)|dotnet/runtime#123508|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|4|18|

**Comment by Jozkee** [comment]
This is just FileSystemWatcher being flaky in Windows as always... We may try to add more retries and see if that makes it less noisy.

**Comment by jakobbotsch** [comment]
@Jozkee Can you disable the test until the flakiness is resolved? This is marked blocking-clean-ci so I don't think putting it in a 10.0 milestone is appropriate.

**Comment by Jozkee** [comment]
What makes an issue be tagged as blocking-clean-ci? i.e. how many times does it have to fail for it to not be blocking-clean-ci-optional?

**Comment by jakobbotsch** [comment]
blocking-clean-ci = it is failing in the default pipelines that run on all PRs. blocking-clean-ci-optional = it is failing in non-default pipelines (like libraries-jitstress).

In both cases the failures are disruptive to a lot of people and should be made non-blocking asap, either by resolving the underlying problems, disabling the tests (with expected future investigation), or removing the tests.

> I'm hesitant on disabling the tests because they are multiple methods, I would have to disable the whole class which seems risky.

If these tests are flaky isn't that flakiness just going to mask any real failures, making the test not very useful?

**Comment by danmoseley** [comment]
In the past I've fixed other FSW tests by adding more retries (or firing more events). Retries are easy to add and they should be outer loop if not already.

**Comment by jakobbotsch** [comment]
We have a ton of open issues about this problem: #103549, #103584, #103630, #103940, #104269, #104564, #104930
It seems to have super high impact. @Jozkee can you please look into resolving this issue with high priority?

**Comment by jakobbotsch** [comment]
Still seeing failures, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=747310&view=ms.vss-test-web.build-test-results-tab&runId=18893294&resultId=119514&paneView=debug, console log https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3c8d50d456884ef49b/System.IO.FileSystem.Watcher.Tests/1/console.7ac301db.log?helixlogtype=result.

```
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_LastWriteTime(filter: LastWrite) [FAIL]
      Changed event did not occur as expected
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(317,0): at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(198,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(168,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.Directory.NotifyFilter.cs(136,0): at System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_LastWriteTime(NotifyFilters filter)
           at InvokeStub_Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_LastWriteTime(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
RetryHelper: retrying FileSystemWatcher_Directory_Changed_LastWrite 1th time of 3: got Changed event did not occur as expected
```

**Comment by Jozkee** [comment]
Yes, I disabled the ones reported, it was expected that more would come up.

**Comment by jeffhandley** [comment]
@Jozkee Are there any other tests in this realm that are still active and causing noise, or do you think they're all disabled now? It looks like the hit count has dropped off since you merged in #105254 but I wanted to confirm with you.

If you think we're now clean for the 9.0.0 branch, we can move this to Future and clear the assignee.

**Comment by Jozkee** [comment]
> Are there any other tests in this realm that are still active and causing noise

Not that I'm aware of.

> we can move this to Future and clear the assignee.

https://github.com/dotnet/runtime/pull/105254 left us with a huge test gap for FileSystemWatcher in Windows. We should find ways to re-enable the tests a reduce their noise. Future is not a good idea, 10.0.0 perhaps.
