### ISSUE TITLE
[6.0/8.0] Failure in BackwardsCompatibility_DowngradeToHttp11: no exception thrown

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104390]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=719981
Build error leg or test failing: `System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11`

## Error Message

```json
{
  "ErrorMessage" : ["System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11 [FAIL]", "No exception was thrown"],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/103895
- Queue: `Libraries Test Run release coreclr windows x86 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=719981&view=logs&j=f967148e-4c68-5d25-c313-1c7f2944d30b
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-103895-merge-0c6ec0294a6340daa4/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.da84d930.log?helixlogtype=result
- Output:
```
    System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11 [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Exception)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/BidirectionStreamingTest.cs(335,0): at System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11()
        --- End of stack trace from previous location ---
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[742366](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742366)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742366&view=ms.vss-test-web.build-test-results-tab&runId=18747048&resultId=194446)||
|[742370](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370&view=ms.vss-test-web.build-test-results-tab&runId=18746974&resultId=174022)||
|[742256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742256)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742256&view=ms.vss-test-web.build-test-results-tab&runId=18742990&resultId=154092)|dotnet/runtime#104934|
|[742221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742221)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742221&view=ms.vss-test-web.build-test-results-tab&runId=18742012&resultId=170485)||
|[742118](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742118)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742118&view=ms.vss-test-web.build-test-results-tab&runId=18740100&resultId=209370)|dotnet/runtime#104929|
|[742096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742096)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742096&view=ms.vss-test-web.build-test-results-tab&runId=18739098&resultId=179687)|dotnet/runtime#103597|
|[742110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110&view=ms.vss-test-web.build-test-results-tab&runId=18738516&resultId=177224)||
|[741767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767&view=ms.vss-test-web.build-test-results-tab&runId=18737504&resultId=169030)||
|[742042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742042)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742042&view=ms.vss-test-web.build-test-results-tab&runId=18737424&resultId=211740)|dotnet/runtime#104395|
|[742030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742030)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742030&view=ms.vss-test-web.build-test-results-tab&runId=18736722&resultId=146728)|dotnet/runtime#104925|
|[742005](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742005)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742005&view=ms.vss-test-web.build-test-results-tab&runId=18735980&resultId=149453)||
|[741960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741960)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741960&view=ms.vss-test-web.build-test-results-tab&runId=18734290&resultId=177337)||
|[741764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741764)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741764&view=ms.vss-test-web.build-test-results-tab&runId=18732928&resultId=179766)||
|[741834](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741834)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741834&view=ms.vss-test-web.build-test-results-tab&runId=18730782&resultId=186756)|dotnet/runtime#103267|
|[741712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741712)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741712&view=ms.vss-test-web.build-test-results-tab&runId=18730680&resultId=181077)|dotnet/runtime#104828|
|[741844](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741844)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741844&view=ms.vss-test-web.build-test-results-tab&runId=18730446&resultId=150050)||
|[741284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741284)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741284&view=ms.vss-test-web.build-test-results-tab&runId=18728914&resultId=179344)|dotnet/runtime#104893|
|[741723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741723)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741723&view=ms.vss-test-web.build-test-results-tab&runId=18727664&resultId=213213)|dotnet/runtime#104541|
|[741113](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741113)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741113&view=ms.vss-test-web.build-test-results-tab&runId=18710726&resultId=153271)|dotnet/runtime#104838|
|[741074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741074)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741074&view=ms.vss-test-web.build-test-results-tab&runId=18708336&resultId=158920)|dotnet/runtime#104892|
|[739967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967&view=ms.vss-test-web.build-test-results-tab&runId=18675458&resultId=163097)||
|[740021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740021)|dotnet/runtime|[System.Net.Http.WinHttpHandler.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740021&view=ms.vss-test-web.build-test-results-tab&runId=18669924&resultId=200830)|dotnet/runtime#104852|
|[739577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577&view=ms.vss-test-web.build-test-results-tab&runId=18667262&resultId=195750)||
|[739937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937&view=ms.vss-test-web.build-test-results-tab&runId=18666914&resultId=182857)||
|[739539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539&view=ms.vss-test-web.build-test-results-tab&runId=18666648&resultId=158430)||
|[739884](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739884)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739884&view=ms.vss-test-web.build-test-results-tab&runId=18664996&resultId=178915)||
|[739868](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739868)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739868&view=ms.vss-test-web.build-test-results-tab&runId=18664670&resultId=188213)||
|[739582](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739582)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739582&view=ms.vss-test-web.build-test-results-tab&runId=18664450&resultId=193010)|dotnet/runtime#104828|
|[739573](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739573)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739573&view=ms.vss-test-web.build-test-results-tab&runId=18664432&resultId=184965)||
|[739585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739585)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739585&view=ms.vss-test-web.build-test-results-tab&runId=18664404&resultId=158040)|dotnet/runtime#104829|
|[739782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739782)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739782&view=ms.vss-test-web.build-test-results-tab&runId=18664126&resultId=147625)||
|[739723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739723)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739723&view=ms.vss-test-web.build-test-results-tab&runId=18663486&resultId=140301)||
|[739547](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739547)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739547&view=ms.vss-test-web.build-test-results-tab&runId=18661086&resultId=180865)|dotnet/runtime#104578|
|[739536](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739536)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739536&view=ms.vss-test-web.build-test-results-tab&runId=18659076&resultId=177698)||
|[739523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739523)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739523&view=ms.vss-test-web.build-test-results-tab&runId=18658840&resultId=178872)|dotnet/runtime#104395|
|[739519](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739519)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739519&view=ms.vss-test-web.build-test-results-tab&runId=18658530&resultId=182156)|dotnet/runtime#103267|
|[739510](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739510)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739510&view=ms.vss-test-web.build-test-results-tab&runId=18656926&resultId=143364)|dotnet/runtime#104565|
|[739497](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739497)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739497&view=ms.vss-test-web.build-test-results-tab&runId=18655616&resultId=143140)||
|[733225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733225)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733225&view=ms.vss-test-web.build-test-results-tab&runId=18655208&resultId=179018)|dotnet/runtime#104501|
|[739485](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739485)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739485&view=ms.vss-test-web.build-test-results-tab&runId=18653160&resultId=145065)||
|[738807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738807)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738807&view=ms.vss-test-web.build-test-results-tab&runId=18636988&resultId=145049)||
|[738612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738612)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=738612&view=ms.vss-test-web.build-test-results-tab&runId=18631820&resultId=182434)|dotnet/runtime#104722|
|[737515](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737515&view=ms.vss-test-web.build-test-results-tab&runId=18623266&resultId=159309)||
|[737708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737708)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737708&view=ms.vss-test-web.build-test-results-tab&runId=18615320&resultId=184548)|dotnet/runtime#104744|
|[737840](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737840)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737840&view=ms.vss-test-web.build-test-results-tab&runId=18613700&resultId=150286)|dotnet/runtime#104748|
|[737818](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737818)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737818&view=ms.vss-test-web.build-test-results-tab&runId=18613374&resultId=152166)|dotnet/runtime#104747|
|[737692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737692)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737692&view=ms.vss-test-web.build-test-results-tab&runId=18607970&resultId=177065)|dotnet/runtime#104743|
|[737512](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737512)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737512&view=ms.vss-test-web.build-test-results-tab&runId=18599716&resultId=167149)||
|[737237](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737237)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737237&view=ms.vss-test-web.build-test-results-tab&runId=18589806&resultId=186453)|dotnet/runtime#104722|
|[737130](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737130)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737130&view=ms.vss-test-web.build-test-results-tab&runId=18584300&resultId=207873)|dotnet/runtime#104711|
|[737071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737071)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=737071&view=ms.vss-test-web.build-test-results-tab&runId=18581868&resultId=161065)|dotnet/runtime#104714|
|[736260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736260)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736260&view=ms.vss-test-web.build-test-results-tab&runId=18558518&resultId=176995)||
|[736264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736264)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736264&view=ms.vss-test-web.build-test-results-tab&runId=18558302&resultId=207603)||
|[735197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735197)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735197&view=ms.vss-test-web.build-test-results-tab&runId=18528318&resultId=151694)||
|[735380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735380)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735380&view=ms.vss-test-web.build-test-results-tab&runId=18527494&resultId=152984)||
|[735194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735194)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735194&view=ms.vss-test-web.build-test-results-tab&runId=18519482&resultId=207875)||
|[735190](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735190)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=735190&view=ms.vss-test-web.build-test-results-tab&runId=18519108&resultId=161389)||
|[734944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734944)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734944&view=ms.vss-test-web.build-test-results-tab&runId=18510864&resultId=184951)||
|[2491473](https://dev.azure.com/dnceng/internal/_build/results?buildId=2491473)|dotnet-runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng//internal/_build/results?buildId=2491473&view=ms.vss-test-web.build-test-results-tab&runId=53850689&resultId=164943)|[#40928](https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/pullrequest/40928)|
|[734947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734947)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734947&view=ms.vss-test-web.build-test-results-tab&runId=18510180&resultId=168470)||
|[734813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734813)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734813&view=ms.vss-test-web.build-test-results-tab&runId=18507322&resultId=180007)|dotnet/runtime#104630|
|[734820](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734820)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734820&view=ms.vss-test-web.build-test-results-tab&runId=18507300&resultId=147924)|dotnet/runtime#104631|
|[734733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734733)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734733&view=ms.vss-test-web.build-test-results-tab&runId=18505170&resultId=178537)|dotnet/runtime#104623|
|[734748](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734748)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734748&view=ms.vss-test-web.build-test-results-tab&runId=18504994&resultId=153713)|dotnet/runtime#104624|
|[731587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731587)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731587&view=ms.vss-test-web.build-test-results-tab&runId=18475598&resultId=213212)|dotnet/runtime#103984|
|[733773](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733773)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733773&view=ms.vss-test-web.build-test-results-tab&runId=18473812&resultId=168521)|dotnet/runtime#104578|
|[2490544](https://dev.azure.com/dnceng/internal/_build/results?buildId=2490544)|dotnet-runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng//internal/_build/results?buildId=2490544&view=ms.vss-test-web.build-test-results-tab&runId=53843213&resultId=167126)|[#40928](https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/pullrequest/40928)|
|[732707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732707)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732707&view=ms.vss-test-web.build-test-results-tab&runId=18444070&resultId=163170)|dotnet/runtime#104541|
|[732070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732070)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732070&view=ms.vss-test-web.build-test-results-tab&runId=18422156&resultId=175468)|dotnet/runtime#103393|
|[731708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731708)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731708&view=ms.vss-test-web.build-test-results-tab&runId=18419750&resultId=164137)|dotnet/runtime#104499|
|[731755](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731755)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=731755&view=ms.vss-test-web.build-test-results-tab&runId=18409898&resultId=211855)|dotnet/runtime#104501|
|[730977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730977)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730977&view=ms.vss-test-web.build-test-results-tab&runId=18389874&resultId=195106)||
|[730974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730974)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730974&view=ms.vss-test-web.build-test-results-tab&runId=18388210&resultId=179610)||
|[730040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730040)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=730040&view=ms.vss-test-web.build-test-results-tab&runId=18360434&resultId=186057)|dotnet/runtime#103984|
|[729973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729973)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729973&view=ms.vss-test-web.build-test-results-tab&runId=18357916&resultId=154120)|dotnet/runtime#103366|
|[729920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729920)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729920&view=ms.vss-test-web.build-test-results-tab&runId=18356628&resultId=207870)||
|[729950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729950)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729950&view=ms.vss-test-web.build-test-results-tab&runId=18356586&resultId=169027)||
|[729825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729825)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729825&view=ms.vss-test-web.build-test-results-tab&runId=18354200&resultId=156573)||
|[729703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729703)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729703&view=ms.vss-test-web.build-test-results-tab&runId=18352276&resultId=179018)|dotnet/runtime#103267|
|[729693](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729693)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729693&view=ms.vss-test-web.build-test-results-tab&runId=18351734&resultId=180448)|dotnet/runtime#104378|
|[729707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729707)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729707&view=ms.vss-test-web.build-test-results-tab&runId=18351410&resultId=183695)||
|[729710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729710)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729710&view=ms.vss-test-web.build-test-results-tab&runId=18351278&resultId=182292)||
|[729670](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729670)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729670&view=ms.vss-test-web.build-test-results-tab&runId=18350526&resultId=148283)|dotnet/runtime#104330|
|[729645](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729645)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729645&view=ms.vss-test-web.build-test-results-tab&runId=18348556&resultId=154229)||
|[729486](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729486)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729486&view=ms.vss-test-web.build-test-results-tab&runId=18344528&resultId=176488)|dotnet/runtime#104377|
|[729080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729080)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=729080&view=ms.vss-test-web.build-test-results-tab&runId=18330622&resultId=164777)|dotnet/runtime#104353|
|[719981](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719981)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719981&view=ms.vss-test-web.build-test-results-tab&runId=18049544&resultId=153046)|dotnet/runtime#103895|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|20|64|87|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=719981
**Error message validated:** `[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11 [FAIL] No exception was thrown`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/3/2024 6:10:28 PM UTC

**Comment by liveans** [comment]
Same issue as #103754

**Comment by carlossanlop** [comment]
@dotnet/ncl this is a very impactful change in servicing branches. Any chance you can take a look at this soon?

**Comment by liveans** [comment]
> @dotnet/ncl this is a very impactful change in servicing branches. Any chance you can take a look at this soon?

I'm working on it, will get it merged soon.

**Comment by carlossanlop** [comment]
Thanks. Is it a product issue? Just a reminder that the code complete date is today at 4pm PT.

**Comment by liveans** [comment]
> Thanks. Is it a product issue? Just a reminder that the code complete date is today at 4pm PT.

Specifically for this test no.

**Comment by liveans** [comment]
Fixed 8.0 in #104837, 6.0 in #104838.

**Comment by carlossanlop** [comment]
@liveans this is still happening in the 8.0 branch:

https://github.com/dotnet/runtime/pull/105055/checks?check_run_id=27596364317

Reopening.

**Comment by carlossanlop** [comment]
Hmm or maybe not. I think the CI finished shortly before you merged your PR. Let me monitor the branch a couple more work days to confirm.

**Comment by liveans** [comment]
> @liveans this is still happening in the 8.0 branch:
> 
> https://github.com/dotnet/runtime/pull/105055/checks?check_run_id=27596364317
> 
> Reopening.

We fixed `release/8.0-staging`, should we also port this to `release/8.0` ?

**Comment by carlossanlop** [comment]
Ah no, nevermind, you're right. I think it was fixed in the staging branch after the code complete day. I'll close this.
