### ISSUE TITLE
Calling a CsWinRT NAOT dll's DllCanUnloadNow export triggers CFG failure

### ISSUE THREAD

**Issue by jevansaks** [dotnet/runtime#105330]
### Description

Using ControlFlowGuard when creating a native dll that uses CsWinRT (which generates the DllGetActivationFactory and DllCanUnloadNow native exports) and publishing that as AOT creates a dll with DllCanUnloadNow not in the icall table. This causes an external caller of DllCanUnloadNow (in my case, combase.dll since this is part of implementing the WinRT contract) to failfast with FAST_FAIL_GUARD_ICALL_CHECK_FAILURE.

### Reproduction Steps

Minimal repro project with repro steps in readme: 

https://github.com/jevansaks/NAOTControlFlowGuardRepro/tree/main

### Expected behavior

All exports of the dll should be in the CFG table since they're designed to be called virtually.

### Actual behavior

DllGetActivationFactory export is in the CFG table but DllCanUnloadNow is not.

### Regression?

I don't know. Probably not a regression.

### Configuration

.NET 8, running on Windows 11, compiling for windows-x64 native. I didn't try any other windows native targets.

**Comment by jevansaks** [comment]
FYI @MichalStrehovsky

**Comment by jkoritzinsky** [comment]
@MichalStrehovsky fixed by https://github.com/dotnet/runtime/pull/106132?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky fixed by #106132?

No, that one only affects OptimizationPreference=Size and there's no observable failure mode. We still don't know what this one is. I'm going to spend time on this in the coming weeks.

**Comment by jkotas** [comment]
> For some reason that I want not able to figure out, 2 does not happen for native AOT object files.

You can ask linker dev to figure this out for you. This may be a symptom of some other problem that we may want to fix.

**Comment by MichalStrehovsky** [comment]
> > For some reason that I want not able to figure out, 2 does not happen for native AOT object files.
> 
> You can ask linker dev to figure this out for you. This may be a symptom of some other problem that we may want to fix.

I've sent them an email with a repro... will see.
