### ISSUE TITLE
[Tracing] EventProvider Disposal hangs within a callback

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#106087]
### Description

https://github.com/dotnet/runtime/issues/80666 uncovered an issue where [EventPipeEventProvider's callback had been invoked after the gchandle was freed](https://github.com/dotnet/runtime/issues/80666#issuecomment-2249343314). To align EventPipe with [ETW which blocks disposal for in-flight callbacks](https://github.com/dotnet/runtime/issues/80666#issuecomment-2253506595), https://github.com/dotnet/runtime/pull/106040 added a signal wait/set blocking behavior to `ep_delete_provider`. As a result, a deadlock can occur should users invoke EventPipeEventProvider's Unregister or `ep_delete_provider` within a callback.

### Reproduction Steps

```C#
using System.Diagnostics.Tracing;

MyEventSource eventSource = new MyEventSource();
Console.WriteLine("MyEventSource is ready to be enabled");
Console.ReadLine();

[EventSource(Name ="MyEventSource")]
class MyEventSource : EventSource
{
    override protected void OnEventCommand(EventCommandEventArgs command)
    {
        Console.WriteLine($"Command: {command.Command}");
        this.Dispose();
        Console.WriteLine($"Dispose() complete");
    }
}
```

`dotnet-trace collect --providers MyEventSource -p <pid of running sample>`

### Expected behavior

Sample's output
```
MyEventSource is ready to be enabled
Command: Enable
Dispose() complete
```

### Actual behavior

Sample's output
```
MyEventSource is ready to be enabled
Command: Enable
```

**Comment by lateralusX** [comment]
@mdh1418 is this fixed with latest changes in EventPipe around session lifetime management?

**Comment by mdh1418** [comment]
No, it still reproduces as the deadlock path is specifically `EventPipeEventProvider.Unregister` -> `EventPipeInternal.DeleteProvider` -> `ep_delete_provider` waiting on callbacks_pending during the callback. Working on a fix now
