### ISSUE TITLE
Memory is not released when using TransactionScope with async option

### ISSUE THREAD

**Issue by neymecc** [dotnet/runtime#108447]
### Sample code
```c#
while (true)
{
    using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
        scope.Complete();
    }
}
```
![snapshot1](https://github.com/user-attachments/assets/8559be45-e717-4f5a-9ca0-246e6f0e26f3)

Memory usage grows, and response times increase until the web api halts. Removing the async option resolves the issue, but async is required in my case. 😞

### Workaround

I created a factory (singleton) around it to manually trigger GC, something like this simplified:
```c#
public class TransactionScopeFactory
{
    private const int GcThreshold = 200_000;
    private static int _createdScopes = 0;

    public TransactionScope CreateScope()
    {
        int currentCreatedScopes = Interlocked.Increment(ref _createdScopes);

        if (currentCreatedScopes >= GcThreshold)
        {
            if (Interlocked.CompareExchange(ref _createdScopes, 0, GcThreshold) >= GcThreshold)
            {
                GC.Collect(2);
            }
        }

        return new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
    }
}
```

### Questions
- Is the workaround okay? I'm a bit hesitant about manual GC, as the docs advises against it without a clear purpose and the TransactionScope docs doesn't mention anything about manually invoking GC.
- Why does the workaround only work in release mode? It doesn't seem to work in debug mode.

Used versions: .NET 8, 9

Thank you 😄

**Comment by roji** [comment]
@neymecc if `GC.Collect()` makes the memory go down again, that means that there's no memory problem with TransactionScope - simply that the GC hasn't kicked in yet to reclaim unneeded memory. In .NET (like other GC languages), memory isn't released immediately, but at arbitrary points, when the GC actually kicks in, based on a variety of considerations. For example, if memory on your machine becomes low, it's very likely that the GC will kick in at that point. You can try to keep doing the above in a loop, and eventually memory usage will go down (a real leak would produce an OutOfMemoryException).

I suggest reading the [GC docs](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals) for more information; if you think you're application is using too much memory, you may want to tweak the GC settings (take a look at workstation vs. server mode for instance).

**Comment by neymecc** [comment]
I might have worded this badly sorry about that, but the app is in fact gets killed by the OS with OOM. I created a sample repo for this that can reproduce this issue every time:

https://github.com/neymecc/runtime-issue-108447
 
I used these commands to setup a docker container with only 2GB of ram & no swap and start the app.

You might have to install libicu (apt-get update &c apt-get install -y libicu-dev)

- docker run -d --memory="2g" --memory-swap="2g" --name="runtime-issue-108447" -p 32999:5000 ubuntu:latest tail -f /dev/null
- dotnet publish -r linux-x64 --self-contained -c Release -o .build
- docker cp "<project-location>\runtime-issue-108447\src\RuntimeIssue108447\.build" runtime-issue-108447:/opt/.build
- docker exec -it runtime-issue-108447 bash
- cd /opt
- chmod +x .build
- cd /opt/.build
- ./RuntimeIssue108447 --urls "http://0.0.0.0:5000"

Do a benchmark with http benchmarking app like bombardier 
- .\bombardier -c 125 -n 10000000 http://localhost:32999/weatherforecast

See the memory charts in these test, the memory is only increasing, latency is degrading, in my system the app gets killed about in a minute.

If you have remove the async option it is going to be stable.

I know the test could be better, but without the workaround i have to restart the app like every week.

**Comment by neymecc** [comment]
@roji, I edited you into the comment above, I’m not sure if it sends a notification after the edit, but just in case, thank you! 😄

**Comment by roji** [comment]
So just so I understand, is the `GC.Collect` workaround that you ask about in your original list in fact a workaround, i.e. does it actually prevent the OOM?

**Comment by neymecc** [comment]
Yes, it does prevent the OOM. In the test above, using that workaround keeps the memory usage ~200 MB.

**Comment by roji** [comment]
This does not repro for me. I'm running a simple console program with the following code:

```c#
while (true)
{
    using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
        scope.Complete();
    }
}
```

Memory usage is extremely stable at with the expected ups-and-downs as the GC reclaims memory:

<img width="568" alt="image" src="https://github.com/user-attachments/assets/190d4a1e-752f-433b-ac35-da38b8520509">

In general, I highly recommend isolating your repro, providing as minimal a repro as possible (e.g. a console program rather than an ASP.NET application - the web components shouldn't be relevant here in any way).

>> So just so I understand, is the GC.Collect workaround that you ask about in your original list in fact a workaround, i.e. does it actually prevent the OOM?
>
> Yes, it does prevent the OOM. 

Note that if there's an actual memory leak where memory cannot be reclaimed by the GC, and an OutOfMemoryException is triggered, that means that GC.Collect() shouldn't help the situation in any way. Either the memory can be reclaimed - in which case it should get reclaimed regardless of GC.Collect() - or it can't be reclaimed because it's still being referenced - in which case GC.Collect() wouldn't do anything to help.

**Comment by neymecc** [comment]
I'm very confused right now, are you testing the code on Mac? 

I'm on Windows and also tested the code in Linux.

I created the web api sample because it allocates memory faster than console although I don't know why. So the kill is minutes not hours.

I created a sample again with ```dotnet new console``` and just pasted that above while loop code

Start:
![image](https://github.com/user-attachments/assets/573689c0-d965-4a39-ac4d-8062b2c57ddc)

Few minutes later:
![image](https://github.com/user-attachments/assets/34081aba-6448-4d80-a5ac-e59d9fe65ea2)

Again few minutes later:
![image](https://github.com/user-attachments/assets/21aeeac4-4307-4b7e-bd3c-105a87b0a581)

More time given:
![image](https://github.com/user-attachments/assets/fb7d337c-117f-48c4-9684-c75260705e2e)

**Comment by KeterSCP** [comment]
@roji I can reproduce the issue locally with your minimal repro code:

![image](https://github.com/user-attachments/assets/dbc78a80-a969-40cc-aae3-e2d3d6b5f27a)

My configuration is:

OS: Windows 11
Arch: AMD x64
.NET version: .NET 9 RC2
Run configuration: Release

Comparing two snapshots shows that most of the memory consumption comes from the ConditionalWeakTable:
![image](https://github.com/user-attachments/assets/5001ab28-6df5-428f-9ce7-b470e734d6d5)

**Comment by roji** [comment]
So again, it's OK for the memory to be increasing - the question is whether you get an OOM. You can make memory go faster by spinning up multiple threads that do this loop in parallel.

**Comment by andrewjsaid** [comment]
If i run the supposedly broken loop in a podman container with 1.5GB memory it reaches and 1.4GB and does not crash. If I lower it to 512MB it reaches ~450MB and remains stable at that level too.

Looks to me like the `ConditionalWeakTable` is just doing its job.

**Comment by neymecc** [comment]
> If i run the supposedly broken loop in a podman container with 1.5GB memory it reaches and 1.4GB and does not crash. If I lower it to 512MB it reaches ~450MB and remains stable at that level too.
> 
> Looks to me like the `ConditionalWeakTable` is just doing its job.

@andrewjsaid Do you have swap enabled or disabled? If enabled, can you please disable it and run the loop again? Thank you :)

**Comment by neymecc** [comment]
First of all, thank you guys for taking time to help me, sorry for the uncertainness it's hard for me to explain this issue, even on my primary language. This is my first real "brawl" with the GC but I'm learning so much. 😃

## Console test

I have been running the console test for about ~11 hours now, it's fine, although it will consume nearly all the RAM up as @andrewjsaid hinted in his comment. Doing snapshot reveals that it's all ```ConditionalWeakTable```, like 16gb of all usage its ~14gb of that. If it is fine @roji as you said, I trust you. 😄

**The issue is only reproducible inside in a web app.** The sample repo that I linked is a "real usage scenario for us" where the task loop is simulating the clients (faster than real to avoid waiting a week or more) using transactions and the weatherforecast endpoint is for to check the overall latency.

Please run the [sample repo](https://github.com/neymecc/runtime-issue-108447) in a vm/container and **disable swap**, Two possible outcomes:
- OS will kill it in seconds or minutes. 
- If somehow lives then in the end, more and more time will be spent doing GC, weatherforecast will even go timeout in some asks.

## Solution & story time

@roji asked to try to get an OOM exception. I tried to get one in debug mode on Windows. I thought there is no way that I can fill all the RAM to get OOM exception in reasonable issue reply timeframe so I searched a way to limit memory that the app can use to speed up getting an OOM exception **if it is even possible**, that's when I found ```DOTNET_GCHeapHardLimit``` and ```DOTNET_GCHeapHardLimitPercent``` env variables. **When set one of them, it remains stable within the set limit, no OOM exception.**

**The env variables even fixes the sample repo, no more OS OOM kill.** Although using the other ```GC.Collect``` solution results faster RPS and less overall RAM usage, there will be no leftover GB++ ```ConditionalWeakTable``` + GC time will be less. It is also better in our project.

## Question

I have one more question, the [docs](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit) says ```The default value, which only applies in certain cases, is the greater of 20 MB or 75% of the memory limit on the container.``` The web app is like the certain case? I mean running the sample repo without any of the solutions, the 75% will be quickly passed before OS OOM kill.

**Comment by markples** [comment]
Yes, having the answer to "what exact error/exception are you seeing" would be very helpful here.

My guess is that this is the Linux OOM killer.  If the overall machine is at/near the limit, it will choose a process and kill it in order to get some space.  It might be this process, but it also could be another.

The default 75% limit works for many deployments but may need to be modified.  It allows for some other space to be used by the OS and others.  Depending on the size of the machine and what else is running, it can be possible to run with a higher limit, but also it is quite possible that less than 75% is needed.  As the .NET process approaches the specified limit (OR if the overall machine is approaching its limit), the GC will get more aggressive.  In some cases, it will reclaim lots of memory more quickly.  In other cases, there isn't anything to collect, so it just keeps trying and reclaiming small amounts.  But the OOM killer can externally step in and kill the process.  It is hard to give definitive advice because we don't know all of the specifics of your setup, but it sounds like lowering the 75% limit might be appropriate here.

Separately, in the workaround in the original description on this item, there is a race condition in the count.  If `_createdScopes` is incremented twice by different threads before the `CompareExchange` happens, then its value can end up larger then `GcThreshold`.  This will cause the return value to be `GcThreshold + k` but the zero _not_ stored.  Every iteration will then cause a gen2 collection, so the work will slow to a near halt.

**Comment by neymecc** [comment]
Oops, sorry, forgot to include in my last comment that issue can be closed. I can't provide any additional useful information and essentially the question/issue is solved. 

@markples Strange when I set the default limit 75% explicitly in our environment its behaving correctly, probably something is messed up in our side. I thought the interlocked increment & exchange along with two step >= check solves that race. I may have to revisit that again. Thanks for the heads up. 😄

**Comment by markples** [comment]
> I thought the interlocked increment & exchange along with two step >= check solves that race.

The `>=` makes sure that you still get `true` as a result since the return value from the compare-exchange might be larger, but it doesn't impact the operation of the compare-exchange itself, which is "update if the old value equals GcThreshold", not "update if the old value is greater than GcThreshold".  Just use a lock around the increment and compare-exchange (and then they don't need to be interlocked) as a simpler solution.

**Comment by markples** [comment]
Please see #50683 for more information about this.  To answer a few things brought up in this issue:
- There is a grey area with the word "leak" here.  This benchmark (specifically the `ConditionalWeakTable` internally used by it) creates a finalizable object graph that is problematic for garbage collection - basically all of the objects require gen2 in order to make progress even though they seem like they should be short-lived.  When the program approaches the memory limit, the frequent gen2s limit further growth.  However, the app shouldn't be using anywhere near that much memory, so while it's not the traditional kind of "leak" it's still a problem.
- The GC threshold discussion is a workaround for that underlying problem.  Assuming that my guess about the Linux OOM killer is correct, the GC threshold is simply making the GC more aggressive earlier so that the gen2s kick in before the OOM killer gets involved.  I'm not sure why the default doesn't work for you, though maybe the GC somehow isn't getting the memory limit in order to use it to find the 75% value (i.e., setting the limit directly rather than as a percentage means you can determine that limit rather than depending on the GC to find it).

**Comment by neymecc** [comment]
@markples Thank you for the deeper dive 😄. Based on your comments, I tried to run the sample repo handful of times with DOTNET_GCHeapHardLimit set to "0x20000000" [512 MB]. This may explain why I can sometimes trigger an OOM exception with this limit set — like 1 in 10 attempts.


![Image](https://github.com/user-attachments/assets/6693b621-6410-4e1f-9278-cf8430d24d15)

![Image](https://github.com/user-attachments/assets/7f1d22d1-f593-4072-abc3-de5f600fdc4e)


```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.ExecutionContext.SetLocalValue(IAsyncLocal local, Object newValue, Boolean needChangeNotifications)
   at System.Transactions.CallContextCurrentData.CreateOrGetCurrentData(ContextKey contextKey)
   at System.Transactions.TransactionScope.PushScope()
   at System.Transactions.TransactionScope..ctor(TransactionScopeOption scopeOption, TransactionScopeAsyncFlowOption asyncFlowOption)
   at Program.<>c.<<Main>$>b__0_1() in C:\Users\******\Desktop\runtime-issue-108447\src\RuntimeIssue108447\Program.cs:line 42
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
