### ISSUE TITLE
ManagedError: EndOfStringNotFound when starting Blazor in BlazorWebAssembly application with AoT

### ISSUE THREAD

**Issue by Kizuto3** [dotnet/runtime#111151]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I encountered an issue with Blazor wasm where non-primitive (class and struct) arguments passed through JSInterop are failing to be parsed with EndOfStringNotFound exception for both cases where arguments are passed from dotnet to JS and from JS to dotnet. However, this issue appears to be environment dependent, as it's only reproduceable on our machines in France and only with AoT compilation enabled. Without AoT compilation no issue is present.   

### Expected Behavior

Arguments should be passed successfully between JS and dotnet.

### Steps To Reproduce

Example project: https://github.com/Kizuto3/Blazor-JavaScript-Interop

Steps:
1. Make sure wasm tools are installed via running "dotnet workload install wasm-tools-net8".
2. Publish the project to a desired folder. 
3. Host the project via IIS Manager. Here's my settings example: 
![Image](https://github.com/user-attachments/assets/7b62a925-3a9a-4e7d-a4b5-6f4e18671ab9)

4. Open the hosted website in the browser and observe console via F12. I believe this issue depends on the environment, so it might work as expected on your machine. If everything is fine you should see a console log like "guid - string" appear in the console when mouse cursor leaves the website. If not, you should see an exception similar to the one in the Exceptions section below. 

### Exceptions (if any)

When passing arguments from dotnet to JS:
![Image](https://github.com/user-attachments/assets/2a792a65-2e38-409a-a739-60c7679eaa27)
I believe there is some code in Blazor.Start() JS method that invokes JSInterop and passes arguments from dotnet to JS.

When passing arguments from JS to dotnet:
![Image](https://github.com/user-attachments/assets/0f4d029d-55cd-4c13-a3dd-78f7515848ce)
In this case there are 2 arguments: Guid and string, that are being passed from JS to dotnet.

### .NET Version

8.0.11

### Anything else?

Environment: 
![Image](https://github.com/user-attachments/assets/71c749af-c122-477f-a114-9059cb794909)

ASP.NET Core shared framework version 8.0.11
Microsoft .NET Windows Server Hosting version 8.0.11

Publishing the project without AoT seem to fix the issue, so the root of this issue might be related to AoT compilation.
Please let me know if you need any more information.

**Comment by javiercn** [comment]
Note, the delta here is AoT vs non-AoT

**Comment by pavelsavara** [comment]
I believe this is the exception we are getting.

https://github.com/dotnet/runtime/blob/e9a91f90b84e79a2d21f480778e5d4850579b594/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs#L1315

The message is localized and I wonder if the problem is missing French resources.

Something like `fr-FR\System.Private.CoreLib.resources.dll`

The other question is why the JSON text is invalid. Does it contain non-UTF8 character ?

**Comment by pavelsavara** [comment]
> Should I push these changes to the example project?

Yes please, thanks!

**Comment by Kizuto3** [comment]
@pavelsavara I updated the example project

**Comment by pavelsavara** [comment]
There is mix of versions 8 and 9 with 
```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.13" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
```

in the project file. That's probably unrelated, but it is not supported and may have undefined consequences.

@Kizuto3 please update the project to same version and test if this still reproduces.

Also please add
```xml
<WasmNativeStrip>false</WasmNativeStrip>
<WasmNativeDebugSymbols>true</WasmNativeDebugSymbols>
```

and provide the stack trace again, with more details.

Also you mentioned that it happens only on machine in France. Does the A) build need to be in France or the B) browser or the web C) server in order to reproduce ?

**Comment by Kizuto3** [comment]
Hi @pavelsavara 

I downgraded the DevServer nuget package to 8.0.13, but the issue persists.
Here's more detailed stack trace:

[localhost-1739883507247.log](https://github.com/user-attachments/files/18845519/localhost-1739883507247.log)

Regarding your question, there are a few scenarios where this issue is reproduceable. Our real project is hosted via Azure, and Blazor loads and works as expected on most machines except those physically located in France. I tried creating VMs with French locale on my machine (that is physically located in Ukraine), but I wasn't able to reproduce the issue. 
With the example project, I publish it into a folder on my local machine and transfer the files to the machine in France. I then host it locally via IIS Manager on both my machine and the one in France. On my machine everything works fine, but the French one fails.
So it seems the browser needs to be in France to reproduce the issue.

**Comment by pavelsavara** [comment]
Is that single machine or multiple machines in France ? (something about it could be corrupted, maybe browser, maybe hardware)

**Comment by Kizuto3** [comment]
There are multiple machines in France with this issue.

**Comment by pavelsavara** [comment]
I can't reproduce yet. I set my browser to french only, but no luck.

![Image](https://github.com/user-attachments/assets/a73fbad8-dc4a-4784-bc87-b2a387492041)

![Image](https://github.com/user-attachments/assets/277cfda6-1246-41ae-9448-e9713fc62e84)

> I then host it locally via IIS Manager on both my machine and the one in France. 

Please clean browser caches to make sure that you are really testing your repro app.

**Comment by pavelsavara** [comment]
I can reproduce, when I manually corrupt the serialized string

![Image](https://github.com/user-attachments/assets/4aeada69-e9c9-4b22-a726-7086f2de0f72)

**Comment by pavelsavara** [comment]
It seems this screenshot is not from the same app that you gave me as repro.

In the repro app, this event never hits the `endInvokeJSFromDotNet` and also has different payload.

**Comment by Kizuto3** [comment]
@pavelsavara It is the same app. I believe endInvokeJSFromDotNet is called from Blazor.Start() JS method. In the example project Blazor wouldn't start on French machines, so the exceptions are from Blazor.Start() method, I believe.

**Comment by pavelsavara** [comment]
I'm confused about the scenario. I thought we are only trying to reproduce the fail in mouse event processing.

Anyway, so talking about blazor startup. I can see this
- 3 async calls to JS, `Blazor._internal.attachWebRendererInterop`, `Blazor._internal.domWrapper.focusBySelector` and `Blazor._internal.PageTitle.getAndRemoveExistingTitle`
- first two are void and the last one is serializing the response.

![Image](https://github.com/user-attachments/assets/b3145a1b-b3bf-46f8-add1-de0c22fac5cc)

![Image](https://github.com/user-attachments/assets/2e68e49f-0d42-4b6e-8212-27a9fbce28a8)

**Is there some wide UTF character in the title ? Maybe high surrogate ?**

Then the JSON is encoded as UTF16

![Image](https://github.com/user-attachments/assets/3095f3a1-50d5-4646-8ed5-907314d1b669)

![Image](https://github.com/user-attachments/assets/e1b49019-05b4-41ca-93a8-ee48e98b6fc9)

![Image](https://github.com/user-attachments/assets/509bdbdc-d673-4860-ae09-f78f59e83edc)

**Comment by pavelsavara** [comment]
I just tested multi-codepoint character, `AA≩︀BB` which is 6x16 bits and it works fine. 

![Image](https://github.com/user-attachments/assets/69f7104d-2f43-4d0f-b49c-4f09bfc6a9fe)

**Comment by pavelsavara** [comment]
@Kizuto3 does the repository also reproduce the issue Net9 ?

```xml
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
  </ItemGroup>
```

Maybe there is some AOT bug we fixed already.

**Comment by Kizuto3** [comment]
Hi @pavelsavara, It seems like the issue is NOT reproduceable with .NET 9. I updated target framework to .NET 9 and both WebAssembly packages to 9.0.2 and blazor started successfully and mouse event is working as expected

**Comment by Kizuto3** [comment]
If I remember correctly, at some point in the past I tried upgrading .NET to 9 and it didn't solve the issue. However, I didn't upgrade WebAssembly packages, so that might have been the reason.

**Comment by pavelsavara** [comment]
Speculation: On Net8, this could be caused by https://github.com/dotnet/runtime/pull/106313 which was not backported yet
