### ISSUE TITLE
`DateTime` with `CultureInfo("en-US")` has inconsistent string logic

### ISSUE THREAD

**Issue by Marvin-Brouwer** [dotnet/runtime#113478]
### Description

In [this issue](https://github.com/dotnet/runtime/issues/95620) it's stated that the new US dates need a no-break space (`\u202F`) instead of a normal space for `DateTime.ParseExact` with the global (`g`) pattern.

This is fine, however it breaks when you compare the output to itself.
When running the following code, the date strings are not equal:

```csharp
using System;
using System.Globalization;

const string input = "4/20/2096 4:20\u202FAM";
const string format = "g";
var culture = new CultureInfo("en-US");

var parseExact  = DateTime.ParseExact(input, format, culture, DateTimeStyles.AssumeUniversal);
var stringExact = parseExact.ToString(format, culture);

Console.Write(input.Equals(stringExact)); // output: False
```

### Reproduction Steps

Compare a serialized DateTime string to an original with the no-break space as shown:

```csharp
using System;
using System.Globalization;

const string input = "4/20/2096 4:20\u202FAM";
const string format = "g";
var culture = new CultureInfo("en-US");

var parseExact  = DateTime.ParseExact(input, format, culture, DateTimeStyles.AssumeUniversal);
var stringExact = parseExact.ToString(format, culture);

Console.Write(input.Equals(stringExact)); // output: False
```

### Expected behavior

Either the output of `DateTime.ToString(format, provider)` should match `DateTime.ParseExact`.
Or DateTime.ParseExact should offer a way to be more lenient towards whitespace.

### Actual behavior

The date string produced by `DateTime.ToString` is not equal to what `DateTime.ParseExact` expects.

### Regression?

I'm not sure when this broke exactly because my repo has been stale for a while.
But, this change broke existing Unit-Tests.
See: https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/13838822332 

### Known Workarounds

Not Applicable

### Configuration

- Dotnet Version: `Net 9.0`
- OS: Version `ubuntu-latest`
- OS Architecture: `unknown`
- Yes, on my local machine (`Windows 11 Enterprise; 64-bit operating system, x64-based processor`) it works
- No Blazor. 

See: https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/13838822332

**Comment by tarekgh** [comment]
I tried this on `Ubuntu 25.04` and I couldn't reproduce too:

```
Input:       0034, 002f, 0032, 0030, 002f, 0032, 0030, 0039, 0036, 0020, 0034, 003a, 0032, 0030, 202f, 0041, 004d
stringExact: 0034, 002f, 0032, 0030, 002f, 0032, 0030, 0039, 0036, 0020, 0034, 003a, 0032, 0030, 202f, 0041, 004d
ShortDatePattern 'M/d/yyyy': 004d, 002f, 0064, 002f, 0079, 0079, 0079, 0079
LongTimePattern 'h:mm:ss tt': 0068, 003a, 006d, 006d, 003a, 0073, 0073, 202f, 0074, 0074

True
```

I see this can reproduce on Windows machine with the exact same code. This is because you are doing `var culture = new CultureInfo("en-US");`. Creating a culture like this on Windows will pick the user override settings from the user settings. This will make the long time pattern to use normal space `\u0020` instead of `\u202f`. You can fix this by either creating the culture with `var culture = new CultureInfo("en-US", useUserOverride: false);` or use `var culture = new CultureInfo.GetCultureInfo("en-US");`. This should make your code work as expected. 

You may follow up with @Clockwork-Muse as he has good recommendations how to do globalization stuff too.

**Comment by Marvin-Brouwer** [comment]
I can reproduce it still, even with the `new CultureInfo("en-US", useUserOverride: false);`
See this `sharplab.io` code: https://sharplab.io/#gist:e4761f08ab7a1ad4c831e8148c025449.
I did put the same code in `dotnetfiddle` where I got the expected result.
I'm not convinced this is behaving consistently still.
If it helps, my local machine is on a Dutch locale in GMT+1, I don't think it should matter when creating cultures instead of assigning or using them, but, I figured I'd mention it.
(So is my browser, maybe `sharplab.io` uses that?).

@tarekgh I don't suppose `DateTimeStyles` really matter in this instance, the dates are correct.
Also, I'm merely assigning values for testing, so I can assume universal because I assign them. I don't want any adjustments made.

@Clockwork-Muse One of the examples I showed you is indeed running in CI, and, if you have advice to offer it's more than welcome.
However, I'm also running these tests locally and they fail similarly (but also not exactly) on my local PC.
I've Updated the reproduction code to show the strings in console.
When I run the same code in `dotnetfiddle` it works as expected:
https://dotnetfiddle.net/IfB6YV
```text
"4/20/2096 4:20\u202FAM"
"4/20/2096 4:20\u202FAM"
True
```
However when I run it on `sharplab.io` I get:
https://sharplab.io/#gist:2d81fe7dcde4e3496e23b85d26593bd6
```text
"4/20/2096 4:20\u202FAM"
"4/20/2096 4:20 AM"
False
```

I'm not sure what version of C# `sharplab.io` is on so I also tried `Net8.0` in `dotnetfiddle`.

@Clockwork-Muse could you please reopen this issue, I'm not convinced this is working as intended.

**Comment by Marvin-Brouwer** [comment]
I have tried to fix this in my tests using a hack, since the results between the CI pipeline and my local machine differ.
When I add the following line:
```csharp
// https://github.com/dotnet/runtime/issues/95620
if (!Environment.OSVersion.Platform.Equals(OSPlatform.Windows)) expectedValue = expectedValue.Replace(" ", " ");
```

Two tests fail with the following message:
https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/13852528603#summary-38762302818
```text
FluentSerializer.Json.Tests: Tests.Converting.Converters.DateTimeByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""\u00224/20/2096 4:20 AM\u0022"", but found ""\u00224/20/2096 4:20\u202FAM\u0022"".

FluentSerializer.Xml.Tests: Tests.Converting.Converters.DateTimeByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""4/20/2096 4:20 AM"", but found ""4/20/2096 4:20\u202FAM"".
```

However, when I remove line, other tests fail:
https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/13852458253#summary-38762096858
```text
FluentSerializer.Json.Tests: Tests.Converting.Converters.DateTimeOffsetByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""\u00224/20/2096 4:20\u202FAM \u002B00:00\u0022"", but found ""\u00224/20/2096 4:20 AM \u002B00:00\u0022"".

FluentSerializer.Json.Tests: Tests.Converting.Converters.TimeOnlyByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""\u00224:20\u202FAM\u0022"", but found ""\u00224:20 AM\u0022"".

FluentSerializer.Xml.Tests: Tests.Converting.Converters.DateTimeOffsetByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""4/20/2096 4:20\u202FAM \u002B00:00"", but found ""4/20/2096 4:20 AM \u002B00:00"".

FluentSerializer.Xml.Tests: Tests.Converting.Converters.TimeOnlyByFormatConverterTests.SerializePattern_ReturnsString
Expected result to be ""4:20\u202FAM"", but found ""4:20 AM"".
```

I think it's important to note here, that with the fix, `DateTime` seems to behave incorrectly.
And without the fix `DateTimeOffset` and `TimeOnly` behave unexpected.
[The only thing I changed](https://github.com/Marvin-Brouwer/FluentSerializer/commit/7deba8cfacd30e990bf059f751d2a47997d5f8c1#diff-52f8892ef9889a3ff1120814ebd830040af7b06523d4bd2a9b7cf68a5cd20dc7) was whether the string replacement was applied on the expected result before running the test.

**Comment by tarekgh** [comment]
@Marvin-Brouwer nothing wrong in DateTime. The problem is when you run on older version of the OS you end up using older ICU library which not carrying the updated time format. I have updated the code in the sharp lab to print the values.

```
Microsoft Windows 10.0.17763
.NET 9.0.0
.... C:\Windows\SYSTEM32\icuuc.dll: 61, 1, 0, 0
.... C:\Windows\SYSTEM32\icuin.dll: 61, 1, 0, 0
```

As you see this is using ICY version 61 which not having the updating time format that replace the space with `\u202f`. So, .NET is behaving correctly according to that. Here is the dump of the long time format which is showing the space as `0x20`

```
h:mm:ss tt ... 0068, 003a, 006d, 006d, 003a, 0073, 0073, 0020, 0074, 0074
```

If you need to write reliable code, either you check the long time format or you write a string compare method that allow `0x20` equals to `0x202f`. In general, I am seeing the test is wrong too because you are assuming this format will never change which it is possible to change at any time. If you want to guarantee the result, you'll need to either use the Invariant culture or to use date/time format that is culture independent like `o` format. Let me know if you still have any question or is there anything unclear yet.

**Comment by Marvin-Brouwer** [comment]
@tarekgh When you say:
> @Marvin-Brouwer nothing wrong in DateTime. The problem is when you run on older version of the OS you end up using older ICU library which not carrying the updated time format. I have updated the code in the sharp lab to print the values.

The older version of the OS part makes sense to me.  
However, it still doesn't make sense to me why the behavior of `DateTime` and `DateTimeOffset` would be different here.
Even if by design, that seems rather inconsistent to me.

About the pattern.
> If you want to guarantee the result, you'll need to either use the Invariant culture or use date/time format that is culture independent like `o` format. Let me know if you still have any question or is there anything unclear yet.

The reason I have `g` is because I consulted the MSDN docs on this.
https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#GeneralDateShortTime

According to the MSDN definition: 
> The "g" standard format specifier represents a combination of the short date ("d") and short time ("t") patterns, separated by a space.

My test doesn't care about TimeZones (or even cultures), I just need to illustrate it can handle different formats. 
That's why I chose `g`.  
Since the TimeZone is completely arbitrary to me and the test, I figured the `o` pattern wouldn't be necessary.  
I'm happy to give it a try and see if it helps somewhere next week, but I don't see how it would make a difference, really.

Could you maybe elaborate on how using `o` would help me here?

**Comment by tarekgh** [comment]
> However, it still doesn't make sense to me why the behavior of DateTime and DateTimeOffset would be different here.

Could you please summarize what exactly the wrong behavior you are talking about here?  

> My test doesn't care about TimeZones (or even cultures), I just need to illustrate it can handle different formats. That's why I chose g.

You can still use `g` format with the Invariant culture.

**Comment by Clockwork-Muse** [comment]
> One of the examples I showed you is indeed running in CI, and, if you have advice to offer it's more than welcome.

See [this advice about testing](https://learn.microsoft.com/en-us/dotnet/core/extensions/best-practices-for-developing-world-ready-apps#recommendations-for-robust-testing).

For simple tests you can probably just get away with passing in the invariant culture for formatting operation tests.

**Comment by Marvin-Brouwer** [comment]
@tarekgh I will have a look at modifying my test to better suit the standard, but here's where I think it's inconsistent.

I have 6 tests, these tests are to illustrate the data converters can handle multiple DateTime and/or Time formats.  
These tests are duplicated, for JSON and for XML, basically the same logic for another data format.  
You can find all the tests here: https://github.com/search?q=repo%3AMarvin-Brouwer%2FFluentSerializer%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fissues%2F113478&type=code.  

When you look closely you can see that 4 tests are always applying the string replacement patch I added, those are the respective tests for `TimeOnly` and `DateTimeOffset`.  
When you look at the `DateTime` tests, there's an if statement before the fix, removing it when running on windows.  
I had to do this because the fix was breaking my tests locally, while fixing the tests in the CI pipeline.
You can see all my unit-tests succeeding here: https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/13934230563/job/38998491345.

This may very well still be related to the user culture of my machine, however, I did apply the `useUserOverride: false` everywhere.

**Comment by Clockwork-Muse** [comment]
@Marvin-Brouwer - 
[These lines](https://github.com/Marvin-Brouwer/FluentSerializer/blob/7b78eed6c9f6d1be1d107c2d85c0d6a92932c4a1/src/FluentSerializer.Json.Tests/Tests/Converting/Converters/DateTimeOffsetByFormatConverterTests.cs#L46-L48) using explicit format strings this way will sidestep any of the culture data:

```csharp
yield return new object[] { "M/d/yyyy zzz", "\"4/20/2096 +00:00\"", new CultureInfo("en-US", useUserOverride: false) };
yield return new object[] { "M/d/yyyy h:mm tt zzz", "\"4/20/2096 4:20 AM +00:00\"", new CultureInfo("en-US", useUserOverride: false) };
yield return new object[] { "dd-MM-yyyy HH:mm zzz", "\"20-04-2096 04:20 +00:00\"", new CultureInfo("nl-NL", useUserOverride: false) };
```
... you shouldn't need the replacement at all.

[These lines](https://github.com/Marvin-Brouwer/FluentSerializer/blob/7b78eed6c9f6d1be1d107c2d85c0d6a92932c4a1/src/FluentSerializer.Json.Tests/Tests/Converting/Converters/DateTimeByFormatConverterTests.cs#L46C1-L48C111)

```csharp
yield return new object[] { "d", "\"4/20/2096\"", new CultureInfo("en-US", useUserOverride: false) };
yield return new object[] { "g", "\"4/20/2096 4:20 AM\"", new CultureInfo("en-US", useUserOverride: false) };
yield return new object[] { "g", "\"20-04-2096 04:20\"", new CultureInfo("nl-NL", useUserOverride: false) };
```
... are inherently brittle, and _will_ fail in the future.  The proper way to deal with it in tests is to either only use the invariant culture, or to create your own custom culture with completely static data that you control.

That said...
> I have 6 tests, these tests are to illustrate the data converters can handle multiple DateTime and/or Time formats.
These tests are duplicated, for JSON and for XML, basically the same logic for another data format.

Except for certain rare situations, in almost all cases anything serialized (dates, times, numbers...) should be into one of the roundtrip formats with the invariant culture.  Especially if the intention is for persistence for any length of time.  Even when culture-specific serialization is valid, it shouldn't be deserialized from that value, and only be presented as the formatted string.

That guidance is to deal with this exact problem you're dealing with explicitly.

**Comment by Marvin-Brouwer** [comment]
Okay, I think I understand the problem.
I'm still not convinced it should behave differently between Ubuntu and Windows.
But, if you're convinced that's not a problem I'm happy to leave it here.

I'm going to see if changing `g` to `o` helps my tests, and otherwise, I'll just add a column to the test data to facilitate what I'm trying to do.

Thanks.

**Comment by Clockwork-Muse** [comment]
Again, your fundamental problem is that regardless of if multiple OSes updated this data at the same rate, and even if you somehow updated all deployments at the exact same instant, you still have to account for changes in this data.

For that matter, even if the OSes had the same information by default, there's various ways for users to customize it (especially on Linux), including in ways that developers have no insight or control over.

It's something you have to account for.
