### ISSUE TITLE
SLE15 repository for dotnet is missing matching dotnet-runtime-deps package

### ISSUE THREAD

**Issue by dirkmueller** [dotnet/runtime#115554]
### Description

``` 
Problem: 1: nothing provides 'dotnet-runtime-deps-9.0 >= 9.0.5' needed by the to be installed dotnet-runtime-9.0-9.0.5-1.x86_64
  Solution 1: do not install dotnet-runtime-9.0-9.0.5-1.x86_64
  Solution 2: break dotnet-runtime-9.0-9.0.5-1.x86_64 by ignoring some of its dependencies
```

### Reproduction Steps

zypper install dotnet-runtime-9.0

### Expected behavior

it installs successfully

### Actual behavior

there is an unresolved dependency due to a package missing.

### Regression?

yes

**Comment by NikolaMilosavljevic** [comment]
@dirkmueller this issue was fixed. Can you confirm and close the issue if it does not repro anymore?

**Comment by dirkmueller** [comment]
@NikolaMilosavljevic I still see the issue for 8.0.16:

```
Problem: 1: nothing provides 'dotnet-runtime-deps-8.0 >= 8.0.16' needed by the to be installed dotnet-runtime-8.0-8.0.16-1.x86_64
```

I can confirm that there is a dotnet-runtime-deps-9.0-9.0.5 that matches but it requires `libopenssl1_1` again while the plan previously was to use `libopenssl3`. it seems something is not quite right?

**Comment by NikolaMilosavljevic** [comment]
@rbhanda deps package issue is present for 8.0.16 release. Can this be fixed as well?

@dirkmueller `libopenssl3` fix was merged on time for June release, it is not present in May release.

**Comment by rbhanda** [comment]
> [@rbhanda](https://github.com/rbhanda) deps package issue is present for 8.0.16 release. Can this be fixed as well?
> 
> [@dirkmueller](https://github.com/dirkmueller) `libopenssl3` fix was merged on time for June release, it is not present in May release.

fixed for 8.0.16

**Comment by dirkmueller** [comment]
Looks good now, thanks!

**Comment by mssucksalot** [comment]
> > [@rbhanda](https://github.com/rbhanda) deps package issue is present for 8.0.16 release. Can this be fixed as well?
> > [@dirkmueller](https://github.com/dirkmueller) `libopenssl3` fix was merged on time for June release, it is not present in May release.
> 
> fixed for 8.0.16

dotnet-runtime-deps-8.0-8.0.15-1.x86_64.rpm is latest available for .NET 8 at https://packages.microsoft.com/opensuse/15/prod/Packages/d/

so problem is not solved

**Comment by rbhanda** [comment]
> > > [@rbhanda](https://github.com/rbhanda) deps package issue is present for 8.0.16 release. Can this be fixed as well?
> > > [@dirkmueller](https://github.com/dirkmueller) `libopenssl3` fix was merged on time for June release, it is not present in May release.
> > 
> > 
> > fixed for 8.0.16
> 
> dotnet-runtime-deps-8.0-8.0.15-1.x86_64.rpm is latest available for .NET 8 at https://packages.microsoft.com/opensuse/15/prod/Packages/d/
> 
> so problem is not solved

apologies, https://packages.microsoft.com/opensuse/15/prod/Packages/d/dotnet-runtime-deps-8.0-8.0.16-1.x86_64.rpm - I see the package is available now
