### ISSUE TITLE
Detecting .NET 10 Regression in startup performance affecting AWS Lambda

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#120288]
### Description

I'm testing .NET 10 vs .NET 8 in AWS Lambda to get ready for adding .NET 10 as a managed runtime in AWS Lambda. I know I should have done the performance testing months ago but always something getting in the way. 

Breaking down the AWS Lambda environment into a more basic explanation I'm testing both .NET 8 and .NET 10 as self contained applications with no trimming enabled and R2R enabled. In Lambda you are working with a small slice of CPU power in the compute environment. The Lambda function itself is nothing more then a hello world. The .NET Lambda runtime client is started up and is largely a glorified HttpClient making calls to make calls communicating the status of processing an event. The HTTP calls are local going over IP addresses and not using HTTPS.

I'm seeing .NET 10 having a 5 to 10 percent regression in the first invoke where the .NET runtime has to be started. 

In Lambda I can't attach a profiler but I added the following event listener to capture the .NET runtime events.
```
public class ConsoleListener : EventListener
{
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        // Attach to interesting sources
        if (eventSource.Name == "Microsoft-Windows-DotNETRuntime")
        {
            EnableEvents(eventSource, EventLevel.Informational,
                (EventKeywords)(-1)); // All keywords
        }
    }

    protected override void OnEventWritten(EventWrittenEventArgs e)
    {
        string value = string.Empty;
        if (e.Payload != null)
        {
            value = string.Join(", ", e.Payload);
        }
        Console.WriteLine($"{e.EventName}: {value}");
    }
}
```

Below are the links for the output of the cold start for both .NET 8 and 10 containing the .NET events.
.NET 8: https://github.com/normj/DotnetStartupPerformanceTest/blob/main/LambdaCaptures/dotnet8-metrics.txt
.NET 10: https://github.com/normj/DotnetStartupPerformanceTest/blob/main/LambdaCaptures/dotnet10-metrics.txt

I know data for this report is light. I'm working on collecting more information but given how close we are to .NET 10 release I didn't want to wait any longer to start a conversation. I'm kicking myself for not finding time to do this sooner. Maybe somebody on the .NET Team can see something important in the metrics files. From my analysis I see more .NET type being loaded, does this mean .NET 10 just does more at startup then .NET 8.

### Regression?

This is a regression in cold start for .NET 8

### Data

I have collected the metrics captures in the following repo
https://github.com/normj/DotnetStartupPerformanceTest/tree/main

I also added a console application that I explain in the README that I see some similar behavior when I run inside a container when using the `--cpus=0.1` switch to simulate the slice of CPU Lambda would give. Without the switch .NET 10 is faster but with the switch .NET 8 is faster although the difference is not as much as I'm seeing in Lambda. The README in the repo gives the instructions on how I run it.

**Comment by EgorBo** [comment]
@normj can you test it on .NET 9 as well to narrow it down to one release? Does AWS Lambda use Server GC? if so, can you see if `DOTNET_GCDynamicAdaptationMode=0` helps?

**Comment by normj** [comment]
@EgorBo I'll give .NET 9 a try. As for Server GC because my Lambda is set to low resources it has less then a CPU so Server GC is not enabled. I confirmed by updating my Lambda function calling `System.Runtime.GCSettings.IsServerGC` which returns `false.

**Comment by normj** [comment]
@EgorBo Here is the output of my test harness. This is the P90 of a 100 cold start invokes as a self contained Lambda function deployed to the generic Linux Lambda runtime instead of the .NET managed runtime. .NET 9 actually showed improvement over .NET 8. In this run I actually swapped down .NET 10 to preview 1 because I thought maybe I could isolate when the regression happen but it happened even at preview 1. When I was analyzing the .NET metrics differences between .NET 8 and 10 there were more loads from `System.Runtime.Intrinsics`. Is it possible anything with the preview 1 [AVX10.2 support](https://github.com/dotnet/core/blob/main/release-notes/10.0/preview/preview1/runtime.md#avx102-support) that could trigger this.

```
Total Duration .NET 8 P90 (ms): 680.3749999999999
Total Duration .NET 9 P90 (ms): 670.995
Total Duration .NET 10 P90 (ms): 730.268
```

**Comment by richlander** [comment]
@mangod9

**Comment by mangod9** [comment]
Thanks for reporting @normj. Does this also repro in a local lambda environment or only in cloud lambda invocations? If we can repro locally would be easier to diagnose.

**Comment by normj** [comment]
@mangod9 There isn't really a local Lambda environment. In the link repo I described how I tried to simulate the issue running a container with a heavily restricted CPU. I'm not a 100% sure it is an accurate reproduction of the issue in Lambda.

I had a chat with @EgorBo and I'm working on providing the event data with the setting set at verbose as opposed to informational which is what I did so far. I'm also trying to run the comparisons of runtimes on ARM to see if this is an X64 only issue.

**Comment by normj** [comment]
@EgorBo I added new log captures in the repo with the event listener set to verbose. 

https://github.com/normj/DotnetStartupPerformanceTest/tree/main/LambdaCaptures

**Comment by JulieLeeMSFT** [comment]
Thanks for the logs. We are taking a look.

**Comment by EgorBo** [comment]
@normj just curious, what ISAs your hw you're running AWS Lambda on have? e.g. AVX, SSE4.2 etc.
~~We bumped the minimal ISA level in .NET 10 for crossgen~~ (ah, that was in .NET 11.0)

**Comment by EgorBo** [comment]
When I run your repro locally on Linux-x64 I only see 55 methods being jitted with .NET 10.0 RC1 (slightly more with .NET 8.0):

```
   1: JIT compiled System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[byte]) [Tier0, IL size=69, code size=220]
   2: JIT compiled System.Net.IPAddress:.ctor(System.ReadOnlySpan`1[byte],long) [Tier0, IL size=67, code size=215]
   3: JIT compiled System.Net.IPAddress:ReadUInt16NumbersFromBytes(System.ReadOnlySpan`1[byte]) [Instrumented Tier0, IL size=96, code size=161]
   4: JIT compiled System.RuntimeType+IGenericCacheEntry`1[System.__Canon]:CreateAndCache(System.RuntimeType) [Instrumented Tier0, IL size=165, code size=1066]
   5: JIT compiled (dynamicClass):InvokeStub_EventSourceAttribute.set_Name(System.Object,System.Object,ptr) [FullOpts, IL size=25, code size=25]
   6: JIT compiled System.Collections.Concurrent.ConcurrentQueue`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:.ctor() [Tier0, IL size=44, code size=169]
   7: JIT compiled System.Collections.Concurrent.ConcurrentQueueSegment`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:.ctor(int) [Instrumented Tier0, IL size=65, code size=215]
   8: JIT compiled (dynamicClass):InvokeStub_EventSourceAttribute.set_Name(System.Object,System.Span`1[System.Object]) [FullOpts, IL size=26, code size=29]
   9: JIT compiled System.ReadOnlySpan`1[Interop+Sys+SocketEvent]:.ctor(ptr,int) [Tier0, IL size=46, code size=60]
  10: JIT compiled System.Collections.Concurrent.ConcurrentQueue`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:Enqueue(System.Net.Sockets.SocketAsyncEngine+SocketIOEvent) [Tier0, IL size=24, code size=75]
  11: JIT compiled System.Threading.Thread:GetThreadStaticsBase() [Tier0, IL size=18, code size=24]
  12: JIT compiled System.Collections.Concurrent.ConcurrentQueueSegment`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:TryEnqueue(System.Net.Sockets.SocketAsyncEngine+SocketIOEvent) [Instrumented Tier0, IL size=120, code size=358]
  13: JIT compiled System.Collections.Concurrent.ConcurrentQueue`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:TryDequeue(byref) [Tier0, IL size=45, code size=120]
  14: JIT compiled System.Collections.Concurrent.ConcurrentQueueSegment`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:TryDequeue(byref) [Instrumented Tier0, IL size=252, code size=597]
  15: JIT compiled System.Collections.Concurrent.ConcurrentQueue`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:get_IsEmpty() [Tier0, IL size=13, code size=50]
  16: JIT compiled System.Collections.Concurrent.ConcurrentQueue`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:TryPeek(byref,bool) [Instrumented Tier0, IL size=62, code size=239]
  17: JIT compiled System.Collections.Concurrent.ConcurrentQueueSegment`1[System.Net.Sockets.SocketAsyncEngine+SocketIOEvent]:TryPeek(byref,bool) [Instrumented Tier0, IL size=196, code size=604]
  18: JIT compiled System.SpanHelpers:SequenceCompareTo(byref,int,byref,int) [Instrumented Tier0, IL size=274, code size=689]
  19: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:.ctor(System.Collections.Generic.IEqualityComparer`1[System.__Canon]) [Tier0, IL size=9, code size=41]
  20: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:.ctor(int,System.Collections.Generic.IEqualityComparer`1[System.__Canon]) [Tier0, IL size=136, code size=384]
  21: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:set_Item(System.__Canon,System.ConsoleKeyInfo) [Tier0, IL size=11, code size=59]
  22: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:TryInsert(System.__Canon,System.ConsoleKeyInfo,byte) [Instrumented Tier0, IL size=565, code size=1575]
  23: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:Initialize(int) [Tier0, IL size=56, code size=225]
  24: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:GetBucket(uint) [Tier0, IL size=29, code size=90]
  25: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:Resize() [Tier0, IL size=19, code size=52]
  26: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:Resize(int,bool) [Instrumented Tier0, IL size=254, code size=1225]
  27: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:get_Count() [Tier0, IL size=14, code size=34]
  28: JIT compiled System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo]:GetEnumerator() [Tier0, IL size=8, code size=172]
  29: JIT compiled System.Collections.Generic.Dictionary`2+Enumerator[System.__Canon,System.ConsoleKeyInfo]:.ctor(System.Collections.Generic.Dictionary`2[System.__Canon,System.ConsoleKeyInfo],int) [Tier0, IL size=46, code size=95]
  30: JIT compiled System.Collections.Generic.Dictionary`2+Enumerator[System.__Canon,System.ConsoleKeyInfo]:MoveNext() [Instrumented Tier0, IL size=146, code size=472]
  31: JIT compiled System.Collections.Generic.KeyValuePair`2[System.__Canon,System.ConsoleKeyInfo]:.ctor(System.__Canon,System.ConsoleKeyInfo) [Tier0, IL size=15, code size=67]
  32: JIT compiled System.Collections.Generic.Dictionary`2+Enumerator[System.__Canon,System.ConsoleKeyInfo]:get_Current() [Tier0, IL size=7, code size=57]
  33: JIT compiled System.Collections.Generic.KeyValuePair`2[System.__Canon,System.ConsoleKeyInfo]:get_Key() [Tier0, IL size=7, code size=31]
  34: JIT compiled System.Collections.Generic.Dictionary`2+Enumerator[System.__Canon,System.ConsoleKeyInfo]:Dispose() [Tier0, IL size=1, code size=24]
Server received: hello world
  35: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:.ctor(int) [Tier0, IL size=9, code size=39]
  36: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:.ctor(int,System.Collections.Generic.IEqualityComparer`1[int]) [Tier0, IL size=136, code size=116]
  37: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:Initialize(int) [Tier0, IL size=56, code size=156]
  38: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:Add(int,int) [Tier0, IL size=11, code size=48]
  39: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:TryInsert(int,int,byte) [Instrumented Tier0, IL size=565, code size=1502]
  40: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:GetBucket(uint) [Tier0, IL size=29, code size=90]
  41: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:.ctor(int) [Tier0, IL size=9, code size=39]
  42: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:.ctor(int,System.Collections.Generic.IEqualityComparer`1[int]) [Tier0, IL size=136, code size=116]
  43: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:Initialize(int) [Tier0, IL size=56, code size=156]
  44: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:Add(int,int) [Tier0, IL size=11, code size=48]
  45: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:TryInsert(int,int,byte) [Instrumented Tier0, IL size=565, code size=1502]
  46: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:GetBucket(uint) [Tier0, IL size=29, code size=90]
  47: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:TryGetValue(int,byref) [Tier0, IL size=39, code size=90]
  48: JIT compiled System.Collections.Generic.Dictionary`2[int,int]:FindValue(int) [Instrumented Tier0, IL size=297, code size=1079]
  49: JIT compiled System.Collections.Generic.EqualityComparer`1[int]:get_Default() [Tier0, IL size=6, code size=35]
  50: JIT compiled System.Collections.Generic.EqualityComparer`1[int]:.cctor() [Tier0, IL size=26, code size=81]
  51: JIT compiled System.Collections.Generic.EnumEqualityComparer`1[int]:.ctor() [Tier0, IL size=7, code size=31]
  52: JIT compiled System.Collections.Generic.EqualityComparer`1[int]:.ctor() [Tier0, IL size=7, code size=31]
  53: JIT compiled System.Collections.Generic.EnumEqualityComparer`1[int]:GetHashCode(int) [Tier0, IL size=14, code size=34]
  54: JIT compiled System.Collections.Generic.EnumEqualityComparer`1[int]:Equals(int,int) [Tier0, IL size=8, code size=39]
  55: JIT compiled System.Runtime.CompilerServices.RuntimeHelpers:EnumEquals[int](int,int) [Tier0, IL size=5, code size=34]
```

**Comment by EgorBo** [comment]
Although, this doesn't seem to align with what your logs say
UPD: ah, that because of the EventSource

**Comment by normj** [comment]
The results for ARM are really interesting. There is actually an improvement over .NET 8 but a regression over .NET 9. Do you want the event metrics captures for ARM?

```
  Total Duration .NET 8 P90 (ms): 761.803
  Total Duration .NET 9 P90 (ms): 684.4830000000001
  Total Duration .NET 10 P90 (ms): 733.656
```

**Comment by EgorBo** [comment]
Things I've checked so far:

1) The local repro reproduces only inside the docker with a limited CPU budget, the same repro with e.g. affinity mask (`taskset -c 0`) doesn't repro (or, in fact, is faster on .NET 10.0)
2) JIT compiles 55 methods in .NET 10.0 and 64 in .NET 8.0. I've also confirmed that `DOTNET_ReadyToRun=0` doesn't fix the problem. In fact, with R2R=0 the difference is even more visible (**>10%**) between 8 and 10. This rules out R2R as a potential source of the problem.
3) I tried to run `docker run` under `perf record` but couldn't extract any useful information/symbolicate it properly
4) TieredPGO=0 doesn't change the picture
5) With `-e DOTNET_ReadyToRun=0 -e DOTNET_TieredCompilation=0` .NET 10 is **25% slower**.
6) No difference with `DOTNET_JITMinOpts=1` so whatever this is, JIT optimizations aren't the culprit.

I also played with many other knobs like W^X, GC knobs, spin-waits -- none of them helped.

@AndyAyersMS so in case if you want to play with it locally:
```sh
# install .NET 8/9/10
# install docker
git clone https://github.com/normj/DotnetStartupPerformanceTest.git
cd DotnetStartupPerformanceTest/DotnetStartupPerformanceTest
sudo docker build -f Dockerfile.net8 -t startup:net8 .
sudo docker build -f Dockerfile.net10 -t startup:net10 .

# Measurements e.g.:
sudo taskset -c 0 docker run --rm -it --cpus=0.1 -e DOTNET_ReadyToRun=0 -e DOTNET_TieredCompilation=0 startup:net10
```

@normj thanks for providing the event data. Unfortunately, EventSource comes with an extra overhead by it's own - this explains the difference in methods jitted in your logs (>350 vs 55 when running without it).

**Comment by mangod9** [comment]
is there a floor for the cpu constraint when it does start reproing? e.g. Is it fine with 1 dedicated core, but repros as the cpu fraction reduces?

**Comment by JulieLeeMSFT** [comment]
Thanks @EgorBo for running various checks. Next, we will try varying a CPU fraction.

**Comment by EgorBo** [comment]
> is there a floor for the cpu constraint when it does start reproing? e.g. Is it fine with 1 dedicated core, but repros as the cpu fraction reduces?

hard to tell, it practically disappears after cpus=1 with the default args. With the default args the regression is around 4-5% for 0.1

**Comment by noahfalk** [comment]
@normj - you mentioned you couldn't run a profiler but can you set environment variables? If you can that should be sufficient to use EventPipe which will let the runtime profile itself:
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe#trace-using-environment-variables

**Comment by normj** [comment]
I think I found a way for you all to reproduce the issue locally, at least via containers and then using the Lambda Runtime Emulator. I updated instructions on the repo. Let me know if something doesn't work for you all. https://github.com/normj/DotnetStartupPerformanceTest?tab=readme-ov-file#simulate-locally-with-lambda-emulator

**Comment by normj** [comment]
> [@normj](https://github.com/normj) - you mentioned you couldn't run a profiler but can you set environment variables? If you can that should be sufficient to use EventPipe which will let the runtime profile itself: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/eventpipe#trace-using-environment-variables

I can set environment variables. I'll take a look at your link.

**Comment by normj** [comment]
@noahfalk The challenge I'm running into using the environment variables is the trace file is only finalize to disk when the process exits but in Lambda's case the process never exits and if did via a forced crash the compute environment is recycled right away. Hopefully the new local repo setup I posted earlier works for you all. If not I can see if I can create a wrapper process in Lambda using the `DiagnosticsClient` which will have a different set of challenges with knowing when to stop the snapshot and upload to S3.

**Comment by AndyAyersMS** [comment]
Thanks Norm. We are still investigating on our end -- hopefully will get some insights soon.

**Comment by normj** [comment]
> Thanks Norm. We are still investigating on our end -- hopefully will get some insights soon.

Were you able to repo the issue locally with my Lambda emulator sample I mentioned above?

**Comment by AndyAyersMS** [comment]
> > Thanks Norm. We are still investigating on our end -- hopefully will get some insights soon.
> 
> Were you able to repo the issue locally with my Lambda emulator sample I mentioned above?

Haven't had a chance to try this yet, but will do so soon.

**Comment by EgorBo** [comment]
@normj meanwhile, could you please test on the real scenario exactly the same code but with:
```diff
-var localEndPoint = new IPEndPoint(IPAddress.Loopback, port);
+var localEndPoint = new IPEndPoint(16777343, port); //int64 representation of 127.0.0.1
```

**Comment by normj** [comment]
> @normj meanwhile, could you please test on the real scenario exactly the same code but with:

You mean in the `DotnetStartupPerformanceTest` test app? I can try that and see what difference I see. I'm away from my laptop till this evening, I'll try it tonight.

**Comment by steveisok** [comment]
> > Thanks Norm. We are still investigating on our end -- hopefully will get some insights soon.
> 
> Were you able to repo the issue locally with my Lambda emulator sample I mentioned above?

I can get it rolling, but beware trying to run it on a mac. The container crashes and burns no matter if the host is arm64 or x64.

**Comment by normj** [comment]
@steveiosk I haven't tried it on a Mac. Something that might cause you trouble is in the Dockerfile I am doing a .NET publish for X64. https://github.com/normj/DotnetStartupPerformanceTest/blob/main/LambdaWithEmulatorTest/Dockerfile#L9

**Comment by EgorBo** [comment]
Linux `perf` profiles (for an empty console app, since it seems to also is a bit slower)
.NET 10: https://egorbot2.blob.core.windows.net/telegafiles/flamegraph10_norm_868a04d5dd.svg
.NET 9: https://egorbot2.blob.core.windows.net/telegafiles/flamegraph9_norm_45fbe4e47b.svg

It seems `EventSource::InitializeDefaultEventSources` is taking longer on .NET 10... (I was using `perf` so no dotnet-trace overhead)
Or `RuntimeEventSource::.cctor` calling `Guid::.ctor` to be specific.

>  I can try that and see what difference I see. 

I was just suspecting an issue that turned out to be not impactful

**Comment by EgorBo** [comment]
And here are the flamegraphs for the actual repro (collected with `perf record`), default env.vars:
.NET 10: https://egorbot2.blob.core.windows.net/telegafiles/repro_flamegraph10_norm_991d2e0ad6.svg
.NET 9: https://egorbot2.blob.core.windows.net/telegafiles/repro_flamegraph9_norm_4074047734.svg
where the difference seems to be pointing to `EventSource::GetName` ?

**Comment by noahfalk** [comment]
Looking at the two flamegraphs I see:

```
              Total samples     EventSource.GetName samples
.NET 9        175M              6.7M
.NET 10       239M              22M
```

The increase in GetName accounts for an extra 15.3M samples out of a 64M sample difference. That still leaves 49M excess samples elsewhere unaccounted for. The rest of this analyzes the EventSource.GetName part but on its own that may only be 25% of the full regression.


It looks like the underlying change is System.Attribute.GetCustomAttribute() has a higher startup cost than it used to. GetCustomAttribute is pretty much the entire cost of the GetName call. I'm seeing increased costs across many of the calls inside GetCustomAttribute but the most notable difference was CreateStringFromEncoding which doesn't show up there in .NET 9 and takes 7.2M samples on .NET 10. ( CreateStringFromEncoding does show up in a different calltree in .NET 9 accounting for 4.5M samples so some of this could be just shifting the same load cost to a different caller).

In .NET 10 CreateStringFromEncoding is reached here:

```
 	string.CreateStringFromEncoding(byte*, int, System.Text.Encoding)	C#
 	System.Text.Encoding.GetString(System.ReadOnlySpan<byte>)	C#
 	System.MdUtf8String.ToString()	C#
>	System.RuntimeMethodHandle.GetName(System.RuntimeMethodHandleInternal)	C#
 	System.RuntimeMethodHandle.GetName(System.IRuntimeMethodInfo)	C#
 	System.Reflection.RuntimeMethodInfo.Name.get()	C#
 	System.Reflection.InvokerEmitUtil.CreateInvokeDelegate_ObjSpanArgs(System.Reflection.MethodBase, bool)	C#
 	System.Reflection.MethodInvokerCommon.DetermineStrategy_ObjSpanArgs(ref System.Reflection.MethodBase.InvokerStrategy, ref System.Reflection.InvokerEmitUtil.InvokeFunc_ObjSpanArgs, System.Reflection.MethodBase, bool, bool)	C#
 	System.Reflection.MethodBaseInvoker.InvokePropertySetter(object, System.Reflection.BindingFlags, System.Reflection.Binder, object, System.Globalization.CultureInfo)	C#
 	System.Reflection.CustomAttribute.AddCustomAttributes(ref System.RuntimeType.ListBuilder<object>, System.Reflection.RuntimeModule, int, System.RuntimeType, bool, System.RuntimeType.ListBuilder<object>)	C#
 	System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, int, int, System.RuntimeType)	C#
 	System.Reflection.CustomAttribute.GetCustomAttributes(System.RuntimeType, System.RuntimeType, bool)	C#
 	System.RuntimeType.GetCustomAttributes(System.Type, bool)	C#
 	System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo, System.Type, bool)	C#
 	System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo, System.Type, bool)	C#
 	System.Reflection.CustomAttributeExtensions.GetCustomAttribute(System.Reflection.MemberInfo, System.Type, bool)	C#
 	System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(System.Reflection.MemberInfo, System.Type, System.Diagnostics.Tracing.EventManifestOptions)	C#
```

The relevant change appears to be https://github.com/dotnet/runtime/commit/0f04f6d7e59487fab5bb98e90c90d049cc7d48e1. In that change the implementation of RuntimeMethodHandle.GetName(RuntimeMethodHandleInternal method) changed from an internal call to instead call GetUtf8Name() which calls to MdUtf8String.ToString() leading into CreateStringFromEncoding.

We could either:
a) Try to improve the 1st invocation performance of GetCustomAttribute as it was before
b) Try to change this particular call path to avoid invoking GetCustomAttribute.

Option (b) doesn't look too bad though it also doesn't protect against any other code that might call GetCustomAttribute() later and incur the same startup penalty. [In the networking code](https://source.dot.net/#System.Net.Sockets/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs,38) switching from:

```C#
public static readonly NetEventSource Log = new NetEventSource();
```

to:

```C#
public static readonly NetEventSource Log = new NetEventSource(MyEventSourceName, EventSourceSettings.EtwManifestEventFormat);
```

should initialize the EventSource without needing to reflect over the custom attribute to figure out the name. A tiny wrinkle is that the source file is shared across multiple assemblies to define multiple EventSources that all have the same class name but different event source names. The new `MyEventSourceName` string constant will need to be individually initialized to proper value for each EventSource sharing that code.

heads up:
- @AaronRobinsonMSFT for the MethodHelperFrame change
- @karelz @dotnet/ncl for the networking code

Hope that helps!

**Comment by EgorBo** [comment]
> The relevant change appears to be https://github.com/dotnet/runtime/commit/0f04f6d7e59487fab5bb98e90c90d049cc7d48e1. In that change the implementation of

Yes, I blamed this change offline too 🙂 interesting that our guesses match

**Comment by EgorBo** [comment]
It might not be the culprit, thought, as https://github.com/dotnet/runtime/commit/0f04f6d7e59487fab5bb98e90c90d049cc7d48e1 indeed introduced a new call to `Encoding.GetString`, but the actual repro contains another call to `Encoding.GetString` ([this](https://github.com/normj/DotnetStartupPerformanceTest/blob/main/DotnetStartupPerformanceTest/Program.cs#L25)) so the difference in traces is where R2R load of that method (and the Utf8Transcode) appears, that's why in .NET 9 flamegraph is looking a bit different

**Comment by AaronRobinsonMSFT** [comment]
@jkotas looks like some potential impact from the HMF removal. Callstacks are a bit different between Net 9 and Net 10 though. I also see some of the newer Reflection stack being exercised in these paths.

**Comment by jkotas** [comment]
Yes, the HMF change moved where strlen and utf8 encoding/decoding get called for the first time and gets the blame for its cost. I do not think it is interesting to be tweaking where these primitive operations are called for the first time. Any Unix workload - even the simplest ones - are going to use them a ton. Instead, we need to figure out how to make them less expensive.

**Comment by noahfalk** [comment]
@EgorBo - did the .NET 10 and .NET 9 performance traces you took run the same number of iterations? I originally assumed you had but looking at this a little more closely I see a somewhat uniform increase across many methods. Often that means one workload ran more iterations than the other. If so we'd either need to rescale all the samples or compare sample % rather than sample counts.

And yeah, I did see that CreateStringFromEncoding had a cost that showed under a different callstack in .NET 9. In .NET 10 the cost was 60% higher so I couldn't fully explain it away as just a shift in caller. Assuming there were ~35% more iterations sampled in .NET 10 accounts for yet more of it though it still leaves about 1.2M samples unaccounted for there. At 0.5% of total samples that could be noise or it could be a small part of the overall regression.

@EgorBo - do you have the raw data available to do a numeric comparison rather than a graphical one? Especially if we need to be rescaling sample counts and re-attributing costs across different callstacks spotting small differences in a flame graph by eye isn't that easy.

Another spot I noticed that differs in behavior is Guid::.ctor (~0.35M vs 4.91M samples). In .NET 10 there are a bunch of R2R loading costs that weren't present in 9 but as before its possible a more accurate accounting will find all of those costs were billed to some other caller and got shifted around.

**Comment by am11** [comment]
<details>
  <summary>Don't seem to find much difference on arm64 between net9 vs. 10 in <code>GetCustomAttributes</code> benchmark:</summary>

```c#
using System;
using System.Linq;
using System.Reflection;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<ReflectionBenchmarks>();

[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
public class DemoAttribute : Attribute
{
    public string Name { get; }
    public DemoAttribute(string name) => Name = name;
}

[Demo("ClassLevel")]
public class SampleClass
{
    [Demo("MethodLevel")]
    public void Method() { }
}

[SimpleJob(RuntimeMoniker.Net90)]
[SimpleJob(RuntimeMoniker.Net10_0)]
[MemoryDiagnoser]
public class ReflectionBenchmarks
{
    private readonly Type _type = typeof(SampleClass);
    private readonly MethodInfo _method;

    public ReflectionBenchmarks()
    {
        _method = _type.GetMethod("Method")!;
    }

    [Benchmark]
    public object[] GetClassAttributes() =>
        _type.GetCustomAttributes(inherit: true).ToArray();

    [Benchmark]
    public object[] GetMethodAttributes() =>
        _method.GetCustomAttributes(inherit: true).ToArray();
}
```
</details>

```
// * Summary *

BenchmarkDotNet v0.15.4, Linux Alpine Linux v3.22
Unknown processor
.NET SDK 10.0.100-rtm.25479.115
  [Host]    : .NET 9.0.9 (9.0.9, 9.0.925.41916), Arm64 RyuJIT armv8.0-a
  .NET 10.0 : .NET 10.0.0 (10.0.0-rtm.25479.115, 10.0.25.48015), Arm64 RyuJIT armv8.0-a
  .NET 9.0  : .NET 9.0.9 (9.0.9, 9.0.925.41916), Arm64 RyuJIT armv8.0-a


| Method              | Job       | Runtime   | Mean     | Error    | StdDev  | Gen0   | Allocated |
|-------------------- |---------- |---------- |---------:|---------:|--------:|-------:|----------:|
| GetClassAttributes  | .NET 10.0 | .NET 10.0 | 577.4 ns |  6.45 ns | 5.72 ns | 0.0668 |     280 B |
| GetMethodAttributes | .NET 10.0 | .NET 10.0 | 593.3 ns | 10.44 ns | 8.72 ns | 0.0668 |     280 B |
| GetClassAttributes  | .NET 9.0  | .NET 9.0  | 665.0 ns |  8.05 ns | 6.73 ns | 0.0668 |     280 B |
| GetMethodAttributes | .NET 9.0  | .NET 9.0  | 578.7 ns |  6.35 ns | 5.63 ns | 0.0668 |     280 B |
```

**Comment by am11** [comment]
Ah, maybe it's about cold start penalty, not the entire thing slowed down? 👀

**Comment by jkotas** [comment]
> Ah, maybe it's about cold start penalty

This issue is about warm startup time (startup time when you run the binary in a loop).

**Comment by AndyAyersMS** [comment]
@normj running the lambda emulator I am getting a crash, this was I think iteration 16 of the .NET 10 run

```
**** Invoking Lambda function (Attempt 1149)****
System.Exception: Failed to find Billed Duration in output
04 Oct 2025 18:16:42,201 [INFO] (rapid) exec './bootstrap' (cwd=/var/task, handler=)
START RequestId: 701a0456-e3f6-47a7-acaf-d05c32dfdb56 Version: $LATEST
04 Oct 2025 18:16:42,223 [INFO] (rapid) INIT START(type: on-demand, phase: init)
04 Oct 2025 18:16:42,224 [INFO] (rapid) The extension's directory "/opt/extensions" does not exist, assuming no extensions to be loaded.
04 Oct 2025 18:16:42,224 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
START RequestId: 25f32ecd-136f-4a91-81f0-1d4667f1daaf Version: $LATEST
04 Oct 2025 18:16:42,868 [INFO] (rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6ab69f]

goroutine 11 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:666 +0xdf
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke in goroutine 8
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:649 +0x1f1



   at ProcessorWrapper.RunDockerImageUntilBilledDuration(String imageName) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/ProcessorWrapper.cs:line 73
   at Program.<<Main>$>g__ComputeP80|0_0(String imageName) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/Program.cs:line 24
   at Program.<Main>$(String[] args) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/Program.cs:line 13
**** Invoking Lambda function (Attempt 1150)****
```

**Comment by normj** [comment]
@AndyAyersMS Were you running on a Mac or Windows? I only tested it on a Windows X64 machine. Interesting that it made it a few iterations and then failed. I'll add some retries in the iterations to make it more resilient.

**Comment by AndyAyersMS** [comment]
Windows, though from a WSL2/Ubuntu 24.04 subsystem, if that matters.

Does the host container have diagnostic tools (eg `perf`)? If not, is it easy to add them?

**Comment by EgorBo** [comment]
So the current theory is that [this cctor](https://github.com/dotnet/runtime/blob/a869b45f1d8e46a0032e303d13bafac468dbae77/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs#L17) is slower in .NET 10.0 (although, it appeared in .NET 9.0 with https://github.com/dotnet/runtime/pull/106014) but .NET 10.0 is slower due to some generics unifications/abstractions landed in .NET 10.0 around parsing (e.g. https://github.com/dotnet/runtime/pull/105654)

I presume there are multiple ways to optimize it.

**Comment by EgorBo** [comment]
> [@EgorBo](https://github.com/EgorBo) - did the .NET 10 and .NET 9 performance traces you took run the same number of iterations? I originally assumed you had but looking at this a little more closely I see a somewhat uniform increase across many methods. Often that means one workload ran more iterations than the other. If so we'd either need to rescale all the samples or compare sample % rather than sample counts.

I was running just a single iteration under `perf record`, something like this:
```sh
sudo systemd-run --expand-environment=yes --scope \
  -p CPUQuota=10% \
  bash -lc "DOTNET_PROCESSOR_COUNT=1 DOTNET_PerfMapEnabled=1 DOTNET_PerfMapStubGranularity=2 DOTNET_PerfMapShowOptimizationTiers=0 perf record -k 1 -g -F 9999 -- ./out$TFM/DotnetStartupPerformanceTest"
```

> [@EgorBo](https://github.com/EgorBo) - do you have the raw data available to do a numeric comparison rather than a graphical one? Especially if we need to be rescaling sample counts and re-attributing costs across different callstacks spotting small differences in a flame graph by eye isn't that easy.


I can collect.

Here are the flamegraphs collected on Amazon Linux 2023 with just one change to the source file: `_ = Encoding.UTF8.GetString("hello world"u8);` added as the first line in the snippet just to make sure Aaron's PR is not the culprit.

.NET 8.0 svg: https://egorbot2.blob.core.windows.net/telegafiles/awslinux2023_net8_1bc0e9bf8b.svg
.NET 9.0 svg: https://egorbot2.blob.core.windows.net/telegafiles/awslinux2023_net9_0328c3c355.svg
.NET 10.0 svg: https://egorbot2.blob.core.windows.net/telegafiles/awslinux2023_net10_6ce6757930.svg

Note: that there is an extra overhead in .NET 10.0 due to `DOTNET_PerfMapStubGranularity=2` and https://github.com/dotnet/runtime/pull/113943 (see `LogStubs` in the traces) - this env.var is required on .NET 10.0 otherwise all managed symbols become just module names.

**Comment by AndyAyersMS** [comment]
@normj is there some way to get the lambda emulation not to kill everything at the end of the bootstrap?

**Comment by normj** [comment]
@AndyAyersMS If you set the environment variable `AWS_LAMBDA_DOTNET_DEBUG_RUN_ONCE` to `true`, I set it in the Dockerfile, the .NET process will process one event and then exit it's forever loop. The emulator which runs in a separate process will throw errors because the .NET part ended unexpertly from it's point of view.

Instead of using `LambdaEmulatorPerformanceRunner` to drive running the container to get metrics you can also individual run the `invoke-lambda.ps1` powershell script in LambdaWithEmulatorTest to send one invoke to the Lambda emulator which will kick off the .NET process.

As far as getting the diagnostic tools tools on the container I don't see any reason why that wouldn't work. Keep in mind my default it doesn't have .NET runtime or SDK installed hence the reason I deploy as a self contained. Also the base image does not have libicu installed. If you need libicu add `RUN dnf install libicu-67.1-7.amzn2023.0.3.x86_64 --assumeyes` to the dockerfile.

**Comment by normj** [comment]
I have a way now to get nettrace files using the emulator using the repo project from my [repository](https://github.com/normj/DotnetStartupPerformanceTest/tree/main/LambdaWithEmulatorTest). 

Go to the `LambdaWithEmulatorTest` directory and build the container. Here is the command for .NET 10. For .NET 8 or 9 replace the `net10.0` with the TFM in the build args and tag.

```
docker build --build-arg TARGET_FRAMEWORK=net10.0 -t lambda-coldstart-issue:net10.0 .
```

Then run the container with `bash` as the entrypoint so you can run commands on the container. The command is also going to restrict the CPU usage and mount the current host directory to the `/var/traces/` directory in the container.
```
docker run --rm -it -p 9000:8080 -v "$(pwd):/var/traces" --cpus=0.1 --entrypoint bash lambda-coldstart-issue:net10.0
```

Once on the bash shell in the container set the following environment variables. As mention in a previous comment the `AWS_LAMBDA_DOTNET_DEBUG_RUN_ONCE` environment variable tells the .NET process part of the Lambda workflow to process one event and then exit it's forever loop. The other environment variables turn on the diagnostic tracing and write to the mounted folder.
```
export AWS_LAMBDA_DOTNET_DEBUG_RUN_ONCE=true
export DOTNET_EnableEventPipe=1
export DOTNET_EventPipeOutputPath=/var/traces/lambda-net10.nettrace
```
Now run the Lambda emulator. This is all assuming you are still in the `/var/task` directory which is the default.
```
/usr/local/bin/aws-lambda-rie ./bootstrap
```
Back on the host machine open another terminal in the same directory and run the `./invoke-lambda.ps1`. This will return back an error because the emulator hosting the .NET process didn't like the fact the .NET process exited. At this point though the .NET process has exited cleanly after processing the Lambda function and the nettrace file will be in the host machine's current directory.

In the terminal that ran the container the output will complain about the error about the .NET process exiting. You can just Ctrl-C to exit out.

In the https://github.com/normj/DotnetStartupPerformanceTest/tree/main/LambdaCaptures folder I added nettrace files for 8, 9 and 10 but I wanted to explain how I produced them so you all could evaluate my process and do it yourself if you want different information.

**Comment by normj** [comment]
@AndyAyersMS I pushed up a new commit to the LambdaEmulatorPerformanceRunner project that should make it more resilient. I believe there could be problems with the host port not being freed in time for the next iteration. I updated the tool so that if it gets into that state increment the host port number to try and then retry the iteration.

> [@normj](https://github.com/normj) running the lambda emulator I am getting a crash, this was I think iteration 16 of the .NET 10 run
> 
> ```
> **** Invoking Lambda function (Attempt 1149)****
> System.Exception: Failed to find Billed Duration in output
> 04 Oct 2025 18:16:42,201 [INFO] (rapid) exec './bootstrap' (cwd=/var/task, handler=)
> START RequestId: 701a0456-e3f6-47a7-acaf-d05c32dfdb56 Version: $LATEST
> 04 Oct 2025 18:16:42,223 [INFO] (rapid) INIT START(type: on-demand, phase: init)
> 04 Oct 2025 18:16:42,224 [INFO] (rapid) The extension's directory "/opt/extensions" does not exist, assuming no extensions to be loaded.
> 04 Oct 2025 18:16:42,224 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
> START RequestId: 25f32ecd-136f-4a91-81f0-1d4667f1daaf Version: $LATEST
> 04 Oct 2025 18:16:42,868 [INFO] (rapid) ReserveFailed: AlreadyReserved
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6ab69f]
> 
> goroutine 11 [running]:
> go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
>         /LambdaRuntimeLocal/lambda/rapidcore/server.go:666 +0xdf
> created by go.amzn.com/lambda/rapidcore.(*Server).Invoke in goroutine 8
>         /LambdaRuntimeLocal/lambda/rapidcore/server.go:649 +0x1f1
> 
> 
> 
>    at ProcessorWrapper.RunDockerImageUntilBilledDuration(String imageName) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/ProcessorWrapper.cs:line 73
>    at Program.<<Main>$>g__ComputeP80|0_0(String imageName) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/Program.cs:line 24
>    at Program.<Main>$(String[] args) in /home/andya/bugs/r120288/DotnetStartupPerformanceTest/LambdaEmulatorPerformanceRunner/Program.cs:line 13
> **** Invoking Lambda function (Attempt 1150)****
> ```

**Comment by AndyAyersMS** [comment]
Thanks @normj, but even with this I am still seeing a decent rate of failure, and once a failure happens things seem to go off the rails somehow and things don't recover. So it's been hard to get enough runs in to have a reliable P80 estimate. Killing the whole thing somehow does clean things up as the next attempt at a set of runs goes along ok.

**Comment by AndyAyersMS** [comment]
Ah I am being dumb. All of my lambda invocations are failing when I run under WSL2, likely some networking issue that I need to sort out. But instead I'll just run all this under windows.

**Comment by AndyAyersMS** [comment]
That works better, but is still not super robust... not sure how things end up like this:
```
**** Invoking Lambda function (Attempt 1191)****
**** Invoking Lambda function (Attempt 30)****
**** Invoking Lambda function (Attempt 1192)****
**** Invoking Lambda function (Attempt 1193)****
**** Invoking Lambda function (Attempt 31)****
```

**Comment by normj** [comment]
@AndyAyersMS It will be common to get multiple lines of the `Invoking Lambda function (Attempt ...` because it starts attempting to send events to the emulator as soon as the container is started but it doesn't know when it the endpoint will be available. That said the most attempts I have seen is around 8.

I suspect you are seeing some orphan background polling tasks that didn't get kill when the containers got in an error state. They should be benign because they are not part of what is measured. I did just push a commit to add a timeout on the ` 

I updated the code to add a timeout on the `CancellationTokenSource` as well made sure the explicit `cancellationTokenSource.Cancel();` call was being done in a finally block to help make sure the background poller is shut down.

**Comment by AndyAyersMS** [comment]
Yes I see stretches of 8 or so failed attempts sometimes, but the above persists from one measurement attempt to the next and ultimately creates huge numbers of failed attempts. 

Let me try your latest.

**Comment by normj** [comment]
Looking at the PRs that have been submitted, which I appreciate the work here, the description says for trivial workloads. I only used trivial in the sample to remove any other noise. The regression for first invoke happens even with non-trivial workloads. For example I update the sample app in the repo to make an AWS service call and you can see with measurements blew .NET 8 was still faster at first invoke.

```
P80 .NET 10: 2377 ms
P80 .NET  8: 2199 ms
```

I'm working on collecting the data to see at what point during the warm invokes does .NET 10 get faster or comparable.

**Comment by AndyAyersMS** [comment]
I have been running a custom 10RC1 with those PRs and indeed they are not the full story. We are still looking into what else might be a factor.

**Comment by AndyAyersMS** [comment]
We've identified one other change that is a factor in the lambda emulator test perf and are looking ways to expediently fix it in .NET 10.

**Comment by normj** [comment]
@AndyAyersMS That is great. Let me know if/when there is a daily or experimental build I can pick up and test with.

**Comment by AndyAyersMS** [comment]
Looks like still more fixing is needed. Will keep you posted.

**Comment by normj** [comment]
Not sure if this will be helpful for this performance investigation but I'm also measuring the performance of .NET 10 vs 9 and 8 for the warm invokes. Meaning what is the P90 for a 100 invokes after the initial cold start invoke. I updated the function to compute primes to add some CPU intensive pressure.

What I'm seeing is .NET 10 take a bit longer to get to optimal state. For example here is the P90 for the prime computing Lambda function for the first 100 invokes after cold start.
```
Total Duration .NET 8 P90 (ms): 465.436
Total Duration .NET 9 P90 (ms): 485.781
Total Duration .NET 10 P90 (ms): 521.895
```

If I start computing the P90 after ignoring the first 10 invokes and then doing another 100 invokes the numbers still show .NET 10 slower.
```
Total Duration .NET 8 P90 (ms): 330.785
Total Duration .NET 9 P90 (ms): 346.34400000000005
Total Duration .NET 10 P90 (ms): 425.288
```

If ignore the first 25 and then measure the P90 for the next 100 calls is when .NET 10 gets in line with the performance of .NET 8 and 9.
```
Total Duration .NET 8 P95 (ms): 324.3855
Total Duration .NET 9 P95 (ms): 324.135
Total Duration .NET 10 P95 (ms): 324.416
```

<details>

<summary>Lambda code for Reference</summary>

This is the code I'm used to add some CPU pressure while testing warm invokes. At one point I was also making an AWS service call which was the reason for creating the `AmazonSecurityTokenServiceClient` instance but I the code to make the service call was commented out when I generated the numbers above.

```csharp
public class Function
{
    static IAmazonSecurityTokenService _stsClient = new AmazonSecurityTokenServiceClient();

    private static async Task Main(string[] args)
    {
        //using var listener = new ConsoleListener();
        Func<Stream, ILambdaContext, Stream> handler = FunctionHandler;
        await LambdaBootstrapBuilder.Create(handler)
            .Build()
            .RunAsync();
    }

    public static Stream FunctionHandler(Stream stream, ILambdaContext context)
    {
        //var response = _stsClient.GetCallerIdentityAsync(new GetCallerIdentityRequest()).Result;
        //context.Logger.LogInformation("Account: {account}", response.Account);

        var startTime = DateTime.Now;

        // CPU-intensive prime calculation
        int count = 0;
        int limit = 500000; // Adjust this number to control execution time

        for (int i = 2; i <= limit; i++)
        {
            if (IsPrime(i))
            {
                count++;
            }
        }

        var endTime = DateTime.Now;
        Console.WriteLine($"Found {count} primes up to {limit}");
        Console.WriteLine($"Execution time: {(endTime - startTime).TotalSeconds:F2} seconds");


        context.Logger.LogInformation("IsServerGC: {serverGC}", System.Runtime.GCSettings.IsServerGC);
        context.Logger.LogInformation("Function invoked with stream of length: " + stream.Length);
        var responseStream = new MemoryStream(UTF8Encoding.UTF8.GetBytes("Hello World"));
        return responseStream;
    }

    private static bool IsPrime(int number)
    {
        if (number < 2) return false;

        for (int i = 2; i <= Math.Sqrt(number); i++)
        {
            if (number % i == 0)
                return false;
        }
        return true;
    }
}
```
</details>

**Comment by AndyAyersMS** [comment]
Thanks, Norm. We will take a look at that as well.

Not much of an update from our side just now. Our current set of fixes is not helping as much as we expected, so we will keep digging.

Do you know how well the lambda emulator environment models what happens in the real lambda environment? In particular is the 0.1 cpu restriction in docker on the high side of what lambdas actually get, or on the low side, or ...?

**Comment by normj** [comment]
The 0.1 CPU is probably a bit on the low side but we are using 2 different units so hard to match up. 

In Lambda world the actual amount of CPU given a function is a bit abstract. The configuration knob users have is how much memory to allocate which gives a proportion of vCPU based on memory. If memory is set at 1,769 MB that would give you 1 vCPU. The default memory setting we suggest for .NET is 512 MB and is what I have been doing all my benchmarking with. So if Lambda does it completely proportional then that would be about 0.29 vCPU. I don't think Lambda's vCPU and Docker's CPU switch are the exact same unit but should be in the rough ball park.

**Comment by AndyAyersMS** [comment]
We've identified a couple of fixes that should help mitigate the regression. Unfortunately, the fixes need more time to validate, so we're not going to be able to get them into the GA release in November. We hope to have them ready in time for one of the servicing releases early next year.

**Comment by normj** [comment]
Thanks for the update @AndyAyersMS. That is unfortunate the fixes won't make GA but understand this is very late in the release cycle and changes at this low level need validation. 

A couple questions for you:
* Are you thinking these fixes will be in patch 1?
* With these fixes should we expect performance to be at the level of .NET 8 for cold start?
* Are there any environment variables / settings that I could use in the meantime to at least give a partial mitigation?
* We are going to have to make a call whether to release with .NET 10 GA with the known regression or wait till the patch. If we went with .NET 10 GA in our communication would it be fair to say in customer communication that we recognize the regression and we are working with the MSFT .NET Team who plan to have addressed the issue in an upcoming patch for .NET 10? I'm not in charge of the marketing side but basically how confident do we feel about a public commitment that this will be addressed so if/when customers hit this we can give confidence this is temporary.

**Comment by AndyAyersMS** [comment]
> ... this is very late in the release cycle and changes at this low level need validation.

One of the key fixes changes aspects of type loading in the runtime. Bugs here tend to be subtle, and it will take us a while to gain confidence that the fix does not introduce problems. We will merge this fix into main and get some mileage on it, and once it's in good shape we'll port it back to 10.0. Can't say for sure yet which servicing release this will make, but we'll try and get it in as soon as we can.

We have not found any workarounds.

**Comment by normj** [comment]
@AndyAyersMS Thanks for the info and I really appreciate the effort on this. I can appreciate the sensitivity of making changes at such a low level.

Going forward for us this issue definitely raised the importance of measuring early and will try and run the same benchmarks we setup for .NET 10 on all the previews going forward.

**Comment by richlander** [comment]
We'll ensure this issus is rel-noted for GA.

**Comment by mangod9** [comment]
the fix for improving type loads has been ported to 10: https://github.com/dotnet/runtime/pull/120712, so should be included in 10.0.2 servicing release.
