### ISSUE TITLE
Could not load content for githubusercontent

### ISSUE THREAD

**Issue by Vizual-Dev** [dotnet/runtime#121804]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Since upgrading to Visual Studio 2026 and .NET 10 I have started to receive a number of "Could not load content..." errors in the browser.

For example:

Could not load content for https://raw.githubusercontent.com/dotnet/runtime/b0f34d51fccc69fd334253924abd8d6853fad7aa/src/mono/browser/runtime/debug.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

The **Sources** tab in the browser shows:

<img width="1693" height="407" alt="Image" src="https://github.com/user-attachments/assets/21fb1f29-57db-4664-b114-0fbd50450332" />

I have tried cleareing the cache and done a hard refresh, updating the .NET workloads, and even installed the .NET 10.0 WebAssembly Build Tools but I still receive the errors. 

Is it possible I have missed a step in the upgrade?

**Comment by dave-gcv** [comment]
I am also experiencing this error after upgrading a Blazor project from .NET9 to .NET10.

The effect it has is when i'm starting the Blazor App (Server + Client) in debug mode via Visual Studio it's taking ages for the app to load.  It eventually becomes responsive after the request to `debug.ts` fails.

What I find odd however is that if I create a brand new Blazor project (Auto render mode) this request never gets called - there is no reference to any raw.githubusercontent.com content at all.

This makes me think there's a missing step in the upgrade process

**Comment by jeffputz** [comment]
Same, and because the OP didn't explicitly say it, this is for debugging .net10 Blazor.

**Comment by akoeplinger** [comment]
This is because we switched to building .NET inside of the VMR repo (https://github.com/dotnet/dotnet) in .NET 10 and so this URL for the source map needs to be updated: https://github.com/dotnet/runtime/blob/928eb5fd02d066bfeada8d58547cac48baebe78a/src/mono/browser/runtime/rollup.config.js#L134

**Comment by pavelsavara** [comment]
And this one too 

https://github.com/dotnet/runtime/blob/928eb5fd02d066bfeada8d58547cac48baebe78a/src/native/rollup.config.plugins.js#L148

**Comment by akoeplinger** [comment]
I opened the backport for 10.0 in #121926, currently tracking the 10.0.2 release

**Comment by dave-gcv** [comment]
Despite this ticket being closed off I am still seeing the issue with unreachable githubusercontent requests.. are further steps required?

**Comment by cyconx** [comment]
@dave-gcv I am just a customer, however from reading through the dotnet repo in Github I believe this issue has been resolved in release 10.0.102 - see line 134 here [https://github.com/dotnet/dotnet/blob/release/10.0.102/src/runtime/src/mono/browser/runtime/rollup.config.js](https://github.com/dotnet/dotnet/blob/release/10.0.102/src/runtime/src/mono/browser/runtime/rollup.config.js)

Like you I am waiting for this fix, andI am not sure how to load this version as the official version is currently 101 [https://dotnet.microsoft.com/en-us/download/dotnet/10.0](https://dotnet.microsoft.com/en-us/download/dotnet/10.0). I suspect we will need to be patient for a little while longer...

Perhaps someone from the MS team could confirm?

**Comment by dave-gcv** [comment]
I've updated to the latest runtime and sdk (10.0.2 / 10.0.102) after it's release today and also to the latest release fof VS 2026 and this problem still persists.

<img width="1402" height="111" alt="Image" src="https://github.com/user-attachments/assets/0e6a246d-534e-4506-ad39-31dbb030d49e" />

**Comment by martinfletchersustainware** [comment]
We are also experiencing this issue...

**Comment by Vizual-Dev** [comment]
Still waiting for a fix. This is a real pain when debugging.

**Comment by akoeplinger** [comment]
@cyconx I understand that you can't share the full repo, but which URL are you seeing in the sourcemap?

**Comment by dave-gcv** [comment]
> [@dave-gcv](https://github.com/dave-gcv) try updating the workload separately.

Cheers.. This seems to have addressed my issue too.

**Comment by cyconx** [comment]
It says `workload-set`
