### ISSUE TITLE
System.Private.CoreLib assembly missing `NeutralResourcesLanguage("en-US")`

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#13507]
See https://github.com/dotnet/coreclr/issues/26472#issuecomment-536176848

Appears to be a regression in 3.0.  Not sure if this is intentional or not, but it does seem to be observable.

/cc @tarekgh

**Comment by buyaa-n** [comment]
@tarekgh is this fixed in 3.1? Or do we have to fix this for 5.0?

**Comment by ericstj** [comment]
We should first fix in 5.0 then backport via servicing if we need it.  I checked and we're still missing this attribute in 5.0.

**Comment by ericstj** [comment]
I think you can fix this by adding an entry here:
https://github.com/dotnet/runtime/blob/200b197559fc49f91b8db3f20fd6df6b5660d7bf/eng/versioning.targets#L56

Something like:
```
      <AssemblyAttribute Include="System.Resources.NeutralResourcesLanguage">
        <_Parameter1>en-US</_Parameter1>
      </AssemblyAttribute>
```

**Comment by tarekgh** [comment]
I checked and I am seeing this is not fixed either in 3.x nor 5.0. I agree we should fix it for 5.0.

@buyaa-n do you want to submit a PR for that? U can do it if you don't have cycles.

**Comment by buyaa-n** [comment]
Thanks for looking @ericstj , @tarekgh, unfortunately i am a bit tight with the analyzers, please fix it if you have capacity

**Comment by tarekgh** [comment]
I'll try to get this soon as @ericstj suggestion should be simple.

**Comment by tarekgh** [comment]
@ericstj I tried your suggestion and worked very well. The only thing is it didn't work for the corelib. do you know how we can add this attribute there? I hope we'll not need any change from the build tools.

**Comment by ericstj** [comment]
CoreLib doesn't include Versioning.targets it seems.  Only libraries build does.  It looks like SPC had decided to define such attributes directly:
https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Internal.cs
https://github.com/dotnet/runtime/blob/master/src/mono/netcore/System.Private.CoreLib/src/System/Internal.cs

So I'd imagine we just add to those files.
