### ISSUE TITLE
Checked / debug Crossgen2 fails building 8 framework assemblies due to a JIT assert

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#1777]
FYI @AndyAyersMS - I suspect this is related to

https://github.com/dotnet/runtime/pull/1593

that added the assert in question at

https://github.com/dotnet/runtime/blob/5182dadd4a5ea7e1d769322e845349088f06e9a2/src/coreclr/src/jit/codegencommon.cpp#L1379

We can see in the runtime-coreclr crossgen2 pipeline result history,

https://dev.azure.com/dnceng/public/_build?definitionId=674&_a=summary

that in the run before @GrabYourPitchforks' commit of the  GetArrayDataReference mop-up change (that broke System.Private.Corelib crossgenning) just a handful of tests failed:

https://dev.azure.com/dnceng/public/_build/results?buildId=475696&view=results

After Levi's commit, we started failing the SPC build in

https://dev.azure.com/dnceng/public/_build/results?buildId=478729&view=logs&j=6fdf90ec-154e-5293-972c-dfc4f172f2aa&t=871c2e7e-c1a2-56bc-b778-cc1c296911b3

In the latest runs, we're failing 7 assemblies:

  System.Net.WebHeaderCollection.dll
  System.Net.HttpListener.dll
  System.Text.Encodings.Web.dll
  System.Private.Uri.dll
  System.Text.RegularExpressions.dll
  System.Text.Json.dll
  System.Private.CoreLib.dll

[I have a fix for the SPC crossgen failure related to Levi's change but it seems to be also hitting the assert.]

/cc: @dotnet/crossgen-contrib

**Comment by trylek** [comment]
<pre>
 	KernelBase.dll!00007ff93ee80192()	Unknown
>	clrjitilc.dll!assertAbort(const char * why, const char * file, unsigned int line) Line 310	C++
 	clrjitilc.dll!CodeGen::genCreateAddrMode(GenTree * addr, bool fold, bool * revPtr, GenTree * * rv1Ptr, GenTree * * rv2Ptr, unsigned int * mulPtr, __int64 * cnsPtr) Line 1379	C++
 	clrjitilc.dll!Compiler::gtMarkAddrMode(GenTree * addr, int * pCostEx, int * pCostSz, var_types type) Line 2875	C++
 	clrjitilc.dll!Compiler::gtSetEvalOrder(GenTree * tree) Line 3744	C++
 	clrjitilc.dll!Compiler::gtSetEvalOrder(GenTree * tree) Line 3893	C++
 	clrjitilc.dll!Compiler::gtSetEvalOrder(GenTree * tree) Line 3491	C++
 	clrjitilc.dll!Compiler::gtSetStmtInfo(Statement * stmt) Line 1320	C++
 	clrjitilc.dll!Compiler::fgFindOperOrder() Line 9657	C++
 	clrjitilc.dll!Compiler::compCompile(void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 4387	C++
 	clrjitilc.dll!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags, CorInfoInstantiationVerification instVerInfo) Line 5808	C++
 	clrjitilc.dll!`Compiler::compCompile'::`50'::__Body::Run(Compiler::compCompile::__l2::__JITParam * __JITpParam) Line 5119	C++
 	clrjitilc.dll!Compiler::compCompile(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 5123	C++
 	clrjitilc.dll!``jitNativeCode'::`8'::__Body::Run'::`6'::__Body::Run(jitNativeCode::__l8::__Body::Run::__l5::__JITParam * __JITpParam) Line 6446	C++
 	clrjitilc.dll!`jitNativeCode'::`8'::__Body::Run(jitNativeCode::__l2::__JITParam * __JITpParam) Line 6450	C++
 	clrjitilc.dll!jitNativeCode(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags, void * inlineInfoPtr) Line 6474	C++
 	clrjitilc.dll!CILJit::compileMethod(ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, unsigned int flags, unsigned char * * entryAddress, unsigned long * nativeSizeOfCode) Line 320	C++
 	jitinterface.dll!JitCompileMethod(CorInfoException * * ppException, Jit * pJit, void * thisHandle, void * * callbacks, void * methodInfo, unsigned int flags, void * entryAddress, void * nativeSizeOfCode) Line 88	C++
 	[Managed to Native Transition]	
 	ILCompiler.ReadyToRun.dll!Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode methodCodeNodeNeedingCode, Internal.IL.MethodIL methodIL) Line 186	C#
 	ILCompiler.ReadyToRun.dll!Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.IReadyToRunMethodCodeNode methodCodeNodeNeedingCode) Line 215	C#
</pre>

MethodBeingCompiled: [System.Drawing.Primitives]System.Drawing.KnownColorTable.GetSystemColorId(KnownColor)

<pre>
  .method private hidebysig static int32 
          GetSystemColorId(valuetype System.Drawing.KnownColor color) cil managed
  {
    // 
    .maxstack  3
    .locals (valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> V_0)
    IL_0000:  ldarg.0
    IL_0001:  ldc.i4.s   27
    IL_0003:  blt.s      IL_001e

    IL_0005:  call       valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> System.Drawing.KnownColorTable::get_SystemColorIdTable()
    IL_000a:  stloc.0
    IL_000b:  ldloca.s   V_0
    IL_000d:  ldarg.0
    IL_000e:  ldc.i4     0xa8
    IL_0013:  sub
    IL_0014:  ldc.i4.s   26
    IL_0016:  add
    IL_0017:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_001c:  ldind.u1
    IL_001d:  ret

    IL_001e:  call       valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> System.Drawing.KnownColorTable::get_SystemColorIdTable()
    IL_0023:  stloc.0
    IL_0024:  ldloca.s   V_0
    IL_0026:  ldarg.0
    IL_0027:  ldc.i4.1
    IL_0028:  sub
    IL_0029:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_002e:  ldind.u1
    IL_002f:  ret
  } // end of method KnownColorTable::GetSystemColorId
</pre>

**Comment by trylek** [comment]
I have uploaded the NgenDump at

\\clrmain\public\writable\users\trylek\cpaot\sdp.ngendump

- sorry, don't know how to publish this for non-Microsoftees, I am reluctant to paste the 300K file in this thread.

**Comment by trylek** [comment]
OK, JanV has just taught me how to upload the dump as a "gist":

https://gist.github.com/trylek/0df9adf8e51b52f891b2f3dcef0656d8

**Comment by janvorli** [comment]
@AndyAyersMS I've used git bisect to find the offending commit and it was the #1309 change of yours:

**Comment by AndyAyersMS** [comment]
This should be getting blocked by code in #1309
```
Assertion prop in BB12:
Constant Assertion: V15 == [00000000004205D0] index=#01, mask=0000000000000001
               [000211] ------------              *  CNS_INT(h) long   0x4205D0 static
```
but earlier we've typed it as BYREF so it is probably getting past the block.
```
fgMorphTree BB12, STMT00024 (before)
               [000143] -AC---------              *  ASG       byref 
               [000142] D------N----              +--*  LCL_VAR   byref  V15 tmp13        
               [000163] ------------              \--*  CNS_INT(h) byref  0x4205D0 static Fseq[5BA88E4D75E602A110836E9E38358016215A1533AE7CED3DFB2B8D2403F7D1C3]
```

**Comment by AndyAyersMS** [comment]
I think this should fix it.. I'll work up an actual PR but if you can test this quickly, let me know if it works:
```diff
diff --git a/src/coreclr/src/jit/assertionprop.cpp b/src/coreclr/src/jit/assertionprop.cpp
index bcd2021f165..4018209ca6b 100644
--- a/src/coreclr/src/jit/assertionprop.cpp
+++ b/src/coreclr/src/jit/assertionprop.cpp
@@ -1324,7 +1324,7 @@ AssertionIndex Compiler::optCreateAssertion(GenTree*         op1,
                 assert((iconFlags & ~GTF_ICON_HDL_MASK) == 0);
                 assertion.op2.u1.iconFlags = iconFlags;
 #ifdef _TARGET_64BIT_
-                if (op2->AsOp()->gtOp1->TypeGet() == TYP_LONG)
+                if ((op2->AsOp()->gtOp1->TypeGet() == TYP_LONG) || (op2->AsOp()->gtOp1->TypeGet() == TYP_BYREF))
                 {
                     assertion.op2.u1.iconFlags |= 1; // Signify that this is really TYP_LONG
                 }
@@ -1342,7 +1342,7 @@ AssertionIndex Compiler::optCreateAssertion(GenTree*         op1,
                 assert((iconFlags & ~GTF_ICON_HDL_MASK) == 0);
                 assertion.op2.u1.iconFlags = iconFlags;
 #ifdef _TARGET_64BIT_
-                if (op2->TypeGet() == TYP_LONG)
+                if ((op2->TypeGet() == TYP_LONG) || (op2->TypeGet() == TYP_BYREF))
                 {
                     assertion.op2.u1.iconFlags |= 1; // Signify that this is really TYP_LONG
                 }
```

**Comment by janvorli** [comment]
I will give it a try right away and share the result in a minute

**Comment by janvorli** [comment]
Unfortunately it didn't change anything. Still getting 8 failed framework builds.

**Comment by AndyAyersMS** [comment]
Ok, I can repro the failure. Issue is that handles are always classified as O2K_CONST_INT, even on 64 bit targets; their "longness" is tracked separately.

Updated patch:
```diff
diff --git a/src/coreclr/src/jit/assertionprop.cpp b/src/coreclr/src/jit/assertionprop.cpp
index bcd2021f165..6e88e2e23bf 100644
--- a/src/coreclr/src/jit/assertionprop.cpp
+++ b/src/coreclr/src/jit/assertionprop.cpp
@@ -2624,13 +2624,6 @@ GenTree* Compiler::optConstantAssertionProp(AssertionDsc*        curAssertion,

         case O2K_CONST_LONG:

-#ifdef _TARGET_64BIT_
-            // Don't propagate handles if we need to report relocs.
-            if (opts.compReloc && ((curAssertion->op2.u1.iconFlags & GTF_ICON_HDL_MASK) != 0))
-            {
-                return nullptr;
-            }
-#endif
             if (newTree->gtType == TYP_LONG)
             {
                 newTree->ChangeOperConst(GT_CNS_NATIVELONG);
@@ -2646,13 +2639,11 @@ GenTree* Compiler::optConstantAssertionProp(AssertionDsc*        curAssertion,

         case O2K_CONST_INT:

-#ifndef _TARGET_64BIT_
             // Don't propagate handles if we need to report relocs.
             if (opts.compReloc && ((curAssertion->op2.u1.iconFlags & GTF_ICON_HDL_MASK) != 0))
             {
                 return nullptr;
             }
-#endif

             if (curAssertion->op2.u1.iconFlags & GTF_ICON_HDL_MASK)
             {
```
This lets me successfully run crossgen2 on System.Drawing.Primitives and SPC. Will start some broader testing.

**Comment by trylek** [comment]
Great, thanks Andy for the quick update. Please just keep in mind the SPC release build will still fail with the PInvoke issue that needs my pending PR #1762.

**Comment by janvorli** [comment]
Trying the new fix now ...

**Comment by janvorli** [comment]
@AndyAyersMS I can confirm that this fixes the problem.
