### ISSUE TITLE
Some mono files show as modified on Linux even with clean checkout

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#2222]
I guess that it is most likely caused by wrong line endings, as there was a problem recently with the same symptoms caused by that. I get the following output from git status even though my local repo clone is completely clean:
```
        modified:   src/mono/mono/tests/bug-335131.2.cs
        modified:   src/mono/mono/tests/bug-472600.2.cs
        modified:   src/mono/mono/tests/bug-515884.il
        modified:   src/mono/mono/tests/checked.cs
        modified:   src/mono/mono/tests/exiting/appdomain.out
        modified:   src/mono/mono/tests/exiting/delegate-async-exit.out
        modified:   src/mono/mono/tests/exiting/delegate-delegate-exit.out
        modified:   src/mono/mono/tests/exiting/delegate.out
        modified:   src/mono/mono/tests/exiting/finalizer-abort.out
        modified:   src/mono/mono/tests/exiting/finalizer-exit.out
        modified:   src/mono/mono/tests/exiting/main-exit.out
        modified:   src/mono/mono/tests/exiting/main-returns-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background.out
        modified:   src/mono/mono/tests/exiting/main-returns.out
        modified:   src/mono/mono/tests/exiting/subthread-exit.out
        modified:   src/mono/mono/tests/load-missing.il
        modified:   src/mono/mono/tests/metadata-verifier/module.il
        modified:   src/mono/mono/tests/mutexes.cs
        modified:   src/mono/mono/tests/thread4.cs
        modified:   src/mono/mono/tests/verifier/unverifiable_ldobj_with_generic_type_definition.il
        modified:   src/mono/mono/tests/verifier/unverifiable_throw_with_unboxed_generic_argument.il
        modified:   src/mono/msvc/libmonoruntime.targets
        modified:   src/mono/msvc/mono_csharp.vssettings
        modified:   src/mono/msvc/monoposixhelper.def
        modified:   src/mono/msvc/win32.xml
        modified:   src/mono/netcore/sample/AspNetCore/Properties/launchSettings.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.Development.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.json
```
Trying to do `git checkout --` on any of these files has no effect.

**Comment by janvorli** [comment]
@akoeplinger - are you the right one to look into this?

**Comment by akoeplinger** [comment]
Hm I'm not seeing this in a clean Linux Docker container. What's the value of your `core.autocrlf` setting?

**Comment by janvorli** [comment]
I don't have it set to anything, but googling suggests that the default is "false".

**Comment by akoeplinger** [comment]
Ok, can you please share more details about your environment? Linux distro/version, git version etc. And maybe try deleting the checkout and cloning again.

**Comment by janvorli** [comment]
Ubuntu 16.04, git 2.7.4. I did a brand new clone and I have the same issue.

**Comment by akoeplinger** [comment]
Ok I can repro on that environment. It seems to be git version specific since I don't see this issue on Ubuntu 18.04 with git 2.17.1.

It seems to be a bug in git fixed by this: https://github.com/git/git/blob/228f53135a4a41a37b6be8e4d6e2b6153db4a8ed/Documentation/RelNotes/2.10.0.txt#L248-L254

**Comment by janvorli** [comment]
Ok, but it still seems there is something wrong with how the files were checked in. It doesn't happen to other files and I believe we should fix it. I would not like to require that people install a newer git version to fix this. 
I've tried to run `git check-attr -a` on one of the problematic files (one of the .cs files) and then on another .cs file that doesn't have such a problem. Here is the result:
```
git check-attr -a src/mono/mono/tests/bug-335131.2.cs
src/mono/mono/tests/bug-335131.2.cs: diff: csharp
src/mono/mono/tests/bug-335131.2.cs: text: auto
src/mono/mono/tests/bug-335131.2.cs: crlf: unset

git check-attr -a src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeWaitHandle.cs
src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeWaitHandle.cs: diff: csharp
src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeWaitHandle.cs: text: auto
```

So it seems the crlf: unset is causing the problem. I've found that when the attribute is not in the list, it means "unspecified".

I've looked more into it and for most of the files it seems to be caused by the settings in the .gitattributes files. E.g. `src/mono/mono/tests/.gitattributes` specifies all the problematic files with `-crlf`. 

Is this really needed or is it something historical that we can get rid of?

However, it is not true for some of the other files, like `src/mono/msvc/libmonoruntime.targets`. For this one, I've found that it contains a mix of line ending styles (the third line is terminated with CRLF, the rest of the lines just with LF on Linux). And e.g. the src/mono/netcore/sample/AspNetCore/Properties/launchSettings.json contains all CRLF when checked out on my Linux.

**Comment by akoeplinger** [comment]
For the ones with `-crlf` those are most certainly historical artifacts so we can get rid of it if that fixes the issue, same for the mixed line endings.

**Comment by jaredpar** [comment]
I'm still seeing this on a fresh install of Ubuntu 16.04. Full list of affected files is:

```
        modified:   src/mono/mono/arch/arm/arm-wmmx.h
        modified:   src/mono/mono/benchmark/bulkcpy.il
        modified:   src/mono/mono/benchmark/zipmark.cs
        modified:   src/mono/mono/cil/make-opcode-def.xsl
        modified:   src/mono/mono/metadata/normalization-tables.h
        modified:   src/mono/mono/mini/genmdesc.py
        modified:   src/mono/mono/tests/bug-335131.2.cs
        modified:   src/mono/mono/tests/bug-472600.2.cs
        modified:   src/mono/mono/tests/bug-515884.il
        modified:   src/mono/mono/tests/checked.cs
        modified:   src/mono/mono/tests/exiting/appdomain.out
        modified:   src/mono/mono/tests/exiting/delegate-async-exit.out
        modified:   src/mono/mono/tests/exiting/delegate-delegate-exit.out
        modified:   src/mono/mono/tests/exiting/delegate.out
        modified:   src/mono/mono/tests/exiting/finalizer-abort.out
        modified:   src/mono/mono/tests/exiting/finalizer-exit.out
        modified:   src/mono/mono/tests/exiting/main-exit.out
        modified:   src/mono/mono/tests/exiting/main-returns-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background.out
        modified:   src/mono/mono/tests/exiting/main-returns.out
        modified:   src/mono/mono/tests/exiting/subthread-exit.out
        modified:   src/mono/mono/tests/load-missing.il
        modified:   src/mono/mono/tests/metadata-verifier/module.il
        modified:   src/mono/mono/tests/mutexes.cs
        modified:   src/mono/mono/tests/thread4.cs
        modified:   src/mono/mono/tests/verifier/unverifiable_ldobj_with_generic_type_definition.il
        modified:   src/mono/mono/tests/verifier/unverifiable_throw_with_unboxed_generic_argument.il
        modified:   src/mono/msvc/eglib-posix.targets
        modified:   src/mono/msvc/eglib-posix.targets.filters
        modified:   src/mono/msvc/libmonoruntime.targets
        modified:   src/mono/msvc/mono_csharp.vssettings
        modified:   src/mono/msvc/monoposixhelper.def
        modified:   src/mono/msvc/win32.xml
        modified:   src/mono/netcore/sample/AspNetCore/Properties/launchSettings.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.Development.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.json
```

**Comment by jaredpar** [comment]
Followed these instructions and it got me unblocked on Ubuntu 16.04

https://unix.stackexchange.com/a/170831

**Comment by danmosemsft** [comment]
Only one area label at a time please

**Comment by jaykrell** [comment]
I get lots of this problem in the mono repo too.
