### ISSUE TITLE
Create APIs to deal with processing ASCII text (as bytes)

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#28230]
**EDIT**: most up to date proposal can be found here: https://github.com/dotnet/runtime/issues/28230#issuecomment-1330880316

Most recent API review comment: https://github.com/dotnet/runtime/issues/28230#issuecomment-603439786

If you are interested in the original proposal, click "details" below:

<details>

To make @KrzysztofCwalina happy. :)

Networking protocols and parsers in particular use ASCII very frequently - even more so than UTF-8. It would be useful to introduce high-performance APIs that work very specifically on ASCII text without trying to interpret it as UTF-8.

```cs
using System;
using System.Buffers;

/*
 * This work item proposes a new static class for performing operations
 * on byte buffers assumed to contain ASCII text. For the purposes of
 * these APIs, an ASCII byte / char is any value in the range [ 00 .. 7F ], inclusive;
 * and ASCII text is a sequence of such values. Most APIs in this type will
 * treat non-ASCII values as opaque data unless the API description specifies
 * a different behavior.
 *
 * For APIs which take both a source and a destination buffer, the behavior of
 * the method is undefined if the source and destination buffers overlap,
 * unless the API description specifies otherwise. The behavior of all APIs
 * is undefined if another thread mutates the buffers while these APIs are
 * operating on them.
 *
 * All case conversion APIs are culture-unaware.
 */

namespace System.Buffers.Text
{
    public static class Ascii
    {
        // Compares two ASCII buffers for equality, optionally treating [A-Z] and [a-z] as equal.
        // All non-ASCII bytes / chars are compared for pure binary equivalence.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool Equals(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);

        // Compares an ASCII byte buffer and an ASCII char buffer for equality, optionally treating
        // [A-Z] and [a-z] as equal. Returns false if the ASCII byte buffer contains any non-ASCII
        // data or if the char buffer contains any element in the range [ 0080 .. FFFF ], as we
        // wouldn't know what encoding to use to perform the transcode-then-compare operation.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool Equals(ReadOnlySpan<byte> left, string right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, string right);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. All non-ASCII bytes are compared for pure
        // binary equivalence. Returns the index of where the first match is found, else returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. Returns the index of where the first match
        // is found, else returns -1. If the target string contains any non-ASCII chars ([ 0080 .. FFFF ]),
        // the search is assume to have failed, and the method returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOf(ReadOnlySpan<byte> text, string value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, string value);

        // Given a buffer, returns the index of the first element in the buffer which
        // is a non-ASCII byte, or -1 if the buffer is empty or all-ASCII. The bool-
        // returning method is a convenience shortcut to perform the same check.

        public static int GetIndexOfFirstNonAsciiByte(ReadOnlySpan<byte> buffer);
        public static int GetIndexOfFirstNonAsciiChar(ReadOnlySpan<char> buffer);
        public static bool IsAllAscii(ReadOnlySpan<byte> buffer);
        public static bool IsAllAscii(ReadOnlySpan<char> buffer);

        // Returns true iff the provided byte is an ASCII byte; i.e., in the range [ 00 .. 7F ];
        // or if the provided char is in the range [ 0000 .. 007F ].

        public static bool IsAsciiByte(byte value);
        public static bool IsAsciiChar(char value);

        // Copies source to destination, converting [A-Z] -> [a-z] or vice versa during
        // the copy. All values outside [A-Za-z] - including non-ASCII values - are unchanged
        // during the copy.
        //
        // If source.Length <= destination.Length, succeeds and returns source.Length (# bytes copied).
        // If source.Length > destination.Length, returns -1.

        public static int ToLowerInvariant(ReadOnlySpan<byte> source, Span<byte> destination);
        public static int ToLowerInvariant(ReadOnlySpan<char> source, Span<char> destination);
        public static int ToUpperInvariant(ReadOnlySpan<byte> source, Span<byte> destination);
        public static int ToUpperInvariant(ReadOnlySpan<char> source, Span<char> destination);

        // Performs case conversion ([A-Z] -> [a-z] or vice versa) in-place. All values
        // outside [A-Za-z] - including non-ASCII values - are unchanged.

        public static void ToLowerInvariantInPlace(Span<byte> buffer);
        public static void ToLowerInvariantInPlace(Span<char> buffer);
        public static void ToUpperInvariantInPlace(Span<byte> buffer);
        public static void ToUpperInvariantInPlace(Span<char> buffer);

        // Performs case conversion on a single value, converting [A-Z] -> [a-z] or vice versa.
        // All values outside [A-Za-z] - including non-ASCII values - are unchanged.

        public static byte ToLowerInvariant(byte value);
        public static byte ToLowerInvariant(char value);
        public static byte ToUpperInvariant(byte value);
        public static byte ToUpperInvariant(char value);

        // Returns a hash code for the provided buffer suitable for use in a dictionary or
        // other keyed collection. For the OrdinalIgnoreCase method, the values [A-Z] and [a-z]
        // are treated as equivalent during hash code computation. All non-ASCII values
        // are treated as opaque data. The hash code is randomized but is not guaranteed to
        // implement any particular algorithm, nor is it guaranteed to be a member of the same
        // PRF family as other GetHashCode routines in the framework.

        public static int GetHashCode(ReadOnlySpan<byte> buffer);
        public static int GetHashCode(ReadOnlySpan<char> buffer);
        public static int GetHashCodeOrdinalIgnoreCase(ReadOnlySpan<byte> buffer);
        public static int GetHashCodeOrdinalIgnoreCase(ReadOnlySpan<char> buffer);

        // Widens an ASCII buffer to UTF-16 or narrows a UTF-16 buffer to ASCII.
        // Returns OperationStatus.InvalidData if the source buffer contains a non-ASCII byte
        // or a char in the range [ 0080 .. FFFF ].
        // OPEN QUESTION: Should we have an equivalent with Latin-1 semantics? Probably doesn't
        // belong on the ASCII class if we do that.

        public static OperationStatus WidenToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int bytesRead, out int charsWritten);
        public static OperationStatus NarrowFromUTf16(ReadOnlySpan<char> source, Span<byte> destination, out int charsRead, out int bytesWritten);

        // Widens the provided buffer to UTF-16, then returns a new string instance from it.
        // Throws ArgumentException if the buffer contains non-ASCII data. If the desired behavior
        // is character substitution instead of throwing an exception, consider instead using
        // Encoding.ASCII.GetString.        

        public static string ToString(ReadOnlySpan<byte> buffer);

        // Trims only ASCII whitespace values from the buffer, returning the trimmed buffer.

        public static ReadOnlySpan<byte> Trim(ReadOnlySpan<byte> buffer);
        public static ReadOnlySpan<char> Trim(ReadOnlySpan<char> buffer);
        public static ReadOnlySpan<byte> TrimStart(ReadOnlySpan<byte> buffer);
        public static ReadOnlySpan<char> TrimStart(ReadOnlySpan<char> buffer);
        public static ReadOnlySpan<byte> TrimEnd(ReadOnlySpan<byte> buffer);
        public static ReadOnlySpan<char> TrimEnd(ReadOnlySpan<char> buffer);

        // Similar to Trim, but returns the Range of the untrimmed data. Useful for
        // scenarios where the resulting ROS<byte> needs to be mapped back to some
        // container data structure.
        // Example: Assume ROM<byte> mem = GetSomeAsciiData();
        // Then ROM<byte> trimmed = mem[Ascii.GetTrimmedRange(mem.Span)];

        public static Range GetTrimmedRange(ReadOnlySpan<byte> buffer);
        public static Range GetTrimmedRange(ReadOnlySpan<char> buffer);
    }
}
```

</details>

**Comment by terrajobst** [comment]
* Should this be `System.Text.Unicode`? Seems odd to have `Ascii` and `Utf8` in different namespaces.
* We called it `EqualsIgnoreCase` because `Ordinal` doesn't add a lot and ASCII is well-defined.
* We think `searchSpace` and `target` are odd choices. We settled on `text` and `value`.
* It seems there is a different behavior for values larger than `127`. Are we sure that's the right behavior?

```C#
namespace System.Buffers.Text
{
    public static class Ascii
    {
        // Compares two ASCII buffers for equality, optionally treating [A-Z] and [a-z] as equal.
        // All non-ASCII bytes are compared for pure binary equivalence.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);

        // Compares an ASCII byte buffer and an ASCII char buffer for equality, optionally treating
        // [A-Z] and [a-z] as equal. Returns false if the ASCII byte buffer contains any non-ASCII
        // data or if the char buffer contains any element in the range [ 0080 .. FFFF ], as we
        // wouldn't know what encoding to use to perform the transcode-then-compare operation.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool Equals(ReadOnlySpan<byte> left, string right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, string right);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. All non-ASCII bytes are compared for pure
        // binary equivalence. Returns the index of where the first match is found, else returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. Returns the index of where the first match
        // is found, else returns -1. If the target string contains any non-ASCII chars ([ 0080 .. FFFF ]),
        // the search is assume to have failed, and the method returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOf(ReadOnlySpan<byte> text, string value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, string value);
    }
}
```

**Comment by scalablecory** [comment]
in HTTP code we could make use of:

```c#
public static int ToLowerInvariant(ReadOnlySpan<char> source, Span<byte> destination);
public static int ToUpperInvariant(ReadOnlySpan<char> source, Span<byte> destination);
```

@GrabYourPitchforks, do you think this is reasonable to add here?

**Comment by GrabYourPitchforks** [comment]
@scalablecory seems reasonable. What do you expect the behavior to be when non-ASCII data is encountered?

**Comment by scalablecory** [comment]
@GrabYourPitchforks throw, or perhaps change signature to Try pattern.

**Comment by scalablecory** [comment]
Here are some examples:

## char -> lowercase byte, unvalidated truncate to 8 bits
https://github.com/dotnet/runtime/blob/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12/src/libraries/Common/src/System/Net/Http/aspnetcore/Http2/Hpack/HPackEncoder.cs#L130-L166

## char -> lowercase byte, pre-validated as ASCII
https://github.com/dotnet/runtime/blob/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12/src/libraries/Common/src/System/Net/Http/aspnetcore/Http2/Hpack/HPackEncoder.cs#L336-L371
https://github.com/dotnet/runtime/blob/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12/src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs#L265-L296

## char-> byte, throw when non-ASCII
https://github.com/dotnet/runtime/blob/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12/src/libraries/Common/src/System/Net/Http/aspnetcore/Http2/Hpack/HPackEncoder.cs#L373-L394
https://github.com/dotnet/runtime/blob/9dec6ae2ea81d46884bf49d2df8b26cc1e28eb12/src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs#L248-L263

## compare byte/byte, case-insensitive, unvalidated
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Http/src/System/Net/Http/ByteArrayHelpers.cs#L11-L41

## compare byte/byte, unvalidated, one argument is pre-lowercased
https://github.com/scalablecory/runtime/blob/1ecb01d4fec2160348fcd95afb84453b0a7a2e11/src/libraries/System.Net.Http/src/System/Net/Http/Primitives/Http11Connection.cs#L608-L628

**Comment by terrajobst** [comment]
@GrabYourPitchforks I incorrectly marked this as blocked (instead of blocking). If this this ready for review and it blocks you, we should remove blocked.

**Comment by terrajobst** [comment]
* `Equals` ignores non-ASCII characters. Should it return `false` or even throw?
* `IndexOf` et. al. should return `-1` if the "needle" contains non-ASCII characters; it's acceptable to return a successful match if the "needle" is found in the "haystack" and the haystack has non-ASCII anywhere (to the left or right of the match). IOW, only the "needle" is validated, not the "haystack".
* It seems a bit odd that some APIs have both `ReadOnlySpan<char>` and `string` and some only have `ReadOnlySpan<char>`. We should make it consistent.
* `IsAllAscii`, `IsAsciiChar`, `IsAsciiByte` should be an overloaded `IsAscii` method
* We should drop `Invariant` suffix (for the same reason we dropped `Ordinal`, it's all ASCII here)
* `ToLower()` / `ToUpper()` should throw when destination is too small (returning the `int` is still fine)
* `GetHashCodeOrdinalIgnoreCase()` should be `GetHashCodeIgnoreCase()`
* `ToString()` should be dropped in favor of `Encoding.Ascii.GetString()`
* `Trim`, `TrimStart`, `TrimEnd` should return `Range` so that callers can do the right thing
* `GetTrimmedRange()` suggest that it returns the whitespace
* Several parameters were renamed from `buffer` to `value`

```C#
namespace System.Buffers.Text
{
    public static class Ascii
    {
        // Compares two ASCII buffers for equality, optionally treating [A-Z] and [a-z] as equal.
        // All non-ASCII bytes / chars are compared for pure binary equivalence.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool Equals(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);

        // Compares an ASCII byte buffer and an ASCII char buffer for equality, optionally treating
        // [A-Z] and [a-z] as equal. Returns false if the ASCII byte buffer contains any non-ASCII
        // data or if the char buffer contains any element in the range [ 0080 .. FFFF ], as we
        // wouldn't know what encoding to use to perform the transcode-then-compare operation.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool Equals(ReadOnlySpan<byte> left, string right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, string right);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. All non-ASCII bytes are compared for pure
        // binary equivalence. Returns the index of where the first match is found, else returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);

        // Searches for the first occurrence of the target substring within the search space,
        // optionally treating [A-Z] and [a-z] as equal. Returns the index of where the first match
        // is found, else returns -1. If the target string contains any non-ASCII chars ([ 0080 .. FFFF ]),
        // the search is assume to have failed, and the method returns -1.
        // ADDENDUM: Also assume there are *Last equivalents of the following.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOf(ReadOnlySpan<byte> text, string value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, string value);

        // Given a buffer, returns the index of the first element in the buffer which
        // is a non-ASCII byte, or -1 if the buffer is empty or all-ASCII. The bool-
        // returning method is a convenience shortcut to perform the same check.

        public static int GetIndexOfFirstNonAsciiByte(ReadOnlySpan<byte> buffer);
        public static int GetIndexOfFirstNonAsciiChar(ReadOnlySpan<char> buffer);
        public static bool IsAscii(ReadOnlySpan<byte> value);
        public static bool IsAscii(ReadOnlySpan<char> value);

        // Returns true iff the provided byte is an ASCII byte; i.e., in the range [ 00 .. 7F ];
        // or if the provided char is in the range [ 0000 .. 007F ].

        public static bool IsAscii(byte value);
        public static bool IsAscii(char value);

        // Copies source to destination, converting [A-Z] -> [a-z] or vice versa during
        // the copy. All values outside [A-Za-z] - including non-ASCII values - are unchanged
        // during the copy.
        //
        // If source.Length <= destination.Length, succeeds and returns source.Length (# bytes copied).
        // If source.Length > destination.Length, returns -1.

        public static int ToLower(ReadOnlySpan<byte> source, Span<byte> destination);
        public static int ToLower(ReadOnlySpan<char> source, Span<char> destination);
        public static int ToUpper(ReadOnlySpan<byte> source, Span<byte> destination);
        public static int ToUpper(ReadOnlySpan<char> source, Span<char> destination);

        // Performs case conversion ([A-Z] -> [a-z] or vice versa) in-place. All values
        // outside [A-Za-z] - including non-ASCII values - are unchanged.

        public static void ToLowerInPlace(Span<byte> value);
        public static void ToLowerInPlace(Span<char> value);
        public static void ToUpperInPlace(Span<byte> value);
        public static void ToUpperInPlace(Span<char> value);

        // Performs case conversion on a single value, converting [A-Z] -> [a-z] or vice versa.
        // All values outside [A-Za-z] - including non-ASCII values - are unchanged.

        public static byte ToLower(byte value);
        public static byte ToLower(char value);
        public static byte ToUpper(byte value);
        public static byte ToUpper(char value);

        // Returns a hash code for the provided buffer suitable for use in a dictionary or
        // other keyed collection. For the OrdinalIgnoreCase method, the values [A-Z] and [a-z]
        // are treated as equivalent during hash code computation. All non-ASCII values
        // are treated as opaque data. The hash code is randomized but is not guaranteed to
        // implement any particular algorithm, nor is it guaranteed to be a member of the same
        // PRF family as other GetHashCode routines in the framework.

        public static int GetHashCode(ReadOnlySpan<byte> value);
        public static int GetHashCode(ReadOnlySpan<char> value);
        public static int GetHashCodeIgnoreCase(ReadOnlySpan<byte> value);
        public static int GetHashCodeIgnoreCase(ReadOnlySpan<char> value);

        // Widens an ASCII buffer to UTF-16 or narrows a UTF-16 buffer to ASCII.
        // Returns OperationStatus.InvalidData if the source buffer contains a non-ASCII byte
        // or a char in the range [ 0080 .. FFFF ].
        // OPEN QUESTION: Should we have an equivalent with Latin-1 semantics? Probably doesn't
        // belong on the ASCII class if we do that.

        public static OperationStatus WidenToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int bytesConsumed, out int charsWritten);
        public static OperationStatus NarrowFromUTf16(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);

        // Trims only ASCII whitespace values from the buffer, returning the trimmed buffer.

        public static Range Trim(ReadOnlySpan<byte> value);
        public static Range Trim(ReadOnlySpan<char> value);
        public static Range TrimStart(ReadOnlySpan<byte> value);
        public static Range TrimStart(ReadOnlySpan<char> value);
        public static Range TrimEnd(ReadOnlySpan<byte> value);
        public static Range TrimEnd(ReadOnlySpan<char> value);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
Follow-up for self: Should we make guarantees about when inputs contain Latin-1 (non-ASCII) data? For example, with things like `Equals` and `GetHashCode`? At minimum we should consider the long term consequences of the current proposed behavior of treating everything as not-equal.

**Comment by GrabYourPitchforks** [comment]
Was thinking a bit more on the consequences of `Equals` always returning _false_ when comparing non-ASCII data. There is a potential pit of failure here. If you're using ASCII buffers as keys in a dictionary (a scenario we enable through the existence of `GetHashCode` routines), then this opens the door that the dictionary could be flooded with keys that appear to be equal but where `ContainsKey` always returns _false_.

One way to work around this would be for both `Equals` and `GetHashCode` to fail (with an exception) when they see non-ASCII data. But this becomes very weird, as: (a) I expect many of these values to be user-provided and I want generally to avoid exceptions during data processing; and (b) nobody ever really expects `Equals` or `GetHashCode` to throw an exception.

This is making me lean toward the original design of having `Equals` skip over non-ASCII characters (that is, require binary equality for non-ASCII characters). This also matches the existing behavior of `string.Equals` or `MemoryExtensions.SequenceEqual(..., StringComparison)` when they see invalid UTF-16 data. In that case, any invalid UTF-16 data between the two strings being compared are checked for binary equivalence, regardless of the `StringComparison` being used.

Thoughts? I know @bartonjs you had opinions on this. But I'm having trouble squaring the desire to "fail" on non-ASCII data with avoiding introducing weird pits of failure.

**Comment by tarekgh** [comment]
Can Equals return enum instead of boolean? I am imagining returning enum values Equal, NonEqual and InvalidNonAscii.

**Comment by GrabYourPitchforks** [comment]
@tarekgh Even if it returned `InvalidNonAscii`, we'd still have the problem I mentioned in my previous comment. Any comparer built on top of this would need to normalize that return value to _false_ or would need to throw an exception, both of which are problematic.

**Comment by scalablecory** [comment]
> This is making me lean toward the original design of having Equals skip over non-ASCII characters (that is, require binary equality for non-ASCII characters)

I'd be comfortable with this behavior if we explicitly state "these are high-perf APIs only for expert use; they don't validate in this list of cases: a,b,c". Maybe call them `EqualsUnsafe`.

Otherwise, I think it is dangerous to just do a byte-wise compare. A Latin-1 string and a UTF-8 string, or even just a Windows-1252 string, might have equal encodings but different code points.

> Was thinking a bit more on the consequences of `Equals` always returning _false_ when comparing non-ASCII data. There is a potential pit of failure here. If you're using ASCII buffers as keys in a dictionary (a scenario we enable through the existence of `GetHashCode` routines), then this opens the door that the dictionary could be flooded with keys that appear to be equal but where `ContainsKey` always returns _false_.

That is indeed a compelling scenario.

> @tarekgh Even if it returned `InvalidNonAscii`, we'd still have the problem I mentioned in my previous comment. Any comparer built on top of this would need to normalize that return value to _false_ or would need to throw an exception, both of which are problematic.

Would an `enum { NonEqual, Equal, EqualNonAscii }` work instead?

A dictionary might choose to accept `EqualNonAscii`, while someone explicitly wanting only ASCII could choose to error out in whichever way is best to them.

**Comment by GrabYourPitchforks** [comment]
> Otherwise, I think it is dangerous to just do a byte-wise compare. A Latin-1 string and a UTF-8 string, or even just a Windows-1252 string, might have equal encodings but different code points.

Yeah, this is also bugging me. :(

On one hand I want to make it difficult to do the wrong thing with these APIs. There is always the chance that somebody is mixing and matching Latin-1 with UTF-8, but I don't think mixing and matching like that would be commonplace. What I think will be more common is for somebody to pass (Latin-1, Latin-1) or (UTF-8, UTF-8) to these APIs. And for these scenarios where the two sides are using the same encoding _with respect to each other_, even if the encoding isn't ASCII, then the proposed behavior of `Equals` falling back to ordinal equality for non-ASCII bytes is actually relatively sane. There are some exceptions. GB18030 comes to mind. But I don't realistically see anybody ever running into that in practice.

Consider the sample below, which shows that the APIs as proposed here will give "better" answers than the normal `Encoding` APIs for certain inputs.

```cs
byte[] input1 = new byte[] { 0x60, 0xC0, 0xC0 };
byte[] input2 = new byte[] { 0x60, 0xD0, 0xD0 };

Console.WriteLine(input1.SequenceEquals(input2)); // prints False
Console.WriteLine(Ascii.Equals(input1, input2)); // prints False
Console.WriteLine(Encoding.ASCII.GetString(input1) == Encoding.ASCII.GetString(input2)); // prints True
Console.WriteLine(Encoding.UTF8.GetString(input1) == Encoding.UTF8.GetString(input2)); // prints True
```

Though if you're working with UTF-8 data specifically, I'd strongly recommend that you use the APIs on `Utf8String` or `Utf8Span` than these APIs. Those APIs are meant specifically for UTF-8 data.

**Comment by GrabYourPitchforks** [comment]
Taking another stab at this, based on things we've learned over the past few years and feedback received via this forum, API reviews, and email.

### High-level summary of changes

__The APIs are now more eager to fail when they see non-ASCII data.__

This deserves a bit of exposition since there are conflicting goals of "the API shouldn't try to allow data it doesn't understand" vs. "the API is going to be used in networking scenarios and needs to handle anything thrown at it."

The typical use case for networking scenarios is going to be performing a check against a literal value, e.g.,

```cs
byte[] networkBuffer = GetSomeRawData();
if (Ascii.StartsWithIgnoreCase(networkBuffer, "HELLO "u8))
{
    DoSomethingWith(networkBuffer.Slice(6));
}
```

The way this works philosophically is that the needle is turned into the structure `{ [Hh] [Ee] [Ll] [Ll] [Oo] [<space>] }`, where we're building up a list of which ASCII values map to individual elements within the needle. And it's ok to compare this against a haystack that contains non-ASCII values, since the needle will simply never be found in those portions of the haystack.

However, we can't create this map if the _needle_ itself contains non-ASCII values. If we see a non-ASCII element such as `[ 80 ]` in the needle, we don't know which values map to it. _We don't even know if `[ 80 ]` maps to itself._ It's simply outside the range of what we're able to understand, and so we must fail the operation with an `ArgumentException`.

This should also satisfy the scenario of allowing the haystack to contain arbitrary network data without an exception being thrown.

Now, on to `Equals[IgnoreCase]`, which doesn't have a concept of a needle \& haystack and instead just takes two buffers. This is somewhat similar, since we're in spirit going element-by-element and seeing if the elements match between the two buffers. There are two interesting cases to consider: when we attempt to compare an ASCII element to a non-ASCII element; and when we attempt to compare two non-ASCII elements.

In the case of comparing ASCII to non-ASCII, we can say that the comparison returns _not equal_ without error. The domain and range for all ASCII transforms (whether it be the identity transform or a case-mapping transform) are equivalent: you start with an element in the domain `[ 00 .. 7F ]`, and you get an element in the range `[ 00 .. 7F ]`. So if we see a non-ASCII value, we know that no ASCII transform can ever result in it, nor can any ASCII transform ever convert the non-ASCII value back into an ASCII value. So we don't even need to run the transforms. We just say "they're not even compatible" and move on.

However, that same claim cannot be made when comparing two non-ASCII elements against one another. We don't know how to run transforms over non-ASCII data, and even if we did, we wouldn't know how to determine equality. Is bitwise equality appropriate? We don't know: the only thing we were programmed to understand is ASCII data.

> For a thought experiment, consider the two methods below.
> ```cs
> bool EqualsX(bool a, bool b) => a == b;
> bool EqualsY(bool a, bool b) => a ^ !b;
> ```
> The truth table for both methods is the same: `TT -> T`; `FF -> T`; `TF -> F`; `FT -> F`. What happens when you instead pass `5` and `6`? Do the two methods behave identically?

__The `SequenceEquals`-equivalent APIs were removed.__

Just use `SequenceEquals`.

__`ToUpper` and `ToLower` signatures changes considerably.__

The overloads that took individual bytes / chars were removed since there wasn't a strong reason to have them. Almost every other API on this type deals with buffers, not individual elements. We can add them later if there's demand.

The remaining overloads became `OperationStatus`-based or try-based to better indicate that they might not be able to complete. The typical reason for this would be that there's data which cannot be processed. In both cases, the caller receives an indication of where processing ended and can perform whatever fixup they need before continuing.

There are also `Span<char> <-> Span<byte>` APIs for case conversion, since it came up a few times from the networking team that they had such scenarios.

__`GetHashCode` is also a try-based API.__

This solves the problem of somebody trying to put non-ASCII text into a dictionary using these APIs as the workhorse for a comparer routine. Simply don't allow it, and force the comparer to implement their own appropriate fallback.

__`ToUtf16` and `FromUtf16` names changed.__

Dropped the _Widen_ and _Narrow_ prefix, since there's more going on than a simple widening / narrowing operation. Keeping the prefixes could give the wrong impression of what's taking place. The `ToUtf16` and `FromUtf16` method names in this new proposal match what's on the existing `Utf8` type.

### Modified API

```cs
/*
 * This work item proposes a new static class for performing operations
 * on byte buffers assumed to contain ASCII text. For the purposes of
 * these APIs, an ASCII byte / char is any value in the range [ 00 .. 7F ], inclusive;
 * and ASCII text is a sequence of such values.
 *
 * When comparing two buffers for equality, unless short-circuiting has caused
 * the method to return false, an element-by-element comparison will take place
 * utilizing the following logic:
 *
 * - If both elements are ASCII...
 *   ... and are equivalent, continue looping.
 *   ... and are not equivalent, return false eagerly.
 * - If only one element is ASCII, return false eagerly.
 * - If neither element is ASCII, fail with an exception.
 *
 * The reasoning behind this is that only ASCII elements are within our understood
 * domain, and when we transform them they become other ASCII elements. We can
 * easily compare two ASCII elements against one another. Additionally, since
 * we know that ASCII elements can never transform into non-ASCII objects, any
 * comparison of ASCII against non-ASCII should return not equal. However, we don't
 * know how to transform a non-ASCII element, so we cannot perform any meaningful
 * comparison between two non-ASCII elements.
 * If ever we are asked to compare two non-ASCII elements, we fail with a usage error.
 *
 * For APIs which take both a source and a destination buffer, the method
 * will throw an exception if the source and destination buffers overlap.
 *
 * All casing-related APIs are ordinal (non-linguistic).
 */

namespace System.Buffers.Text
{
    public static class Ascii
    {
        // Compares an ASCII byte buffer and an ASCII char buffer for value equality.

        public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);

        // Compare two ASCII buffers for value equality, treating [A-Z] and [a-z] as equal.

        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);

        // Searches for the first (last) occurrence of the target substring within the
        // search space, optionally treating [A-Z] and [a-z] as equal.
        // Returns -1 if not found.
        // Throws an exception if the needle contains non-ASCII data.
        // The haystack is allowed to contain non-ASCII data.

        public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static int LastIndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int LastIndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int IndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static int LastIndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static int LastIndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
        public static int LastIndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static int LastIndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        // Given a buffer, determines whether it starts (ends) with the given value,
        // optionally treating [A-Z] and [a-z] as equal.
        // Throws an exception if the needle contains non-ASCII data.
        // The haystack is allowed to contain non-ASCII data.

        public static bool StartsWith(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static bool StartsWith(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static bool EndsWith(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static bool EndsWith(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static bool StartsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static bool StartsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
        public static bool StartsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static bool StartsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        public static bool EndsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
        public static bool EndsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
        public static bool EndsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
        public static bool EndsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

        // Given a buffer, returns the index of the first element in the buffer which
        // is a non-ASCII byte, or -1 if the buffer is empty or all-ASCII. The bool-
        // returning method is a convenience shortcut to perform the same check.

        public static int GetIndexOfFirstNonAsciiByte(ReadOnlySpan<byte> buffer);
        public static int GetIndexOfFirstNonAsciiChar(ReadOnlySpan<char> buffer);
        public static bool IsAscii(ReadOnlySpan<byte> value);
        public static bool IsAscii(ReadOnlySpan<char> value);

        // Returns true iff the provided byte is an ASCII byte; i.e., in the range [ 00 .. 7F ];
        // or if the provided char is in the range [ 0000 .. 007F ].

        public static bool IsAscii(byte value);
        public static bool IsAscii(char value);

        // Copies source to destination, converting [A-Z] <-> [a-z] during the copy.
        // Returns OperationStatus.InvalidData on non-ASCII input.

        public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesConsumed, out int bytesWritten);
        public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<char> destination, out int charsConsumed, out int charsWritten);
        public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<char> destination, out int bytesConsumed, out int charsWritten);
        public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);

        public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesConsumed, out int bytesWritten);
        public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<char> destination, out int charsConsumed, out int charsWritten);
        public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<char> destination, out int bytesConsumed, out int charsWritten);
        public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);

        // Performs case conversion ([A-Z] <-> [a-z]) in-place.
        // Returns true on success, false if any non-ASCII data was found (and stops processing).
        // Always outs the number of elements it was able to convert.

        public static bool TryToUpperInPlace(Span<byte> value, out int bytesProcessed);
        public static bool TryToUpperInPlace(Span<char> value, out int charsProcessed);

        public static bool TryToLowerInPlace(Span<byte> value, out int bytesProcessed);
        public static bool TryToLowerInPlace(Span<char> value, out int charsProcessed);

        // Returns a hash code for the provided buffer suitable for use in a dictionary or
        // other keyed collection, optionally treating [A-Z] and [a-z] as equal.
        // The hash code is randomized and is not guaranteed to match string.GetHashCode
        // or any other public PRF within the framework. The ROS<byte> and ROS<char> overloads
        // will produce the same hash code if Equals[IgnoreCase](ROS<byte>, ROS<char>) returns
        // true. The Try* methods return false (and out 0) if the input is not ASCII;
        // the non-Try* methods throw an exception.

        public static bool TryGetHashCode(ReadOnlySpan<byte> value, out int hashCode);
        public static bool TryGetHashCode(ReadOnlySpan<char> value, out int hashCode);
        public static bool TryGetHashCodeIgnoreCase(ReadOnlySpan<byte> value, out int hashCode);
        public static bool TryGetHashCodeIgnoreCase(ReadOnlySpan<char> value, out int hashCode);

        public static int GetHashCode(ReadOnlySpan<byte> value);
        public static int GetHashCode(ReadOnlySpan<char> value);
        public static int GetHashCodeIgnoreCase(ReadOnlySpan<byte> value);
        public static int GetHashCodeIgnoreCase(ReadOnlySpan<char> value);

        // Widens an ASCII buffer to UTF-16 or narrows a UTF-16 buffer to ASCII.
        // Returns OperationStatus.InvalidData if the source buffer contains a non-ASCII byte
        // or a char in the range [ 0080 .. FFFF ].

        public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int bytesConsumed, out int charsWritten);
        public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);

        // Trims only ASCII whitespace values from the buffer, returning the trimmed buffer.
        // The full set of trimmed values is: U+0009..U+000D and U+0020.
        // All other elements, including non-ASCII elements, are ignored.

        public static Range Trim(ReadOnlySpan<byte> value);
        public static Range Trim(ReadOnlySpan<char> value);
        public static Range TrimStart(ReadOnlySpan<byte> value);
        public static Range TrimStart(ReadOnlySpan<char> value);
        public static Range TrimEnd(ReadOnlySpan<byte> value);
        public static Range TrimEnd(ReadOnlySpan<char> value);
    }
}
```

**Comment by iSazonov** [comment]
>        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
>        public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
>        public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);

Is it intentional to skip one option `public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<byte> right);`?

**Comment by GrabYourPitchforks** [comment]
> > ```
> >    public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
> >    public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
> >    public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);
> > ```
> 
> 
> Is it intentional to skip one option `public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<byte> right);`?

Yes, just swap the parameters at the call site if needed. Equals follows this same pattern.

If it's a usability issue we can add the extra overload.

**Comment by danmoseley** [comment]
Past feature complete date. Moving to future.

**Comment by jeffhandley** [comment]
We are still going to explore possible ways to add some UTF8/ASCII helpers in the .NET RC2/GA timeframe, but until that plan solidifies this issue can sit in 8.0.0.

**Comment by adamsitnik** [comment]
```diff
namespace System.Buffers.Text
{
    public static class Ascii
    {
        // Compares an ASCII byte buffer and an ASCII char buffer for value equality.
        
-       public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
-       public static bool Equals(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
-       public static bool Equals(ReadOnlySpan<byte> left, string right);


-       public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
-       public static int IndexOf(ReadOnlySpan<byte> text, string value);
+       public static int IndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);


-       public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, string value);
+       public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);

-       public static void ToLowerInPlace(Span<byte> value);
+       public static bool TryToUpperInPlace(Span<byte> value, out int bytesProcessed);
-       public static void ToLowerInPlace(Span<char> value);
+       public static bool TryToUpperInPlace(Span<char> value, out int charsProcessed);
-       public static void ToUpperInPlace(Span<byte> value);
+       public static bool TryToLowerInPlace(Span<byte> value, out int bytesProcessed);
-       public static void ToUpperInPlace(Span<char> value);
+       public static bool TryToLowerInPlace(Span<char> value, out int charsProcessed);
        

-        public static OperationStatus WidenToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int bytesConsumed, out int charsWritten);
-        public static OperationStatus NarrowFromUTf16(ReadOnlySpan<char> source, Span<byte> destination, out int charsConsumed, out int bytesWritten);
+        public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
+        public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    }
}
```

**Comment by danmoseley** [comment]
```diff
+       public static int IndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);
+       public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
```
is the difference between these intentional?

**Comment by terrajobst** [comment]
* There is a concern that `System.Buffers.Text` isn't discoverable. Should this be in `System.Text`?
* We need to clarify the behavior for throwing vs returning `false`
    - We don't want behavior that are function of lengths
    - **It's OK** to have APIs where haystack (`text`) is never validated but needle (`value`) is
    - **It's *not* OK** to have an API where the needle is sometimes not validated, e.g. if `if (value.Length > text.Length) return false`.
* The `text` parameter (the haystack) should probably called `source` because in some cases we use it as a binary that contains ASCII but also other data.
* `Equals`
    - Don't throw if either side isn't ASCII, just return `false`
    - We should add these to match `EqualsIgnoreCase`
        + `Equals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right)`
        + `Equals(ReadOnlySpan<char> left, ReadOnlySpan<char> right)`
* We need to be more deliberate about the types we accept. We don't want to duplicated APIs that already exist, such as `SequenceEqual`
* The `ToLowerInPlace` API doesn't follow the standard try-pattern. It should probably use operation status.

Original API:

```C#
namespace System.Buffers.Text;

public static class Ascii
{
    public static bool Equals(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);

    public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
    public static bool EqualsIgnoreCase(ReadOnlySpan<char> left, ReadOnlySpan<char> right);
    public static bool EqualsIgnoreCase(ReadOnlySpan<byte> left, ReadOnlySpan<char> right);

    public static int IndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static int IndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static int LastIndexOf(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static int LastIndexOf(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
    public static int IndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
    public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static int IndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static int LastIndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
    public static int LastIndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
    public static int LastIndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static int LastIndexOfIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static bool StartsWith(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static bool StartsWith(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static bool EndsWith(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static bool EndsWith(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static bool StartsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
    public static bool StartsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
    public static bool StartsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static bool StartsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static bool EndsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value);
    public static bool EndsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<char> value);
    public static bool EndsWithIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<char> value);
    public static bool EndsWithIgnoreCase(ReadOnlySpan<char> text, ReadOnlySpan<byte> value);

    public static int GetIndexOfFirstNonAsciiByte(ReadOnlySpan<byte> buffer);
    public static int GetIndexOfFirstNonAsciiChar(ReadOnlySpan<char> buffer);
    public static bool IsAscii(ReadOnlySpan<byte> value);
    public static bool IsAscii(ReadOnlySpan<char> value);

    public static bool IsAscii(byte value);
    public static bool IsAscii(char value);

    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<byte> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<byte> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static bool TryToUpperInPlace(Span<byte> value, out int bytesProcessed);
    public static bool TryToUpperInPlace(Span<char> value, out int charsProcessed);

    public static bool TryToLowerInPlace(Span<byte> value, out int bytesProcessed);
    public static bool TryToLowerInPlace(Span<char> value, out int charsProcessed);

    public static bool TryGetHashCode(ReadOnlySpan<byte> value, out int hashCode);
    public static bool TryGetHashCode(ReadOnlySpan<char> value, out int hashCode);
    public static bool TryGetHashCodeIgnoreCase(ReadOnlySpan<byte> value, out int hashCode);
    public static bool TryGetHashCodeIgnoreCase(ReadOnlySpan<char> value, out int hashCode);

    public static int GetHashCode(ReadOnlySpan<byte> value);
    public static int GetHashCode(ReadOnlySpan<char> value);
    public static int GetHashCodeIgnoreCase(ReadOnlySpan<byte> value);
    public static int GetHashCodeIgnoreCase(ReadOnlySpan<char> value);

    public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static Range Trim(ReadOnlySpan<byte> value);
    public static Range Trim(ReadOnlySpan<char> value);
    public static Range TrimStart(ReadOnlySpan<byte> value);
    public static Range TrimStart(ReadOnlySpan<char> value);
    public static Range TrimEnd(ReadOnlySpan<byte> value);
    public static Range TrimEnd(ReadOnlySpan<char> value);
}
```

**Comment by adamsitnik** [comment]
To make some progress on #75012 I would like to discuss only a subset of the ASCII APIs. Here is what was changes since last discussion:


```diff
- namespace System.Buffers.Text;
+ namespace System.Text;

public static class Ascii
{
    public static int GetIndexOfFirstNonAsciiByte(ReadOnlySpan<byte> buffer);
    public static int GetIndexOfFirstNonAsciiChar(ReadOnlySpan<char> buffer);
    
-    public static bool IsAscii(ReadOnlySpan<byte> value);
-    public static bool IsAscii(ReadOnlySpan<char> value);

+    public static bool IsValid(ReadOnlySpan<byte> value);
+    public static bool IsValid(ReadOnlySpan<char> value);

-    public static bool IsAscii(byte value);
-    public static bool IsAscii(char value);

+    public static bool IsValid(byte value);
+    public static bool IsValid(char value);

    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<byte> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<byte> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static bool TryToUpperInPlace(Span<byte> value, out int bytesProcessed);
    public static bool TryToUpperInPlace(Span<char> value, out int charsProcessed);

    public static bool TryToLowerInPlace(Span<byte> value, out int bytesProcessed);
    public static bool TryToLowerInPlace(Span<char> value, out int charsProcessed);

    public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
    public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);

    public static Range Trim(ReadOnlySpan<byte> value);
    public static Range Trim(ReadOnlySpan<char> value);
    public static Range TrimStart(ReadOnlySpan<byte> value);
    public static Range TrimStart(ReadOnlySpan<char> value);
    public static Range TrimEnd(ReadOnlySpan<byte> value);
    public static Range TrimEnd(ReadOnlySpan<char> value);
}
```

> There is a concern that `System.Buffers.Text` isn't discoverable. Should this be in `System.Text`?

Very good point, fixed.

> The `ToLowerInPlace` API doesn't follow the standard try-pattern. It should probably use operation status.

`OperationStatus` defines four values:
* `Done` - success.
* `InvalidData` - for ASCII it means that we have found some non-ASCII bytes/characters.
* `DestinationTooSmall` in case of ASCII this is impossible: for valid data the size is always the same, for invalid we would return `InvalidData`.
* `NeedMoreData` same as above

In my opinion, users would be confused if `TryToLowerInPlace/TryToLowerInPlace` were defined as returning `OperationStatus`, but using only `OperationStatus.Done` and `OperationStatus.InvalidData`.

Writing the following code is just more natural and obvious to me:


```cs
if (Ascii.TryToLowerInPlace(buffer, out int cosumed))
{
    // success
}
else
{
    // non-ascii found at index "consumed"
}
```

**Comment by adamsitnik** [comment]
@GrabYourPitchforks @stephentoub while studying ASP.NET code today I've realized that their corresponding helper for `ToUtf16` method treats NULL character (0) as an invalid character:

https://github.com/dotnet/aspnetcore/blob/792e021af928d435276ffdb2149082ea3d8ce9c5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/HttpUtilities.cs#L96-L97

The check if performed here: https://github.com/dotnet/aspnetcore/blob/c4b57c452447f70ab874097436226542c70d74c0/src/Shared/ServerInfrastructure/StringUtilities.cs#L799

So what we have right now in the proposal won't meet their requirements. What is your opinion on extending `ToUtf16` and `FromUtf16` with a boolean parameter that describes how to treat NULL characters?

```diff
-    public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int elementsProcessed);
+    public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, bool allowNullCharacters = true, out int elementsProcessed);
-    public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int elementsProcessed);
+    public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, bool allowNullCharacters = true, out int elementsProcessed);
```

I just want to make sure that they can delete their own copy of `ASCIIUtility` when we introduce the new `Ascii` APIs.

**Comment by gfoidl** [comment]
@adamsitnik in case you missed it: https://github.com/dotnet/aspnetcore/pull/44040#issuecomment-1289517635

**Comment by bartonjs** [comment]
* For the case of an OperationStatus API where Consumed is guaranteed equal to Written we decided to go with omitting Consumed (and documenting the behavior), leaving the naming up to the destination type (for bytesWritten/charsWritten/elementsWritten).
* We discussed, and rejected, adding replacement semantics to the UTF-16->ASCII transformations.

```C#
namespace System.Text;

public static class Ascii
{   
    public static bool IsValid(ReadOnlySpan<byte> value);
    public static bool IsValid(ReadOnlySpan<char> value);

    public static bool IsValid(byte value);
    public static bool IsValid(char value);

    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<char> destination, out int charsWritten);
    public static OperationStatus ToUpper(ReadOnlySpan<byte> source, Span<char> destination, out int charsWritten);
    public static OperationStatus ToUpper(ReadOnlySpan<char> source, Span<byte> destination, out int bytesWritten);

    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesWritten);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<char> destination, out int charsWritten);
    public static OperationStatus ToLower(ReadOnlySpan<byte> source, Span<char> destination, out int charsWritten);
    public static OperationStatus ToLower(ReadOnlySpan<char> source, Span<byte> destination, out int bytesWritten);

    public static OperationStatus ToUpperInPlace(Span<byte> value, out int bytesWritten);
    public static OperationStatus ToUpperInPlace(Span<char> value, out int charsWritten);

    public static OperationStatus ToLowerInPlace(Span<byte> value, out int bytesWritten);
    public static OperationStatus ToLowerInPlace(Span<char> value, out int charsWritten);

    public static OperationStatus ToUtf16(ReadOnlySpan<byte> source, Span<char> destination, out int charsWritten);
    public static OperationStatus FromUtf16(ReadOnlySpan<char> source, Span<byte> destination, out int bytesWritten);

    public static Range Trim(ReadOnlySpan<byte> value);
    public static Range Trim(ReadOnlySpan<char> value);
    public static Range TrimStart(ReadOnlySpan<byte> value);
    public static Range TrimStart(ReadOnlySpan<char> value);
    public static Range TrimEnd(ReadOnlySpan<byte> value);
    public static Range TrimEnd(ReadOnlySpan<char> value);
}
```

**Comment by bartonjs** [comment]
> What do you think about renaming written to processed for the in-place conversions?

The guideline is

> CONSIDER naming an out parameter that reports the number of values
written by a buffer-writing method “bytesWritten,” “charsWritten,” or
“valuesWritten” (as appropriate to the data type).

If you see any existing OperationStatus method that has done something other than "Written" and has a similar justification, then maybe... but "Written" is what the pattern suggests, and it isn't so wrong as to feel like it needs something different.
