### ISSUE TITLE
Console.Clear() doesn't clear the scrollback buffer on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#28355]
[`Console.Clear()`'s documentation](https://docs.microsoft.com/en-us/dotnet/api/system.console.clear?view=netcore-2.2) states (emphasis added):

> _Clears the console buffer_ and corresponding console window of display information.

Indeed, not just clearing the current terminal _window_ (screen), but also the scrollback buffer is the typical use case, and it is how this method has always worked on Windows.<sup>[1]</sup>

By contrast, **the Unix implementation currently only clears the _screen_, which makes for an inconsistent cross-platform experience.**

While there is no POSIX-compliant way to clear the scrollback buffer (only clearing the _screen_ is mandated by POSIX, via `tput clear`), [xterm](https://en.wikipedia.org/wiki/Xterm)-compatible terminal applications do support escape sequence `<esc>[3J` - see [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences).

In practice, the macOS terminal application and the one on Ubuntu, for instance, do support this escape sequence - generally, terminal emulators based on the [X Window System](https://en.wikipedia.org/wiki/X_Window_System).

I don't know if there are popular terminal emulators out there that do _not_ support it, but even a best-effort implementation would be useful.

Here's a workaround that demonstrates use of the escape sequence:

```csharp
// Clears the screen and the scrollback buffer in xterm-compatible terminals.
Console.Clear(); Console.WriteLine("\x1b[3J")
```
---

<sup>[1] Whether there should be an opt-in for predictably clearing _only_ the screen across platforms, while leaving the scrollback buffer intact, is a separate question.</sup>

**Comment by carlossanlop** [comment]
@mkelement0 have you had a chance to continue looking into this?

**Comment by janvorli** [comment]
I understand that the planned change is going to align the behavior with Windows, however, I am not aware of any text mode application on Unix that would clear the scrollback buffer. I myself would consider such a behavior of any application intrusive and unexpected. What are scenarios when clearing the scrollback buffer is beneficial?

**Comment by mklement0** [comment]
My apologies for dropping the ball on this, @danmosemsft , @carlossanlop and @iSazonov  - can you please unassign me? I hope someone else will take this on.

However, it sounds like maybe there isn't consensus yet as to what to do:

@janvorli, I can see how for _programmatic_ (as opposed to _interactive_ use in a _shell_) clearing the scrollback buffer _by default_ could be considered too invasive.

(On re-reading the documentation, it doesn't actually talk about the _scrollback_ buffer, only about the "console buffer", which can justifiably be interpreted to mean the current screen only.)

Even though also clearing the scroll-back buffer is how it has always worked in regular console windows on Windows, I now see that in Windows Terminal it does _not_.

This takes us back to @SteveL-MSFT's [suggestion to make buffer clearing an _opt-in_ via a Boolean parameter](https://github.com/dotnet/runtime/issues/28355#issuecomment-452853751).

We could therefore:

* Introduce the proposed overload, `public static void Clear (bool includeScrollBackBuffer);`

* make that overload work as intended when `false` is passed in regular console windows on Windows too (which I assume is possible)

* leave the current _default_ behavior (parameterless overload: scrollback-buffer-too clearing in Windows console windows, current-screen clearing only on Unix and in Windows Terminals) and _document_ the inconsistency, recommending use of the overload where you signal the intent _explicitly_ going forward

**Comment by danmosemsft** [comment]
To add a new API (rather than simply align behavior) we'd want a bit more evidence of need. What sort of scenario would lead someone to pass "true" ?

**Comment by khellang** [comment]
> What sort of scenario would lead someone to pass "true" ?

I don't have a specific scenario in mind, but from researching this a while back, it seems like quite a few people are interested in clearing the buffer as well. Whether that is programmatically or interactively isn't clear (no pun intended) though. 

On Windows, there's no need as the existing parameterless overload already does clear the buffer. But that overload isn't consistent across platforms. If you want to to be consistent, call the overload with either `true` or `false` and it'll work the same cross-platform 😊

That's the only way I can see this working out and not break everyone relying on the existing behavior.

**Comment by mklement0** [comment]
Good points, @khellang.

When implementing a _shell_ or _REPL_ the feature is of particular interest: often you want to start with a clean slate in a terminal before submitting a new command, so as not to get confused between the most recent command's output and unrelated output that preceded it.

Indeed, it was the desire for consistent cross-platform behavior of PowerShell's `Clear-Host` command that brought us here - https://github.com/PowerShell/PowerShell/issues/8606

While PowerShell could certainly implement the behavior without using `Console.Clear()`, I can see other shells / REPLs benefitting from support in the CLR too.

---

As for native shell / utility behavior:

* On Windows, users of `cmd.exe` (`cls`) and PowerShell (`Clear-Host`, aliased to `cls`) are used to the scrollback-buffer getting cleared, by default and invariably - though, as stated, Windows Terminal will change that experience.

* On Linux, `/usr/bin/clear` is _meant_ to clear the scrollback buffer by default - but still doesn't, as of Ubuntu 18.04, due to the terminal-capabilities database still not having been updated - see https://unix.stackexchange.com/a/375784/54804. Option `-x` is the _opt-out_ that clears the current screen only.

* On macOS, `/usr/bin/clear` was only ever designed to clear the current screen, but the default terminal offers keyboard shortcut <kbd>Command-K</kbd> to clear the scrollback buffer too.

**Comment by Alex-K-O-R** [comment]
> 
> 
> To add a new API (rather than simply align behavior) we'd want a bit more evidence of need. What sort of scenario would lead someone to pass "true" ?

I do:
https://github.com/Alex-K-O-R/NeatMenu

**Comment by Alex-K-O-R** [comment]
If it is logically correct ("clear" doesn't mean "scroll" or "rewind") and doesn't require a galactic-scale efforts, why .Clear(true) could not be done?

**Comment by hamarb123** [comment]
Hi, I've noticed this issue as well and developed a solution for my code on macOS:
On macOS, you can use `Console.Write("\f\u001bc\x1b[3J");` to clear the console fully and reset the cursor to the top. I'm not sure if this is portable to other unix platforms.
This line of code properly emulates what windows does with `Console.Clear()` in terms of the text buffer (not sure about colours etc.).

**Comment by towianisci** [comment]
I'm new to this programming gang as far as programming in C#. this was really frustrating me and the last comment thank you. thank you. It was very annoying.
.net 7 the latest version of C# on windows
static void ClearHost()
{
    Console.Write("\f\u001bc\x1b[3J");   
}

This cleared the host completely now as opposed to just using Console.Clear() which appears to just clear the last buffer.

**Comment by towianisci** [comment]
I'm new to this programming gang as far as programming in C#. This was really frustrating me, and the last comment thank you. thank you. It was very annoying.
you've seen net 7 the latest version of C# on windows
static void ClearHost()
{
    Console.Write("\f\u001bc\x1b[3J");   
}

**Comment by adamsitnik** [comment]
The issue got fixed by https://github.com/dotnet/runtime/pull/88487 and is included in .NET 8.

**Comment by iSazonov** [comment]
@adamsitnik It did not fix MacOS. 
1. Is it possible to add the MacOS fix using direct escapes?
2. Or should we document the MacOS behavior exclusion for Console.Clear?
3. Should we reopen the issue or https://github.com/dotnet/core/issues/8260?

**Comment by hamarb123** [comment]
Did you try printing a bunch of lines first, instead of immediately clearing @kasperk81 ?
I've not tested it with the "fix" yet, but plan to tomorrow when 8.0 releases, and I personally don't think it will work for macOS.

**Comment by hamarb123** [comment]
> of course

How is it of course if it's not in the code you showed.

**Comment by mklement0** [comment]
I just installed the officially released `8.0.100` version and, as far as I can tell, it does NOT work on macOS - neither in Terminal.app nor in popular third-party alternative iTerm2.app:

Repro code (reproduces the symptom on macOS 13.5.2):

```c#
for (var i = 0; i < 500; ++i) { Console.WriteLine(i); }; 
Console.Write("Press a key to clear the terminal"); 
Console.ReadKey(true); 
Console.Clear();  // Scroll back up afterwards - you'll see that the numbers are still there.
```

By contrast, adding the escape sequence that clears the scrollback buffer shown in the initial post works, in both terminal applications:

```c#
Console.Clear(); Console.WriteLine("\x1b[3J");
```

Shell alternatives:

Note: `/usr/bin/clear` on macOS clears only the current screen, not the scrollback buffer.

* Bash

```sh
/usr/bin/clear; printf '\x1b[3J'
```

* PowerShell

```powershell
/usr/bin/clear; printf "`e[3J"
```

**Comment by hamarb123** [comment]
Can confirm the following for Terminal.app:
- Fixed on macOS 14.1
- Broken on macOS 13.6.1

We should fix this since macOS 10.15+ is supported.

**Comment by adamsitnik** [comment]
The referenced fix (https://github.com/dotnet/runtime/pull/88487) checks the terminfo for an `E3` capability and uses it (not a hardcoded "\x1b[3J") when it's available.

I would love to fix it for all terminals, but how can we do that reliably if they don't define this capability? Sharing https://unix.stackexchange.com/questions/375743/why-clear-do-not-clear-whole-screen/375784#375784 for reference.

**Comment by mklement0** [comment]
@adamsitnik: Given @hamarb123's summary above, there's a pragmatic solution:
 
Instead of:

https://github.com/dotnet/runtime/blob/fd4621c11168ab9c21450f3c764fb46fe9aa8d29/src/libraries/System.Console/src/System/TerminalFormatStrings.cs#L77-L80

use:

```csharp
if (
  (
    RuntimeInformation.IsOSPlatform(OSPlatform.OSX) && Environment.OSVersion.Version.Major < 14 ?
      "\x1b[3J"
      :
      db.GetExtendedString("E3")
  ) is string clearScrollbackBuffer
)
{
    Clear += clearScrollbackBuffer; // the E3 command must come after the Clear command
}
```

Windows is not affected, and I'm not aware of issues on Linux distros, so this should be the only workaround required.

Once .NET no longer supports macOS 13 and below, this workaround can be removed.

**Comment by hamarb123** [comment]
I think something like the above is a good solution. (`OperatingSystem.IsMacOS() && !OperatingSystem.IsMacOSVersionAtLeast(14)` seems better suited though)

Note that with https://github.com/dotnet/roslyn/pull/70497, we should be able to even write `\e[3J` with C# next :)

If it concerns you that it might print something random out after it @adamsitnik, you could also re-append `TermInfo.WellKnownStrings.Clear` (or something similar) to it again to ensure that a clear goes through for this workaround - it seems to me like this should work well in most cases.

Ie, you could write:
```csharp
if (db.GetExtendedString("E3") is string clearScrollbackBuffer)
{
    Clear += clearScrollbackBuffer; // the E3 command must come after the Clear command
}
else if (OperatingSystem.IsMacOS() && !OperatingSystem.IsMacOSVersionAtLeast(14))
{
    Clear += "\e[3J" + db.GetString(TermInfo.WellKnownStrings.Clear); //use \e[3J to do a full clear on macOS terminal, and print the clear string again in case some terminal emulators don't understand this code to ensure we don't get random characters printed out
}
```
(note: I've not tested the above actually does what it's intended to)

I can make a PR for it if you'd like @adamsitnik

**Comment by adamsitnik** [comment]
The solution that you suggested assumes that **every** Terminal that runs on macOS supports `"\x1b[3J"`. I doubt it's always true.

Don't get me wrong, I want to get all the bugs fixed. But in reliable way.

My current best idea is to recognize the Terminals that support it, but don't define that in Terminfo. Similarly to what we do in:

https://github.com/dotnet/runtime/blob/33d7f9815a4cf0ceb19f7014f978137218855a32/src/libraries/System.Console/src/System/TerminalFormatStrings.cs#L89

But I doubt that such a fix would be approved for backporting to .NET 8 (unless we can guarantee that older versions of this Terminals support it).

**Comment by hamarb123** [comment]
> The solution that you suggested assumes that **every** Terminal that runs on macOS supports `"\x1b[3J"`. I doubt it's always true.

The point of the way I suggested doing it is assuming that they don't all support it. That's why I suggested a normal clear after. Would that not work?
