### ISSUE TITLE
Mono runtime NuGet versions on blob storage

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#33111]
Since the merge of #33074 the new `Microsoft.NETCore.Runtime.Mono` packages are generated from CI pipelines in the dotnet/runtime repository with versioning matching the rest of packages. Unfortunately, previous builds from mono/mono CI pipelines were uploaded to the same blob storage and used different versioning strategy (ie. match Mono major.minor version and commit distance). The result is that automatic NuGet versioning would now pick the historic 6.x versions of packages instead of the 5.0.0-preview.2 ones which are newer.

**Comment by filipnavara** [comment]
![image](https://user-images.githubusercontent.com/1764393/75800573-12248d00-5d7a-11ea-8451-a04471a97168.png)

**Comment by akoeplinger** [comment]
@dotnet/runtime-infrastructure can we easily delete these 6.x package versions from dotnetfeed.blob.core.windows.net?

**Comment by ViktorHofer** [comment]
I don't have permissions to do so but I believe @MattGal or @mmitche should have.

**Comment by MattGal** [comment]
> I don't have permissions to do so but I believe @MattGal or @mmitche should have.

I have the permissions, but deleting packages from a sleet feed is not as simple as deleting the blob.  One has to use their API to prevent messing up the manifests.  @jcagme has experience with this and is coincidentally on FR this week so should be able to handle it.

**Comment by jcagme** [comment]
There are 1,037 6.x versions for `Microsoft.NETCore.Runtime.Mono`. Do you want all those removed?

**Comment by filipnavara** [comment]
@jcagme Yep, also the `runtime.<rid>.Microsoft.NETCore.Runtime.Mono` packages of which there is plenty.

**Comment by jcagme** [comment]
Ok. Doable but it will take up to days depending on how busy the feed is. I can provide status as things move forward.

**Comment by filipnavara** [comment]
It was broken for weeks (including the time the packages were not published after repository consolidation) so a day or few won't make a big difference. I am just happy that there is a way to resolve this. Thanks!

**Comment by mmitche** [comment]
They probably also need to be deleted from the .net 5 feeds..i'm guessing.

**Comment by filipnavara** [comment]
@mmitche Which feed is that? I don't think these NuGets were published to any other feed, at least not a public one.

**Comment by mmitche** [comment]
> @mmitche Which feed is that? I don't think these NuGets were published to any other feed, at least not a public one.

dotnet5. https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.NETCore.Runtime.Mono&protocolType=NuGet&version=6.11.0.265-preview

Btw, We're going to stop publishing to the dotnet-core feed soon, and the AzDO feeds will be the only feeds regularly getting new packages.

**Comment by filipnavara** [comment]
> Btw, We're going to stop publishing to the dotnet-core feed soon, and the AzDO feeds will be the only feeds regularly getting new packages. That's what we should be telling customers to use for daily builds.

Uh, didn't know that, thanks for the heads up. I rely on the dotnet-core feed in quite a few projects.

**Comment by mmitche** [comment]
The dotnet5 and dotnet5-transport feeds (you probably only need dotnet5 if you're relying on shipping packages) have any of the new packages (from ~september onwards). See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#which-feeds-does-arcade-infra-publish-to

We're stopping publishing to the dotnet-core feed for a couple reasons:
- It's a 'fake' feed that has some crappy experiences when browsing for or downloading packages directly
- We already have to use AzDO feeds for any internal scenario (the blob feeds don't have authentication
- It's a pretty expensive feed to push to (a push from another repo at the same time locks the feed).

There was a preliminary mail sent yesterday to the dncpartners alias detailing the change.

**Comment by filipnavara** [comment]
Thanks for the explanation.

> There was a preliminary mail sent yesterday to the dncpartners alias detailing the change.
As a non-Microsoftie I usually don't get those. I also rarely follow the changes on the arcade repository.

The reasoning for the change makes sense. Consider it a friendly reminder that people not on the list, or the .NET team, may be consuming the feed.

**Comment by jcagme** [comment]
400 `Microsoft.NETCore.Runtime.Mono` packages have been removed so far from the dotnet-core feed. ~600 to go. Then I'll work on the `runtime.<rid>.Microsoft.NETCore.Runtime.Mono` and check the .net 5 feeds

**Comment by jcagme** [comment]
`Microsoft.NETCore.Runtime.Mono` deletion completed. Moving to runtime packages now

**Comment by jcagme** [comment]
@filipnavara are `runtime.<rid>.Microsoft.NETCore.Runtime.Mono` packages in the same feed? Can you please give me the name of one?

**Comment by filipnavara** [comment]
@jcagme Yep. They are on the same feed. The affected packages seem to be:

- runtime.linux-arm64.Microsoft.NETCore.Runtime.Mono
- runtime.linux-x64.Microsoft.NETCore.Runtime.Mono
- runtime.osx-x64.Microsoft.NETCore.Runtime.Mono
- runtime.win-x64.Microsoft.NETCore.Runtime.Mono

Thanks!

**Comment by jcagme** [comment]
`https://github.com/dotnet/arcade/pull/4838` complete, moving to `runtime.linux-x64.Microsoft.NETCore.Runtime.Mono`

**Comment by jcagme** [comment]
`runtime.linux-x64.Microsoft.NETCore.Runtime.Mono` done, onto `runtime.osx-x64.Microsoft.NETCore.Runtime.Mono`

**Comment by jcagme** [comment]
`runtime.osx-x64.Microsoft.NETCore.Runtime.Mono` done, closing with `runtime.win-x64.Microsoft.NETCore.Runtime.Mono`

**Comment by filipnavara** [comment]
Thanks a lot!

**Comment by jcagme** [comment]
`runtime.win-x64.Microsoft.NETCore.Runtime.Mono` is now deleted. Do we need to remove more packages?

**Comment by filipnavara** [comment]
I checked all the packages and there's still few broken versions on the feed:

runtime.linux-arm64.Microsoft.NETCore.Runtime.Mono has 2 wrong packages (6.x)
runtime.linux-x64.Microsoft.NETCore.Runtime.Mono has 6 wrong packages (5.3 + 6.x)
runtime.os-x64.Microsoft.NETCore.Runtime.Mono has 7 wrong packages (5.3 + 6.x)
runtime.win-x64.Microsoft.NETCore.Runtime.Mono has 2 wrong packages (5.3 + 6.x)

**Comment by jcagme** [comment]
Done, can you please verify?

**Comment by filipnavara** [comment]
All the 5.3.x.x versions disappeared but I still see the rest.

**Comment by jcagme** [comment]
Where do you see the versions? When looking for a package in VS, looking at the blob feed, or?

**Comment by filipnavara** [comment]
NuGet Explorer when looking at the specific feed.

**Comment by sebastienros** [comment]
Here is the url that lists what is available: https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/runtime.linux-x64.microsoft.netcore.runtime.mono/index.json

Note that nothing after April 5 has been added to the feed (which is a concern for me personally)

**Comment by filipnavara** [comment]
@sebastienros The primary feed has changed to https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json.

**Comment by sebastienros** [comment]
FYI here is the url listing all available versions on this feed, confirming anything after April 5th hasn't been added, and all 6.* version are available there.

https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/7d9f5c21-0d79-403f-bfe3-9a4506529760/nuget/v3/flat2/runtime.linux-x64.microsoft.netcore.runtime.mono/index.json

**Comment by jcagme** [comment]
Packages from https://dotnetfeed.blob.core.windows.net/dotnet-core should all be removed by now (please confirm if this is not the case). For the artifact feeds in Azure, I don't have any automation to delete packages.

**Comment by akoeplinger** [comment]
@filipnavara yes we stopped publishing these `runtime.*` packages in favor of runtime packs like https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.NETCore.App.Runtime.ios-x64&protocolType=NuGet&version=5.0.0-preview.4.20213.12.

We haven't done the work to add runtime packs for desktop OS since we'll need to figure out how to distinguish between coreclr vs. mono there.
