### ISSUE TITLE
Jit HardwareInterinsics NotSupported runtime tests failing on Mono

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#35906]
These two runtime tests are failing on mono (currently disabled in /src/coreclr/tests/issues.targets):

/JIT/HardwareIntrinsics/General/NotSupported_ro/*
/JIT/HardwareIntrinsics/General/NotSupported_r/*

The following is a helix log of the failure:

```xecuted on dci-mac-build-021.local
+ export CORE_ROOT=/tmp/helix/working/985108B8/p
+ CORE_ROOT=/tmp/helix/working/985108B8/p
+ export __TestEnv=/tmp/helix/working/985108B8/w/A71D08C9/u/SetStressModes_no_tiered_compilation.sh
+ __TestEnv=/tmp/helix/working/985108B8/w/A71D08C9/u/SetStressModes_no_tiered_compilation.sh
+ export __TestTimeout=600000
+ __TestTimeout=600000
+ export __CollectDumps=1
+ __CollectDumps=1
+ export __CrashDumpFolder=/cores
+ __CrashDumpFolder=/cores
+ cat /tmp/helix/working/985108B8/w/A71D08C9/u/SetStressModes_no_tiered_compilation.sh
#!/usr/bin/env bash
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
+ ulimit -c unlimited
+ /tmp/helix/working/985108B8/p/corerun /tmp/helix/working/985108B8/p/xunit.console.dll JIT/HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics
CLR: Managed code called FailFast, saying "Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_DllNotFoundException"

=================================================================
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10813a416 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_dump_native_crash_info
	0x1080dc3f5 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_handle_native_crash
	0x108139b7f - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : sigabrt_signal_handler
	0x7fff6f9d9f5a - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x7fff6f7771ae - /usr/lib/system/libsystem_c.dylib : abort
	0x1081cfb4f - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : ves_icall_System_Environment_FailFast
	0x1081d2786 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : ves_icall_System_Environment_FailFast_raw
	0x109efed64 - Unknown
	0x109ef7acb - Unknown
	0x109ef7a4b - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108217168 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_invoke_checked
	0x108217003 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_object_init_handle
	0x1081bfb88 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_exception_from_token
	0x109efe64b - Unknown
	0x109efe45b - Unknown
	0x109ef7fe5 - Unknown
	0x109ef7acb - Unknown
	0x109ef7a4b - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108217168 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_invoke_checked
	0x108217003 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_object_init_handle
	0x1081bfb88 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_exception_from_token
	0x109ef766b - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108218bff - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_try_invoke
	0x1082177cf - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_class_init_full
	0x108065a80 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_method_to_ir
	0x108034ed9 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mini_method_compile
	0x1080373cc - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_inner
	0x10803b2d2 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x1080def2f - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : common_call_trampoline
	0x1080de9a0 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_magic_trampoline
	0x1084c4396 - Unknown
	0x109ef66fb - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108218bff - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_try_invoke
	0x1082177cf - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_class_init_full
	0x108065a80 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_method_to_ir
	0x108034ed9 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mini_method_compile
	0x1080373cc - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_inner
	0x10803b2d2 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x1080def2f - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : common_call_trampoline
	0x1080de9a0 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_magic_trampoline
	0x1084c4396 - Unknown
	0x1086b7fb3 - Unknown
	0x1086b7c93 - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108218bff - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_try_invoke
	0x1082177cf - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_class_init_full
	0x108037814 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_inner
	0x10803b2d2 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_compile_method_with_opt
	0x1080def2f - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : common_call_trampoline
	0x1080de9a0 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_magic_trampoline
	0x1084c4396 - Unknown
	0x1086b5963 - Unknown
	0x1086b3c7b - Unknown
	0x1086b3373 - Unknown
	0x1086af6c1 - Unknown
	0x10803f7ee - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_runtime_invoke
	0x108217168 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_invoke_checked
	0x10821d4e5 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_runtime_exec_main_checked
	0x10809a4ac - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_jit_exec
	0x10809d5a6 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : mono_main
	0x1081162d9 - /private/tmp/helix/working/985108B8/p/libcoreclr.dylib : monovm_execute_assembly
	0x108019f5e - /tmp/helix/working/985108B8/p/corerun : _Z22ExecuteManagedAssemblyPKcS0_S0_iPS0_
	0x108018f3c - /tmp/helix/working/985108B8/p/corerun : main
	0x7fff6f6cb015 - /usr/lib/system/libdyld.dylib : start
	0xb - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x123145551892480x from 0x140736013112192x
Could not exec mono-hang-watchdog, expected on path '/Users/runner/runners/2.166.4/work/1/s/artifacts/obj/mono/OSX.x64.Release/out/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x140736013112192x
Finished thread summarizer pause from 0x140736013112192x.
Failed to create breadcrumb file (null)/crash_hash_0xc067e40a2

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff6f81bb66):0x7fff6f81bb56  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7fff6f81bb66  73 08 48 89 c7 e9 75 6f ff ff c3 90 90 90 b8 4c  s.H...uo.......L
0x7fff6f81bb76  01 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 5d 6f  ...I....s.H...]o
0x7fff6f81bb86  ff ff c3 90 90 90 b8 49 01 00 02 49 89 ca 0f 05  .......I...I....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Environment:FailFast <0x00093>
	  at System.Environment:FailFast <0x00042>
	  at System.SR:InternalGetResourceString <0x00212>
	  at System.SR:GetResourceString <0x0006a>
	  at System.SR:GetResourceString <0x0004a>
	  at System.SR:get_Arg_DllNotFoundException <0x0003a>
	  at System.DllNotFoundException:.ctor <0x0003a>
	  at System.Object:runtime_invoke_void__this__ <0x000b0>
	  at <unknown> <0xffffffff>
	  at Globalization:GetDefaultLocaleName <0x0007a>
	  at System.Globalization.CultureData:GetDefaultLocaleName <0x0009a>
	  at System.Globalization.CultureInfo:GetUserDefaultCulture <0x0006a>
	  at System.Globalization.CultureInfo:InitializeUserDefaultCulture <0x00042>
	  at System.Globalization.CultureInfo:GetUserDefaultUICulture <0x00032>
	  at System.Globalization.CultureInfo:InitializeUserDefaultUICulture <0x00042>
	  at System.Globalization.CultureInfo:get_UserDefaultUICulture <0x00052>
	  at System.Globalization.CultureInfo:get_CurrentUICulture <0x00072>
	  at System.Resources.ResourceManager:GetString <0x0008a>
	  at System.SR:InternalGetResourceString <0x00434>
	  at System.SR:GetResourceString <0x0006a>
	  at System.SR:GetResourceString <0x0004a>
	  at System.SR:get_Arg_DllNotFoundException <0x0003a>
	  at System.DllNotFoundException:.ctor <0x0003a>
	  at System.Object:runtime_invoke_void__this__ <0x000b0>
	  at <unknown> <0xffffffff>
	  at Globalization:LoadICU <0x0007a>
	  at System.Globalization.GlobalizationMode:LoadICU <0x00032>
	  at System.Globalization.GlobalizationMode:GetGlobalizationInvariantMode <0x00052>
	  at System.Globalization.GlobalizationMode:.cctor <0x00032>
	  at System.Object:runtime_invoke_void <0x000a5>
	  at <unknown> <0xffffffff>
	  at System.Globalization.CultureData:CreateCultureWithInvariantData <0x00d5a>
	  at System.Globalization.CultureData:get_Invariant <0x00052>
	  at System.Globalization.TextInfo:.cctor <0x00032>
	  at System.Object:runtime_invoke_void <0x000a5>
	  at <unknown> <0xffffffff>
	  at System.IO.PathInternal:GetIsCaseSensitive <0x00172>
	  at System.IO.PathInternal:.cctor <0x00032>
	  at System.Object:runtime_invoke_void <0x000a5>
	  at <unknown> <0xffffffff>
	  at System.IO.File:Exists <0x00102>
	  at Xunit.AssemblyHelper:.ctor <0x0009a>
	  at Xunit.AssemblyHelper:SubscribeResolveForAssembly <0x000a2>
	  at Xunit.ConsoleClient.Program:Main <0x000ea>
	  at <Module>:runtime_invoke_int_object <0x000b0>
=================================================================
/tmp/helix/working/985108B8/p/scripts/5eeee85c571b4dc3be40b1e31121290d/execute.sh: line 11:  6234 Abort trap: 6           $CORE_ROOT/corerun $CORE_ROOT/xunit.console.dll JIT/HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics
+ export _commandExitCode=134
+ _commandExitCode=134
+ /bin/sh /tmp/helix/working/985108B8/p/reporter/run.sh https://dev.azure.com/dnceng/ public 19733408 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzYzMzI2NSIsImF1aSI6ImNhNjcwMGFiLTYzY2MtNDBjYS05NzI3LTY0ZDRjNGI0NWY1YSIsInNpZCI6IjQ2ZTU5YmZlLTM3ZTYtNGU0NC04MjM2LWNiMDkxMDEzNjZiNyIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7NjMzMjY1Iiwib3JjaGlkIjoiYzA5YjYyZTAtMDgzZC00MmQ0LTg1NTgtNTZlNGE1NzZhODU1LnJ1bl90ZXN0X3AwX21vbm9fX29zeF94NjRfcmVsZWFzZS5fX2RlZmF1bHQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTg4Nzc0Mjc3LCJleHAiOjE1ODg3ODc0Nzd9.z9kVN__yRJ9R-gcnD2epg7RhLohNHDWUI_ctgf9EDjUIB-VgAben3ZgxitlCqM6F5P89Pvd1ADbAeSjQ5N3WHJb4GSn15eD_p1uBqgviB8blqBrZaDaqw_RPi-B_vnvjWckJt87AygfO1kJtkPebkm9x7DJwHuJUrJSNR9TosfsjvTE9e9YWTMI6saIR1v88koLToTNiRKIJmP35bk4UPiI-NHZTAYN3f_wvo5oM0wTiDVj62oXTle6ONKY2dNJbYXUWf2K8XYRkNuBec6E7j5cU2OFsmQepHsHEzYIHrISIdPa894FD-HHSZ7Y4sw0-8SDAFt1aRAxsAVPVTWARzw
++ whoami
+ '[' helix-runner = root ']'
+ exec sudo -E /tmp/helix/working/985108B8/p/reporter/run.sh https://dev.azure.com/dnceng/ public 19733408 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzYzMzI2NSIsImF1aSI6ImNhNjcwMGFiLTYzY2MtNDBjYS05NzI3LTY0ZDRjNGI0NWY1YSIsInNpZCI6IjQ2ZTU5YmZlLTM3ZTYtNGU0NC04MjM2LWNiMDkxMDEzNjZiNyIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7NjMzMjY1Iiwib3JjaGlkIjoiYzA5YjYyZTAtMDgzZC00MmQ0LTg1NTgtNTZlNGE1NzZhODU1LnJ1bl90ZXN0X3AwX21vbm9fX29zeF94NjRfcmVsZWFzZS5fX2RlZmF1bHQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTg4Nzc0Mjc3LCJleHAiOjE1ODg3ODc0Nzd9.z9kVN__yRJ9R-gcnD2epg7RhLohNHDWUI_ctgf9EDjUIB-VgAben3ZgxitlCqM6F5P89Pvd1ADbAeSjQ5N3WHJb4GSn15eD_p1uBqgviB8blqBrZaDaqw_RPi-B_vnvjWckJt87AygfO1kJtkPebkm9x7DJwHuJUrJSNR9TosfsjvTE9e9YWTMI6saIR1v88koLToTNiRKIJmP35bk4UPiI-NHZTAYN3f_wvo5oM0wTiDVj62oXTle6ONKY2dNJbYXUWf2K8XYRkNuBec6E7j5cU2OFsmQepHsHEzYIHrISIdPa894FD-HHSZ7Y4sw0-8SDAFt1aRAxsAVPVTWARzw
++ whoami
+ '[' root = root ']'
+++ dirname -- /tmp/helix/working/985108B8/p/reporter/run.sh
++ CDPATH=
++ cd -- /tmp/helix/working/985108B8/p/reporter
++ pwd
+ script_path=/tmp/helix/working/985108B8/p/reporter
+ ENV_PATH=/Users/helix-runner/.azdo-env
+ TMP_ENV_PATH=/Users/helix-runner/.azdo-env-tmp
+ date -u +%FT%TZ
2020-05-06T14:36:53Z
+ '[' '!' -f /Users/helix-runner/.azdo-env/bin/python ']'
+ _OLD_PYTHONPATH=
+ export PYTHONPATH=
+ PYTHONPATH=
+ /Users/helix-runner/.azdo-env/bin/python -c 'import azure.devops'
+ echo 'azure-devops module already available'
azure-devops module already available
+ /Users/helix-runner/.azdo-env/bin/python -c 'import future'
+ echo 'future module already available'
future module already available
+ date -u +%FT%TZ
2020-05-06T14:36:53Z
+ /Users/helix-runner/.azdo-env/bin/python -B /tmp/helix/working/985108B8/p/reporter/run.py https://dev.azure.com/dnceng/ public 19733408 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzYzMzI2NSIsImF1aSI6ImNhNjcwMGFiLTYzY2MtNDBjYS05NzI3LTY0ZDRjNGI0NWY1YSIsInNpZCI6IjQ2ZTU5YmZlLTM3ZTYtNGU0NC04MjM2LWNiMDkxMDEzNjZiNyIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7NjMzMjY1Iiwib3JjaGlkIjoiYzA5YjYyZTAtMDgzZC00MmQ0LTg1NTgtNTZlNGE1NzZhODU1LnJ1bl90ZXN0X3AwX21vbm9fX29zeF94NjRfcmVsZWFzZS5fX2RlZmF1bHQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTg4Nzc0Mjc3LCJleHAiOjE1ODg3ODc0Nzd9.z9kVN__yRJ9R-gcnD2epg7RhLohNHDWUI_ctgf9EDjUIB-VgAben3ZgxitlCqM6F5P89Pvd1ADbAeSjQ5N3WHJb4GSn15eD_p1uBqgviB8blqBrZaDaqw_RPi-B_vnvjWckJt87AygfO1kJtkPebkm9x7DJwHuJUrJSNR9TosfsjvTE9e9YWTMI6saIR1v88koLToTNiRKIJmP35bk4UPiI-NHZTAYN3f_wvo5oM0wTiDVj62oXTle6ONKY2dNJbYXUWf2K8XYRkNuBec6E7j5cU2OFsmQepHsHEzYIHrISIdPa894FD-HHSZ7Y4sw0-8SDAFt1aRAxsAVPVTWARzw
2020-05-06 07:36:54,088: INFO: 4321125248: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2020-05-06 07:36:54,091: INFO: 4321125248: run(89): main: Beginning reading of test results.
2020-05-06 07:36:54,091: INFO: 4321125248: run(95): main: Uploading results in batches of size 1000
2020-05-06 07:36:54,114: INFO: 4321125248: run(100): main: Main thread finished queueing batches
2020-05-06 07:36:54,114: INFO: 4321125248: run(104): main: Main thread exiting
Searching '/tmp/helix/working/985108B8/w/A71D08C9/e/..' for log files
Found log '/tmp/helix/working/985108B8/w/A71D08C9/e/../console.430327d5.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35790-merge-f412552733714e3c96/JIT.HardwareIntrinsics/console.430327d5.log?sv=2019-02-02&se=2020-05-16T14%3A32%3A42Z&sr=c&sp=rl&sig=WRZKvWY2F0yAHL%2BfQuPIUZUBEy%2FRb%2FaO2LeJ1LRz4%2Fo%3D'
Generated log list: console.430327d5.log:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35790-merge-f412552733714e3c96/JIT.HardwareIntrinsics/console.430327d5.log?sv=2019-02-02&se=2020-05-16T14%3A32%3A42Z&sr=c&sp=rl&sig=WRZKvWY2F0yAHL%2BfQuPIUZUBEy%2FRb%2FaO2LeJ1LRz4%2Fo%3D

Searching '/private/tmp/helix/working/985108B8/w/A71D08C9/e' for test results files
No results file found in any of the following formats: xunit, junit, trx
+ date -u +%FT%TZ
2020-05-06T14:36:54Z
+ export PYTHONPATH=
+ PYTHONPATH=
+ /usr/local/bin/python3 -B /tmp/helix/working/985108B8/p/xunit-reporter.py
2020-05-06T14:36:54.691Z	ERROR  	xunit-reporter.py	xunit-reporter(80)	main	Unable to report xunit results: no test results xml file found.
+ exit 134
```

**Comment by SamMonoRT** [comment]
Some other hardware intrinsics failures : MAC platform specific failures ::  System.PlatformNotSupportedException: Operation is not supported on this platform
1.	GC/API/GCSettings/InputValidation/InputValidation.sh
2.	GC/Features/LOHCompaction/lohpin/lohpin.sh
3.	JIT/HardwareIntrinsics/X86/Lzcnt.X64/Lzcnt.X64_r/Lzcnt.X64_r.sh 
4.	JIT/HardwareIntrinsics/X86/Popcnt.X64/Popcnt.X64_r/Popcnt.X64_r.sh
5.	JIT/HardwareIntrinsics/X86/Lzcnt.X64/Lzcnt.X64_ro/Lzcnt.X64_ro.sh
6.	JIT/HardwareIntrinsics/X86/Lzcnt/Lzcnt_r/Lzcnt_r.sh
7.	JIT/HardwareIntrinsics/X86/Popcnt/Popcnt_ro/Popcnt_ro.sh
8.	JIT/HardwareIntrinsics/X86/Popcnt.X64/Popcnt.X64_ro/Popcnt.X64_ro.sh
9.	JIT/HardwareIntrinsics/X86/Lzcnt/Lzcnt_ro/Lzcnt_ro.sh
10.	JIT/HardwareIntrinsics/X86/Popcnt/Popcnt_r/Popcnt_r.sh
11.	JIT/HardwareIntrinsics/X86/Popcnt.X64/Popcnt.X64_r/Popcnt.X64_r.sh

**Comment by naricc** [comment]
@imhameed This issue is resolved, isn't it?

**Comment by imhameed** [comment]
Maybe. An easy way to check is to try reenabling the tests. Fan already has a PR open to enable the x86-specific intrinsics tests, and we still have a few outstanding issues there that need to be fixed.

**Comment by imhameed** [comment]
All these tests will be enabled in https://github.com/dotnet/runtime/pull/54127.

**Comment by imhameed** [comment]
https://github.com/dotnet/runtime/pull/54127/ was merged.
