### ISSUE TITLE
how to open library in visual studio  in order to contribute

### ISSUE THREAD

**Issue by vscodewinodws** [dotnet/runtime#37003]
i want to contribute to the .net core so for that i cloned runtime and the build it , i got it build successfully . but when i follow this for the building libs 

i have executed build.cmd command then trying to open in vs 

https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries

it gets visual studio  open ( i tried both preview and stable ) but both shows error in code , there are so many errors in different solution , but i know this might be not the case  i might be wrong .

apart from it if i go to the directory and try to open solution it shows error **_Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version._**

i can not see that this specific version (5.0.100-preview.5.20251.2) in installed in my machine with the dotnet info command but during build.cmd i see it is downloading the this version 5.0.100-preview.5.20251.2  but opening with vs does not works and i never got success to build it can any one guide me on correct way to do it  ?

**Comment by ViktorHofer** [comment]
Please also install a corresponding SDK globally as Visual Studio can't use our local acquired SDK and always looks into the %PATH%.

https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md#net-sdk

**Comment by vscodewinodws** [comment]
yes by your suggestion i downloaded exe for the preview sdk and installed it and it is working as expected it solved my half problem , but the strange errors visual studio still reports by opening solutions i think it should be not there since i got the code when build was passing and green so can you help me here ?

**Comment by ViktorHofer** [comment]
Have you already built from the repo root first? `build.cmd clr+libs -runtimeConfiguration Release` should do it.

**Comment by vscodewinodws** [comment]
yes i did that and it was successful

**Comment by ViktorHofer** [comment]
ok, so what's the exact error that you are hitting now?

**Comment by vscodewinodws** [comment]
there are so many different errors in different solutions adding snap for one of solution 

system.console 

![image](https://user-images.githubusercontent.com/42150151/83020792-03571a80-9ff7-11ea-9b3e-a85b3c6632be.png)
so if i open other solution there are different set of errors preventing me to write code and send pr

**Comment by ViktorHofer** [comment]
Ok I have a hint. Can you please try restoring the test assemblies on the CLI and then open VS again:

```
build.cmd libs.tests -restore
```

This might be related to a VS restore issue.

**Comment by vscodewinodws** [comment]
trying it out will ping you back with results

**Comment by vscodewinodws** [comment]
as per your suggestion i executed command 

build.cmd libs.tests -restore

with below op

![image](https://user-images.githubusercontent.com/42150151/83033329-fc370900-a004-11ea-9133-267ff2d3c407.png)

when i see few solution e.g system.console are working fine after this restore but System.Text.Json , System.net.http etc shows the errors but very few compare to earlier 

i have executed clean and rebuild also but does not seems to be working as expected , please see below
![image](https://user-images.githubusercontent.com/42150151/83033647-5f28a000-a005-11ea-96de-dea52397e5cc.png)

any advice for me  ?

**Comment by ViktorHofer** [comment]
This is super weird. cc @Anipik @ericstj

**Comment by vscodewinodws** [comment]
just to add few words with preview version of vs , shows same error with latest preview

**Comment by ericstj** [comment]
Doesn't repro for me.  It should bind to System.Linq.Enumerable.Zip but it looks like its binding to System.Linq.Queryable.Zip (badly).

I can force it to reproduce if I delete System.Linq.dll from `<repoRoot>\artifacts\bin\ref\net5.0`.  Check if you have this file present.

I suspect in some of your rebuilding you managed to clean System.Linq and not rebuild it (guess).  

If the file is missing try doing a `<repoRoot>\.dotnet\dotnet build <repoRoot>\src\libraries\System.Linq\ref\System.Linq.csproj` and see if it fixes it.

If you can reliably get to this state we could look at a log to see what deleted System.Linq.dll

**Comment by vscodewinodws** [comment]
i did that as well executed build.cmd from build.cmd but still errors persist , vs shows the error as shows in below image with 

![image](https://user-images.githubusercontent.com/42150151/83110124-9728f500-a090-11ea-80d0-40550d633907.png)

and log for vs stack trace open log file 


=====================
28-05-2020 03:08:08
Recoverable
System.AggregateException: Project system data flow 'DataflowBlockSlim (ActionBlockSlimAsync`1 : 52753602)' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Must contain activeTargetFramework (Unsupported,Version=v0.0).
Parameter name: dependenciesByTargetFramework
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot..ctor(String projectPath, ITargetFramework activeTargetFramework, ImmutableDictionary`2 dependenciesByTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot.SetTargets(ImmutableArray`1 targetFrameworks, ITargetFramework activeTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<>c__DisplayClass38_0.<UpdateProjectContextAndSubscriptionsAsync>b__2(DependenciesSnapshot previousSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.SnapshotUpdater.TryUpdate(Func`2 updateFunc, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<UpdateProjectContextAndSubscriptionsAsync>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.SemaphoreSlimExtensions.<ExecuteWithinLockAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<OnProjectFactoryCompletedAsync>g__OnActiveConfiguredProjectEvaluatedAsync|30_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Must contain activeTargetFramework (Unsupported,Version=v0.0).
Parameter name: dependenciesByTargetFramework
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot..ctor(String projectPath, ITargetFramework activeTargetFramework, ImmutableDictionary`2 dependenciesByTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot.SetTargets(ImmutableArray`1 targetFrameworks, ITargetFramework activeTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<>c__DisplayClass38_0.<UpdateProjectContextAndSubscriptionsAsync>b__2(DependenciesSnapshot previousSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.SnapshotUpdater.TryUpdate(Func`2 updateFunc, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<UpdateProjectContextAndSubscriptionsAsync>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.SemaphoreSlimExtensions.<ExecuteWithinLockAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<OnProjectFactoryCompletedAsync>g__OnActiveConfiguredProjectEvaluatedAsync|30_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---
. ---> System.ArgumentException: Must contain activeTargetFramework (Unsupported,Version=v0.0).
Parameter name: dependenciesByTargetFramework
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot..ctor(String projectPath, ITargetFramework activeTargetFramework, ImmutableDictionary`2 dependenciesByTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot.SetTargets(ImmutableArray`1 targetFrameworks, ITargetFramework activeTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<>c__DisplayClass38_0.<UpdateProjectContextAndSubscriptionsAsync>b__2(DependenciesSnapshot previousSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.SnapshotUpdater.TryUpdate(Func`2 updateFunc, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<UpdateProjectContextAndSubscriptionsAsync>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.SemaphoreSlimExtensions.<ExecuteWithinLockAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<OnProjectFactoryCompletedAsync>g__OnActiveConfiguredProjectEvaluatedAsync|30_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Must contain activeTargetFramework (Unsupported,Version=v0.0).
Parameter name: dependenciesByTargetFramework
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot..ctor(String projectPath, ITargetFramework activeTargetFramework, ImmutableDictionary`2 dependenciesByTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.DependenciesSnapshot.SetTargets(ImmutableArray`1 targetFrameworks, ITargetFramework activeTargetFramework)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<>c__DisplayClass38_0.<UpdateProjectContextAndSubscriptionsAsync>b__2(DependenciesSnapshot previousSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.SnapshotUpdater.TryUpdate(Func`2 updateFunc, CancellationToken token)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<UpdateProjectContextAndSubscriptionsAsync>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.SemaphoreSlimExtensions.<ExecuteWithinLockAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider.<<OnProjectFactoryCompletedAsync>g__OnActiveConfiguredProjectEvaluatedAsync|30_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

**Comment by ViktorHofer** [comment]
That's actually a project-system bug that was already fixed. @drewnoakes do we have a VS Preview version with the fix?

**Comment by vscodewinodws** [comment]
just to update i have latest vs preview installed . but still shows error in code

**Comment by ericstj** [comment]
> i did that as well executed build.cmd from build.cmd but still errors persist , vs shows the error as shows in below image with

I'm sorry that's the case.  Let's find out why that reference is missing.  Do you think you could tell me more information about the specific steps I called out?

1.  Did `<repoRoot>\artifacts\bin\ref\net5.0\System.Linq.dll' exist?
2.  If not, build the `<repoRoot>\src\libraries\System.Linq\ref\System.Linq.csproj` project and see if it fixes it.  If that does not, please share a binlog for the build of that project.  (use `dotnet build <project> /bl`  it will produce an msbuild.binlog file which you can add to the issue).
3. If System.Linq.dll does exist in the ref folder then please share a binlog for your design time build.  See https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017-or-later for steps on how to collect this.

**Comment by drewnoakes** [comment]
The bug was fixed in https://github.com/dotnet/project-system/pull/6205/ which inserted in https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/249548 on May 20. That was pretty close to the deadline for 16.7p2, but should have made it in. That build should be available soon.

**Comment by ViktorHofer** [comment]
Thanks Drew

**Comment by vscodewinodws** [comment]
> * Did `\artifacts\bin\ref\net5.0\System.Linq.dll' exist?

yes it exist now , I rebuild the project and this particular solution vs does not complains any error as it should be , and it's working fine regarding my issue i check more couple of solutions and found they are working with vs.

but one System.text.json has weird errors vs shows rebuild all 4 project successful



![image](https://user-images.githubusercontent.com/42150151/83234820-e3db0180-a15e-11ea-95e2-c25fe3d7e722.png)

**Comment by vscodewinodws** [comment]
but i seems to be able to work with many more solutions and very few has kind of weird errors

**Comment by drewnoakes** [comment]
@vscodewinodws it's quite likely that VS's "design-time build" is failing. You can diagnose the failure by following the instructions at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017-or-later

**Comment by ViktorHofer** [comment]
@vscodewinodws can you please try it again with the `build.cmd -vs` switch and the latest VS Preview version. Thanks.

**Comment by ViktorHofer** [comment]
Closing as we haven't heard back from @vscodewinodws
