### ISSUE TITLE
StackFrame.GetMethod returns null in Blazor wasm

### ISSUE THREAD

**Issue by michael-gould** [dotnet/runtime#38627]
In Blazor WebAssembly, 

    new System.Diagnostics.StackFrame().GetMethod()

returns null.

I'm on Windows 10 using VS2019 16.6.2, Blazor WebAssembly 3.2.0.

To reproduce: Create a new Blazor WebAssembly application (.Net Core 3.1), and replace Counter.razor with this:
```
@page "/counter"

<h1>Counter</h1>

<p>MethodName: @methodName</p>

<button class="btn btn-primary" @onclick="SetMethodName">Click me</button>

@code {
    private string methodName;

    private void SetMethodName()
    {
        var stackFrame = new System.Diagnostics.StackFrame();
        var method = stackFrame.GetMethod();
        methodName = method.Name;
    }
}
```
Run the application, navigate to the Counter page and click on "Click me". Fails with a NullReferenceException.

For context the reason I came across this is that I have libraries that use NLog (4.7.2), and it doesn't include the class name in the log output. I believe NLog LogManager.GetCurrentClassLogger() uses StackFrame.GetMethod() then gets the DeclaringType.

**Comment by mkArtakMSFT** [comment]
@marek-safar FYI

**Comment by marek-safar** [comment]
@vargaz is this because we need some special runtime support?

**Comment by SamMonoRT** [comment]
@thaystg - do we need to track this anymore based on comments in https://github.com/mono/mono/pull/20156 ?

**Comment by thaystg** [comment]
This should be fixed when this https://github.com/mono/mono/pull/20159 that Zoltan did is merged.

**Comment by kg** [comment]
Even though Zoltan's PR is merged both here and in mono/mono, I can still reproduce the issue. ```new System.Diagnostics.StackFrame().GetMethod();``` is returning null for me in the wasm sample.

**Comment by thaystg** [comment]
I have tested on mono/mono and it's completely working. I think that this PR will fix on dotnet/runtime.
https://github.com/dotnet/runtime/pull/40031

**Comment by marek-safar** [comment]
Should be fixed with #40031

**Comment by michael-gould** [comment]
Thanks everyone - much appreciated

**Comment by StefanLundmark** [comment]
Running into this still. Have got the .NET Core SDK 3.1.402 and .NET Framework 4.8 runtimes installed. How can I tell what versions these PR's are included in? Sorry if this doesn't belong here and thanks in advance!

**Comment by vargaz** [comment]
Can somebody at MS still reproduce this ?
