### ISSUE TITLE
[wasm] Enable System.Xml.Linq.Tests.XTypeDescriptionProviderTests class

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#39709]
While enabling `System.ComponentModel.TypeConverter.Tests` on Browser WASM, I faced the failures in  [System.Xml.Linq.Tests.XTypeDescriptionProviderTests](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.ComponentModel.TypeConverter/tests/XTypeDescriptionProviderTests.cs) test class.

There are 7 test cases which mostly test the property-related logic for XElement and XAttribute classes (https://github.com/dotnet/corefx/pull/33082).
Those classes are annotated with `System.ComponentModel.TypeDescriptionProviderAttribute` so that TypeDescriptor.GetProperties() can provide with some additional properties https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.ComponentModel.TypeConverter/src/MS/Internal/Xml/Linq/ComponentModel/XComponentModel.cs#L36-L61.

The mentioned tests get a collection of property descriptors by calling something like below
```
var xel = new XElement("someElement");
var props = TypeDescriptor.GetProperties(xel);
```
Actually `props` contains only a collection of some general properties and doesn't include the additional ones.

**Comment by ericstj** [comment]
cc @eerhardt looks like a linker correctness issue.

**Comment by eerhardt** [comment]
We annotated `TypeDescriptionProviderAttribute` correctly to preserve the TypeDescriptionProvider types in .NET 5 RC1. However, it appears this usage exposed an ILLinker issue - it doesn't seem to handle generic types correctly. I've logged https://github.com/mono/linker/issues/1469 for this.

We won't be able to make progress on this issue in dotnet/runtime since this is an ILLinker issue. Adding `blocked`.

**Comment by eerhardt** [comment]
The underlying linker bug has been fixed. Removing "blocked". When we get a new linker in dotnet/runtime, we should be able to enable these tests now.

**Comment by MaximLipnin** [comment]
https://github.com/dotnet/runtime/pull/42201 should bring related linker changes

**Comment by MaximLipnin** [comment]
Tried to run `System.ComponentModel.TypeConverter` tests on the latest master, which includes changes from #42201, and the failures still exist. 
From `artifacts/bin/System.ComponentModel.TypeConverter.Tests/net5.0-release/browser-wasm/AppBundle/xharness-output/testResults.xml`:
```
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementElementsPropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementElementsPropertyDescriptor" time="0.0057949" result="Fail">
        <failure exception-type="Xunit.Sdk.NotNullException">
          <message><![CDATA[Assert.NotNull() Failure]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementElementsPropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementAttributePropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementAttributePropertyDescriptor" time="0.000769" result="Fail">
        <failure exception-type="Xunit.Sdk.NotNullException">
          <message><![CDATA[Assert.NotNull() Failure]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementAttributePropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementValuePropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementValuePropertyDescriptor" time="0.0081339" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementValuePropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XAttributeValuePropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XAttributeValuePropertyDescriptor" time="0.001141" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XAttributeValuePropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementDescendantsPropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementDescendantsPropertyDescriptor" time="0.000545" result="Fail">
        <failure exception-type="Xunit.Sdk.NotNullException">
          <message><![CDATA[Assert.NotNull() Failure]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementDescendantsPropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementXmlPropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementXmlPropertyDescriptor" time="0.0004369" result="Fail">
        <failure exception-type="Xunit.Sdk.NotNullException">
          <message><![CDATA[Assert.NotNull() Failure]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementXmlPropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementElementPropertyDescriptor" type="System.Xml.Linq.Tests.XTypeDescriptionProviderTests" method="XElementElementPropertyDescriptor" time="0.0006809" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at System.Xml.Linq.Tests.XTypeDescriptionProviderTests.XElementElementPropertyDescriptor()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```

**Comment by MaximLipnin** [comment]
E.g. `XElementElementsPropertyDescriptor` test expects a property descriptor named `Elements` which doesn't exist:

```
        [Fact]
        public void XElementElementsPropertyDescriptor()
        {
            var xel = new XElement("someElement");
            var props = TypeDescriptor.GetProperties(xel);

            var xelElsPD = props["Elements"];
            Assert.NotNull(xelElsPD);
           // ...
```
Below is what `props` has: 
```
FirstAttribute
HasAttributes
HasElements
IsEmpty
LastAttribute
Name
NodeType
Value
FirstNode
LastNode
NextNode
PreviousNode
BaseUri
Document
Parent
```

**Comment by eerhardt** [comment]
I got the time to investigate this issue today, and it appears to be another linker issue. I opened https://github.com/mono/linker/issues/1536 for this issue. Marking this as `blocked` again.

**Comment by eerhardt** [comment]
I retested this scenario with the latest builds and it is still blocked by https://github.com/mono/linker/issues/1536.

Note: 

```C#
            var xel = new XElement("someElement");
            var props = TypeDescriptor.GetProperties(xel);
```

The call to `TypeDescriptor.GetProperties(object)` is now marked as "RequiresUnreferencedCode" and using it in a trimmed app will emit a warning. This is because the Type of the `object` can't be statically analyzed, and thus all the properties of `XElement` are getting trimmed. Which means the default TypeDescriptor system won't find those properties. So as written, I don't expect this test to work in a trimmed app.

**Comment by eerhardt** [comment]
Moving to 7.0 as this scenario isn't necessary in order to ship 6.0. The underlying linker issue https://github.com/mono/linker/issues/1536 needs to be fixed before this issue can be resolved.

**Comment by ilonatommy** [comment]
Unblocked, if @eerhardt you could see if we are able to close it soon, it would be great.
