### ISSUE TITLE
.NET 5 Preview 8, Single-File deployment of WebApi project throws Segmentation fault on ARM

### ISSUE THREAD

**Issue by Hubert-Rybak** [dotnet/runtime#41816]
### Description

Repro:

1. Create new WebApi project
dotnet new webapi -n RaspSegFaultTest

2. Publish as single file 
dotnet publish -c Release -r linux-arm /p:PublishSingleFile=true

3. Try to run on ARM (Raspberry PI 3 in my case)
Result:
```
Unhandled exception. Segmentation fault
```
### Configuration

λ dotnet --info                                                           
.NET SDK (reflecting any global.json):                                    
 Version:   5.0.100-preview.8.20417.9                                     
 Commit:    fc62663a35                                                    
                                                                          
Runtime Environment:                                                      
 OS Name:     Windows                                                     
 OS Version:  10.0.17763                                                  
 OS Platform: Windows                                                     
 RID:         win10-x64                                                   
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\      
                                                                          
Host (useful for support):                                                
  Version: 5.0.0-preview.8.20407.11                                       
  Commit:  bf456654f9                                                     

ARM env:

Raspberry PI 3 model 3

```
uname -a
Linux nextcloudplus 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by Hubert-Rybak** [comment]
Some output from gdb

```shell
pi@nextcloudplus:~/net5 $ gdb ./RaspPiSegFault
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./RaspPiSegFault...(no debugging symbols found)...done.
(gdb) run -d -L debug
Starting program: /home/pi/net5/RaspPiSegFault -d -L debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x768963d0 (LWP 7529)]
[New Thread 0x7608c3d0 (LWP 7530)]
[New Thread 0x756cf3d0 (LWP 7532)]
[New Thread 0x74ece3d0 (LWP 7533)]
[New Thread 0x746ac3d0 (LWP 7534)]
[New Thread 0x740dc3d0 (LWP 7535)]
[New Thread 0x73eff3d0 (LWP 7536)]
[New Thread 0x73bff3d0 (LWP 7537)]
[New Thread 0x73b7e3d0 (LWP 7538)]
[New Thread 0x73e5e3d0 (LWP 7539)]
[New Thread 0x37eff3d0 (LWP 7540)]
[New Thread 0x731ff3d0 (LWP 7541)]
Unhandled exception.
Thread 1 "RaspPiSegFault" received signal SIGSEGV, Segmentation fault.
0x005ad356 in PEDecoder::CheckNTHeaders() const ()
(gdb) bt
#0  0x005ad356 in PEDecoder::CheckNTHeaders() const ()
#1  0x00672c4c in PEImage::GetLayoutInternal(unsigned int, unsigned int) ()
#2  0x00671a16 in PEImage::GetLayout(unsigned int, unsigned int) ()
#3  0x0064fbaa in BinderAcquireImport ()
#4  0x006c1b6a in BINDER_SPACE::AssemblyBinder::GetAssembly(SString&, int, int, BINDER_SPACE::Assembly**, char16_t const*, BundleFileLocation) ()
#5  0x006c25d8 in BINDER_SPACE::AssemblyBinder::BindByTpaList(BINDER_SPACE::ApplicationContext*, BINDER_SPACE::AssemblyName*, bool, BINDER_SPACE::BindResult*) ()
#6  0x006c2082 in BINDER_SPACE::AssemblyBinder::BindLocked(BINDER_SPACE::ApplicationContext*, BINDER_SPACE::AssemblyName*, bool, bool, BINDER_SPACE::BindResult*) ()
#7  0x006c14b0 in BINDER_SPACE::AssemblyBinder::BindByName(BINDER_SPACE::ApplicationContext*, BINDER_SPACE::AssemblyName*, bool, bool, bool, BINDER_SPACE::BindResult*) ()
#8  0x006c105e in BINDER_SPACE::AssemblyBinder::BindAssembly(BINDER_SPACE::ApplicationContext*, BINDER_SPACE::AssemblyName*, char16_t const*, PEAssembly*, int, int, bool, BINDER_SPACE::Assembly**) ()
#9  0x005d304c in CLRPrivBinderCoreCLR::BindAssemblyByName(IAssemblyName*, ICLRPrivAssembly**) ()
#10 0x0064f4d6 in AssemblySpec::Bind(AppDomain*, int, CoreBindResult*, int, int) ()
#11 0x00621224 in AppDomain::BindAssemblySpec(AssemblySpec*, int) ()
#12 0x00515fec in AssemblySpec::LoadDomainAssembly(FileLoadLevel, int) ()
#13 0x0057d91e in LoadDomainAssembly(SString*, Assembly*, ICLRPrivBinder*, int) ()
#14 0x0057caee in TypeName::GetTypeWorker(int, int, Assembly*, int, int, Assembly*, ICLRPrivBinder*, Object**) ()
#15 0x0057d164 in TypeName::GetTypeManaged(char16_t const*, DomainAssembly*, int, int, int, Assembly*, Object**, ICLRPrivBinder*) ()
#16 0x00562f16 in RuntimeTypeHandle::GetTypeByName(char16_t const*, int, int, QCall::StackCrawlMarkHandle, QCall::ObjectHandleOnStack, QCall::ObjectHandleOnStack, QCall::ObjectHandleOnStack) ()
#17 0x71ac5578 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/runtime/issues/41609, should be fixed

**Comment by Hubert-Rybak** [comment]
Referenced issue is for ARM64, not ARM. 
I tested latest RC2 bits (0de0eccfbb976f24bf4c472c3be20ad841e5f9b9 5.0.100-rc.2.20465.5) and I still have this error.

**Comment by agocke** [comment]
Sorry, didn't realize this is ARM32, not ARM64

**Comment by agocke** [comment]
@vitek-karas @sbomer Could you see if this looks similar to ARM64? Let's see if we can find an ARM32 machine to validate on.

**Comment by sbomer** [comment]
The stack trace makes me think it is failing one of the alignment checks, like this one https://github.com/dotnet/runtime/blob/master/src/coreclr/src/utilcode/pedecoder.cpp#L268 - though I would have expected more failures on other platforms if that's the case.

**Comment by ahopper** [comment]
I'm seeing this on an Avalonia project on raspberry pi 4 with an arm32 build using rc1.

**Comment by vitek-karas** [comment]
5.0-rc2 port is opened in https://github.com/dotnet/runtime/pull/42528.

**Comment by vitek-karas** [comment]
The RC2 port has been merge - the fix should make it into the final RC2 build.
https://github.com/dotnet/runtime/pull/42528
