### ISSUE TITLE
[5.0.100-rc.2.20471.7] Single File for OpenMU/HandyControl/TuringTrader target 5.0 app, tests failed

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#42665]
**Application Names:** OpenMU
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.2.20471.7
**App Location:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\OpenMU-5.0
**App Source:**  \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\OpenMU-5.0
**DevDiv issue:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1218902](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1218902)

**Repro steps:**
Retarget 5.0
Single File exe was created by
dotnet publish MUnique.OpenMU.Startup.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true
using 5.0.100-rc.2.20471.7 SDK
Copy '\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\OpenMU-5.0' to local machine.
Double-click on MUnique.OpenMU.Startup.exe

**Expected Result:**
Open OpenMU app successful.

**Actual Result:**
The OpenMU app thrown exception and unable to start.

**Findings:**
According to the exception, we think it might be caused by related Pull Request:
[https://github.com/dotnet/runtime/pull/40974](https://github.com/dotnet/runtime/pull/40974)

**Exception from command window for OpenMU:**
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator' threw an exception.
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator.LoadSettings()
   at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator..cctor()
   --- End of inner exception stack trace ---
   at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator.Configure(DbContext context, DbContextOptionsBuilder optionsBuilder)
   at MUnique.OpenMU.Persistence.EntityFramework.EntityDataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at MUnique.OpenMU.Persistence.EntityFramework.GenericRepository`1..ctor(PersistenceContextProvider contextProvider)
   at MUnique.OpenMU.Persistence.EntityFramework.AccountRepository..ctor(PersistenceContextProvider contextProvider)
   at MUnique.OpenMU.Persistence.EntityFramework.RepositoryManager.RegisterRepositories(PersistenceContextProvider contextProvider)
   at MUnique.OpenMU.Persistence.EntityFramework.PersistenceContextProvider..ctor()
   at MUnique.OpenMU.Startup.Program.PrepareRepositoryManager(Boolean reinit, Boolean autoupdate)
   at MUnique.OpenMU.Startup.Program..ctor(String[] args)
   at MUnique.OpenMU.Startup.Program.Main(String[] args)
```

cc @dotnet-actwx-bot

**Comment by jiangzeng01** [comment]
We have 3 apps effected by this PR: [https://github.com/dotnet/runtime/pull/40974](https://github.com/dotnet/runtime/pull/40974)
**Effected 3 Apps:**
OpenMU
HandyControl
TuringTrader

@LakshanF Please help to confirm if this is by design change.

**Comment by agocke** [comment]
Should be fixed by https://github.com/dotnet/runtime/issues/42352

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/runtime/issues/42352

**Comment by jiangzeng01** [comment]
@agocke We verified with both RC2 build: 5.0.100-rc.2.20480.7 and RTM build:5.0.100-rtm.20508.1, the issue is still happening with the same error log.
which .Net 5 release will the fix [https://github.com/dotnet/runtime/pull/42435](https://github.com/dotnet/runtime/pull/42435) be located?

**Comment by agocke** [comment]
@jiangzeng01 Sorry, I should have been more detailed. For app compat, the apps may need to pass the `IncludeAllContentForSelfExtract=true` flag. That should be working in the latest 5.0 RTM builds.

Without that flag, apps may not work without modification to their source code.

**Comment by jiangzeng01** [comment]
This issue is verified as fixed with 5.0 RTM.
But there are other issues for 2 of the apps when we continue:
**OpenMU (Retarget 5.0)**: the same issue with target 3.1, [https://github.com/dotnet/runtime/issues/42570](https://github.com/dotnet/runtime/issues/42570)
**TuringTrader (Retarget 5.0)**: new issue created, [https://github.com/dotnet/runtime/issues/43251](https://github.com/dotnet/runtime/issues/43251)
