### ISSUE TITLE
Superfluous mov(s) opcodes around left shifting/vmovmskps

### ISSUE THREAD

**Issue by damageboy** [dotnet/runtime#430]
## Repro Repo:
https://github.com/damageboy/coreclr-jit-why-mov-now

## Relevant piece of code:

https://github.com/damageboy/coreclr-jit-why-mov-now/blob/09e990e4d87190e33ca9ea1a794ec045a6651f97/Program.cs#L37-L44

```csharp
            maskyMcMaskFace  = (ulong) (uint) MoveMask(CompareGreaterThan(L0, P).AsSingle()) << 00;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L1, P).AsSingle()) << 08;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L2, P).AsSingle()) << 16;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L3, P).AsSingle()) << 24;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L4, P).AsSingle()) << 32;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L5, P).AsSingle()) << 40;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L6, P).AsSingle()) << 48;
            maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L7, P).AsSingle()) << 56;
```

## Generated asm:

https://github.com/damageboy/coreclr-jit-why-mov-now/blob/09e990e4d87190e33ca9ea1a794ec045a6651f97/listing.asm#L57-L115

```nasm
;             maskyMcMaskFace  = (ulong) (uint) MoveMask(CompareGreaterThan(L0, P).AsSingle()) << 00;
00007F05AE6B097A C5F566C8             vpcmpgtd ymm1,ymm1,ymm0
00007F05AE6B097E C5FC50F9             vmovmskps edi,ymm1
00007F05AE6B0982 8BFF                 mov     edi,edi


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L1, P).AsSingle()) << 08;
00007F05AE6B0984 C5ED66C8             vpcmpgtd ymm1,ymm2,ymm0
00007F05AE6B0988 C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B098C 8BC0                 mov     eax,eax
00007F05AE6B098E 48C1E008             shl     rax,8
00007F05AE6B0992 480BF8               or      rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L2, P).AsSingle()) << 16;
00007F05AE6B0995 C5E566C8             vpcmpgtd ymm1,ymm3,ymm0
00007F05AE6B0999 C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B099D 8BC0                 mov     eax,eax
00007F05AE6B099F 48C1E010             shl     rax,10h
00007F05AE6B09A3 480BC7               or      rax,rdi
00007F05AE6B09A6 488BF8               mov     rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L3, P).AsSingle()) << 24;
00007F05AE6B09A9 C5DD66C8             vpcmpgtd ymm1,ymm4,ymm0
00007F05AE6B09AD C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B09B1 8BC0                 mov     eax,eax
00007F05AE6B09B3 48C1E018             shl     rax,18h
00007F05AE6B09B7 480BC7               or      rax,rdi
00007F05AE6B09BA 488BF8               mov     rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L4, P).AsSingle()) << 32;
00007F05AE6B09BD C5D566C8             vpcmpgtd ymm1,ymm5,ymm0
00007F05AE6B09C1 C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B09C5 8BC0                 mov     eax,eax
00007F05AE6B09C7 48C1E020             shl     rax,20h
00007F05AE6B09CB 480BC7               or      rax,rdi
00007F05AE6B09CE 488BF8               mov     rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L5, P).AsSingle()) << 40;
00007F05AE6B09D1 C5CD66C8             vpcmpgtd ymm1,ymm6,ymm0
00007F05AE6B09D5 C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B09D9 8BC0                 mov     eax,eax
00007F05AE6B09DB 48C1E028             shl     rax,28h
00007F05AE6B09DF 480BC7               or      rax,rdi
00007F05AE6B09E2 488BF8               mov     rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L6, P).AsSingle()) << 48;
00007F05AE6B09E5 C5C566C8             vpcmpgtd ymm1,ymm7,ymm0
00007F05AE6B09E9 C5FC50C1             vmovmskps eax,ymm1
00007F05AE6B09ED 8BC0                 mov     eax,eax
00007F05AE6B09EF 48C1E030             shl     rax,30h
00007F05AE6B09F3 480BC7               or      rax,rdi
00007F05AE6B09F6 488BF8               mov     rdi,rax


;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L7, P).AsSingle()) << 56;
00007F05AE6B09F9 C5BD66C0             vpcmpgtd ymm0,ymm8,ymm0
00007F05AE6B09FD C5FC50C0             vmovmskps eax,ymm0
00007F05AE6B0A01 8BC0                 mov     eax,eax
00007F05AE6B0A03 48C1E038             shl     rax,38h
00007F05AE6B0A07 480BC7               or      rax,rdi
00007F05AE6B0A0A 488BF8               mov     rdi,rax
```

## Issue
In the asm listing, you can see that the first left shift by 0 has no effect, which is great!
The second one generates proper code.

But the 3rd and onwards (<<16..<<56) all generate an additional `mov` instruction:
```nasm
or      rax,rdi
mov     rdi,rax
```

Where it could simple do a single:
```nasm
or rdi,rax
```

Which it did for the first shift only...?

I do realize these opcodes are the most expensive to execute, but this is completely erratic and does impact decoding and to some extent the execution speed of the code.

It is perhaps indicative of a more fundamental issue as well?

category:cq
theme:register-allocator
skill-level:intermediate
cost:medium

**Comment by mikedn** [comment]
When I try your example using the current master I don't see those extra moves:
```asm
       C57D6F81E0000000     vmovdqa  ymm8, ymmword ptr[rcx+224]
       C5F566C8             vpcmpgtd ymm1, ymm1, ymm0
       C5FC50C9             vmovmskps yrcx, ymm1
       8BC9                 mov      ecx, ecx
       C5ED66C8             vpcmpgtd ymm1, ymm2, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E008             shl      rax, 8
       480BC8               or       rcx, rax
       C5E566C8             vpcmpgtd ymm1, ymm3, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E010             shl      rax, 16
       480BC8               or       rcx, rax
       C5DD66C8             vpcmpgtd ymm1, ymm4, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E018             shl      rax, 24
       480BC8               or       rcx, rax
       C5D566C8             vpcmpgtd ymm1, ymm5, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E020             shl      rax, 32
       480BC8               or       rcx, rax
       C5CD66C8             vpcmpgtd ymm1, ymm6, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E028             shl      rax, 40
       480BC8               or       rcx, rax
       C5C566C8             vpcmpgtd ymm1, ymm7, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E030             shl      rax, 48
       480BC8               or       rcx, rax
       C5BD66C0             vpcmpgtd ymm0, ymm8, ymm0
       C5FC50C0             vmovmskps yrax, ymm0
       8BC0                 mov      eax, eax
       48C1E038             shl      rax, 56
       480BC8               or       rcx, rax
       33F6                 xor      esi, esi
       F3480FB8F1           popcnt   rsi, rcx
```
Maybe the issue was already fixed, though I don't remember any change going in that could have affected this.

**Comment by damageboy** [comment]
@mikedn I'll give it a try with 3.1 preview / master.

It is somewhat flaky for me to: For example if I move the same code to the `Main` function it does not happen, but in the `BugBugBug` function it does...

**Comment by damageboy** [comment]
@mikedn I'm still getting the same thing with latest master.

Just to be clear, I did some hotpatching:

1. Compiled master in release
2. Published my repro: `dotnet publish -o linux-x64 -r linux-x64`
3. Copied over dll,so files from artifacts/bin/coreclr/Linux.x64.Release to my publish folder:
  ```bash
  # corerun will fail without this...
  $ cp *.{so,dll} /tmp/coreclr-jit-why-mov-now/linux-x64
  ```
4. Ran: `./corerun /tmp/coreclr-jit-why-mov-now/linux-x64/coreclr-jit-why-mov-now.dll`
5. Ran jitdasm: `sudo $HOME/.dotnet/tools/jitdasm -p $(pgrep -f corerun) -m coreclr-jit-why-mov-now`
6. Got this:

```nasm
;             maskyMcMaskFace  = (ulong) (uint) MoveMask(CompareGreaterThan(L0, P).AsSingle()) << 00;
00007F4C5E0A0F1A C5F566C8             vpcmpgtd ymm1,ymm1,ymm0
00007F4C5E0A0F1E C5FC50F9             vmovmskps edi,ymm1
00007F4C5E0A0F22 8BFF                 mov     edi,edi

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L1, P).AsSingle()) << 08;
00007F4C5E0A0F24 C5ED66C8             vpcmpgtd ymm1,ymm2,ymm0
00007F4C5E0A0F28 C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F2C 8BC0                 mov     eax,eax
00007F4C5E0A0F2E 48C1E008             shl     rax,8
00007F4C5E0A0F32 480BF8               or      rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L2, P).AsSingle()) << 16;
00007F4C5E0A0F35 C5E566C8             vpcmpgtd ymm1,ymm3,ymm0
00007F4C5E0A0F39 C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F3D 8BC0                 mov     eax,eax
00007F4C5E0A0F3F 48C1E010             shl     rax,10h
00007F4C5E0A0F43 480BC7               or      rax,rdi
00007F4C5E0A0F46 488BF8               mov     rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L3, P).AsSingle()) << 24;
00007F4C5E0A0F49 C5DD66C8             vpcmpgtd ymm1,ymm4,ymm0
00007F4C5E0A0F4D C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F51 8BC0                 mov     eax,eax
00007F4C5E0A0F53 48C1E018             shl     rax,18h
00007F4C5E0A0F57 480BC7               or      rax,rdi
00007F4C5E0A0F5A 488BF8               mov     rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L4, P).AsSingle()) << 32;
00007F4C5E0A0F5D C5D566C8             vpcmpgtd ymm1,ymm5,ymm0
00007F4C5E0A0F61 C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F65 8BC0                 mov     eax,eax
00007F4C5E0A0F67 48C1E020             shl     rax,20h
00007F4C5E0A0F6B 480BC7               or      rax,rdi
00007F4C5E0A0F6E 488BF8               mov     rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L5, P).AsSingle()) << 40;
00007F4C5E0A0F71 C5CD66C8             vpcmpgtd ymm1,ymm6,ymm0
00007F4C5E0A0F75 C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F79 8BC0                 mov     eax,eax
00007F4C5E0A0F7B 48C1E028             shl     rax,28h
00007F4C5E0A0F7F 480BC7               or      rax,rdi
00007F4C5E0A0F82 488BF8               mov     rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L6, P).AsSingle()) << 48;
00007F4C5E0A0F85 C5C566C8             vpcmpgtd ymm1,ymm7,ymm0
00007F4C5E0A0F89 C5FC50C1             vmovmskps eax,ymm1
00007F4C5E0A0F8D 8BC0                 mov     eax,eax
00007F4C5E0A0F8F 48C1E030             shl     rax,30h
00007F4C5E0A0F93 480BC7               or      rax,rdi
00007F4C5E0A0F96 488BF8               mov     rdi,rax

;             maskyMcMaskFace |= (ulong) (uint) MoveMask(CompareGreaterThan(L7, P).AsSingle()) << 56;
00007F4C5E0A0F99 C5BD66C0             vpcmpgtd ymm0,ymm8,ymm0
00007F4C5E0A0F9D C5FC50C0             vmovmskps eax,ymm0
00007F4C5E0A0FA1 8BC0                 mov     eax,eax
00007F4C5E0A0FA3 48C1E038             shl     rax,38h
00007F4C5E0A0FA7 480BC7               or      rax,rdi
00007F4C5E0A0FAA 488BF8               mov     rdi,rax

```

**Comment by mikedn** [comment]
Hmm, if I try to use the Linux altjit I see different register allocation (`edi` used instead of `ecx` like in my previous post) but still no `movs`:
```asm
       8BFF                 mov      edi, edi
       C5ED66C8             vpcmpgtd ymm1, ymm2, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E008             shl      rax, 8
       480BF8               or       rdi, rax
       C5E566C8             vpcmpgtd ymm1, ymm3, ymm0
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E010             shl      rax, 16
       480BF8               or       rdi, rax
…
```
I wonder if the this difference could perhaps be caused by different input IL.

**Comment by damageboy** [comment]
@mikedn Super weird.

After your comment, my impostor syndrome led me to test this on 3.0 on Linux+Windows.
Another Developer's machine on Linux.
And the master branch JIT on Linux.

In all 4 cases, the compiler was the regular compiler that comes with 
the 3.0.100 SDK and the issue resurfaced.

**Comment by damageboy** [comment]
Here is the MSIL listing obtained from `monodis` at any rate:

```msil
.assembly extern System.Runtime
{
  .ver 4:2:1:0
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A ) // .?_....:
}
.assembly extern System.Runtime.Extensions
{
  .ver 4:2:1:0
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A ) // .?_....:
}
.assembly extern System.Runtime.Intrinsics
{
  .ver 4:0:0:0
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 ) // .{...-.Q
}
.assembly extern System.Console
{
  .ver 4:1:1:0
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A ) // .?_....:
}
.assembly 'coreclr-jit-why-mov-now'
{
  .custom instance void class [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::'.ctor'(int32) =  (01 00 08 00 00 00 00 00 ) // ........

  .custom instance void class [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::'.ctor'() =  (
		01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
		63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01       ) // ceptionThrows.

  .custom instance void class [mscorlib]System.Diagnostics.DebuggableAttribute::'.ctor'(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) =  (01 00 02 00 00 00 00 00 ) // ........

  .custom instance void class [mscorlib]System.Runtime.Versioning.TargetFrameworkAttribute::'.ctor'(string) =  (
		01 00 18 2E 4E 45 54 43 6F 72 65 41 70 70 2C 56   // ....NETCoreApp,V
		65 72 73 69 6F 6E 3D 76 33 2E 30 01 00 54 0E 14   // ersion=v3.0..T..
		46 72 61 6D 65 77 6F 72 6B 44 69 73 70 6C 61 79   // FrameworkDisplay
		4E 61 6D 65 00                                  ) // Name.

  .custom instance void class [mscorlib]System.Reflection.AssemblyCompanyAttribute::'.ctor'(string) =  (
		01 00 17 63 6F 72 65 63 6C 72 2D 6A 69 74 2D 77   // ...coreclr-jit-w
		68 79 2D 6D 6F 76 2D 6E 6F 77 00 00             ) // hy-mov-now..

  .custom instance void class [mscorlib]System.Reflection.AssemblyConfigurationAttribute::'.ctor'(string) =  (01 00 07 72 65 6C 65 61 73 65 00 00 ) // ...release..

  .custom instance void class [mscorlib]System.Reflection.AssemblyFileVersionAttribute::'.ctor'(string) =  (01 00 07 31 2E 30 2E 30 2E 30 00 00 ) // ...1.0.0.0..

  .custom instance void class [mscorlib]System.Reflection.AssemblyInformationalVersionAttribute::'.ctor'(string) =  (01 00 05 31 2E 30 2E 30 00 00 ) // ...1.0.0..

  .custom instance void class [mscorlib]System.Reflection.AssemblyProductAttribute::'.ctor'(string) =  (
		01 00 17 63 6F 72 65 63 6C 72 2D 6A 69 74 2D 77   // ...coreclr-jit-w
		68 79 2D 6D 6F 76 2D 6E 6F 77 00 00             ) // hy-mov-now..

  .custom instance void class [mscorlib]System.Reflection.AssemblyTitleAttribute::'.ctor'(string) =  (
		01 00 17 63 6F 72 65 63 6C 72 2D 6A 69 74 2D 77   // ...coreclr-jit-w
		68 79 2D 6D 6F 76 2D 6E 6F 77 00 00             ) // hy-mov-now..

  .permissionset reqmin = {[System.Runtime.Extensions]System.Security.Permissions.SecurityPermissionAttribute = {property bool 'SkipVerification' = bool(true)}}
  .hash algorithm 0x00008004
  .ver  1:0:0:0
}
.module 'coreclr-jit-why-mov-now.dll' // GUID = {D17A0BF9-FA0E-4D55-84FD-7219AB98C9C7}

.custom instance void class [mscorlib]System.Security.UnverifiableCodeAttribute::'.ctor'() =  (01 00 00 00 ) // ....

.stackreserve 0x400000

.namespace superfluous_mov
{
  .class private auto ansi beforefieldinit Program
  	extends [System.Runtime]System.Object
  {

    // method line 1
    .method private static hidebysig 
           default void Main (string[] args)  cil managed 
    {
        // Method begins at RVA 0x2048
	.entrypoint
	// Code size 6 (0x6)
	.maxstack 8
	IL_0000:  call void class superfluous_mov.Program::BugBugBug()
	IL_0005:  ret 
    } // end of method Program::Main

    // method line 2
    .method private static hidebysig 
           default void BugBugBug ()  cil managed unknown-flag-200 
    {
        // Method begins at RVA 0x2050
	// Code size 379 (0x17b)
	.maxstack 3
	.locals init (
		int32	V_0,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_1,
		int32*	V_2,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_3,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_4,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_5,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_6,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_7,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_8,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_9,
		class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>	V_10,
		unsigned int64	V_11,
		unsigned int64	V_12)
	IL_0000:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>::get_Count()
	IL_0005:  stloc.0 
	IL_0006:  ldc.i4.s 0x64
	IL_0008:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::Create(int32)
	IL_000d:  stloc.1 
	IL_000e:  ldc.i4 256
	IL_0013:  conv.u 
	IL_0014:  localloc 
	IL_0016:  stloc.2 
	IL_0017:  ldloc.2 
	IL_0018:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_001d:  stloc.3 
	IL_001e:  ldloc.2 
	IL_001f:  ldloc.0 
	IL_0020:  conv.i 
	IL_0021:  ldc.i4.4 
	IL_0022:  mul 
	IL_0023:  add 
	IL_0024:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0029:  stloc.s 4
	IL_002b:  ldloc.2 
	IL_002c:  ldc.i4.2 
	IL_002d:  ldloc.0 
	IL_002e:  mul 
	IL_002f:  conv.i 
	IL_0030:  ldc.i4.4 
	IL_0031:  mul 
	IL_0032:  add 
	IL_0033:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0038:  stloc.s 5
	IL_003a:  ldloc.2 
	IL_003b:  ldc.i4.3 
	IL_003c:  ldloc.0 
	IL_003d:  mul 
	IL_003e:  conv.i 
	IL_003f:  ldc.i4.4 
	IL_0040:  mul 
	IL_0041:  add 
	IL_0042:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0047:  stloc.s 6
	IL_0049:  ldloc.2 
	IL_004a:  ldc.i4.4 
	IL_004b:  ldloc.0 
	IL_004c:  mul 
	IL_004d:  conv.i 
	IL_004e:  ldc.i4.4 
	IL_004f:  mul 
	IL_0050:  add 
	IL_0051:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0056:  stloc.s 7
	IL_0058:  ldloc.2 
	IL_0059:  ldc.i4.5 
	IL_005a:  ldloc.0 
	IL_005b:  mul 
	IL_005c:  conv.i 
	IL_005d:  ldc.i4.4 
	IL_005e:  mul 
	IL_005f:  add 
	IL_0060:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0065:  stloc.s 8
	IL_0067:  ldloc.2 
	IL_0068:  ldc.i4.6 
	IL_0069:  ldloc.0 
	IL_006a:  mul 
	IL_006b:  conv.i 
	IL_006c:  ldc.i4.4 
	IL_006d:  mul 
	IL_006e:  add 
	IL_006f:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0074:  stloc.s 9
	IL_0076:  ldloc.2 
	IL_0077:  ldc.i4.7 
	IL_0078:  ldloc.0 
	IL_0079:  mul 
	IL_007a:  conv.i 
	IL_007b:  ldc.i4.4 
	IL_007c:  mul 
	IL_007d:  add 
	IL_007e:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::LoadAlignedVector256(int32*)
	IL_0083:  stloc.s 10
	IL_0085:  ldloc.3 
	IL_0086:  ldloc.1 
	IL_0087:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_008c:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_0091:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_0096:  conv.u8 
	IL_0097:  stloc.s 11
	IL_0099:  ldloc.s 11
	IL_009b:  ldloc.s 4
	IL_009d:  ldloc.1 
	IL_009e:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_00a3:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_00a8:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_00ad:  conv.u8 
	IL_00ae:  ldc.i4.8 
	IL_00af:  shl 
	IL_00b0:  or 
	IL_00b1:  stloc.s 11
	IL_00b3:  ldloc.s 11
	IL_00b5:  ldloc.s 5
	IL_00b7:  ldloc.1 
	IL_00b8:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_00bd:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_00c2:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_00c7:  conv.u8 
	IL_00c8:  ldc.i4.s 0x10
	IL_00ca:  shl 
	IL_00cb:  or 
	IL_00cc:  stloc.s 11
	IL_00ce:  ldloc.s 11
	IL_00d0:  ldloc.s 6
	IL_00d2:  ldloc.1 
	IL_00d3:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_00d8:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_00dd:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_00e2:  conv.u8 
	IL_00e3:  ldc.i4.s 0x18
	IL_00e5:  shl 
	IL_00e6:  or 
	IL_00e7:  stloc.s 11
	IL_00e9:  ldloc.s 11
	IL_00eb:  ldloc.s 7
	IL_00ed:  ldloc.1 
	IL_00ee:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_00f3:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_00f8:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_00fd:  conv.u8 
	IL_00fe:  ldc.i4.s 0x20
	IL_0100:  shl 
	IL_0101:  or 
	IL_0102:  stloc.s 11
	IL_0104:  ldloc.s 11
	IL_0106:  ldloc.s 8
	IL_0108:  ldloc.1 
	IL_0109:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_010e:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_0113:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_0118:  conv.u8 
	IL_0119:  ldc.i4.s 0x28
	IL_011b:  shl 
	IL_011c:  or 
	IL_011d:  stloc.s 11
	IL_011f:  ldloc.s 11
	IL_0121:  ldloc.s 9
	IL_0123:  ldloc.1 
	IL_0124:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_0129:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_012e:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_0133:  conv.u8 
	IL_0134:  ldc.i4.s 0x30
	IL_0136:  shl 
	IL_0137:  or 
	IL_0138:  stloc.s 11
	IL_013a:  ldloc.s 11
	IL_013c:  ldloc.s 10
	IL_013e:  ldloc.1 
	IL_013f:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_0144:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_0149:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_014e:  conv.u8 
	IL_014f:  ldc.i4.s 0x38
	IL_0151:  shl 
	IL_0152:  or 
	IL_0153:  stloc.s 11
	IL_0155:  ldloc.s 11
	IL_0157:  call unsigned int64 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Popcnt/X64::PopCount(unsigned int64)
	IL_015c:  stloc.s 12
	IL_015e:  ldstr "{0}"
	IL_0163:  ldloc.s 12
	IL_0165:  box [System.Runtime]System.UInt64
	IL_016a:  call string string::Format(string, object)
	IL_016f:  call void class [mscorlib]System.Console::WriteLine(string)
	IL_0174:  call string class [mscorlib]System.Console::ReadLine()
	IL_0179:  pop 
	IL_017a:  ret 
    } // end of method Program::BugBugBug

    // method line 3
    .method public hidebysig specialname rtspecialname 
           instance default void '.ctor' ()  cil managed 
    {
        // Method begins at RVA 0x21d7
	// Code size 7 (0x7)
	.maxstack 8
	IL_0000:  ldarg.0 
	IL_0001:  call instance void object::'.ctor'()
	IL_0006:  ret 
    } // end of method Program::.ctor

  } // end of class superfluous_mov.Program
}

```

**Comment by mikedn** [comment]
Thanks! The IL is a bit broken (e.g. treats `Vector256<T>` as a class) but I managed to fix it. And yes, now I see the extra `mov` on both Windows and Linux:
```asm
       C5FC50C1             vmovmskps yrax, ymm1
       8BC0                 mov      eax, eax
       48C1E020             shl      rax, 32
       480BC7               or       rax, rdi
       488BF8               mov      rdi, rax
```

**Comment by mikedn** [comment]
This is an interesting case. When I compile your code I get IL like the following:
```
    IL_00d9:  ldloc.1
    IL_00da:  call       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>,
                                                                                                                                                                                       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
    IL_00df:  call       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32>(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
    IL_00e4:  call       int32 [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
    IL_00e9:  conv.u8
    IL_00ea:  ldc.i4.s   32
    IL_00ec:  shl
    IL_00ed:  or
    IL_00ee:  ldloc.s    V_7
    IL_00f0:  ldloc.1
    IL_00f1:  call       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>,
                                                                                                                                                                                       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
    IL_00f6:  call       valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32>(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
    IL_00fb:  call       int32 [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(valuetype [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
    IL_0100:  conv.u8
    IL_0101:  ldc.i4.s   40
    IL_0103:  shl
    IL_0104:  or
    IL_0105:  ldloc.s    V_8
    IL_0107:  ldloc.1
```
The `maskyMcBoatFace` variable is kept on the evaluation stack, at least for as long as this `or` chain holds.

In your IL the variable the value is stored in an actual location:
```
	IL_0104:  ldloc.s 11
	IL_0106:  ldloc.s 8
	IL_0108:  ldloc.1 
	IL_0109:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32> class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx2::CompareGreaterThan(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>, class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<int32>)
	IL_010e:  call class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32> class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256::AsSingle<int32> (class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<!!0>)
	IL_0113:  call int32 class [System.Private.CoreLib]System.Runtime.Intrinsics.X86.Avx::MoveMask(class [System.Private.CoreLib]System.Runtime.Intrinsics.Vector256`1<float32>)
	IL_0118:  conv.u8 
	IL_0119:  ldc.i4.s 0x28
	IL_011b:  shl 
	IL_011c:  or 
	IL_011d:  stloc.s 11
	IL_011f:  ldloc.s 11
```
I'm not sure where this IL difference comes from but it probably doesn't matter, the JIT should be able to handle this better.

The problem seems to be related to register allocation, though I'm not sure if the register allocator can handle this alone. Ultimately we get something like:
```
V11 = OR expr, V11
```
but since on x86 the first source operand is also the destination there's little that the register allocator can do, short of taking advantage of commutativity and swapping the operands. I vaguely remember that there is some codegen code that's supposed to do something like this, gotta take a closer look.

In the meantime I tried to change the above into
```
V11 = OR V11, expr
```
in lowering and it does fix this issue (and FX diff shows a 789 bytes improvement).

**Comment by kunalspathak** [comment]
I don't see any extra moves from the main at 8d66372138f. Feel free to reopen with updated information if this is still problematic.

<details>
<summary>Assembly code for Linux/x64</summary>

```asm
; Assembly listing for method superfluous_mov.Program:BugBugBug()
; Emitting BLENDED_CODE for X64 CPU with AVX - Unix
; optimized code
; rbp based frame
; partially interruptible
; No PGO data
; 3 inlinees with PGO data; 4 single block inlinees; 0 inlinees without PGO data
; invoked as altjit
; Final local variable assignments
;
;* V00 loc0         [V00    ] (  0,  0   )     int  ->  zero-ref    single-def
;* V01 loc1         [V01,T07] (  0,  0   )  simd32  ->  zero-ref    single-def
;* V02 loc2         [V02    ] (  0,  0   )  simd32  ->  zero-ref   
;* V03 loc3         [V03    ] (  0,  0   )  simd32  ->  zero-ref   
;* V04 loc4         [V04    ] (  0,  0   )  simd32  ->  zero-ref   
;* V05 loc5         [V05    ] (  0,  0   )  simd32  ->  zero-ref   
;* V06 loc6         [V06    ] (  0,  0   )  simd32  ->  zero-ref   
;* V07 loc7         [V07    ] (  0,  0   )  simd32  ->  zero-ref   
;* V08 loc8         [V08    ] (  0,  0   )  simd32  ->  zero-ref   
;* V09 loc9         [V09    ] (  0,  0   )  simd32  ->  zero-ref   
;  V10 loc10        [V10,T04] (  2,  2   )    long  ->  rbx         single-def
;  V11 loc11        [V11    ] (  7,  7   )  struct (40) [rbp-40H]   do-not-enreg[XSF] must-init addr-exposed ld-addr-op
;# V12 OutArgs      [V12    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   "OutgoingArgSpace"
;  V13 tmp1         [V13,T00] (  9, 18   )    long  ->  rdi         "dup spill"
;* V14 tmp2         [V14    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impAppendStmt"
;* V15 tmp3         [V15    ] (  0,  0   )     int  ->  zero-ref    "spilling ret_expr"
;  V16 tmp4         [V16,T02] (  2,  4   )     ref  ->  rax         class-hnd single-def "dup spill"
;  V17 tmp5         [V17,T01] (  5,  4   )     ref  ->  rax         class-hnd "Inline stloc first use temp"
;* V18 tmp6         [V18    ] (  0,  0   )     int  ->  zero-ref    "Inline return value spill temp"
;* V19 tmp7         [V19    ] (  0,  0   )  struct (16) zero-ref    ld-addr-op "NewObj constructor temp"
;  V20 tmp8         [V20,T05] (  3,  1.50)   byref  ->  r14         V19._reference(offs=0x00) P-INDEP "field V19._reference (fldOffset=0x0)"
;  V21 tmp9         [V21,T06] (  3,  1.50)     int  ->  r15         V19._length(offs=0x08) P-INDEP "field V19._length (fldOffset=0x8)"
;  V22 tmp10        [V22,T03] (  2,  4   )     ref  ->  rdi         single-def "argument with side effect"
;  V23 GsCookie     [V23    ] (  1,  1   )    long  ->  [rbp-48H]   do-not-enreg[X] addr-exposed "GSSecurityCookie"
;
; Lcl frame size = 56

G_M61111_IG01:
       push     rbp
       push     r15
       push     r14
       push     rbx
       sub      rsp, 56
       vzeroupper 
       lea      rbp, [rsp+50H]
       vxorps   xmm8, xmm8
       vmovdqa  xmmword ptr [rbp-40H], xmm8
       vmovdqa  xmmword ptr [rbp-30H], xmm8
       xor      eax, eax
       mov      qword ptr [rbp-20H], rax
       mov      rax, 0xD1FFAB1E
       mov      qword ptr [rbp-48H], rax
						;; size=53 bbWeight=1    PerfScore 12.58
G_M61111_IG02:
       mov      edi, 16
						;; size=5 bbWeight=1    PerfScore 0.25
G_M61111_IG03:
       push     0
       push     0
       dec      rdi
       jne      SHORT G_M61111_IG03
       lea      rdi, [rsp]
       vmovdqa  ymm0, ymmword ptr[rdi]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrsi, ymm0
       mov      esi, esi
       vmovdqa  ymm0, ymmword ptr[rdi+20H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 8
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+40H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 16
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+60H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 24
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+80H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 32
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+A0H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 40
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+C0H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrax, ymm0
       mov      eax, eax
       shl      rax, 48
       or       rsi, rax
       vmovdqa  ymm0, ymmword ptr[rdi+E0H]
       vpcmpgtd ymm0, ymm0, ymmword ptr[reloc @RWD00]
       vmovmskps yrdi, ymm0
       mov      edi, edi
       shl      rdi, 56
       or       rdi, rsi
       xor      ebx, ebx
       popcnt   rbx, rdi
       mov      rdi, 0xD1FFAB1E
       mov      esi, 8
       call     CORINFO_HELP_CLASSINIT_SHARED_DYNAMICCLASS
       mov      rdi, 0xD1FFAB1E      ; data for System.Buffers.ArrayPool`1[ushort]:s_shared
       mov      rdi, gword ptr [rdi]
       mov      esi, 256
       mov      rax, 0xD1FFAB1E      ; code for System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1[ushort]:Rent(int):ushort[]:this
       cmp      dword ptr [rdi], edi
       call     [rax]System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1[ushort]:Rent(int):ushort[]:this
       mov      gword ptr [rbp-38H], rax
       test     rax, rax
       je       SHORT G_M61111_IG08
						;; size=293 bbWeight=1    PerfScore 113.75
G_M61111_IG04:
       lea      r14, bword ptr [rax+10H]
       mov      r15d, dword ptr [rax+08H]
						;; size=8 bbWeight=0.50 PerfScore 1.25
G_M61111_IG05:
       mov      bword ptr [rbp-28H], r14
       mov      dword ptr [rbp-20H], r15d
       xor      edi, edi
       mov      dword ptr [rbp-30H], edi
       mov      byte  ptr [rbp-2CH], 0
       lea      rdi, [rbp-40H]
       mov      rsi, rbx
       mov      rax, 0xD1FFAB1E      ; code for System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:AppendFormatted[ulong](ulong):this
       call     [rax]System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:AppendFormatted[ulong](ulong):this
       lea      rdi, [rbp-40H]
       mov      rax, 0xD1FFAB1E      ; code for System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:ToStringAndClear():System.String:this
       call     [rax]System.Runtime.CompilerServices.DefaultInterpolatedStringHandler:ToStringAndClear():System.String:this
       mov      rdi, rax
       mov      rax, 0xD1FFAB1E      ; code for System.Console:WriteLine(System.String)
       call     [rax]System.Console:WriteLine(System.String)
       mov      rax, 0xD1FFAB1E      ; code for System.Console:ReadLine():System.String
       call     [rax]System.Console:ReadLine():System.String
       mov      rdi, 0xD1FFAB1E
       cmp      qword ptr [rbp-48H], rdi
       je       SHORT G_M61111_IG06
       call     CORINFO_HELP_FAIL_FAST
						;; size=100 bbWeight=1    PerfScore 23.00
G_M61111_IG06:
       nop      
						;; size=1 bbWeight=1    PerfScore 0.25
G_M61111_IG07:
       vzeroupper 
       lea      rsp, [rbp-18H]
       pop      rbx
       pop      r14
       pop      r15
       pop      rbp
       ret      
						;; size=14 bbWeight=1    PerfScore 4.50
G_M61111_IG08:
       xor      r14, r14
       xor      r15d, r15d
       jmp      SHORT G_M61111_IG05
						;; size=8 bbWeight=0    PerfScore 0.00
RWD00  	dq	0000006400000064h, 0000006400000064h, 0000006400000064h, 0000006400000064h


; Total bytes of code 482, prolog size 53, PerfScore 203.78, instruction count 114, allocated bytes for code 482 (MethodHash=23a51148) for method superfluous_mov.Program:BugBugBug()
; ============================================================



```
