### ISSUE TITLE
SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName sometimes fails on Browser CI

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43103]
Sample failure: https://helix.dot.net/api/2019-06-17/jobs/00fe3aa1-bb24-4843-81fe-7f699ea9f116/workitems/System.Runtime.Loader.Tests/console

```
[04:58:07] fail: [FAIL] System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(alc: "Empty", assemblyName: "ReferencedClassLibNeutralIsSatellite", culture: "en")
[04:58:07] info: Assert.Same() Failure
[04:58:07] info: Expected: "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
[04:58:07] info: Actual:   "Empty" System.Runtime.Loader.AssemblyLoadContext #4
[04:58:07] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(String alc, String assemblyName, String culture)
[04:58:07] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[04:58:07] fail: [FAIL] System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(alc: "LoadFile", assemblyName: "ReferencedClassLibNeutralIsSatellite", culture: "es")
[04:58:07] info: Assert.Equal() Failure
[04:58:07] info:            â†“ (pos 1)
[04:58:07] info: Expected: es
[04:58:07] info: Actual:   en
[04:58:07] info:            â†‘ (pos 1)
[04:58:07] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(String alc, String assemblyName, String culture)
[04:58:07] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[04:58:07] fail: [FAIL] System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(alc: "ReferencedClassLib", assemblyName: "ReferencedClassLibNeutralIsSatellite", culture: "es")
[04:58:07] info: Assert.Equal() Failure
[04:58:07] info:            â†“ (pos 1)
[04:58:07] info: Expected: es
[04:58:07] info: Actual:   en
[04:58:07] info:            â†‘ (pos 1)
[04:58:07] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(String alc, String assemblyName, String culture)
[04:58:07] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[04:58:07] info: Finished:    System.Runtime.Loader.Tests.dll
```

I suspect this will go away with my next batch of bundle changes, but disabling until then to help keep CI clean.

**Comment by pavelsavara** [comment]
@lewing @Daniel-Genkin could this be caused also by missing `await` on resource loading ? Just wild guess on my part.

**Comment by radekdoulik** [comment]
@CoffeeFlux is this still happening?

**Comment by radekdoulik** [comment]
Seems to run fine for me on windows/chrome 92
```
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 124, Errors: 0, Failed: 0, Skipped: 2, Time: 0.437s
```

**Comment by CoffeeFlux** [comment]
It's possible I fixed this and forgot to re-enable the test, but it was flaky so it sometimes passing is to be expected.

**Comment by ilonatommy** [comment]
@CoffeeFlux, we need a solid confirmation that this is still happening, please. Otherwise I will close the issue.

**Comment by CoffeeFlux** [comment]
@ilonatommy I no longer work at Microsoft, so I'm not sure if it still happens. I haven't looked at CI results in over a year :)

My recollection of the timeline here is that the test was somewhat flaky (failing maybe 2-3/100 times?), I disabled it, and then eventually re-enabled it with some additional loader changes. I don't recall whether it continued to be flaky after that, you'd have to look. Unless things have changed, tools like runfo should help you figure out pretty easily whether it's still happening.

**Comment by ilonatommy** [comment]
Closing due to no failures in the last month: https://runfo.azurewebsites.net/search/tests/?q=name%3ASatelliteLoadsCorrectly.
