### ISSUE TITLE
[Wasm][AOT] System.IO.DirectoryNotFoundException And System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#49232]
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.

- [ ] `System.IO.DirectoryNotFoundException : Could not find a part of the path`
System.Xml.Xsl.XslCompiledTransformApi.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.Xsl.XslCompiledTransformApi.Tests/console.09a0c4d6.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - See also #50196 and https://github.com/dotnet/runtime/issues/50229 this needs to be verified of which is the error before time is spent on fixing.
System.Xml.Xsl.XslTransformApi.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.Xsl.XslTransformApi.Tests/console.9eff6ee6.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - https://github.com/dotnet/runtime/issues/50229
System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/console.cb58f9bb.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - https://github.com/dotnet/runtime/issues/50229
~~System.Data.DataSetExtensions.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Data.DataSetExtensions.Tests/console.0aa225ef.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - https://github.com/dotnet/runtime/issues/50229
~~System.ServiceModel.Syndication.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ServiceModel.Syndication.Tests/console.21df5670.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) 
~~System.IO.Compression.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.IO.Compression.Tests/console.351fd459.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
System.Xml.XmlSchemaSet.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.XmlSchemaSet.Tests/console.db811c0b.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - ~~Same as #46731~~ - See below for failed test run not longer fails with original issue but may be contributed to https://github.com/dotnet/runtime/issues/50229
~~System.IO.Compression.ZipFile.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.IO.Compression.ZipFile.Tests/console.3717c8b9.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
~~System.Xml.XmlResolver.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.XmlResolver.Tests/console.a8c69f01.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
~~System.Xml.RW.XmlSystemPathResolver.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.RW.XmlSystemPathResolver.Tests/console.1249b510.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

- [ ] `System.IO.FileNotFoundException : Could not find file`
System.Reflection.Metadata.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Reflection.Metadata.Tests/console.2b15b3e6.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)  -  See Also https://github.com/dotnet/runtime/issues/50158 (which is Closed by https://github.com/mono/linker/issues/1913)
~~System.IO.Packaging.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.IO.Packaging.Tests/console.25914a62.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
System.Reflection.MetadataLoadContext.Tests [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Reflection.MetadataLoadContext.Tests/console.5dd83fdc.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D) - See also #50171
~~System.Xml.XmlDocument.Tests~~ [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.XmlDocument.Tests/console.03785153.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

Repro:
Check out changes in
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by fanyang-mono** [comment]
These tests are now failing with this new syndrome:
```
  Fatal error in IL Linker
  Unhandled exception. System.Xml.XmlException: The 'assembly' start tag on line 12 position 4 does not match the end tag of 'linker'. Line 17, position 3.
     at System.Xml.XmlTextReaderImpl.Throw(Exception e)
     at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
     at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
     at System.Xml.XmlTextReaderImpl.ParseEndElement()
     at System.Xml.XmlTextReaderImpl.ParseElementContent()
     at System.Xml.XmlTextReaderImpl.Read()
     at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
     at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
     at Mono.Linker.Driver.SetupContext(ILogger customLogger)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)```

**Comment by kjpou1** [comment]
@fanyang-mono all the test are failing with the above?

**Comment by kjpou1** [comment]
Was looking at this and it seems suspiciously close to the error I fixed with https://github.com/emscripten-core/emscripten/pull/13549.  Looks like the same set of tests as well.

**Comment by fanyang-mono** [comment]
@kjpou1 You are right. I am going through every each of them to see which ones are still failing.

**Comment by kjpou1** [comment]
This is what I am getting for System.Xml.Xsl.XslCompiledTransformApi.Tests with running the command

From [head](https://github.com/dotnet/runtime/commit/bcc7e0e0ce1758322015675356efc121b211e312).

```
dotnet.sh build /t:Test /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release src/libraries/System.Private.Xml/tests/Xslt/XslCompiledTransformApi/System.Xml.Xsl.XslCompiledTransformApi.Tests.csproj
```

```
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  System.Xml.Xsl.XslCompiledTransformApi.Tests -> /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.Xsl.XslCompiledTransformApi.Tests/net6.0-Release/browser-wasm/publish/
  AOT'ing 34 assemblies
  Compiling native assets with emcc. This may take a while ...
  XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.Xsl.XslCompiledTransformApi.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll System.Xml.Xsl.XslCompiledTransformApi.Tests.dll -notrait category=OuterLoop -notrait category=failing
  info: 07:17:16.4324380 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Xml.Xsl.XslCompiledTransformApi.Tests.dll -notrait category=OuterLoop -notrait category=failing
        
        
  info: console.info: Arguments: --run,WasmTestRunner.dll,System.Xml.Xsl.XslCompiledTransformApi.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: console.info: Initializing.....
  info: Could not find constructor for 'Xunit.Sdk.CollectionPerAssemblyTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
  info: Discovering: System.Xml.Xsl.XslCompiledTransformApi.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  System.Xml.Xsl.XslCompiledTransformApi.Tests.dll (found 84 of 84 test cases)
  info: Could not find constructor for 'Xunit.Sdk.CollectionPerAssemblyTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
  info: Starting:    System.Xml.Xsl.XslCompiledTransformApi.Tests.dll
  fail: [FAIL] System.Xml.Tests.CLoadReaderTest.LoadXmlReader5
  info: System.Xml.Tests.VerifyException : GetManifestResourceStream() failed
  info: 
  fail: [FAIL] System.Xml.Tests.CLoadReaderTest.LoadXmlReader2
  info: System.Xml.Tests.VerifyException : GetManifestResourceStream() failed
  info: 
  fail: [FAIL] System.Xml.Tests.CLoadXPathNavigableTest.LoadNavigator4
  info: Assert.Equal() Failure
  info:                    ↓ (pos 9)
  info: Expected: Compiling JScript/CSharp scripts is not supported
  info: Actual:   CompilingScriptsNotSupported
  info:                    ↑ (pos 9)
  info: 
  fail: [FAIL] System.Xml.Tests.XPathNodeIteratorTests.NodeIter2
  info: Assert.Equal() Failure
  info:                    ↓ (pos 9)
  info: Expected: Compiling JScript/CSharp scripts is not supported
  info: Actual:   CompilingScriptsNotSupported
  info:                    ↑ (pos 9)
  info: 
  fail: [FAIL] System.Xml.Tests.XPathNodeIteratorTests.NodeIter1
  info: Assert.Equal() Failure
  info:                    ↓ (pos 9)
  info: Expected: Compiling JScript/CSharp scripts is not supported
  info: Actual:   CompilingScriptsNotSupported
  info:                    ↑ (pos 9)
  info: 
  fail: [FAIL] System.Xml.Tests.CTransformStrStrTest.TransformStrStr9
  info: System.Xml.Tests.VerifyException : GetManifestResourceStream() failed
  info: 
  info: Finished:    System.Xml.Xsl.XslCompiledTransformApi.Tests.dll
  info: 
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 84, Errors: 0, Failed: 6, Skipped: 0, Time: 0.7447028s
  info: 
  info: 07:17:19.2721920 Process v8 exited with 1
        
  fail: Application has finished with exit code 1 but 0 was expected
  XHarness exit code: 71 (GENERAL_FAILURE)
  XHarness artifacts: /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.Xsl.XslCompiledTransformApi.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

**Comment by kjpou1** [comment]
From head https://github.com/dotnet/runtime/commit/bcc7e0e0ce1758322015675356efc121b211e312

```
  System.ServiceModel.Syndication.Tests -> /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.ServiceModel.Syndication.Tests/net6.0-Release/browser-wasm/System.ServiceModel.Syndication.Tests.dll
  System.ServiceModel.Syndication.Tests -> /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.ServiceModel.Syndication.Tests/net6.0-Release/browser-wasm/publish/
  AOT'ing 179 assemblies
  Compiling native assets with emcc. This may take a while ...
  XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.ServiceModel.Syndication.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll System.ServiceModel.Syndication.Tests.dll -notrait category=OuterLoop -notrait category=failing
  info: 12:27:16.9268890 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.ServiceModel.Syndication.Tests.dll -notrait category=OuterLoop -notrait category=failing
        
        
  info: console.info: Arguments: --run,WasmTestRunner.dll,System.ServiceModel.Syndication.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: console.info: Initializing.....
  info: Discovering: System.ServiceModel.Syndication.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  System.ServiceModel.Syndication.Tests.dll (found 776 of 776 test cases)
  info: Starting:    System.ServiceModel.Syndication.Tests.dll
  info: Finished:    System.ServiceModel.Syndication.Tests.dll
  info: 
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 1308, Errors: 0, Failed: 0, Skipped: 0, Time: 6.326247s
  info: 
  info: 12:27:26.2675330 Process v8 exited with 0
        
  info: Application has finished with exit code: 0
  XHarness exit code: 0
  XHarness artifacts: /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.ServiceModel.Syndication.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

**Comment by kjpou1** [comment]
System.Xml.XmlSchemaSet.Tests
---

```
  System.Xml.XmlSchemaSet.Tests -> /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.XmlSchemaSet.Tests/net6.0-Release/browser-wasm/System.Xml.XmlSchemaSet.Tests.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  System.Xml.XmlSchemaSet.Tests -> /Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.XmlSchemaSet.Tests/net6.0-Release/browser-wasm/publish/
  AOT'ing 32 assemblies
  Compiling native assets with emcc. This may take a while ...
  XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/Jimmy/websharp/projects/runtime-release/artifacts/bin/System.Xml.XmlSchemaSet.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll System.Xml.XmlSchemaSet.Tests.dll -notrait category=OuterLoop -notrait category=failing
  info: 06:52:53.3630620 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Xml.XmlSchemaSet.Tests.dll -notrait category=OuterLoop -notrait category=failing
        
        
  info: console.info: Arguments: --run,WasmTestRunner.dll,System.Xml.XmlSchemaSet.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: console.info: Initializing.....
  info: Discovering: System.Xml.XmlSchemaSet.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  System.Xml.XmlSchemaSet.Tests.dll (found 258 of 258 test cases)
  info: Starting:    System.Xml.XmlSchemaSet.Tests.dll
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.InvalidAllElementMax_Throws
  info: Assert.Contains() Failure
  info: Not found: all
  info: In value:  Sch_InvalidAllElementMax
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.InvalidExemplar_Throws
  info: Assert.Contains() Failure
  info: Not found: substitutionGroup
  info: In value:  Sch_InvalidExamplar
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.MaxLengthGtBaseMaxLength_Throws
  info: Assert.Contains() Failure
  info: Not found: maxLength
  info: In value:  Sch_MaxLengthGtBaseMaxLength
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.MinLengthLtBaseMinLength_Throws
  info: Assert.Contains() Failure
  info: Not found: minLength
  info: In value:  Sch_MinLengthGtBaseMinLength
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.InvalidAllMax_Throws
  info: Assert.Contains() Failure
  info: Not found: all
  info: In value:  Sch_InvalidAllMax
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.LengthGtBaseLength_Throws
  info: Assert.Contains() Failure
  info: Not found: length
  info: In value:  Sch_LengthGtBaseLength
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.FractionDigitsMismatch_Throws
  info: Assert.Contains() Failure
  info: Not found: fractionDigits
  info: In value:  Sch_FractionDigitsMismatch
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.GroupBaseRestNotEmptiable_Throws
  info: Assert.Contains() Failure
  info: Not found: particle
  info: In value:  Sch_InvalidParticleRestrictionDetailed
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.MinLengthGtMaxLength_Throws
  info: Assert.Contains() Failure
  info: Not found: minLength
  info: In value:  Sch_MinLengthGtMaxLength
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_Compile.FractionDigitsFacetBaseFixed_Throws
  info: Assert.Contains() Failure
  info: Not found: fixed
  info: In value:  Sch_FacetBaseFixed
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v1
  info: Assert.Equal() Failure
  info: Expected: True
  info: Actual:   False
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v2
  info: Assert.Equal() Failure
  info: Expected: True
  info: Actual:   False
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v14
  info: Assert.Equal() Failure
  info: Expected: True
  info: Actual:   False
  info: 
  fail: [FAIL] System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v15
  info: Assert.Equal() Failure
  info: Expected: True
  info: Actual:   False
  info: 
  info: Finished:    System.Xml.XmlSchemaSet.Tests.dll
  info: 
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 258, Errors: 0, Failed: 14, Skipped: 0, Time: 2.125316s
  info: 
  info: 06:52:57.0908410 Process v8 exited with 1
        
  fail: Application has finished with exit code 1 but 0 was expected
```

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
