### ISSUE TITLE
crossgen2 doesn't call DllMain on the JIT

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#49525]
This is specific to PAL, Linux implementations.

The JIT uses the DllMain() `DLL_PROCESS_DETACH` event to call `jitShutdown()`, which is output various information under various debugging modes, and close stdout if being unloaded.

More importantly, SuperPMI uses `DLL_PROCESS_ATTACH` to initialize the PAL (on Unix), initialize the logger, and `DLL_PROCESS_DETACH` to shutdown the logger. Because the PAL isn't initialized, SuperPMI crashes (issue: https://github.com/dotnet/runtime/issues/47960)

@dotnet/crossgen-contrib @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
AFAICT, crossgen2 doesn't call `ICorJitCompiler::ProcessShutdownWork()` either.

**Comment by jkotas** [comment]
Can we change SuperPMI to use `jitStartup` / `ICorJitCompiler::ProcessShutdownWork` for the initialization/shutdown instead of depending on the Win32 DllMain emulator?

> crossgen2 doesn't call ICorJitCompiler::ProcessShutdownWork() either

I agree that we should fix this one.

**Comment by BruceForstall** [comment]
> Can we change SuperPMI to use jitStartup / ICorJitCompiler::ProcessShutdownWork for the initialization/shutdown instead of depending on the Win32 DllMain emulator?

I'm sure we could make that work.

I hadn't noticed before, but even though the JIT uses DllMain `DLL_PROCESS_DETACH` to call its `jitShutdown()` function, `jitShutdown()` is also called by the `ProcessShutdownWork()` API (and the JIT makes sure shutdown only happens once). It appears that _possibly_ only the DllMain shutdown code gets called if, by the comments, "FreeLibrary has been called or the DLL load failed". Maybe we don't need to worry about those cases.

**Comment by trylek** [comment]
Fixed by https://github.com/dotnet/runtime/pull/49531, closing.

**Comment by BruceForstall** [comment]
@trylek, #49531 only worked around the problem, and only for SuperPMI. The problem still exists: we either need crossen2 to call DllMain on attach and detach, like on Windows, or we need a new "shutdown" API call.
