### ISSUE TITLE
CG2 - runtime crash in JIT\SIMD\Ldfld_r\Ldfld_r.cmd / JIT\SIMD\Ldfld_ro\Ldfld_ro.cmd

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#53561]
OS: **Windows**
Architecture: **arm**
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1165903&view=ms.vss-test-web.build-test-results-tab&runId=35147350&resultId=109232&paneView=debug

Diagnostic information:

<pre>
 Starting:    JIT.SIMD.XUnitWrapper
    JIT\SIMD\Ldfld_r\Ldfld_r.cmd [FAIL]
      Could Not Find D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\Ldfld_r.dll.rsp
      
      Return code:      1
      Raw output file:      D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Reports\JIT.SIMD\Ldfld_r\Ldfld_r.output.txt
      Raw output:
      BEGIN EXECUTION
      Ldfld_r.dll
              1 file(s) copied.
      Response file: D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\\Ldfld_r.dll.rsp
      D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\IL-CG2\Ldfld_r.dll
      -o:D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\\Ldfld_r.dll
      --targetarch:arm
      --verify-type-and-field-layout
      -r:D:\h\w\A64C0919\p\System.*.dll
      -r:D:\h\w\A64C0919\p\Microsoft.*.dll
      -r:D:\h\w\A64C0919\p\mscorlib.dll
      -r:D:\h\w\A64C0919\p\netstandard.dll
      -O
      " "dotnet" "D:\h\w\A64C0919\p\crossgen2\crossgen2.dll" @"D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\\Ldfld_r.dll.rsp"   -r:D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\IL-CG2\*.dll"
      Emitting R2R PE file: D:\h\w\A64C0919\w\A9700971\e\JIT\SIMD\Ldfld_r\\Ldfld_r.dll
       "D:\h\w\A64C0919\p\corerun.exe"  Ldfld_r.dll 
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      FAILED
</pre>

/cc @dotnet/crossgen-contrib

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr r2r 20210609.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1179293&view=ms.vss-test-web.build-test-results-tab&runId=35496632&resultId=108108&paneView=debug)

Failed tests:
```
R2R Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/SIMD/Ldfld_r/Ldfld_r.sh
- JIT/SIMD/Ldfld_ro/Ldfld_ro.sh

```
**Error message:**
```
/root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.sh: line 258: -r:/root/helix/work/workitem/JIT/SIMD/Ldfld_r/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.dll.rsp': No such file or directory

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/Ldfld_r/Ldfld_r.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/JIT/SIMD/Ldfld_r/IL-CG2/Ldfld_r.dll
Response file: /root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.dll.rsp
/root/helix/work/workitem/JIT/SIMD/Ldfld_r/IL-CG2/Ldfld_r.dll
-o:/root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.dll
in ReleaseLock
/root/helix/work/correlation/corerun Ldfld_r.dll ''
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/JIT/SIMD/Ldfld_r/Ldfld_r.sh
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._Ldfld_r_Ldfld_r_._Ldfld_r_Ldfld_r_sh()
```

**Comment by mangod9** [comment]
this should be fixed with the field layout changes.

**Comment by am11** [comment]
These issues were closed but still present in the [exclude list](https://github.com/dotnet/runtime/blob/22cee85aa08061e5b2c1e893797a860e3c642e6c/src/tests/issues.targets#L906-L967) (one or more times):
* https://github.com/dotnet/runtime/issues/53561
* https://github.com/dotnet/runtime/issues/43498
* https://github.com/dotnet/runtime/issues/43461
* https://github.com/dotnet/runtime/issues/38291
