### ISSUE TITLE
BadImageFormatException using c# 9 override + generics

### ISSUE THREAD

**Issue by michaelcheers** [dotnet/runtime#54719]
### Description

See on DotNetFiddle: [https://dotnetfiddle.net/2xzsry](https://dotnetfiddle.net/2xzsry)

```csharp
new Derived();

public class IA { }
public class IB { }

public abstract class Base
{
    public abstract IA Key { get; }
    public abstract IB Value { get; }
}
public sealed class Derived : Base<IB>
{
    public class A : IA { }
    public sealed override A Key => default;
}
public abstract class Base<B> : Base where B : IB
{
    public sealed override B Value => null;
}
```

### Configuration

Latest .NET 5 & .NET 6.0 preview

### Other information

BadImageFormatException
`An attempt was made to load a program with an incorrect format.`

**Comment by huoyaoyuan** [comment]
Certain bug about covariant return was identified in the first release of 5.0. Can you confirm they are on the latest patch? The bugs were fixed in patch versions.

**Comment by hez2010** [comment]
Can reproduce in .NET 5.0.7 and .NET 6 preview 5.

**Comment by michaelcheers** [comment]
I installed Visual Studio 2022 preview yesterday as this issue was very frustrating but it did not fix the issue.

**Comment by wzchua** [comment]
if you change the order of Key and Value in Base, it runs
```cs
public abstract class Base
{
    public abstract IB Value { get; }
    public abstract IA Key { get; }
}
```
