### ISSUE TITLE
[mono][aot] Static virtual interface methods do not work with generic sharing

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#54910]
Related to https://github.com/dotnet/runtime/issues/49904

The new tests added in https://github.com/dotnet/runtime/pull/54650 do not work on the WebAssembly AOT lanes.

Stack traces look like this:
https://gist.github.com/lambdageek/eed2cbb34c6c133a29b0429c84e0365b

**Comment by lewing** [comment]
If these aren't going to work do we need to flag them for AOT for 6?

**Comment by marek-safar** [comment]
We discussed that with @lambdageek and we could not compile the managed APIs for browser-wasm

**Comment by lewing** [comment]
I assume that means the work to skip them is targeted for 6.0.0 though?

**Comment by vargaz** [comment]
Should be fixed by:
https://github.com/dotnet/runtime/pull/54981

**Comment by lambdageek** [comment]
This is still an ActiveIssue on some tests.
There's a separate build issue (that i'm working on in https://github.com/dotnet/runtime/pull/57071) but after that there is still an error on these tests like [in this comment](https://github.com/dotnet/runtime/pull/57071#issuecomment-895540274):

```
[19:59:19] fail: console.error: RuntimeError: function signature mismatch
                 
[19:59:19] fail: console.error: RuntimeError: function signature mismatch
                 
[19:59:19] fail:     at System_Runtime_Experimental_Tests_System_Tests_UIntPtrTests_GenericMath_CreateSaturatingFromInt32Test (<anonymous>:wasm-function[13094]:0x43dcac)
                 
[19:59:19] fail:     at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_void_ (<anonymous>:wasm-function[33266]:0xaa1d49)
                 
[19:59:19] fail:     at jit_call_cb (<anonymous>:wasm-function[52301]:0x12d5d3c)
                 
[19:59:19] fail:     at invoke_vi (dotnet.js:10804:25)
                 
[19:59:19] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[68979]:0x14a4cc7)
                 
[19:59:19] fail:     at do_jit_call (<anonymous>:wasm-function[52260]:0x12d4de8)
                 
[19:59:19] fail:     at interp_exec_method (<anonymous>:wasm-function[52197]:0x12c7ba7)
```
