### ISSUE TITLE
System.Text.Json using ReferenceLoopHandling.Ignore in a ASP.NET Core WebApi application results in duplicate string values being set to null

### ISSUE THREAD

**Issue by grantcolley** [dotnet/runtime#55411]
### The Bug
`System.Text.Json` setting `ReferenceLoopHandling` to `ReferenceLoopHandling.Ignore` in a **ASP.NET Core WebApi** application results in duplicate string values being set to null.

### The workaround
Until this is fix I have to [set the default JSON serializer for my ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support) projects back to Newtonsoft.Json (Json.NET).

### To Reproduce

1. Create an **ASP.NET Core WebApi** application using standard project template. 

2. In Startup.cs `ConfigureServices` set `JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles`

```C#
            services.AddControllers()
                .AddJsonOptions(options =>
                    options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles);
```				
				
3. Add a new field `SummaryDupe` to the WeatherForecast class:

```C#
    public class WeatherForecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string Summary { get; set; }
		
	// add new field to hold duplicate value
        public string SummaryDupe { get; set; }
    }
```	
					
3. Hard code the results returned from `WeatherForecastController`'s **Get** method so `Summary` and `SummaryDupe` have the save value e.g. 'abc'.

```C#
        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = "abc",
                SummaryDupe = "abc"
            })
            .ToArray();
        }
```

4. When calling the controller `https://localhost:44344/weatherforecast` the result shows `SummaryDupe` has been nulled out

```C#
[
	{
		"date": "2021-07-04T18:55:16.0432847+01:00",
		"temperatureC": -5,
		"temperatureF": 24,
		"summary": "abc",
		"summaryDupe": null
	},
	{
		"date": "2021-07-05T18:55:16.0435082+01:00",
		"temperatureC": 32,
		"temperatureF": 89,
		"summary": "abc",
		"summaryDupe": null
	},
	{
		"date": "2021-07-06T18:55:16.0435105+01:00",
		"temperatureC": 20,
		"temperatureF": 67,
		"summary": "abc",
		"summaryDupe": null
	},
	{
		"date": "2021-07-07T18:55:16.0435109+01:00",
		"temperatureC": -12,
		"temperatureF": 11,
		"summary": "abc",
		"summaryDupe": null
	},
	{
		"date": "2021-07-08T18:55:16.0435111+01:00",
		"temperatureC": 51,
		"temperatureF": 123,
		"summary": "abc",
		"summaryDupe": null
	}
]
```

### Further technical details
I am using Visual Studio 2019 Preview although I suspect this was a bug introduced with the introduction of ReferenceHandler.IgnoreCycles [#40099](https://github.com/dotnet/runtime/issues/40099)

**Comment by eiriktsarpalis** [comment]
I believe this is a duplicate of https://github.com/dotnet/runtime/issues/51837 which has already been fixed for .NET 6. cc @Jozkee

**Comment by Jozkee** [comment]
Fixed in .NET 6 preview 2 https://github.com/dotnet/runtime/pull/52253. @grantcolley can you please try installing the latest SDK preview https://dotnet.microsoft.com/download/dotnet/6.0 (preview 6)?

**Comment by grantcolley** [comment]
@Jozkee  I installed 16.11.0 Preview 3.0 and followed the steps I provided above to reproduce the issue. Unfortunately the problem persists.

**Comment by Jozkee** [comment]
Can you please check your .NET SDK version on cmd, I want to make sure that you are using the right one.
To do that, run the following command:
```
dotnet --info
```

If your project contains a global.json file, run the command inside your project's directory.

You will see something similar to this:
```
C:\Users\david>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21308.63
 Commit:    3cf5784e2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21308.63\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21308.63 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by grantcolley** [comment]
This is what I am using:

```
PS C:\Users\grant\source\repos\WebApplication6> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Jozkee** [comment]
Hmmm it seems weird that you are facing this with preview3, FWIW I just tried to repro using your exact steps and the issue is not there:
```json
[{"date":"2021-07-15T23:36:17.1028988-07:00","temperatureC":-2,"temperatureF":29,"summary":"abc","summaryDupe":"abc"},{"date":"2021-07-16T23:36:17.1030465-07:00","temperatureC":50,"temperatureF":121,"summary":"abc","summaryDupe":"abc"},{"date":"2021-07-17T23:36:17.1030479-07:00","temperatureC":1,"temperatureF":33,"summary":"abc","summaryDupe":"abc"},{"date":"2021-07-18T23:36:17.1030481-07:00","temperatureC":17,"temperatureF":62,"summary":"abc","summaryDupe":"abc"},{"date":"2021-07-19T23:36:17.1030483-07:00","temperatureC":49,"temperatureF":120,"summary":"abc","summaryDupe":"abc"}]
```

It may be that you are using a NuGet version of System.Text.Json and you ar enot using the dlls from the .NET SDK. Can you please share your `WebApplication6.csproj`?

**Comment by grantcolley** [comment]
@Jozkee That's odd. 

To recreate the issue I use the standard `ASP.NET Core Web API` project template in `Visual Studio Community 2019 16.11.0 Preview 3.0`. I simply follow the exact steps above, compile, run and the problem persists.

Here is the project file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

</Project>
```

Let me know if there is any other information I can provide that may shed some more light on this.

**Comment by eiriktsarpalis** [comment]
It seems almost certain that an older version of STJ is being used because of local state or project configuration. Per @Jozkee's instructions would it be possible to try and run your console app from the command line.

If that doesn't help, would it be possible to share a standalone minimal reproduction that illustrates the issue?

**Comment by grantcolley** [comment]
@eiriktsarpalis I have run the app from the command line and there is no difference i.e. problem persists.

See attached for the code to replicate.

[WebApplication6.zip](https://github.com/dotnet/runtime/files/6825232/WebApplication6.zip)

 I notice my version of the .NET SDK is `6.0.100-preview.3.21202.5` and older than @Jozkee 's which (see above), appears to be `6.0.100-preview.5.21308.63`. Are you suggesting this is almost certainly the issue?

**Comment by Jozkee** [comment]
> See attached for the code to replicate.

Can't repro by running that project either. 

> Are you suggesting this is almost certainly the issue?

Yes, please try installing the latest preview from https://dotnet.microsoft.com/download/dotnet/6.0.

**Comment by eiriktsarpalis** [comment]
Looking at the merge date for #52253, I would say that the first release to incorporate the fix was preview 5. So it would be expected that preview 3 reproduces the issue still.

**Comment by Jozkee** [comment]
@eiriktsarpalis ah you are right, I completely overlooked that. Sorry for all the fuss.

**Comment by grantcolley** [comment]
Thanks @Jozkee @eiriktsarpalis
