### ISSUE TITLE
[QUIC] MsQuicStream ctor code shuffles

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55815]
We should move this before callback handler registration.
https://github.com/dotnet/runtime/blob/f59a132bfe9ff797f9d192d67f07673a13b6b29e/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L120-L124

We should set it before SetCallbackHandlerDelegate since we can get CONNECTION_CLOSED event and that needs this.
If we want to prevent decrementing stream count, we should explicitely unset here.
https://github.com/dotnet/runtime/blob/f59a132bfe9ff797f9d192d67f07673a13b6b29e/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L126

The same applies to outbound ctor.

**Comment by karelz** [comment]
It is unclear how often it shows up in CI -- we can't easily query Kusto for this :( ... bumping it to 6.0.
Per @CarnaViire it is simple fix. Given the (bad) impact on CI, we should try to get it in IMO ...

**Comment by karelz** [comment]
Test failures 7/30-8/19 (incl. PRs):

Day | Run | Test suite
-- | -- | --
8/17 | PR #57530 | System.Net.Http.Functional.Tests
8/17 | PR #57533 | System.Net.Http.Functional.Tests
8/17 | PR #57546 | System.Net.Http.Functional.Tests
8/17 | PR #57078 | System.Net.Http.Functional.Tests
8/17 | PR #57550 | System.Net.Http.Functional.Tests
8/17 | PR #57536 | System.Net.Http.Functional.Tests
8/17 | PR #57581 | System.Net.Http.Functional.Tests
8/17 | PR #57303 | System.Net.Http.Functional.Tests
8/17 | PR #57457 | System.Net.Http.Functional.Tests

**Comment by karelz** [comment]
Given the frequency in CI, we should backport it to 6.0. Reopening to track that.
@CarnaViire can you please kick off the backport? Thanks!

**Comment by ViktorHofer** [comment]
Yes, this is happening in release/6.0 as well: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57765-merge-d32bb18c1a0f47aba1/System.Net.Http.Functional.Tests/1/console.a56010ed.log?sv=2019-07-07&se=2021-09-09T00%3A07%3A38Z&sr=c&sp=rl&sig=bGIxW9Kk0xYnJ6I5POlZmWCK1EPNV1csEQDBxro7LHY%3D

> Given the frequency in CI, we should backport it to 6.0

Shouldn't we also backport into the rc1 branch?

**Comment by karelz** [comment]
@ViktorHofer 

> Shouldn't we also backport into the rc1 branch?

Depends on appetite for RC1.
I assumed we are primarily trying to stabilize it. MsQuic is Preview only in 6.0 and the RC1 branch won't be used that much / long.
I let @danmoseley decide if he wants it to RC1 as well when he gets back on Monday.

**Comment by ViktorHofer** [comment]
As long as the fix lands in any branch that will exist for the next few years I'm good. Was mostly curious about why RC1 vs RC2, stabilization of RC1 makes sense.

**Comment by karelz** [comment]
Fixed for 6.0 RC2 in release/6.0 branch in PR #57742
Fixed for 7.0 in PR #57655

**Comment by ViktorHofer** [comment]
I still see this failing in the release/6.0 branch:

```
Process terminated. Assertion failed.
Exception occurred during handling Stream SHUTDOWN_COMPLETE event: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(State state) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1368
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(State state, StreamEvent& evt) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1024
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 860
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 860
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(IntPtr stream, IntPtr context, StreamEvent& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 824
./RunTests.sh: line 162:    21 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Net.Http.Functional.Tests.runtimeconfig.json --depsfile System.Net.Http.Functional.Tests.deps.json xunit.console.dll System.Net.Http.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

Console: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57834-merge-50fbdb8a87b8472092/System.Net.Http.Functional.Tests/1/console.0270faad.log?sv=2019-07-07&se=2021-09-09T16%3A36%3A18Z&sr=c&sp=rl&sig=GJTBN6Lri4FKLk68D74US5wKkKQYe2DaqOc4PM3QB3U%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1307758&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb

@karelz can you please take a look?

**Comment by ViktorHofer** [comment]
Ah disregard. That failing test happened before the fix went into release/6.0
