### ISSUE TITLE
TimeZoneNotFoundException: The time zone ID 'America/Chicago' was not found on the local computer.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#60175]
I am using .NET RC1 Blazor WebAssembly Hosted App.
In my published app to Azure AppService(windows) which is deployed as self-contained i am running into timezone error.
The app works fine when running on my local dev box

In my Server Controller, i am trying to find the Timezone of business location as shown below.
   
`var timezoneLocation = TimeZoneInfo.FindSystemTimeZoneById(LocalTimeAtOrgLocation);`

but i get the following error.

```
Error Occured in  OrganizationController.GetActiveTokenAtOrgLocationTerminal System.TimeZoneNotFoundException: The time zone ID 'America/Chicago' was not found on the local computer.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at XXXXXV6New.Server.Controllers.OrganizationController.GetActiveTokenAtOrgLocationTerminal(Nullable`1 OrgLocationTerminalID) in C:\Users\admin\source\repos\XXXXXXXV6New\Server\Controllers\OrganizationController.cs:line 2995
```

**Comment by nssidhu** [comment]
Here is the GitHub repo
https://github.com/nssidhu/BlazorAppTimezone

**Comment by danmoseley** [comment]
@nssidhu is that a private repo? the link gives 404.

I think all we need is the snippet of code, the value you're passing to the API, and any details of your configuration (sounds like .NET 6.0 RC1 on Windows?)

**Comment by nssidhu** [comment]
> @nssidhu is that a private repo? the link gives 404.
> 
> I think all we need is the snippet of code, the value you're passing to the API, and any details of your configuration (sounds like .NET 6.0 RC1 on Windows?)

Yes it is using .NET 6 RC1.

C:\Users\admin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by danmoseley** [comment]
Ah - I missed that it was Blazor. @lewing I know we do special time zone things on Blazor..?

**Comment by svick** [comment]
According to [this SO question](https://stackoverflow.com/q/69005962/41071), Azure AppService uses the NLS globalization mode. That would explain this issues since support for IANA time zone IDs does not work in the NLS mode:

https://github.com/dotnet/runtime/blob/3de620787ab3962dcb89664a691cf917653d5bd2/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.FullGlobalizationData.cs#L10-L16

An answer to that question suggest using app local ICU to disable the NLS mode.

**Comment by danmoseley** [comment]
great find @svick BTW thank you.

**Comment by tarekgh** [comment]
I am not clear here what OS used to run the WASM server here? Does WASM server is running with Azure AppService? Answers may help here. 

Some Windows Servers OS's doesn't have ICU versions (or has old ICU versions which .NET doesn't support). If running on such environment, the workaround is to use ICU app-local feature. Add something like the following to the csproj:

```Xml
  <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  </ItemGroup>
```

If the users have no control and Azure AppService is controlling using NLS or ICU, then the solution must come from Azure AppService to allow using ICU. @lewing may know better how the WASM server run and if using Azure AppService. We'll need to understand too why Azure AppServer decided to force NLS mode too. @danmoseley do can you connect us with somebody from Azure side?

**Comment by nssidhu** [comment]
I am finding that I cannot use snapshot debugger on Azure App service with visual Studio 2022, it only supports 2017 & 2019.
will try some different method to capture runtime values.

Details about OS and dotnet version are mentioned up in the chain.

Will post more details once i have them.

**Comment by nssidhu** [comment]
Some more findings

Here is the code which is running into problem when deployed on to Azure App Service(Windows) as self contained.


```
 var LocalTimeAtOrgLocation = orgLocationTerminal?.OrgLocationID_FKNavigation.TimeZone_Blazor;
  telemetryClient.TrackException(new Exception("TimeZone : " + LocalTimeAtOrgLocation));  
      This is the Output// 	TimeZone : America/Chicago
  TimeZoneInfo timezoneID = TimeZoneInfo.FindSystemTimeZoneById(LocalTimeAtOrgLocation); 


  telemetryClient.TrackException(new Exception("TimeZone ID : " + timezoneID.Id));   
      This is the Output // TimeZone ID : America/Chicago
  telemetryClient.TrackException(new Exception("TimeZone Display Name  : " + timezoneID.DisplayName));  
      This is output //TimeZone Display Name : (UTC-06:00) Central Time (US & Canada)
 
 telemetryClient.TrackException(new Exception("TimeZone Standard Name  : " + timezoneID.StandardName));  
     This is output//TimeZone Standard Name : Central Standard Time	

  DateTimeOffset timeAtLcoation = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, timezoneID);

  telemetryClient.TrackException(new Exception("Time at Location Before Offset : " + timeAtLcoation.ToString("MM/dd/yyyy HH:mm:ss tt zzz")));  
        This is output //Time at Location Before Offset : 10/09/2021 20:28:29 PM +00:00
        This is also the issue, it is display correct time but no Timezone info (looks like it is GMT)

 timeAtLcoation = timeAtLcoation.ToOffset(timezoneID.BaseUtcOffset);
  Attempt to add timezone.
 telemetryClient.TrackException(new Exception("Time at Location after Offset : " + timeAtLcoation.ToString("MM/dd/yyyy HH:mm:ss tt zzz")));  
       It does adds time zone, but it messes up the actual time //Time at Location after Offset : 10/09/2021 14:28:29 PM -06:00
```

**Comment by sjuranek** [comment]
I ran into the same thing today - TryConvertIanaIdToWindowsId works locally but not on Azure App Service with self-contained deployment:

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => {
    if (TimeZoneInfo.TryConvertIanaIdToWindowsId("America/Chicago", out var winTZ))
    {
        return winTZ;
    } 
    return "TryConvertIanaIdToWindowsId failed";
});

app.Run();

**Comment by nssidhu** [comment]
@tarekgh  How do I resolve the issue ?

Repo can be found at . It was created in VS2022 as  Blazor wasm hosted project
[https://github.com/nssidhu/BlazorAppTimezone.](https://github.com/nssidhu/BlazorAppTimezone.)

Everything works fine when running in visual studio. when published to Azure App service I get  integrity errors in F12 tools.
Since i am not able to execute the app, i am not sure if the problem on the server side is fixed by including the mentioned package.

I can reproduce the same error when publishing to the local folder and running it from there.

@javiercn  question on Integrity error, I added the following package in the server project only, why is wasm trying to download them, I don't need them for client side functionality, only need them on server ?  

 <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  </ItemGroup>

**Comment by tarekgh** [comment]
@nssidhu 

> I get integrity errors in F12 tools.

Could you please share the errors log you are getting? 

Thanks for sharing the project. You have said you can reproduce the error even when deploying to local folder. Please share all the steps you have from building, publishing, deploying, and getting the integrity error. Also, if you remove the ICU package reference, does it hide the integrity error?

**Comment by nssidhu** [comment]
That is interesting, may be my Visual Studio Environment is messed up. 
Does it work when published to Azure app Service (windows) ?

The attached screen recording is for default Blazor app(without the time zone) one and i still run into integrity errors.
Also when i was inspecting for the size in F12 tool i could see huge size

I have been using the VS from .NET core 3.1 and have been constantly upgrading it the newer release. Will give a try on New VM.

I have attached the Screen recording. I am using VS2022  Version 17.1.0 Preview 1.0

[https://1drv.ms/u/s!AtHk7h6Srnk_h9l9pNOnOyp4rFRdNQ?e=iA3Iaz](https://1drv.ms/u/s!AtHk7h6Srnk_h9l9pNOnOyp4rFRdNQ?e=iA3Iaz)

**Comment by tarekgh** [comment]
@nssidhu something I noticed in your video is when you published to the local folder, looks there should be a folder called `runtime` which is missing in publishing. This folder should be the folder has the ICU bits. May be the NuGet restore somehow didn't run before publishing? could you please validate that?

![image](https://user-images.githubusercontent.com/10833894/141696558-4dda8f65-17b4-4dc3-a760-00032e440aeb.png)

**Comment by nssidhu** [comment]
I am not an expert in internal working of Blazor, but think in Blazor Project these files are copied over into _framework folder which is inside wwwroot folder.
I do see all the file under that folder.

**Comment by tarekgh** [comment]
Could you try publishing to a specific architecture (x64)?

**Comment by nssidhu** [comment]
@tarekgh 
I created  windows 11 VM and installed visual studio 2022 so that i can have clean environment.

GitHub source Code(updated to report error on server)
https://github.com/nssidhu/BlazorAppTimezone

Published Version
https://blazorapptimezoneserver20211114202356.azurewebsites.net/

Screen Recording
https://1drv.ms/u/s!AtHk7h6Srnk_h9oDmK19vXG4CJOavg?e=obU0Gf

1) First part,  running it from visual Studio 2022
2) Second part, when i publish it locally and try to run locally
   In my earlier screen recording i was trying incorrectly to run the locally published version.
   It seems to be working fine even locally, no error.
3) Publishing it to Azure App Service. (Does not seems to be working)
   Looks like none of the call to API are working, it is just returning index.html, even swagger is not working on the published version.

**Comment by tarekgh** [comment]
@lewing could you please have a look? when running WASM server app from VS or when deploying it to local folder, everything works fine as expected. When deploying the app to Azure app service it doesn't work. Looking at the deployment log (from the [video](https://1drv.ms/u/s!AtHk7h6Srnk_h9oDmK19vXG4CJOavg?e=obU0Gf)) it shows first the app get trimmed and then `mono-aot-cross.exe` will run which is most likely is what causing the issue here. does `mono-aot-cross.exe` can handle ICU native libraries which is part of the app?

![image](https://user-images.githubusercontent.com/10833894/141875574-d81a134a-b830-4798-af82-894407855a10.png)

**Comment by nssidhu** [comment]
@tarekgh I suspect something wrong in the routing framework when deployed on Azure app service. I updated my code to have swagger and i cannot even open swagger on the deployed version.

Somehow i am getting feeling that Blazor wasm is very unstable platform. thing works fine when running locally and behaves totally different when deployed to Azure App Service.

I did open another issue on GitHub for the same source code citing why my API calls are not going through on the deployed vversion.

**Comment by tarekgh** [comment]
@nssidhu I have pinged @lewing who may help with the WASM apps deployment to Azure service.

**Comment by lewing** [comment]
This still doesn't look wasm related. @pranavkm any thoughts? or suggestions on who to talk to on the app service side?

**Comment by sebastienros** [comment]
I am having a similar issue with GitHub actions running my unit tests on Windows.
I am loading a time zone by id using an IANA string. It works locally with .NET 6 on Windows 11, but running the test using "windows-latest" in GitHub action returns this:

```
  Failed Fluid.Tests.MiscFiltersTests.DateNumberIsParsedInLocalTimeZone [< 1 ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'Fluid.Tests.MiscFiltersTests' threw an exception.
---- System.TimeZoneNotFoundException : The time zone ID 'America/Los_Angeles' was not found on the local computer.
  Stack Trace:
     at Fluid.Tests.MiscFiltersTests.DateNumberIsParsedInLocalTimeZone() in D:\a\fluid\fluid\Fluid.Tests\MiscFiltersTests.cs:line 474
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at Fluid.Tests.MiscFiltersTests..cctor() in D:\a\fluid\fluid\Fluid.Tests\MiscFiltersTests.cs:line 14

Failed!  - Failed:    12, Passed:   881, Skipped:     0, Total:   893, Duration: 622 ms - Fluid.Tests.dll (net6.0)
```

The code is just 

```
private static readonly TimeZoneInfo Pacific = TimeZoneInfo.FindSystemTimeZoneById("America/Los_Angeles");
```

You can see in the trace that it's effectively running in .NET 6 so I don't expect it to fail.

I have the same tests for net5.0 but using the TimeZoneConverter library, and this works fine. My goal is to remove this dependency when targeting net6.0.

**Comment by safern** [comment]
> but running the test using "windows-latest" in GitHub action returns this:

The "Windows-latest" VM in GitHub actions is: `OS Version: 10.0.17763 Build 2300` which doesn't yet have icu.dll which we depend on to run using ICU, so since we couldn't find it we fall back to NLS, as you can see in your latest output, `UseNls = true`. In order to run using ICU on Windows you need to be on `1903` or later.

> I confirm that adding the ICU package fixes the issue, though it's not ideal.

Well it is ideal if you want to control the version of ICU you depend on and you don't want to rely on OS environments and want to control that stability. 

I see that github actions has a `windows-2022` agent available already, which is: `OS Version: 10.0.20348 Build 350`, so maybe you could use that tag for now?

**Comment by safern** [comment]
> @tarekgh I suspect something wrong in the routing framework when deployed on Azure app service. I updated my code to have swagger and i cannot even open swagger on the deployed version.

@nssidhu by any chance could you share a .zip with the published app layout that is running on Azure App Services?

**Comment by sebastienros** [comment]
> so maybe you could use that tag for now?

I don't really care about mitigating the CI issues. Now that I know that it can "randomly" not work on some customers' machines I don't think I want to use the feature. That's not something that a library can enforce.

**Comment by safern** [comment]
Yeah I totally get that and makes sense. That was the intent of the app local feature. The downside is that an app switch needs to be set. I don't know if from a library it could be set early enough before globalization is enabled.

Maybe you can instead of stripping the feature out limit it to non windows and windows equals or later than 1903?

**Comment by tarekgh** [comment]
> I don't really care about mitigating the CI issues. Now that I know that it can "randomly" not work on some customers' machines I don't think I want to use the feature. That's not something that a library can enforce.

It is up to you to decide to use the feature or not, but I wouldn't suggest not using it. Instead, you can have a fallback mechanism when the API returns false to you. The app author/user is in control. If the NLS mode is used, it is expected to have some limitations. That is why the APIs pattern is returning bool and the callers can decide the fallback they decide to go with. I am expecting in the near future very few users will be using NLS mode. We are already discouraging users from enabling it and using ICU app-local feature when ICU is not available.

Now to focus on the original issue that @nssidhu has, @pranavkm is going to look at the deployment of the app to Azure app service and will get back to us.

**Comment by pranavkm** [comment]
@nssidhu looks like Azure App Services will url decode all incoming routes. In your case, this results in the app selecting the fallback route because there isn't a route that matches `api/WeatherForecast/GetTimeZonetime/{a}/{b}`. Changing the route parameter to a catch-all parameter should resolve this issue and make it so that it works locally and on App Services:

```diff
- [Route("GetTimeZonetime/{TimeZone}")]
+ [Route("GetTimeZonetime/{**TimeZone}")]
[HttpGet]
public IActionResult GetTimeZonetime(string TimeZone)
```

**Comment by nssidhu** [comment]
@tarekhgh
I am vacationing and won’t get chance until Nov 28th.
Also on the other thread someone replied that the problem is because App Sevice auto decode url and then since it does not match with anything it falls back to index.html.
That kind of make sense, but I also ran into issue that even swagger is not working.
Will give a try after I come back from vacation.


Sent from Yahoo Mail for iPhone


On Friday, November 19, 2021, 12:13 PM, Santiago Fernandez Madero ***@***.***> wrote:





@tarekgh I suspect something wrong in the routing framework when deployed on Azure app service. I updated my code to have swagger and i cannot even open swagger on the deployed version.


@nssidhu by any chance could you share a .zip with the published app layout that is running on Azure App Services?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nssidhu** [comment]
@tarekgh 

The issue was due to Routing. Azure App Service runs IIS as a Web Server. When Developing locally Kestrel is the default  web server.

The problem was occurring because on Azure App Service, which run IIS,  automatically decodes the encoded url and than it cannot find the route, after auto decoding the route becomes GetTimeZone/America/chicago, which does not exists.

The solution was to update the server controller methods signature to use asterisk(*) and it works, but this is somewhat dangerous option. The proper way should be to pass the timezone in post instead of get request.

Original which was running into problem
        ```
[Route("GetTimeZonetime/{TimeZone}")]
        [HttpGet]
        public IActionResult GetTimeZonetime(string TimeZone)
        {
        ............................
         }
```

Update method which does not run into error. _Note * (asterisk in front of TimeZone)_
```
[Route("GetTimeZonetime/{*TimeZone}")]
        [HttpGet]
        public IActionResult GetTimeZonetime(string TimeZone)
        {
        ............................
         }
```

App is deployed at 
https://blazorapptimezoneserver20211115142701.azurewebsites.net
Source code at
https://github.com/nssidhu/BlazorAppTimezone

**Comment by tarekgh** [comment]
@nssidhu thanks for the update. Your confirmation match what @pranavkm mentioned. By that I am closing this issue. Please let's know if you still have any issues here.
