### ISSUE TITLE
[Bug] Publishing maui rc2 app to App Store not working -- The app references non-public symbols in MyContactNetwork.MobileMaui: _proc_pidinfo

### ISSUE THREAD

**Issue by baartho** [dotnet/runtime#61265]
### Description

I'm running into an App Store rejection issue with .NET 6.0 RC 2 + MAUI + iOS + WebView.Maui:

ITMS-90338: Non-public API usage - The app references non-public symbols in MyContactNetwork.MobileMaui: _proc_pidinfo. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

I believe that the offending package is `System.Diagnostics.Process`, which I'm guessing is referenced (and so ILLink won't remove, no matter what) because of this line:

https://github.com/dotnet/runtime/blob/1c7100b0c21a2af147362c7b5c61408611743ded/src/libraries/Common/src/Interop/OSX/Interop.libproc.GetProcessInfoById.cs#L93

which is called by 

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs

I tried adding the System.Diagnostics.Process.dll to the trimmer exceptions but it didn't work - I believe something in your code is referencing it.

ILinker build output:

```
ILLink: Processing embedded substitution descriptor ILLink.Substitutions.xml from System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Assembly System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a : skipped (SDK)
         ILLink: Reduced '11' instructions in conditional branches for [System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] method System.SR.GetResourceString(String)
         ILLink: Reduced '4' instructions in conditional branches for [System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] method System.SR.Format(String,Object)
         ILLink: Reduced '236' instructions in conditional branches for [System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] method System.Diagnostics.Process.StartCore(ProcessStartInfo)
ILLink: Reduced '5' instructions in conditional branches for [System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] method System.SR.Format(String,Object,Object)
 ILLink: Reduced '1' instructions in conditional branches for [System.Diagnostics.Process, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a] method System.Diagnostics.ProcessWaitState.Holder.Finalize()
```

### Reproduction Steps

Build the base MAUI Blazor template in Release+iOS+ARM64 and publish to App Store TestFlight, using the following in csproj:

<RuntimeIdentifier Condition="$(TargetFramework.Contains('-ios')) AND '$(Configuration)' == 'Release'">ios-arm64</RuntimeIdentifier>

### Expected behavior

Successful publish to the app store

### Actual behavior

Did not publish

### Regression?

Similar issue: https://github.com/dotnet/runtime/issues/57931

### Configuration

.NET 6 rc2 
MAUI Single Project
Blazor + MAUI.WebView
iOS ARM64 Build

**Comment by josephatkuvio** [comment]
I can confirm this issue on a dotnet new MAUI Blazor and MAUI template, in release/ios-arm64. After release linking, System.Diagnostics.Process.dll is still part of the app bundle, and `proc_pidinfo` is not linked out, even when the linker is explicitly told to link this DLL. So there's gotta be a direct reference somewhere within MAUI or its libraries, I just haven't found it yet.

dotnet new maui:
```
admin@DXT037 Maui.New % grep -r pidinfo .
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/Maui.New matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.llvm.o matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s.opt.bc matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s.bc matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.o matches
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_threadinfo__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_threadinfo__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_ulong__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_ulong__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_taskallinfo__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_taskallinfo__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_threadinfo__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_ulong__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_taskallinfo__int

```

dotnet new maui-blazor:
```
admin@DXT037 mauiblazor.new % grep -r pidinfo .
Binary file ./obj/Release/net6.0-ios/iossimulator-x64/linked/System.Private.CoreLib.dll matches
Binary file ./obj/Release/net6.0-ios/iossimulator-x64/linked/System.Diagnostics.Process.dll matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/MauiBlazor.New matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.llvm.o matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s.opt.bc matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s.bc matches
Binary file ./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.o matches
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_threadinfo__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_threadinfo__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_ulong__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_ulong__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:	.no_dead_strip wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_taskallinfo__int
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:wrapper_managed_to_native_Interop_libproc_proc_pidinfo_int_int_ulong_Interop_libproc_proc_taskallinfo__int:
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl _proc_pidinfo
./obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Diagnostics.Process.dll.s:bl wrapper_managed_to_native_Interop_libproc_pr
```

**Comment by danmoseley** [comment]
@eerhardt do you know what's going on?

**Comment by eerhardt** [comment]
No, I don't. I assume there is some code in the application calling into a Process API that is rooting this `proc_pidinfo` method.

If someone could zip up the output of the linker, I can take a look to see what callstacks are using this method.

Note - in 5.0 we didn't call `proc_pidinfo`, but instead parsed the output of `vmmap`. This was changed to use `proc_pidinfo` in https://github.com/dotnet/runtime/pull/42900.

Is `proc_pidinfo` not supported on iOS? Maybe we have to split our Process code between `macOS` and `iOS` and use different approaches between them?

cc @rolfbjarne @akoeplinger - any thoughts?

**Comment by rolfbjarne** [comment]
> Note - in 5.0 we didn't call `proc_pidinfo`, but instead parsed the output of `vmmap`. This was changed to use `proc_pidinfo` in #42900.

That's not the reason, because the `libproc.h` header doesn't ship with the iOS SDK, so that code doesn't compile for iOS.

The call to `proc_pidinfo` comes from a P/Invoke, I'm guessing this one: https://github.com/dotnet/runtime/blob/6a597253b33464ec38a173d43045d30eeb061841/src/libraries/Common/src/Interop/OSX/Interop.libproc.cs#L247

That managed code will have to be conditionally excluded from iOS (and tvOS) - linking isn't required, which means that it's not possible to rely on the linker to remove private Apple API.

**Comment by eerhardt** [comment]
The reason `System.CodeDom` isn't trimmed by default is because

https://github.com/dotnet/runtime/blob/b07b26dd18ae64cd4a6b091dd4a2c87aee773eec/src/libraries/System.CodeDom/src/System.CodeDom.csproj#L7

(note `System.Diagnostics.Process` is trimmed by default)

See some of the discussion [here](https://github.com/dotnet/runtime/pull/52133#issuecomment-831499730), we didn't expect `System.CodeDom` to be used in mobile applications, but we were probably wrong.

@josephatkuvio - is any code in your application (or 3rd party nugets) using System.CodeDom?

**Comment by josephatkuvio** [comment]
No, it isn't, which is what was confusing. But I've replicated this issue with the base MAUI and MAUI Blazor project templates as well, on Preview 9 and 10 -- a release ios-arm64 version of either of those includes the proc_pidinfo reference by default.

It may be something that's changed in the last few weeks as well -- #57931 was exactly the same story, just a different set of private APIs, but back then proc_pidinfo wasn't one of them.

**Comment by eerhardt** [comment]
Doing a quick look at a Maui app locally, I see `System.CodeDom` is pulled in by `Microsoft.Maui.Controls.Build.Tasks`.

```
      "Microsoft.Maui.Controls.Build.Tasks/6.0.101-preview.11.2122": {
        "type": "package",
        "dependencies": {
          "Microsoft.Maui.Graphics": "6.0.101-preview.11.679",
          "System.CodeDom": "4.7.0"
        },
        "build": {
          "build/Microsoft.Maui.Controls.Build.Tasks.props": {},
          "build/Microsoft.Maui.Controls.Build.Tasks.targets": {}
        }
      },
```

I fixed this with https://github.com/dotnet/maui/pull/888, but it regressed with [Merge branch 'release/6.0.1xx-preview4'](https://github.com/dotnet/maui/commit/f96ac2a45beb60a9e2f676a478d0cef5d5c9e725).

cc @PureWeen 

I will submit a fix again to dotnet/maui.

**Comment by rolfbjarne** [comment]
I'm reopening, because AFACT this is still an issue when the app isn't trimmed.

**Comment by rolfbjarne** [comment]
There are three more `_proc_*` non-public symbols in use, for a total of four:

* _proc_listallpids
* _proc_pid_rusage
* _proc_pidinfo
* _proc_pidpath

This is from trying to submit a non-trimmed app: "ITMS-90338: Non-public API usage - The app references non-public symbols in iTravel: _proc_listallpids, _proc_pid_rusage, _proc_pidinfo, _proc_pidpath. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/"

**Comment by MaximLipnin** [comment]
Thanks, Rolf! I'll try to exclude `src/libraries/Common/src/Interop/OSX/Interop.libproc.cs` on iOS/tvOS in a separate PR.

**Comment by MaximLipnin** [comment]
> I'm reopening, because AFACT this is still an issue when the app isn't trimmed.

@rolfbjarne could you please confirm that the issue is gone as #61590 has been merged to the main?

**Comment by rolfbjarne** [comment]
@MaximLipnin we'll need this in a servicing release (6.0.200 or something similar), we're not targeting 7.0 for a while yet.

**Comment by MaximLipnin** [comment]
> @MaximLipnin we'll need this in a servicing release (6.0.200 or something similar), we're not targeting 7.0 for a while yet.

Opened a backport PR to release/6.0 - https://github.com/dotnet/runtime/pull/61659

**Comment by aokocax** [comment]
> #61265 (comment)
I was able to submit it to AppStore with daily build (SDK 6.0.2-servicing.1.22063.8 ) without any problem. Thanks to everyone involved.

Microsoft (R) Build Engine version 17.1.0-preview-22055-02+797fd829a for .NET

**Comment by akoeplinger** [comment]
This was fixed, it will be available in one of the future previews (not sure exactly which one yet).
