### ISSUE TITLE
Runtime libraries: debug symbols missing for latest patches (5.0.13, 6.0.1)

### ISSUE THREAD

**Issue by vuplea** [dotnet/runtime#62955]
Debug symbols seem to be uploaded with some delay on the classic Microsoft symbol server.
Is this expected?
Are there alternative sources for these symbols?

```
C:\Users\radu.oancea>dotnet-symbol --cache-directory c:\sym\sym -o D:\Downloads "C:\program files\dotnet\shared\microsoft.netcore.app\6.0.1\System.Private.CoreLib.dll"
Downloading from http://msdl.microsoft.com/download/symbols/
Writing files to D:\Downloads
ERROR: Not Found: System.Private.CoreLib.ni.pdb - 'http://msdl.microsoft.com/download/symbols/system.private.corelib.ni.pdb/78f316dca48e9ebf409049db690a91511/system.private.corelib.ni.pdb'
ERROR: Not Found: System.Private.CoreLib.pdb - 'http://msdl.microsoft.com/download/symbols/system.private.corelib.pdb/2e5a78beee0f4abd8ed7ef3636048cf1FFFFFFFF/system.private.corelib.pdb'

C:\Users\radu.oancea>dotnet-symbol --cache-directory c:\sym\sym -o D:\Downloads "C:\program files\dotnet\shared\microsoft.netcore.app\6.0.0\System.Private.CoreLib.dll"
Downloading from http://msdl.microsoft.com/download/symbols/
Writing files to D:\Downloads
Writing: D:\Downloads\System.Private.CoreLib.ni.pdb
Writing: D:\Downloads\System.Private.CoreLib.pdb

C:\Users\radu.oancea>dotnet-symbol --cache-directory c:\sym\sym -o D:\Downloads "C:\program files\dotnet\shared\microsoft.netcore.app\5.0.13\System.Private.CoreLib.dll"
Downloading from http://msdl.microsoft.com/download/symbols/
Writing files to D:\Downloads
ERROR: Not Found: System.Private.CoreLib.ni.pdb - 'http://msdl.microsoft.com/download/symbols/system.private.corelib.ni.pdb/bbedef2c9b15e88208ce6fd454a722291/system.private.corelib.ni.pdb'
ERROR: Not Found: System.Private.CoreLib.pdb - 'http://msdl.microsoft.com/download/symbols/system.private.corelib.pdb/0741d33dd3fc47c2a0e874e1810361afFFFFFFFF/system.private.corelib.pdb'

C:\Users\radu.oancea>dotnet-symbol --cache-directory c:\sym\sym -o D:\Downloads "C:\program files\dotnet\shared\microsoft.netcore.app\5.0.12\System.Private.CoreLib.dll"
Downloading from http://msdl.microsoft.com/download/symbols/
Writing files to D:\Downloads
Writing: D:\Downloads\System.Private.CoreLib.ni.pdb
Writing: D:\Downloads\System.Private.CoreLib.pdb
```

**Comment by pgrawehr** [comment]
+1. Trying to load the symbols for, say, System.Linq.dll, Version 6.0.1 yields the following messages in the VS symbol load information window:

```
C:\projects\iot3\tools\ArduinoCsCompiler\Frontend\bin\Debug\net6.0\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
D:\a\_work\1\s\artifacts\obj\System.Linq\net6.0-Release\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
C:\WINDOWS\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
C:\WINDOWS\symbols\dll\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
C:\WINDOWS\dll\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
D:\SymbolCache\System.Linq.pdb\0076e8e6ba7743958bf805e51262bee6ffffffff\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
D:\SymbolCache\MicrosoftPublicSymbols\System.Linq.pdb\0076e8e6ba7743958bf805e51262bee6ffffffff\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
D:\SymbolCache\System.Linq.pdb\0076e8e6ba7743958bf805e51262bee61\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
D:\SymbolCache\MicrosoftPublicSymbols\System.Linq.pdb\0076e8e6ba7743958bf805e51262bee61\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
C:\projects\iot3\tools\ArduinoCsCompiler\System.Linq.pdb: PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
SYMSRV:  BYINDEX: 0x28
         D:\SymbolCache*https://msdl.microsoft.com/download/symbols
         System.Linq.pdb
         0076E8E6BA7743958BF805E51262BEE6ffffffff
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\System.Linq.pdb - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\System.Linq.pd_ - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE6ffffffff/System.Linq.pdb
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE6ffffffff/System.Linq.pd_
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE6ffffffff/file.ptr
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  RESULT: 0x80190194
SYMSRV:  BYINDEX: 0x29
         D:\SymbolCache*https://msdl.microsoft.com/download/symbols
         System.Linq.pdb
         0076E8E6BA7743958BF805E51262BEE61
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\System.Linq.pdb - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\System.Linq.pd_ - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE61/System.Linq.pdb
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE61/System.Linq.pd_
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE61/file.ptr
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  RESULT: 0x80190194
https://msdl.microsoft.com/download/symbols: Die Symbole wurden auf dem Symbolserver nicht gefunden.
SYMSRV:  BYINDEX: 0x2A
         D:\SymbolCache*https://symbols.nuget.org/download/symbols
         System.Linq.pdb
         0076E8E6BA7743958BF805E51262BEE6ffffffff
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\System.Linq.pdb - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\System.Linq.pd_ - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE6ffffffff\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE6ffffffff/System.Linq.pdb
SYMSRV:  HttpQueryInfo: 80190193 - HTTP_STATUS_FORBIDDEN
SYMSRV:  RESULT: 0x80190193
SYMSRV:  BYINDEX: 0x2B
         D:\SymbolCache*https://symbols.nuget.org/download/symbols
         System.Linq.pdb
         0076E8E6BA7743958BF805E51262BEE61
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\System.Linq.pdb - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\System.Linq.pd_ - path not found
SYMSRV:  UNC: D:\SymbolCache\System.Linq.pdb\0076E8E6BA7743958BF805E51262BEE61\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/System.Linq.pdb/0076E8E6BA7743958BF805E51262BEE61/System.Linq.pdb
SYMSRV:  HttpQueryInfo: 80190193 - HTTP_STATUS_FORBIDDEN
SYMSRV:  RESULT: 0x80190193
https://symbols.nuget.org/download/symbols: Die Symbole wurden auf dem Symbolserver nicht gefunden.
```

**Comment by HighPerfDotNet** [comment]
+1 same thing here!

**Comment by pgrawehr** [comment]
It appears this has been resolved. At least the 6.0 symbols are available now.

**Comment by csinkers** [comment]
Looks like 5.0.13 is still missing

```
dotnet-symbol --symbols --output C:\Symbols "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.13\coreclr.dll"
Downloading from http://msdl.microsoft.com/download/symbols/
Writing files to C:\Symbols
ERROR: Not Found: coreclr.pdb - 'http://msdl.microsoft.com/download/symbols/coreclr.pdb/2a9fafa9e64546068679b2658cb87ac01/coreclr.pdb'
```

**Comment by ericstj** [comment]
@hoyosjs are we still having any publishing errors for symbols?  You helped resolve a similar issue a couple weeks back, could you have a look here?

**Comment by hoyosjs** [comment]
@ericstj 3.1, 5.0, and 6.0 are all having an issue in staging with the gather-drop command, where symbols were classified as release packages. There was an email with ddfun + dnceng dating back before Christmas. I don't have access to a machine with corp access (or any machine other than my phone) for some time. I can manually index them in a couple days, but that's only going to be for a release. The bug still needs to get addressed in darc.

**Comment by ericstj** [comment]
cc @markwilkie

**Comment by markwilkie** [comment]
Adding @epananth and @mmitche who I *think* have context here

**Comment by mmitche** [comment]
There is a side investigation going on about this. We think that it should have been fixed for 6.0, but investigation is still ongoing for 5.0/3.1

**Comment by hoyosjs** [comment]
The issue was caused by https://github.com/dotnet/arcade/issues/8286, the specific issues for 5.0.12/13 and 6.0 have been resolved.
