### ISSUE TITLE
MemoryMappedFile.CreateNew on macOS throws System.IO.PathTooLongException

### ISSUE THREAD

**Issue by evanlouie** [dotnet/runtime#63240]
### Description

`MemoryMappedFile.CreateNew` throws a
`System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.`
exception when passing in `null` as the map name (`null` mapName is required on
unix as noted in https://github.com/dotnet/runtime/issues/21863).

Program.cs:

```cs
using System.IO.MemoryMappedFiles;

// Passing null as mapNames are not supported for mmf on unix
using var mmf = MemoryMappedFile.CreateNew(null, 1);
```

When run, will throw:

```
dotnet run --project MemoryMapIssue
Unhandled exception. System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObjectUsingMemory(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObject(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity)
   at Program.<Main>$(String[] args) in /Users/aida/workspace/MemoryMapIssue/Program.cs:line 5
```

### Configuration

- OS: macOS 12.1
- Arch: ARM64

```
dotnet --version
6.0.101
```

```
dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

```
dotnet --list-sdks
6.0.101 [/usr/local/share/dotnet/sdk]
```

### Regression?

Unknown

### Other information

Following guidance from https://github.com/dotnet/runtime/issues/21863 which
says unix systems do not support named mmf; so passing in `null` as name.

**Comment by MaximLipnin** [comment]
This is being hit on the rolling build as well - https://dev.azure.com/dnceng/public/_build/results?buildId=1537456&view=ms.vss-test-web.build-test-results-tab&runId=43519558&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab&resultId=124535

The console output: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-357565f08acb4f8a98/System.IO.MemoryMappedFiles.Tests/1/console.d0876942.log?sv=2019-07-07&se=2022-01-25T20%3A12%3A46Z&sr=c&sp=rl&sig=WHFq0ofrgZn1W%2F%2FlMBmIsOUIoZSBFLWI3F4NDYoidew%3D

**Comment by xbIm** [comment]
any workaround to fix this issue?
for example use x64 version? 
or just wait for new version of SDK for arm64?

**Comment by kdubau** [comment]
It looks like this is causing the FSharp Interactive pad in VSMac to crash
```
(lldb) pe
Exception object: 0000000105b56c20
Exception type:   <Unknown>
Message:          Error creating evaluation session: System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObjectUsingMemory(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObject(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
   at FSharp.Compiler.AbstractIL.Internal.ByteMemory.CreateMemoryMappedFile(ReadOnlyByteMemory bytes) in F:\workspace\_work\1\s\src\absil\bytes.fs:line 330
   at FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadManifestResources@3099.GenerateNext(IEnumerable`1& next) in F:\workspace\_work\1\s\src\absil\ilread.fs:line 3114
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 372
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 404
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadManifestResources(ILMetadataReader ctxt, Boolean canReduceMemory, ReadOnlyByteMemory mdv, PEReader pectxtEager, ReadOnlyByteMemory pevEager) in F:\workspace\_work\1\s\src\absil\ilread.fs:line 3098
   at FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadModule(ILMetadataReader ctxt, Boolean canReduceMemory, PEReader pectxtEager, ReadOnlyByteMemory pevEager, UInt16 peinfo_0, Tuple`2 peinfo_1, Boolean peinfo_2, Boolean peinfo_3, Boolean peinfo_4, Boolean peinfo_5, Boolean peinfo_6, FSharpOption`1 peinfo_7, Boolean peinfo_8, Int32 peinfo_9, Int32 peinfo_10, Int32 peinfo_11, String ilMetadataVersion, Int32 idx) in F:\workspace\_work\1\s\src\absil\ilread.fs:line 1499
   at FSharp.Compiler.AbstractIL.ILBinaryReader.openMetadataReader(String fileName, BinaryFile mdfile, Int32 metadataPhysLoc, Tuple`8 peinfo, PEReader pectxtEager, ReadOnlyByteMemory pevEager, FSharpOption`1 pectxtCaptured, Boolean reduceMemoryUsage) in F:\workspace\_work\1\s\src\absil\ilread.fs:line 3579
   at FSharp.Compiler.AbstractIL.ILBinaryReader.OpenILModuleReader(String fileName, ILReaderOptions opts) in F:\workspace\_work\1\s\src\absil\ilread.fs:line 3961
   at FSharp.Compiler.CompileOps.assembliesThatForwardToPrimaryAssembly@4977-2.Invoke(AssemblyResolution resolvedAssembly) in F:\workspace\_work\1\s\src\fsharp\CompileOps.fs:line 4979
   at Microsoft.FSharp.Primitives.Basics.List.choose[T,TResult](FSharpFunc`2 f, FSharpList`1 xs) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 189
   at Microsoft.FSharp.Collections.ListModule.Choose[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 154
   at FSharp.Compiler.CompileOps.BuildFrameworkTcImports@4943-1.Invoke(Tuple`2 _arg6) in F:\workspace\_work\1\s\src\fsharp\CompileOps.fs:line 4975
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.bind@707.Invoke(CancellationToken ct) in F:\workspace\_work\1\s\src\absil\illib.fs:line 709
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.bind@707.Invoke(CancellationToken ct) in F:\workspace\_work\1\s\src\absil\illib.fs:line 708
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.bind@707.Invoke(CancellationToken ct) in F:\workspace\_work\1\s\src\absil\illib.fs:line 708
   at FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.runWithoutCancellation[a](Cancellable`1 comp) in F:\workspace\_work\1\s\src\absil\illib.fs:line 752
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2827
```

**Comment by kdubau** [comment]
@jeffschwMSFT can we consider this for 6.0 servicing?

**Comment by jeffschwMSFT** [comment]
Adding @danmoseley for consideration.

**Comment by danmoseley** [comment]
This means MMF are broken on Apple Silicon with no workaround? If so, this clearly meets the bar to me. @adamsitnik  is already on it.

**Comment by MaximLipnin** [comment]
The issue still persists:  

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c8f8453569e34661af/System.IO.MemoryMappedFiles.Tests/1/console.b6477130.log?sv=2019-07-07&se=2022-02-22T08%3A14%3A43Z&sr=c&sp=rl&sig=O0LaW%2F%2Be6W8CxQ1dmDYpftcsPYY2VORsf6RwURCiAeI%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=1586376&view=ms.vss-test-web.build-test-results-tab&runId=44437066&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=121848

**Comment by adamsitnik** [comment]
@MaximLipnin how can I force the CI to run the tests on macOS arm64?

**Comment by MaximLipnin** [comment]
@adamsitnik It's in `runtime-staging` pipeline running as part of the rolling build, so perhaps it could be `/azp run runtime-staging`.

**Comment by am11** [comment]
These (45) tests are failing on mono runtime as well in https://github.com/dotnet/runtime/issues/64947. These tests are currently disabled on iOS, MacCatalyst due to similar reason, so it's not _just_ osx-arm64 either.

**Comment by pkeogh** [comment]
This issue is easily reproducible by attempting to create a Blazor Server App in the current Visual Studio for Mac 17.0 build 7303 on a system with Apple Silicon.

**Comment by shadinamrouti** [comment]
I've got the same error by just creating a blank solution under Mac 17.0 Preview (Build 7303) under MacOS 12.2.1 (Monterey). M1 Chip.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12829248/155370205-17614863-0879-4d5d-b0c8-de368f183560.png">

**Comment by kdubau** [comment]
> I've got the same error by just creating a blank solution under Mac Book Pro using Visual Studio 2022 version 17.0 Preview (Build 7303) under MacOS 12.2.1 (Monterey). M1 Chip.

This issue, specifically in Visual Studio for Mac 2022, is fixed and pending release (Preview 7). However the fix in VSMac was achieved by not using MemoryMappedFiles in the F# interactive pad. 

To the dotnet team, I do believe this is still an active issue.

**Comment by xbIm** [comment]
Any updates on this issue? The problem still exists in SDK 6.0.202 on mac arm64 version
