### ISSUE TITLE
Blazor WASM PWA crashes when there is a list of inherited classes in the <select> component

### ISSUE THREAD

**Issue by dece1ver** [dotnet/runtime#63581]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In my [application](https://test.sunduk.one/), there is a list with inherited classes. When there is a specific inherited class in this list, the application crashes when trying to display this list. The problem appeared after switching to .NET 6, and occurs only on the deployed application, when launched from Visual studio, everything works fine, also works fine on the deployed application with AOT compilation enabled. For example, I deployed 2 test applications without AOT compilation and with AOT compilation.
[https://wasm-pwa.azurewebsites.net/](https://wasm-pwa.azurewebsites.net/)
[https://wasm-pwa-aot.azurewebsites.net/](https://wasm-pwa-aot.azurewebsites.net/)
When the page loads, the list is filled with various instances of the class, except for the SpecialTool class, but if you add it with a button in the application, then the application without AOT compilation immediately stops working.

### Expected Behavior

Launched from Visual Studio and works fine (same behaviour with deployed with AOT compilation):
https://user-images.githubusercontent.com/36793765/147407862-7ca153ae-fc0b-44e2-96a2-5a74f38c7d2d.mp4

or:

* Goto [https://wasm-pwa-aot.azurewebsites.net/](https://wasm-pwa-aot.azurewebsites.net/)
* Click the "Add Special Tool" button
* Click the select component
* Select T0101 "UPOR"

### Steps To Reproduce

Repo with example project: https://github.com/dece1ver/WASM-PWA.Crashtest
Repo with my project: https://github.com/dece1ver/Sunduk/tree/test (complex and contains code of questionable quality)

Launched the deployed app without AOT compilation:
https://user-images.githubusercontent.com/36793765/147407884-634fb901-9b80-4b7f-b4ff-52f5012c54a5.mp4

or:

* Goto [https://wasm-pwa.azurewebsites.net/](https://wasm-pwa.azurewebsites.net/)
* Click the "Add Special Tool" button (app will crash)

### .NET Version

6.0.100

**Comment by SteveSandersonMS** [comment]
Note for @lewing or whoever looks at this: if you visit https://wasm-pwa.azurewebsites.net/ you'll get an `assertion failed` when clicking the button. The sources are at https://github.com/dece1ver/WASM-PWA.Crashtest

**Comment by ldsenow** [comment]
> @ldsenow the issues that you're bringing up are unrelated to the original issue, so please file a separate issue, if you have concerns there.

I believe there is a ticket for the issue i mentioned. I stumbled upon this one and it could be related to the same thing. The symptom looks very similar e.g. .net 6 + published version. I hope asp.net team can take this seriously and start finding out why a minimum weather forecast or this kind of simple application will consume so much memory. It makes me think they are the same root issue e.g. wasm runtime for blazor. I just cant explain why exactly the same code can run in .net 5 but cant run in .net 6 (particularly in published version). My .net 6 blazor production application is having the same symptom and it crashes very often. I have to downgrade to .net 5.

**Comment by SteveSandersonMS** [comment]
@ldsenow I'm afraid we have no way of knowing for sure whether your app's issue is related to this one. However I don't think it's related, because this issue isn't about the amount of memory used, but rather is about getting a crash when some particular code runs. If you are able to file a new issue with a minimal repro of the issue you're facing, we're definitely happy to investigate.

**Comment by thaystg** [comment]
@lewing this is fixed on .net7, I reproduced on .net6, then change the target to .net7 and wasn't able to reproduce again. Do I need to investigate which was the fix?

**Comment by lewing** [comment]
Fixed in .net7 we will investigate servicing it in .NET6

**Comment by thaystg** [comment]
This is the PR that fixed that: https://github.com/dotnet/runtime/pull/58806
Should I open a backport for .net6?

**Comment by lewing** [comment]
fixed in 6.0.9

**Comment by ldsenow** [comment]
> fixed in 6.0.9

I tested this in .net 6.0.9, however, the issue still exists.

![image](https://user-images.githubusercontent.com/177045/190096728-e3a6ecec-374f-4475-ae9b-7313d30f3f3c.png)

```
dotnet.6.0.9.kayz2i7vye.js:1 * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:91

558330 @ dotnet.6.0.9.kayz2i7vye.js:1
_emscripten_asm_const_int @ dotnet.6.0.9.kayz2i7vye.js:1
$func8473 @ 008f3216:0x1bfa2f
$func2151 @ 008f3216:0x8cbe2
$func8021 @ 008f3216:0x1a19c2
$func8024 @ 008f3216:0x1a1a51
$func8027 @ 008f3216:0x1a1aba
$func2623 @ 008f3216:0xa32c6
$func2620 @ 008f3216:0xa23a2
$func2402 @ 008f3216:0x94d74
$func2436 @ 008f3216:0x976d5
$func2412 @ 008f3216:0x9585d
$func2410 @ 008f3216:0x95159
$func2408 @ 008f3216:0x94fc1
$func2407 @ 008f3216:0x94f68
$func2347 @ 008f3216:0x9343f
$func2098 @ 008f3216:0x8782f
$func1638 @ 008f3216:0x7347f
$func1637 @ 008f3216:0x733c6
$func110 @ 008f3216:0xe7e0
$func109 @ 008f3216:0x6142
$func7360 @ 008f3216:0x1816a9
$func1558 @ 008f3216:0x6ee21
$func1556 @ 008f3216:0x6ed93
$func1005 @ 008f3216:0x5244f
$func162 @ 008f3216:0x14786
$func110 @ 008f3216:0x7229
$func109 @ 008f3216:0x6142
$func7360 @ 008f3216:0x1816a9
$func1558 @ 008f3216:0x6ee21
$func1562 @ 008f3216:0x6f552
$mono_wasm_invoke_method @ 008f3216:0x1bc909
Module._mono_wasm_invoke_method @ dotnet.6.0.9.kayz2i7vye.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
A @ blazor.webassembly.js:1
N @ blazor.webassembly.js:1
dispatchGlobalEventToAllElements @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1
Show 13 more frames
dotnet.6.0.9.kayz2i7vye.js:1 * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-ob
```

**Comment by dece1ver** [comment]
I tested it on my app, everything works fine.

**Comment by ldsenow** [comment]
> I tested it on my app, everything works fine.

Lucky you! I wish my app would have the same treatment

**Comment by thaystg** [comment]
> sgen-scan-object.h:91

This is another assertion, can you open another issue for it, and explaining us how to reproduce?
