### ISSUE TITLE
[WINARM][Regression] Fail to run the command – & “C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:loga.txt

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#71098]
**Note:** 
1.It’s regression issue. It doesn’t repro on dotnet-sdk-7.0.100-preview.5.22225.1-win-arm64.
2. Repro VM: vsengarmsfx041

**Builds info:** 
dotnet-runtime-3.1.26-win-x64 
dotnet-sdk-6.0.400-preview.22314.17-win-x64
dotnet-sdk-7.0.100-preview.6.22314.18-win-arm64
dotnet-sdk-7.0.100-preview.6.22314.18-win-x64
dotnet-sdk-7.0.100-preview.6.22314.18-win-x86

**Build Link:**
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-arm64.exe
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x86.exe
https://aka.ms/dotnet/6.0.4xx/daily/dotnet-sdk-win-x64.exe
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-3.1.26-windows-x64-installer

**Steps:**
Execute the following commands by Powershell:
1)	$env:DOTNET_MULTILEVEL_LOOKUP=0
2)	ls env:
3)	dotnet new mstest
4)	Update file UnitTest1.cs with
 
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections;
using System.Diagnostics;
using System.Text;
 
namespace CreateScenarioForVendors
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            StringBuilder builder = new StringBuilder();
 
            builder.AppendLine();
            builder.AppendLine();
            foreach (DictionaryEntry var in Environment.GetEnvironmentVariables())
            {
                if(var.Key.ToString().StartsWith("DOTNET_"))
                {
                    builder.AppendLine($"{var.Key.ToString()} {var.Value}");
                }
            }
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine($"ProcessArchitecture {System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture.ToString()}");
            builder.AppendLine($"Location {typeof(object).Assembly.Location}");
            builder.AppendLine($"Process name {Process.GetCurrentProcess().Modules[0].FileName}");
 
            throw new Exception(builder.ToString());
        }
    }
}
```
  
Update the project file in in this way 
 
```
<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <TargetFrameworks>net7.0;netcoreapp3.1</TargetFrameworks>
    <IsPackable>false</IsPackable>
  <LangVersion>latest</LangVersion>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version=" 17.1.0-preview-20211130-02" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.7" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.7" />
    <PackageReference Include="coverlet.collector" Version="3.1.0" />
  </ItemGroup>
 
</Project>
```
5)	dotnet test --framework net7.0 --diag:loga.txt
6)	&"C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:logna.txt

**Expected Result:**
The command should be run normally as following:
 ![image](https://user-images.githubusercontent.com/87680983/173751881-4b37d665-69cd-4ea1-82a6-1c5dd75ac5f5.png)

**Actual Results:**
Fail to run the command – & “C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:logna.txt
 ![image](https://user-images.githubusercontent.com/87680983/173751916-5d0a3cd8-fb53-462a-8906-7d3a1281d1d7.png)

**--Log:**
```
PS C:\Users\v-wenjj\Desktop\mstest> dotnet test --framework net7.0 --diag:loga.txt
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\7.0.100-preview.6.22314.18\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierIn
ference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support
-policy [C:\Users\v-wenjj\Desktop\mstest\mstest.csproj]
  mstest -> C:\Users\v-wenjj\Desktop\mstest\bin\Debug\net7.0\mstest.dll
Test run for C:\Users\v-wenjj\Desktop\mstest\bin\Debug\net7.0\mstest.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.0-preview-20220610-03 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\v-wenjj\Desktop\mstest\loga.txt
A total of 1 test files matched the specified pattern.
  Failed TestMethod1 [36 ms]
  Error Message:
   Test method CreateScenarioForVendors.UnitTest1.TestMethod1 threw exception:
System.Exception:

DOTNET_HOST_PATH C:\Program Files\dotnet\dotnet.exe
DOTNET_MULTILEVEL_LOOKUP 0


ProcessArchitecture Arm64
Location C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.6.22312.1\System.Private.CoreLib.dll
Process name C:\Program Files\dotnet\dotnet.exe

  Stack Trace:
      at CreateScenarioForVendors.UnitTest1.TestMethod1() in C:\Users\v-wenjj\Desktop\mstest\UnitTest1.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 58 ms - mstest.dll (net7.0)
```
```
PS C:\Users\v-wenjj\Desktop\mstest> &"C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:logna.txt
  Determining projects to restore...
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.6.22314.18\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFramewo
rkInference.targets(54,5): "[MSBuild]::GetTargetFrameworkIdentifier(netcoreapp3.1)" canno
t be evaluated. Exception has been thrown by the target of an invocation. [C:\Users\v-wenjj\Desktop\mstest\mstest.cspro
j]
```

**Comment by danmoseley** [comment]
As the stack suggests, it's executing ref-emitted code here. The regex is either NonTransformItemMetadataPattern or ItemMetadataPattern. So main possibilities are - a bug introduced into the compiled regex engine or a bug in the runtime. Either way, that's showing up only when in 32 bit x86 running on Windows Arm64.

@BenVillalobos since you have a machine set up that repros this, is it possible to dump (out of the debugger) both the regex pattern, regex options, and the string it's running on? Then paste those into a Hello World app to see whether just running that pattern against that string triggers it. If so -- we've substantially narrowed this down.

**Comment by v-hozha1** [comment]
This issue also repro on dotnet-sdk-7.0.100-preview.7.22358.13.
Command:
 & “C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:logna.txt
 & "C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch x64 --diag:logz2.txt
 & "C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch arm64 --diag:logz2.txt
 
![image](https://user-images.githubusercontent.com/100275240/178190627-fd42e4f4-9ea2-4db4-b458-c1b7b0e2dc53.png)


PS C:\tmp\mstest> & "C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch x64 --diag:logz2.txt
  Determining projects to restore...
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(55,5): error MSB4184: The expres
sion "[MSBuild]::GetTargetFrameworkVersion(net7.0, 2)" cannot be evaluated. Exception has been thrown by the target of an invocation. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018: The "MSBuild" task failed unexpectedly. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance o
f an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [C:\
tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, B
indingFlags invokeAttr) [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutp
uts" parameter. Object reference not set to an instance of an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018: The "MSBuild" task failed unexpectedly. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance o
f an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [C:\
tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, B
indingFlags invokeAttr) [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutp
uts" parameter. Object reference not set to an instance of an object. [C:\tmp\mstest\mstest.csproj]
PS C:\tmp\mstest> & "C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch arm64 --diag:logz2.txt
  Determining projects to restore...
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018: The "MSBuild" task failed unexpectedly. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance o
f an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [C:\
tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, B
indingFlags invokeAttr) [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1111,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutp
uts" parameter. Object reference not set to an instance of an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018: The "MSBuild" task failed unexpectedly. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance o
f an object. [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [C:\
tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, B
indingFlags invokeAttr) [C:\tmp\mstest\mstest.csproj]
C:\Program Files (x86)\dotnet\sdk\7.0.100-preview.7.22358.13\NuGet.targets(1208,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutp
uts" parameter. Object reference not set to an instance of an object. [C:\tmp\mstest\mstest.csproj]
PS C:\tmp\mstest>

**Comment by mangod9** [comment]
Does this only repro with x86 emulation on arm64? There was a recent fix which was made recently for that.

**Comment by v-hozha1** [comment]
This issue still repro on today's dotnet-sdk-7.0.100-rc.1.22377.7. 

Does this only repro with x86 emulation on arm64?
--Yes.  For the x64 emulation on arm64, there's another issue https://github.com/dotnet/msbuild/issues/7721 to track.

**Comment by mangod9** [comment]
If this is emulation only then its most likely a dupe of https://github.com/dotnet/runtime/issues/71856.

**Comment by mangod9** [comment]
A similar issue is closed: #71856, Please validate that this is now fixed.

**Comment by v-hozha1** [comment]
This issue still repro on today's build dotnet-sdk-7.0.100-rc.1.22403.8. Here is the repro VM: 172.20.30.177

Please refer to the project & dump file from: \\mlangfs1\public\v-hozha1\20220804-71098\

PS C:\tmp\mstest> &"C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --diag:log1.txt
  Determining projects to restore...
C:\Program Files (x86)\dotnet\sdk\7.0.100-rc.1.22403.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(55,5): error MSB4184: The expression "[MSBuild]::GetTargetFrameworkVersion(net7.0, 2)" cannot be evalua
ted. Exception has been thrown by the target of an invocation. [C:\tmp\mstest\mstest.csproj]
PS C:\tmp\mstest> &"C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch x64 --diag:log2.txt
  Determining projects to restore...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at InvokeStub_IntrinsicFunctions.IsOSPlatform(Object, Object, IntPtr*)
PS C:\tmp\mstest> &"C:\Program Files (x86)\dotnet\dotnet.exe" test --framework net7.0 --arch arm64 --diag:log3.txt
  Determining projects to restore...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at InvokeStub_CheckIfPackageReferenceShouldBeFrameworkReference.get_ShouldRemovePackageReference(Object, Object, IntPtr*)
PS C:\tmp\mstest>

![image](https://user-images.githubusercontent.com/100275240/182752204-145a41ba-922a-40ce-adf4-9324ab49cb56.png)

**Comment by mangod9** [comment]
the fix should be in runtime 7.0.0-rc.1.22403.8 and sdk 7.0.100-rc.1.22404.5

**Comment by mangod9** [comment]
Closing since this should be fixed.

**Comment by v-hozha1** [comment]
This issue has been fixed on dotnet-sdk-7.0.100-rc.1.22414.7. Details please refer to below:
![image](https://user-images.githubusercontent.com/100275240/184611158-d462578d-351a-4c96-8857-3299a1404e96.png)

![image](https://user-images.githubusercontent.com/100275240/184610936-b891d9fd-610f-4af2-a354-9185c4a1f85c.png)
![image](https://user-images.githubusercontent.com/100275240/184610976-9e4d5602-f369-46eb-9e2b-0cee32eb7577.png)
![image](https://user-images.githubusercontent.com/100275240/184611086-ef2e8b21-28e5-43b4-aa0d-03d3726b42d7.png)
