### ISSUE TITLE
Distributed transactions: AccessViolationException on arm64

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#74170]
Happens a lot -- see [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.transactions.local.tests+work+item%22):
- 8/25 - 81x failures on net7.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open
    - First failure on 8/12 in PR [1939026](https://runfo.azurewebsites.net/view/build/?number=1939026)
    - Impact: **6x failures per day** - blocking CI

win-arm64 libraries random JitStress failure

```
D:\h\w\AFDD09E1\w\B09109AB\e>set COMPlus 
COMPlus_JitStress=36f
COMPlus_TieredCompilation=0

D:\h\w\AFDD09E1\w\B09109AB\e>call RunTests.cmd --runtime-path D:\h\w\AFDD09E1\p 
----- start Thu 08/18/2022  0:42:25.05 ===============  To repro directly: ===================================================== 
pushd D:\h\w\AFDD09E1\w\B09109AB\e\
"D:\h\w\AFDD09E1\p\dotnet.exe" exec --runtimeconfig System.Transactions.Local.Tests.runtimeconfig.json --depsfile System.Transactions.Local.Tests.deps.json xunit.console.dll System.Transactions.Local.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

D:\h\w\AFDD09E1\w\B09109AB\e>"D:\h\w\AFDD09E1\p\dotnet.exe" exec --runtimeconfig System.Transactions.Local.Tests.runtimeconfig.json --depsfile System.Transactions.Local.Tests.deps.json xunit.console.dll System.Transactions.Local.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Transactions.Local.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Transactions.Local.Tests (found 131 of 142 test cases)
  Starting:    System.Transactions.Local.Tests (parallel test collections = on, max threads = 8)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at System.Transactions.DtcProxyShim.DtcInterfaces.IResourceManagerFactory2.CreateEx(System.Guid, System.String, System.Transactions.DtcProxyShim.DtcInterfaces.IResourceManagerSink, System.Guid, System.Object ByRef)
--------------------------------
   at System.Transactions.DtcProxyShim.DtcProxyShimFactory+<>c__DisplayClass10_0.<ConnectToProxy>b__2()
   at System.Transactions.DtcProxyShim.OletxHelper.Retry(System.Action)
   at System.Transactions.DtcProxyShim.DtcProxyShimFactory.ConnectToProxy(System.String, System.Guid, System.Object, Boolean ByRef, Byte[] ByRef, System.Transactions.DtcProxyShim.ResourceManagerShim ByRef)
   at System.Transactions.Oletx.DtcTransactionManager.Initialize()
   at System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory()
   at System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(System.Transactions.TransactionOptions)
   at System.Transactions.TransactionStatePromoted.EnterState(System.Transactions.InternalTransaction)
   at System.Transactions.EnlistableStates.EnlistDurable(System.Transactions.InternalTransaction, System.Guid, System.Transactions.IEnlistmentNotification, System.Transactions.EnlistmentOptions, System.Transactions.Transaction)
   at System.Transactions.Transaction.EnlistDurable(System.Guid, System.Transactions.IEnlistmentNotification, System.Transactions.EnlistmentOptions)
   at System.Transactions.Tests.OleTxTests+OleTxFixture..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.ConstructorInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Xunit.Sdk.XunitTestClassRunner+<>c__DisplayClass10_0.<CreateClassFixture>b__3()
   at Xunit.Sdk.ExceptionAggregator.Run(System.Action)
   at Xunit.Sdk.XunitTestClassRunner+<CreateClassFixtureAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.XunitTestClassRunner+<CreateClassFixtureAsync>d__11, xunit.execution.dotnet, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<CreateClassFixtureAsync>d__11 ByRef)
   at Xunit.Sdk.XunitTestClassRunner.CreateClassFixtureAsync(System.Type)
   at Xunit.Sdk.XunitTestClassRunner+<AfterTestClassStartingAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.XunitTestClassRunner+<AfterTestClassStartingAsync>d__13, xunit.execution.dotnet, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AfterTestClassStartingAsync>d__13 ByRef)
   at Xunit.Sdk.XunitTestClassRunner.AfterTestClassStartingAsync()
   at Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestClassRunner`1+<RunAsync>d__37[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__37<System.__Canon> ByRef)
   at Xunit.Sdk.TestClassRunner`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestCollectionRunner`1+<RunTestClassesAsync>d__28[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunTestClassesAsync>d__28<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunTestClassesAsync()
   at Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestCollectionRunner`1+<RunAsync>d__27[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__27<System.__Canon> ByRef)
   at Xunit.Sdk.TestCollectionRunner`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.SynchronizationContextTaskScheduler+<>c.<.cctor>b__8_0(System.Object)
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(System.Threading.SendOrPostCallback, System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
   at Xunit.Sdk.XunitWorkerThread+<>c.<QueueUserWorkItem>b__5_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
```

@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Could this be related to recent changes in this area? I am able to repro this even without the jitstress flags.

This was recently ported to Windows in https://github.com/dotnet/runtime/pull/72051 and seems related to that. 

Here is the call stack on windows/arm64

```
00 MSDTCPRX!CIResourceManagerFactory::CreateEx
01 xunit_console!ILStubClass.IL_STUB_CLRtoCOM(System.Guid, System.String, System.Transactions.DtcProxyShim.DtcInterfaces.IResourceManagerSink, System.Guid, System.Object ByRef)
02 System_Transactions_Local!System.Transactions.DtcProxyShim.DtcProxyShimFactory+<>c__DisplayClass10_0.<ConnectToProxy>b__2()
03 System_Transactions_Local!System.Transactions.DtcProxyShim.OletxHelper.Retry(System.Action)
04 System_Transactions_Local!System.Transactions.DtcProxyShim.DtcProxyShimFactory.ConnectToProxy(System.String, System.Guid, System.Object, Boolean ByRef, Byte[] ByRef, System.Transactions.DtcProxyShim.ResourceManagerShim ByRef)
05 System_Transactions_Local!System.Transactions.Oletx.DtcTransactionManager.Initialize()
06 System_Transactions_Local!System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory()
07 System_Transactions_Local!System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(System.Transactions.TransactionOptions)
08 System_Transactions_Local!System.Transactions.TransactionStatePromoted.EnterState(System.Transactions.InternalTransaction)
09 System_Transactions_Local!System.Transactions.EnlistableStates.EnlistDurable(System.Transactions.InternalTransaction, System.Guid, System.Transactions.IEnlistmentNotification, System.Transactions.EnlistmentOptions, System.Transactions.Transaction)
0a System_Transactions_Local!System.Transactions.Transaction.EnlistDurable(System.Guid, System.Transactions.IEnlistmentNotification, System.Transactions.EnlistmentOptions)
0b System_Transactions_Local_Tests!System.Transactions.Tests.OleTxTests+OleTxFixture..ctor()
0c coreclr!CallDescrWorkerInternal

```

![image](https://user-images.githubusercontent.com/12488060/185493875-e32e210b-7333-4602-a8b4-b6508b599be5.png)


![image](https://user-images.githubusercontent.com/12488060/185494135-87b90ac9-ffd9-40a6-9148-627357211bba.png)

**Comment by roji** [comment]
Will look at this ASAP

**Comment by kunalspathak** [comment]
I would be curious to know why we don't see these failures in other CI pipelines.

**Comment by AaronRobinsonMSFT** [comment]
@roji I may have missed the by-ref for the `GUID`s in this case. In fact, now that I think about it that is the issue. I'd update the interfaces that take a `GUID*` or a `REFGUID` to be defined as `in Guid` or `ref Guid` depending on the desired semantics.

**Comment by roji** [comment]
@AaronRobinsonMSFT thanks, I'll prepare a PR for that tomorrow. Though the debugging session above seems to show that ppvResMgr is the source of the crash, which seems very odd (it's just an out parameter on the .NET side). And yeah, like @kunalspathak I'm wondering why this hasn't shown up before in CI...

**Comment by karelz** [comment]
@roji this is heavily impacting CI -- 6x failures per day. Can you please merge the fix PR #74226, or at least disable the tests ASAP? (incl. 7.0 branch) Thanks!

**Comment by roji** [comment]
I can merge #74226, but @kunalspathak indicated above that the failure still occurs. Looking at the error again, this occurs [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/DtcProxyShimFactory.cs#L107), one of the 1st interop calls done; ConnectToProxy is first thing that ever does interop in Sys.Tx. [The stack trace](https://github.com/dotnet/runtime/issues/74170#issuecomment-1219959409) in #74170 seems to indicate that the last parameter, ppvResMgr, points to an invalid address; since this is a plain .NET out variable, this seems like it could only happen if there's some issue with the signature of the CreateEx method ([signature in this PR](https://github.com/dotnet/runtime/blob/ae78dcc8a012f772b000161c4d18f5e9939f8473/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/DtcInterfaces/IResourceManagerFactory2.cs#L18), [docs](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms681318(v=vs.85))), or something more low level. @AaronRobinsonMSFT note that there's interface inheritance going on here (IResourceManagerFactory.Create and IResourceManagerFactory2.CreateEx), in case that's related.

With this happening only on arm64, and even there not deterministically, I'm out of my depth here... I've pushed a change here to disable the tests on ARM to unblock the build, and will merge. Hopefully we can resolve the issue soon and reenable.

**Comment by AaronRobinsonMSFT** [comment]
I've looked at that signature several times and can't see anything obviously wrong here. The loop and retry is the only thing I'd consider "odd". Let's try an experiement, update the signature to be `out IntPtr` and then manually marshal the `IntPtr` to the type via `Marshal.GetObjectForIUnknown`. This is theoretically what the marshaller should be doing. It might also be helpful to get an assembly dump of the stub.

**Comment by roji** [comment]
@AaronRobinsonMSFT I've pushed [this commit](https://github.com/dotnet/runtime/pull/74226/commits/d0845d842761b64b1790849cbd5cd50960760fca) to #74226, tests pass locally. I'm guessing we're going to need @kunalspathak's help for verifying whether this helps - and also to get an arm64 assembly dump of the stub...

**Comment by karelz** [comment]
Tests disabled in main (8.0) in PR #74572 and in 7.0 (for RC2) in PR #74573 -- not blocking clean CI anymore.

**Comment by karelz** [comment]
@roji this is weird - it seems the problem is still happening in CI - last hit is in 8/26@2pm Rolling run [1970381](https://runfo.azurewebsites.net/view/build/?number=1970381) in main, which should be 21h after your disabling PR. Can you please check it?

**Comment by roji** [comment]
@karelz thanks, I see the issue - this is a test that isn't expected to contact MSDTC (System.Transactions.Tests.NonMsdtcPromoterTests.PSPENonMsdtcGetPromoterTypeMSDTC), and therefore isn't in the test suite where I added the skipping for arm64. I'll sort this out.

**Comment by roji** [comment]
@kunalspathak @AaronRobinsonMSFT how can we make progress on this arm64-specific issue? @kunalspathak neither @AaronRobinsonMSFT nor I have access to an arm64 machine - are you able to help us iterate on this as per https://github.com/dotnet/runtime/issues/74170#issuecomment-1227538603? I'm worried not so much about arm64 distributed transaction support, but more that there's some deeper bug in interop there, since the interop signatures seem to be fine - so we may want to prioritize this as a general arm64 bug. Is there someone we should loop in on this?

If we think we can't manage to investigate this in time, I'll go ahead and a runtime check aganist arm64, so that users get a clean PlatformNotSupportedException right away rather than a non-deterministic AccessViolationException.

**Comment by danmoseley** [comment]
I'm marking blocking-release so this stays on the radar.

**Comment by roji** [comment]
See update in https://github.com/dotnet/runtime/pull/74570#issuecomment-1242035821 - I propose to block ARM for rc2 and am updating PRs #74226 and #74570 to do so. We can continue investigating in parallel, of course.

**Comment by karelz** [comment]
@roji should we re-enable the tests and remove links to this issue? https://github.com/dotnet/runtime/search?q=74170

**Comment by roji** [comment]
@karelz no, unfortunately the issue still persists... My proposal was to block distributed transactions on arm64 because of this, but we may want to allow it instead (see https://github.com/dotnet/runtime/pull/74570#issuecomment-1242984514). In any case, the intention is to get to the bottom of this post-rc2, possibly post-7.0.

**Comment by roji** [comment]
Due to a previous mis-communication, it was believed that we're still seeing AccessViolationException even after some interop fixes (see https://github.com/dotnet/runtime/pull/74226). However, we're no longer able to reproduce the AccessViolationException. arm64 support has been re-enabled in #75703, including all testing.

Closing this, will reopen if we see AccessViolationException again.
