### ISSUE TITLE
Test failure in ilconformance jmp

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#78579]
Test Run: [runtime-coreclr pgo 20221118.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=87531)

Failed tests: 
```
coreclr Linux arm Checked defaultpgo @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
coreclr Linux arm64 Checked defaultpgo @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
coreclr Linux x64 Checked defaultpgo @ Ubuntu.1804.Amd64.Open

-  JIT/IL_Conformance/Old/Base/jmp/jmp.sh
```

Error message:
```
Expected: True
      Actual:   False
      Stack Trace:
           at JIT_IL_Conformance._Old_Base_jmp_jmp_._Old_Base_jmp_jmp_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
```

cc @dotnet/jit-contrib.

**Comment by markples** [comment]
I've now realized that I fell victim to the "pri 1 tests aren't run in CI" issue.  This is the test, not PGO.

**Comment by markples** [comment]
Fixed by #78582

**Comment by jakobbotsch** [comment]
#78582 just fixed one of the examples, looks like there are three more that are still failing (https://dev.azure.com/dnceng-public/public/_build/results?buildId=88961&view=ms.vss-test-web.build-test-results-tab&runId=1872512&paneView=debug&resultId=104375)

**Comment by jakobbotsch** [comment]
I'll look at this since I think Mark is out.

**Comment by markples** [comment]
I can look unless you've already fixed it/them.

**Comment by jakobbotsch** [comment]
Feel free to, I was going to wait until tomorrow.

**Comment by markples** [comment]
The 3 tests use the same source .il file - so the above PR only has one IL file in it.

I scanned the rest of the IL files and didn't find any more jmps from .entrypoint methods, though the scan is crude.

**Comment by kunalspathak** [comment]
There were failures in pgostress on 11/18 but didn't fail in recent run. But just making a note - https://dev.azure.com/dnceng-public/public/_build/results?buildId=88476&view=ms.vss-test-web.build-test-results-tab&runId=1862128&resultId=115601&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
