### ISSUE TITLE
System.Management.dll not working on win-arm64

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#81400]
### Description

This dll works on x64, but fails to load the required native dll on win-arm64.  This is impacting the `Get-HotFix` cmdlet in PowerShell 7.

### Reproduction Steps

```csharp
var scope = new System.Management.ManagementScope(@"root\cimv2");
scope.Connect();
```

### Expected behavior

No error (nothing will happen with this snippet)

### Actual behavior

It appears to be trying to load the native library from `Framework64` when it should be loading it from `FrameworkArm64`:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (193): Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementScope..ctor(String path)
   at Program.<Main>$(String[] args) in C:\Users\slee\test\wmi\Program.cs:line 1
```

### Regression?

Don't know

### Configuration

.NET 7
Windows 11
arm64

**Comment by smasher164** [comment]
Could be related: https://github.com/dotnet/runtime/issues/59844

/cc @ericstj @danmoseley

**Comment by ViktorHofer** [comment]
We probably need to update the lookup code that finds the .NET Framework installation: https://github.com/dotnet/runtime/blob/2327a36c5222a8e4e522ab27455bcbd8002efd06/src/libraries/System.Management/src/System/Management/ManagementScope.cs#L292

**Comment by ericstj** [comment]
If possible, we should also re-enable tests on ARM64 while doing this.  https://github.com/dotnet/runtime/blob/59f7dafe28cae36f33eecbab40635663c042e4d5/src/libraries/System.Management/tests/WmiTestHelper.cs#L14

This wasn't possible in the past when we didn't have an ARM64 .NETFramework.  Now that we do, we should make it work 👍

**Comment by ericstj** [comment]
This is likely not a regression, but rather something that never worked but can now that we have an Arm64 .NET Framework.  @SteveL-MSFT how urgent is a fix here?

**Comment by SteveL-MSFT** [comment]
@ericstj I don't think it's super urgent, but the original issue was reported by a customer.  If it can be addressed within the next couple of months, I think that would be fine.

**Comment by SimonCropp** [comment]
isnt this a duplicate of https://github.com/dotnet/runtime/issues/59844?

just a head up that this also breaks 

 * https://github.com/VerifyTests/Verify
 * https://github.com/shouldly/shouldly
 * https://github.com/approvals/ApprovalTests.Net

since they will all be hit by  https://github.com/VerifyTests/DiffEngine/issues/315

**Comment by Nuklon** [comment]
Can't we ship that DLL with .NET Core instead? It would be much better than relying on .NET Framework being installed.

**Comment by SimonCropp** [comment]
@SteveL-MSFT 

> I don't think it's super urgent, but the original issue was reported by a customer. If it can be addressed within the next couple of months, I think that would be fine.

Note this was actually reported in Oct 2021 in [the ](https://github.com/dotnet/runtime/issues/59844). so a "couple of months" has definitely passed

**Comment by JamesWCCheng** [comment]
I also encountered this problem by using the latest 

https://github.com/dotnet/runtime/blob/2327a36c5222a8e4e522ab27455bcbd8002efd06/src/libraries/System.Management/src/System/Management/ManagementScope.cs#L305

[Experimental change]
If I set registry InstallRoot from C:\Windows\Microsoft.NET\Framework64\ to C:\Windows\Microsoft.NET\FrameworkArm64\

ARM64 process with WMI works fine.

I think it's a simple change, I'm looking forward to seeing it gets fixed soon.

**Comment by JamesWCCheng** [comment]
> I also encountered this problem by using the latest
> 
> https://github.com/dotnet/runtime/blob/2327a36c5222a8e4e522ab27455bcbd8002efd06/src/libraries/System.Management/src/System/Management/ManagementScope.cs#L305
> 
> [Experimental change] If I set registry InstallRoot from C:\Windows\Microsoft.NET\Framework64\ to C:\Windows\Microsoft.NET\FrameworkArm64\
> 
> ARM64 process with WMI works fine.
> 
> I think it's a simple change, I'm looking forward to seeing it gets fixed soon.

.netframework has no such issue since it wrote
System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory() + "\\wminet_utils.dll";
https://referencesource.microsoft.com/#System.Management/managementscope.cs,304
to compose the path. But this API didn't fit .net core.

Can Microsoft fix it as soon as possible? It's a critical issue I think, it makes this package malfunction.

**Comment by ViktorHofer** [comment]
We understand the importance here which is why I'll be working on a fix for this next week. After the fix is merged into main, we plan to backport it into .NET 6 and .NET 7.

**Comment by ViktorHofer** [comment]
Yes, the plan is to backport the fix into both the 6.0 and 7.0 nuget package but a) we don't yet have a fix ready and b) our shiproom needs to first approve the backports.

**Comment by SimonCropp** [comment]
@ViktorHofer 

> the plan is to backport the fix into both the 6.0 and 7.0 nuget package

thanks. thats great to hear

> that runtime is already out-of-support and we strongly discourage staying on it or offering assets for it because of the lack of security fixes

i hear you. but i still have a non-trivial number of people using my libs that are still on unsupported frameworks https://github.com/VerifyTests/Verify/issues/784

**Comment by ericstj** [comment]
WMINet_utils is a native binary and I believe requires machine-wide registration/installation to work correctly.  It also has never been open sourced, so it would need to go through that process.  On top of that the component isn't owned by .NET so it would require some help/permission from the owning team to see that happen assuming such a port was even possible.  That's all out of the scope of this issue and tracked by https://github.com/dotnet/runtime/issues/66386.

**Comment by Dharmateja-Challa-Dell** [comment]
I have done few changes as per previous comments, enabled unit test for ARM64, added one test case for this particular one. Not sure if this solution is correct or not, hence wanted to check, attaching my changes and unit test case and its results in both ARM64 and X64
[.NetCore81400.zip](https://github.com/dotnet/runtime/files/10968094/default.NetCore81400.zip)

**Comment by Dharmateja-Challa-Dell** [comment]
I have done few changes as per previous comments, enabled unit test for ARM64, added one test case for this particular issue. Not sure if this solution is correct or not, hence wanted to check, attaching my changes and unit test case and its results in both ARM64 and X64
[.NetCore81400.zip](https://github.com/dotnet/runtime/files/10968825/default.NetCore81400.zip)

**Comment by ViktorHofer** [comment]
@Dharmateja-Challa-Dell I won't open you attachment. Can you please let me know what your comment refers to?

**Comment by danmoseley** [comment]
@Dharmateja-Challa-Dell  if you want to share a proposed change please do it by pushing a branch to your fork and sending a link to that.

**Comment by Silve2611** [comment]
This is also a critical error for us. When can we expect for that it will be resolved? Do you have a timeframe?

**Comment by Dharmateja-Challa-Dell** [comment]
> @Dharmateja-Challa-Dell if you want to share a proposed change please do it by pushing a branch to your fork and sending a link to that.
Took a fork and added changes to branch
https://github.com/Dharmateja-Challa-Dell/runtime/branches/

**Comment by SimonCropp** [comment]
was this included in v6.0.1?  https://www.nuget.org/packages/System.Management/6.0.1

**Comment by ViktorHofer** [comment]
Yes, the fix is part of:
- https://www.nuget.org/packages/System.Management/6.0.1
- https://www.nuget.org/packages/System.Management/7.0.1
- https://www.nuget.org/packages/System.Management/8.0.0-preview.3.23174.8

**Comment by SimonCropp** [comment]
@ViktorHofer thanks
