### ISSUE TITLE
PublishAot affects non-AOT behavior

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/runtime#81803]
### Description

Adding `<PublishAot>true</PublishAot>` breaks dynamic code even when running the JIT version

### Reproduction Steps

```C#
Expression<Func<int, int, int, int>> e = (_, _, _) => 1;

e.Compile();
```

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```

```dotnet run```

### Expected behavior

No exceptions

### Actual behavior

```
Unhandled exception. System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.
   at System.Reflection.Emit.AssemblyBuilder.ThrowDynamicCodeNotSupported()
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes)
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type delegateType, Func`2 handler)
```

### Configuration

SDK: 8.0.100-preview.1.23107.12

**Comment by MichalStrehovsky** [comment]
This is intentional so that people don't get unpleasant surprise after they debug their app, they're ready to publish, and it doesn't work.

What's the scenario where a working Ref.Emit would be needed during inner dev loop, but got broken on publish?

Cc @eerhardt

**Comment by eerhardt** [comment]
This was fixed with https://github.com/dotnet/runtime/pull/80759. Linq.Expressions should still work, even though PublishAot=true. It just doesn't use Ref.Emit in that case, it falls back to the interpreter mode, like it will for the published app.

@AndriySvyryd - can you try a newer build?

**Comment by AndriySvyryd** [comment]
> This was fixed with https://github.com/dotnet/runtime/pull/80759. Linq.Expressions should still work, even though PublishAot=true. It just doesn't use Ref.Emit in that case, it falls back to the interpreter mode, like it will for the published app.

>This is intentional so that people don't get unpleasant surprise after they debug their app, they're ready to publish, and it doesn't work.

>What's the scenario where a working Ref.Emit would be needed during inner dev loop, but got broken on publish?

I was just using this specific case to illustrate that `PublishAot` has a functional impact on the code. The approach EF Core is using to add support for NativeAOT is to first run a portion of the app in JIT, perform all the dynamic operations that would be normally not supported by NativeAOT, then generate source code for the app that would be compatible with NativeAOT.

Currently it's possible to do this by removing `PublishAot` before running the EF tool, but this would be less than ideal experience once we ship 8.0

**Comment by AndriySvyryd** [comment]
> My understanding is that EF Core doesn't use Ref.Emit directly, but instead uses System.Linq.Expressions. If this is the case, Linq.Expressions will opt to not use Ref.Emit, but instead use an interpreted mode.

Correct. As long as there are no other intentional functional differences than the ones mentioned above it should be fine.

> You just need to upgrade to a newer build.

I still get it with SDK `8.0.100-preview.2.23108.9` and runtime `8.0.0-preview.2.23102.7`

**Comment by jkotas** [comment]
> The approach EF Core is using to add support for NativeAOT is to first run a portion of the app in JIT, perform all the dynamic operations that would be normally not supported by NativeAOT, then generate source code for the app that would be compatible with NativeAOT.

How do you guarantee that the test execution of the app performed all operations that the app needs to perform dynamically?

One of principles is to avoid designs that require trial and error: https://github.com/dotnet/designs/blob/main/accepted/2020/form-factors.md#technical-roadmap .

**Comment by AndriySvyryd** [comment]
> How do you guarantee that the test execution of the app performed all operations that the app needs to perform dynamically?

Of course, we can't guarantee that. We discover the user's DbContext and the statically known LINQ queries. But we also plan to provide a hook that would allow the users to explicitly call the dynamic queries and we'll generate code for the exercised combinations. Truly dynamic models and queries won't be supported. We are investigating whether we can provide an analyzer that would find the unsupported queries to avoid trial and error. Also, if the user runs their tests with `<PublishAot>true</PublishAot>` we'll throw for anything unsupported.

**Comment by agocke** [comment]
Given that this is by design, I'm going to close this issue. If there are more specific concerns, we can address them in a separate issue.

**Comment by AndriySvyryd** [comment]
The specific issue described in the first comment still reproes in 8.0.100-preview.3.23151.5

**Comment by eerhardt** [comment]
Looks like I missed a couple places in System.Linq.Expressions to respect IsDynamicCodeSupported in #80759.

In this case:

https://github.com/dotnet/runtime/blob/967250cc86b4c613015066b47b882e7424fdb590/src/libraries/System.Linq.Expressions/src/System/Dynamic/Utils/DelegateHelpers.cs#L34-L41

`CanEmitObjectArrayDelegate` needs to be updated to respect this switch.

According to 

https://github.com/dotnet/runtime/blob/ef0241ed9316bc4343e715daca4d88c1ff90231b/src/coreclr/tools/aot/ILCompiler/repro/repro.csproj#L38-L40

It looks like `CanCreateArbitraryDelegates` should be updated as well.

Re-opening to fix these places in System.Linq.Expressions.

**Comment by eerhardt** [comment]
@MichalStrehovsky - in trying to fix this issue (https://github.com/dotnet/runtime/compare/main...eerhardt:runtime:Fix81803), I hit a snag:

https://github.com/dotnet/runtime/blob/f59a3f577795f5002fb9a4e14f84db8eabd70d07/src/libraries/System.Linq.Expressions/src/System/Dynamic/Utils/DelegateHelpers.cs#L24-L29

When running on CoreCLR, this type/method doesn't exist. Is there a way to simulate what `CreateObjectArrayDelegate` does when running on CoreCLR?

**Comment by MichalStrehovsky** [comment]
> When running on CoreCLR, this type/method doesn't exist. Is there a way to simulate what `CreateObjectArrayDelegate` does when running on CoreCLR?

We would need Ref.Emit on CoreCLR to emulate it, so it's better to not take this codepath and leave the existing Ref.Emit one since it's ref.emit either way. In Native AOT, this relies on the fact that the AOT compiler will generate extra thunks for each delegate type in the app to support this.

I understand it's a bit of a pickle because we don't want ref.emit to work. We might need some sort of backdoor ref-emit.

What I mean is that we would add a private API from CoreLib that we reflection-discover like the above `CreateObjectArrayDelegate`. It would set a threadstatic somewhere in CoreLib that would say "this thread now allows Ref.Emit" and e.g. return an `IDisposable` (that would set it back to ref emit not supported). Then whenever we're about to throw in CoreLib because someone attempted ref-emit, we would additionally check for this threadstatic.

**Comment by inforithmics** [comment]
I'm not a Runtime Expert, but in Xamarin.iOS the same problem exsists. 
Because on iOS only Native Code is allowed (AOT). So to support Dynamic Code the (Mono) Interpreter is used as a FallBack to handle Reflection.Emit and other dynamic Code Patterns.

Project Property for that
` <UseInterpreter>true</UseInterpreter>`

https://github.com/xamarin/xamarin-android/pull/6556
