### ISSUE TITLE
Blazor Wasm Debugging appears to be broken in Chrome 111.0.5563.65

### ISSUE THREAD

**Issue by Webreaper** [dotnet/runtime#83452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Debugging a .Net 7 Blazor WASM app with Chrome 111.0.5563.65 fails - the WASM loads with the progress meter, but then the Browser closes with an error status (but no error message of any kind). Rolled back to Chrome 110.5481.178, and debugging works again just fine. Edge also works. This is running on Windows, with VS 17.4.3 (but other colleagues have seen the same issue with newer versions of VS).

### Expected Behavior

Debugging should work on any Chrome version. 

### Steps To Reproduce

1. Create a Blazor WASM Hosted project in .Net 7
2. Start debugging
3. Wasm progress bar runs to 100%
4. First page loads
5. Chrome exits.

### Exceptions (if any)

No debugging or exception information available.

### .NET Version

7.0

### Anything else?

Seems to happen to a few people, but not always reproducible. Asked here and at least one other person reported it:

https://twitter.com/DamselflyPhotos/status/1635699445269516290

**Comment by thaystg** [comment]
@javiercn 
This is probably related to this issue on vscode-js-debug and on BrowserDebugProxy.
https://github.com/dotnet/runtime/pull/82852
https://github.com/microsoft/vscode-js-debug/pull/1580

The PR's are already backported to all the versions but we need to wait until they are shipped in the case of the BrowserDebugProxy fix, but for the vscode-js-debug fix the only solution is to wait for a VS fixed and update it.

Pinging @joj for his knowledge.

**Comment by TFTomSun** [comment]
@thaystg Is it possible to manually hotfix it by overwriting some files under 
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\JSDiagnostics\Debugger\DebugAdapter\src
?

We are currently completely blocked by that issue. Typescript debugging in VS doesn't work anymore since we got all the chrome version updated in our enterprise network.

**Comment by thaystg** [comment]
@TFTomSun It looks like this is already fixed on chrome dev version, so if you can use chrome dev version this is a workaround for now.

**Comment by TFTomSun** [comment]
@thaystg  I have a Edge Canary version installed already, but it seems still to be broken there. Is the Edge Canary on the same version like the chrom dev?

**Comment by TFTomSun** [comment]
Ok I'll try the chrom dev then. Thanks alot.

**Comment by jbarrineau06** [comment]
I'm having this issue, but I found that deleting the .vs folder allows me to get in a few debugging runs before it starts happening again.

**Comment by joj** [comment]
Yes, deleting all the breakpoints will prevent the error from happening, and deleting the .vs folder will in most cases remove all your breakpoints. That's not a very good solution for most, though, I believe.

**Comment by Webreaper** [comment]
The only solution we found that scales is to switch to Edge. We can't really roll back a corporate rollout of Chrome for loads of developers in any practical sense.

Edge works reasonably well though, although debugging seems to have some limitations over chrome (mainly around watching nested object properties).

**Comment by mayur-ekbote** [comment]
I have a very similar issue since yesterday (page doesn't load / partly loads) buy with Blazor *server*. Chrome and edge both have the problem . Only Firefox developer version seems to be working.

**Comment by nbiada** [comment]
Without auto launch of browser it works of prod version

**Comment by rasaconsulting-sandy** [comment]
Can I please get a status update on this issue.  Thanks

**Comment by jclarkcds** [comment]
I was referred to this issue by https://learn.microsoft.com/en-us/answers/questions/1189857/blazor-app-crashes-when-debugging-after-windows-se?orderby=newest&source=docs which describes debugging breaking after windows updates.

Similar to [mayur-ekbote](https://github.com/mayur-ekbote), my app is .net7 blazor server with identity.  Yesterday, when starting the application in the debugger, the site freezes on a blank login page, nothing works including F12.  If I step into it, app.Run() never returns.
 
I stumbled upon the forementioned article, which led me to delete all my breakpoints.  The application starts normally.  I can add breakpoints after starting and trap, BUT if I ever stop the application - I have to delete the breakpoints start debugging again.

I also started getting the Page Closed Unexpectedly dialog asking to Restore Pages (which is always my previous crashed session).

I also tried updating to from 17.5.0 to 17.5.2.  No love.  This is frustrating - cost me a day.

All being said, I wanted to throw in my two cents in case this is not the same issue.

**Comment by thaystg** [comment]
The issue that you are seeing are already fixed on newer Chrome/edge versions. 
Please try to use beta/dev version.
This issue is duplicated of this one: https://github.com/dotnet/runtime/issues/83521

**Comment by rasaconsulting-sandy** [comment]
I've managed to resolve my issue by updating MS Edge to Version 111.0.1661.44 (Official build) (64-bit).  A bit frustrating that I had to manually update Edge but I'm happy debugging is working again and I can now work productively.

**Comment by dazinator** [comment]
I switched to firefox dev edition, and probably won't be switching back now! Having to sign up for access to dev releases of google chrome was not in my interest. Likewise edge wasn't fixed straight away so fix there. Lucky we have firefox on stand by.

**Comment by thaystg** [comment]
I'm using this edge version and it's working for me.
![image](https://user-images.githubusercontent.com/4503299/226378916-febf22b9-038e-4c70-9f16-8a05dc9954d8.png)

**Comment by thaystg** [comment]
And it's also working for me on chrome canary:
![image](https://user-images.githubusercontent.com/4503299/226381171-9773db87-2100-4f53-973c-686ed7a3dec9.png)

**Comment by thaystg** [comment]
Can you please help us to reproduce?

**Comment by TFTomSun** [comment]
Ah yes ... I missed the last digit. As I said on my second Laptop I had 111.0.1661.4**1** but now I got also 111.0.1661.4**4** deployed there and it works. Sorry for the confusion.
