### ISSUE TITLE
Frame not in module when hitting a breakpoint in Blazor WASM

### ISSUE THREAD

**Issue by joseangelmt** [dotnet/runtime#86754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to Visual Studio 17.6.0 and 17.6.1 the debugger shows me a _Source Not Available_ page  with the body:

```
Frame not in module
The current stack frame was not found in a loaded module. Source cannot be shown for this location.
```

The curious thing is that in the .razor file the breakpoints selected before executing the application are kept without warnings, but if I add one while the application is running, it appears with the warning: "The breakpoint will not currently be hit. Unbound breakpoint".

When I open the debug window "Modules" I can check that the module "Application.server.dll" has the status "Symbols loaded" and that the "symbol file" is correct.

I have tried deleting the .obj and .bin directories, I have tried with .net 6 and .net 7 (with their corresponding updated NuGet packages), I have tried with different browsers, and in all of them, the error is the same.

When debugging no error appears in the Output window.

The curious thing is that if I create a new application with the wizard, there is no problem and Visual Studio stops at the line in the .razor file. I have analyzed both projects and I do not see what could be the cause of my main project causing this problem.

### Expected Behavior

- That Visual Studio allows me to add breakpoints without displaying the error "The breakpoint will not currently be hit. Unbound breakpoint".
- Visual Studio stops at the correct line in the .razor file once it hits the breakpoint.

### .NET Version

7.0.302

### Anything else?

- ASP.NET Core version: 6.0.16 or 7.0.5
- Visual Studio 17.6.1

```
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by joseangelmt** [comment]
> @joseangelmt I need more help to reproduce/understand what may be happening. First, can you share the code? Second, can you share the file: C:\Users[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt Third, can you share the nuget packages that you are using and the versions in your projects?
> 
> Thanks

- The project is huge, I'm trying to reproduce in a smaller one.
- [visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/11566964/visualstudio-js-debugger.txt)

```
Id                                  Versions                                 ProjectName                                                                                                                  
--                                  --------                                 -----------                                                                                                                  
SharpZipLib                         {1.4.2}                                  Subestaciones.Server                                                                                                         
Microsoft.VisualStudio.Web.CodeG... {7.0.6}                                  Subestaciones.Server                                                                                                         
Microsoft.AspNetCore.ApiAuthoriz... {7.0.5}                                  Subestaciones.Server                                                                                                         
Microsoft.AspNetCore.Components.... {7.0.5}                                  Subestaciones.Server                                                                                                         
Microsoft.EntityFrameworkCore.Sq... {7.0.5}                                  Subestaciones.Server                                                                                                         
Microsoft.AspNetCore.Authenticat... {7.0.5}                                  Subestaciones.Server                                                                                                         
Microsoft.AspNetCore.Identity.UI    {7.0.5}                                  Subestaciones.Server                                                                                                         
Azure.Storage.Blobs                 {12.16.0}                                Subestaciones.Server                                                                                                         
Microsoft.EntityFrameworkCore.Tools {7.0.5}                                  Subestaciones.Server                                                                                                         
Microsoft.Extensions.Http           {7.0.0}                                  Subestaciones.Client                                                                                                         
TG.Blazor.IndexedDB                 {1.5.0-preview}                          Subestaciones.Client                                                                                                         
Blazor.ConnectionStatusDetector     {1.0.0}                                  Subestaciones.Client                                                                                                         
Microsoft.AspNetCore.Components.... {7.0.5}                                  Subestaciones.Client                                                                                                         
Microsoft.AspNetCore.Components.... {7.0.5}                                  Subestaciones.Client                                                                                                         
Blazor.Bootstrap                    {1.7.3}                                  Subestaciones.Client                                                                                                         
BlazorPro.BlazorSize                {6.2.1}                                  Subestaciones.Client                                                                                                         
Microsoft.AspNetCore.Components.... {7.0.5}                                  Subestaciones.Client                                                                                                         
Microsoft.AspNetCore.SignalR.Client {7.0.5}                                  Subestaciones.Client                                                                                                         
System.Threading.Tasks.Dataflow     {7.0.0}                                  Subestaciones.Client    
```

**Comment by joseangelmt** [comment]
Maybe a screenshot of the Call Stack can help. I think in the side of javascript the application is hitting the breakpoint correctly as you can see in the next screenshot. If I double click the "Subestaciones.Client.Pages.EditarPosicion.OnitializedAsync" is when I get the "file not in module" page.

![Screenshot 2023-05-25 182522](https://github.com/dotnet/runtime/assets/3158109/c6faf639-ac17-4cfd-810a-af3ad0a01db3)

**Comment by thaystg** [comment]
I should try to open this PATH: C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor

Is this the correct source path?

**Comment by joseangelmt** [comment]
Yes, it is the correct path.

**Comment by joj** [comment]
The behavior happens when the top of the stack is on a file that doesn't exist. From what I'm seeing in the stack, it looks like the top is being detected as a dotnet generated file (the second line in the screenshot). It's weird that the source file is not being detected (the one in EditarPosicion), but I'm not seeing a file name or position on that stack frame, which would explain it.

**Comment by thaystg** [comment]
Looking at visualstudio-js-debugger.txt
We are sending correctly the source to create:
```
{"tag":"cdp.receive","timestamp":1685030319624,"metadata":{"connectionId":0,"message":{"method":"Debugger.scriptParsed","params":{"scriptId":"dotnet://207_9","url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","executionContextId":2,"executionContextAuxData":{"isDefault":true,"type":"default","frameId":"CC100CA27247A612700FC07839E75128"},"dotNetUrl":"dotnet://Subestaciones.Client.dll/C/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor"},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}
{"tag":"runtime.sourcecreate","timestamp":1685030319624,"message":"Creating source from url","metadata":{"inputUrl":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","absolutePath":"c:\\Users\\josea\\source\\repos\\digi21\\Subestaciones\\Subestaciones\\Client\\Pages\\EditarPosicion.razor"},"level":0}
```

And we are also sending the correct Debugger.paused:

`{"tag":"cdp.receive","timestamp":1685030337423,"metadata":{"connectionId":0,"message":{"method":"Debugger.paused","params":{"callFrames":[{"functionName":"Subestaciones.Client.Pages.EditarPosicion.OnInitializedAsync","callFrameId":"dotnet:scope:1","functionLocation":{"scriptId":"dotnet://623_9","lineNumber":114,"columnNumber":4},"location":{"scriptId":"dotnet://623_9","lineNumber":121,"columnNumber":8},"url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"dotnet:scope:1"},"name":"Subestaciones.Client.Pages.EditarPosicion.OnInitializedAsync","startLocation":{"scriptId":"dotnet://623_9","lineNumber":114,"columnNumber":4},"endLocation":{"scriptId":"dotnet://623_9","lineNumber":134,"columnNumber":4}}]},{"callFrameId":"-3161465823746907321.2.0","functionName":"mono_wasm_fire_debugger_agent_message","functionLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6794},"location":{"scriptId":"20","lineNumber":2,"columnNumber":6797},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.37"},"name":"mono_wasm_fire_debugger_agent_message","startLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6794},"endLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6806}},`

**Comment by thaystg** [comment]
Oh, I can see we sending three times the Debugger.scriptParsed, for the same file:
```
{"tag":"cdp.receive","timestamp":1685030322696,"metadata":{"connectionId":0,"message":{"method":"Debugger.scriptParsed","params":{"scriptId":"dotnet://415_9","url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","executionContextId":3,"executionContextAuxData":{"isDefault":true,"type":"default","frameId":"492609A495AA09D995AEB0B49B582BB8"},"dotNetUrl":"dotnet://Subestaciones.Client.dll/C/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor"},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}

{"tag":"cdp.receive","timestamp":1685030324664,"metadata":{"connectionId":0,"message":{"method":"Debugger.scriptParsed","params":{"scriptId":"dotnet://623_9","url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","executionContextId":4,"executionContextAuxData":{"isDefault":true,"type":"default","frameId":"492609A495AA09D995AEB0B49B582BB8"},"dotNetUrl":"dotnet://Subestaciones.Client.dll/C/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor"},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}
```

**Comment by thaystg** [comment]
@joj Maybe this is causing something weird on the extension side?

**Comment by joj** [comment]
Not sure. Maybe @connor4312 will know?

**Comment by oktayda** [comment]
Hello,

I have the same problem, rollback visualStudio pro to the 17.5.1 make my breakpoints work again

**Comment by connor4312** [comment]
Does Blazor send the `Runtime.executionContext*` events? As of https://github.com/microsoft/vscode-js-debug/pull/1585 the debugger is now aware of them and will remove scripts if their execution context is destroyed, and ignore events for ones that report an unknown execution context.

**Comment by thaystg** [comment]
@connor4312 yes.

If you look at the visualstudio-js-debugger.txt that is attached here you will see this:
Context3 created and destroyed
Context4 created and destroyed
Then we send the scriptParsed after it on line 947. Then we have have the Debugger.Paused using this script on line 1048.

```
line 816: {"tag":"cdp.receive","timestamp":1685030323140,"metadata":{"connectionId":0,"message":{"method":"Runtime.executionContextCreated","params":{"context":{"id":4,"origin":"http://localhost:5020","name":"","uniqueId":"-6852996715997978190.6608325292905543803","auxData":{"isDefault":true,"type":"default","frameId":"492609A495AA09D995AEB0B49B582BB8"}}},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}
line 836: {"tag":"dap.send","timestamp":1685030323141,"metadata":{"connectionId":1,"message":{"seq":234,"type":"event","event":"loadedSource","body":{"reason":"removed","source":{"name":"c:\\Users\\josea\\source\\repos\\digi21\\Subestaciones\\Subestaciones\\Client\\Pages\\EditarPosicion.razor","path":"c:\\Users\\josea\\source\\repos\\digi21\\Subestaciones\\Subestaciones\\Client\\Pages\\EditarPosicion.razor","sourceReference":0}}}},"level":0}
line 861: {"tag":"cdp.receive","timestamp":1685030323174,"metadata":{"connectionId":0,"message":{"method":"Runtime.executionContextDestroyed","params":{"executionContextId":4,"executionContextUniqueId":"-6852996715997978190.6608325292905543803"},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}
line 947: 
{"tag":"cdp.receive","timestamp":1685030324664,"metadata":{"connectionId":0,"message":{"method":"Debugger.scriptParsed","params":{"scriptId":"dotnet://623_9","url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","executionContextId":4,"executionContextAuxData":{"isDefault":true,"type":"default","frameId":"492609A495AA09D995AEB0B49B582BB8"},"dotNetUrl":"dotnet://Subestaciones.Client.dll/C/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor"},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}
line 1048: {"tag":"cdp.receive","timestamp":1685030337423,"metadata":{"connectionId":0,"message":{"method":"Debugger.paused","params":{"callFrames":[{"functionName":"Subestaciones.Client.Pages.EditarPosicion.OnInitializedAsync","callFrameId":"dotnet:scope:1","functionLocation":{"scriptId":"dotnet://623_9","lineNumber":114,"columnNumber":4},"location":{"scriptId":"dotnet://623_9","lineNumber":121,"columnNumber":8},"url":"file:///C:/Users/josea/source/repos/digi21/Subestaciones/Subestaciones/Client/Pages/EditarPosicion.razor","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"dotnet:scope:1"},"name":"Subestaciones.Client.Pages.EditarPosicion.OnInitializedAsync","startLocation":{"scriptId":"dotnet://623_9","lineNumber":114,"columnNumber":4},"endLocation":{"scriptId":"dotnet://623_9","lineNumber":134,"columnNumber":4}}]},{"callFrameId":"-3161465823746907321.2.0","functionName":"mono_wasm_fire_debugger_agent_message","functionLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6794},"location":{"scriptId":"20","lineNumber":2,"columnNumber":6797},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.37"},"name":"mono_wasm_fire_debugger_agent_message","startLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6794},"endLocation":{"scriptId":"20","lineNumber":2,"columnNumber":6806}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.38"},"startLocation":{"scriptId":"20","lineNumber":2,"columnNumber":29},"endLocation":{"scriptId":"20","lineNumber":4,"columnNumber":111718}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.39"},"startLocation":{"scriptId":"20","lineNumber":0,"columnNumber":0},"endLocation":{"scriptId":"20","lineNumber":33,"columnNumber":0}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.40"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.41"}}],"this":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.42"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.2","functionName":"$func855","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":288308},"location":{"scriptId":"21","lineNumber":0,"columnNumber":288322},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.49"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.50"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.51"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.52"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.3","functionName":"$func1026","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":351413},"location":{"scriptId":"21","lineNumber":0,"columnNumber":351428},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.53"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.54"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.55"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.56"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.4","functionName":"$func952","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":310592},"location":{"scriptId":"21","lineNumber":0,"columnNumber":311982},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.57"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.58"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.59"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.60"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.5","functionName":"$func951","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":310491},"location":{"scriptId":"21","lineNumber":0,"columnNumber":310549},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.61"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.62"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.63"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.64"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.6","functionName":"$func886","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":295599},"location":{"scriptId":"21","lineNumber":0,"columnNumber":296759},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.65"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.66"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.67"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.68"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.7","functionName":"$func852","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":287872},"location":{"scriptId":"21","lineNumber":0,"columnNumber":287879},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.69"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.70"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.71"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.72"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.8","functionName":"$func278","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":116116},"location":{"scriptId":"21","lineNumber":0,"columnNumber":116137},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.73"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.74"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.75"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.76"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.9","functionName":"$func221","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":52963},"location":{"scriptId":"21","lineNumber":0,"columnNumber":100364},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.77"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.78"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.79"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.80"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.10","functionName":"$func220","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":52673},"location":{"scriptId":"21","lineNumber":0,"columnNumber":52885},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.81"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.82"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.83"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.84"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.11","functionName":"$func8115","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":1712596},"location":{"scriptId":"21","lineNumber":0,"columnNumber":1712639},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.85"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.86"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.87"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.88"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.12","functionName":"$func2054","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":547770},"location":{"scriptId":"21","lineNumber":0,"columnNumber":547876},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.89"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.90"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.91"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.92"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.13","functionName":"$func2052","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":547699},"location":{"scriptId":"21","lineNumber":0,"columnNumber":547738},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.93"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.94"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.95"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.96"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.14","functionName":"$func1395","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":425794},"location":{"scriptId":"21","lineNumber":0,"columnNumber":427755},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.97"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.98"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.99"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.100"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.15","functionName":"$func313","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":119747},"location":{"scriptId":"21","lineNumber":0,"columnNumber":120000},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.101"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.102"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.103"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.104"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.16","functionName":"$func283","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":116824},"location":{"scriptId":"21","lineNumber":0,"columnNumber":117045},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.105"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.106"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.107"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.108"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.17","functionName":"$func221","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":52963},"location":{"scriptId":"21","lineNumber":0,"columnNumber":57381},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.109"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.110"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.111"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.112"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.18","functionName":"$func220","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":52673},"location":{"scriptId":"21","lineNumber":0,"columnNumber":52885},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.113"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.114"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.115"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.116"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.19","functionName":"$func8115","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":1712596},"location":{"scriptId":"21","lineNumber":0,"columnNumber":1712639},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.117"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.118"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.119"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.120"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.20","functionName":"$func2054","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":547770},"location":{"scriptId":"21","lineNumber":0,"columnNumber":547876},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.121"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.122"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.123"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.124"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.21","functionName":"$func2059","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":549479},"location":{"scriptId":"21","lineNumber":0,"columnNumber":549516},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.125"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.126"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.127"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.128"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.22","functionName":"$func2086","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":557861},"location":{"scriptId":"21","lineNumber":0,"columnNumber":557899},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.129"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.130"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.131"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.132"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.23","functionName":"$mono_wasm_invoke_method_ref","functionLocation":{"scriptId":"21","lineNumber":0,"columnNumber":39811},"location":{"scriptId":"21","lineNumber":0,"columnNumber":39889},"url":"","scopeChain":[{"type":"wasm-expression-stack","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.133"}},{"type":"local","object":{"type":"object","className":"Locals","description":"Locals","objectId":"-3161465823746907321.2.134"}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.135"}}],"this":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.136"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.24","functionName":"Module._mono_wasm_invoke_method_ref","functionLocation":{"scriptId":"20","lineNumber":13,"columnNumber":123744},"location":{"scriptId":"20","lineNumber":13,"columnNumber":123868},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.137"},"name":"Module._mono_wasm_invoke_method_ref","startLocation":{"scriptId":"20","lineNumber":13,"columnNumber":123744},"endLocation":{"scriptId":"20","lineNumber":13,"columnNumber":123890}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.138"},"startLocation":{"scriptId":"20","lineNumber":10,"columnNumber":8},"endLocation":{"scriptId":"20","lineNumber":17,"columnNumber":1}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.139"},"startLocation":{"scriptId":"20","lineNumber":6,"columnNumber":27},"endLocation":{"scriptId":"20","lineNumber":19,"columnNumber":1}},{"type":"module","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.140"},"startLocation":{"scriptId":"20","lineNumber":0,"columnNumber":0},"endLocation":{"scriptId":"20","lineNumber":33,"columnNumber":0}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.141"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.142"}}],"this":{"type":"undefined"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.25","functionName":"_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet","functionLocation":{"scriptId":"257","lineNumber":4,"columnNumber":153},"location":{"scriptId":"257","lineNumber":28,"columnNumber":4},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.143"},"name":"_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet","startLocation":{"scriptId":"257","lineNumber":4,"columnNumber":153},"endLocation":{"scriptId":"257","lineNumber":56,"columnNumber":5}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.144"},"startLocation":{"scriptId":"257","lineNumber":0,"columnNumber":19},"endLocation":{"scriptId":"257","lineNumber":59,"columnNumber":1}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.145"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.146"}}],"this":{"type":"undefined"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.26","functionName":"beginInvokeDotNetFromJS","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":44947},"location":{"scriptId":"17","lineNumber":0,"columnNumber":45086},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.147"},"name":"beginInvokeDotNetFromJS","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":44947},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":45115}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.148"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":44278},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":45261}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.149"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":39953},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":46006}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.150"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":37451},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":46017}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.151"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.152"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.153"}}],"this":{"type":"undefined"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.27","functionName":"b","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1802},"location":{"scriptId":"17","lineNumber":0,"columnNumber":1997},"url":"","scopeChain":[{"type":"block","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.154"},"name":"b","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1979},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":2032}},{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.155"},"name":"b","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1802},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":2060}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.156"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":38},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":5338}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.157"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.158"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.159"}}],"this":{"type":"undefined"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.28","functionName":"e.invokeMethodAsync","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":2712},"location":{"scriptId":"17","lineNumber":0,"columnNumber":2730},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.160"},"name":"e.invokeMethodAsync","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":2712},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":2744}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.161"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":38},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":5338}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.162"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.163"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.164"}}],"this":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.165"},"canBeRestarted":true},{"callFrameId":"-3161465823746907321.2.29","functionName":"","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":60296},"location":{"scriptId":"17","lineNumber":0,"columnNumber":60319},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.166"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":60296},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":60414}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.167"},"name":"Vt","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":58214},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":62356}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.168"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.169"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.170"}}],"this":{"type":"undefined"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.30","functionName":"ke","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28852},"location":{"scriptId":"17","lineNumber":0,"columnNumber":28872},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.171"},"name":"ke","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28852},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28948}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.172"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.173"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.174"}}],"this":{"type":"undefined"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.31","functionName":"Ie","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28455},"location":{"scriptId":"17","lineNumber":0,"columnNumber":28623},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.175"},"name":"Ie","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28455},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":28630}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.176"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.177"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.178"}}],"this":{"type":"undefined"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.32","functionName":"","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":19474},"location":{"scriptId":"17","lineNumber":0,"columnNumber":20040},"url":"","scopeChain":[{"type":"block","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.179"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":19977},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":20053}},{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.180"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":19474},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":20054}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.181"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.182"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.183"}}],"this":{"type":"undefined"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.33","functionName":"","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13351},"location":{"scriptId":"17","lineNumber":0,"columnNumber":13354},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.184"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13351},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13358}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.185"},"name":"onGlobalEvent","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13110},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13361}},{"type":"block","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.186"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.187"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.188"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.189"}}],"this":{"type":"undefined"},"canBeRestarted":false},{"callFrameId":"-3161465823746907321.2.34","functionName":"onGlobalEvent","functionLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13110},"location":{"scriptId":"17","lineNumber":0,"columnNumber":13342},"url":"","scopeChain":[{"type":"local","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.190"},"name":"onGlobalEvent","startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13110},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":13361}},{"type":"block","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.191"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"closure","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.192"},"startLocation":{"scriptId":"17","lineNumber":0,"columnNumber":1},"endLocation":{"scriptId":"17","lineNumber":0,"columnNumber":63684}},{"type":"script","object":{"type":"object","className":"Object","description":"Object","objectId":"-3161465823746907321.2.193"}},{"type":"global","object":{"type":"object","className":"Window","description":"Window","objectId":"-3161465823746907321.2.194"}}],"this":{"type":"object","className":"O","description":"O","objectId":"-3161465823746907321.2.195"},"canBeRestarted":false}],"reason":"other","data":null,"hitBreakpoints":[]},"sessionId":"1CB44918A8FAB5A188397D50F8C4A9CA"}},"level":0}


```

**Comment by connor4312** [comment]
Ah, thanks. Something I notice in that log is that it seems like an execution context was destroyed at the wrong time:

- At +8.173, execution context ID 4 is created
- At +8.173, execution context ID 4 is _destroyed_
- At +9.696, we get the last script for EditarPosicion.razor `scriptParsed` in execution context 4. This is ignored because that context does not exist ⚠️  
- Later `Debugger.paused` references that script. But the source does not exist at that point.

**Comment by joseangelmt** [comment]
With Visual Studio 17.6.3 it's working again.

**Comment by fnils** [comment]
> With Visual Studio 17.6.3 it's working again.

I still get a similar error.
![image](https://github.com/dotnet/runtime/assets/20942566/87b9b051-2bdb-47ed-ace9-6414830e3b37)
When I click "view disassembly"
I get the text "No disassembly available.".

**Comment by MarkLFT** [comment]
I have 17.6.3 installed, and still receiving this message.  This is stopping me working, so will have to roll back my Vs to a previous working version.

**Comment by fnils** [comment]
> Hello,
> 
> I have the same problem, rollback visualStudio pro to the 17.5.1 make my breakpoints work again

How do I downgrade? I tried using Visual studio Installer nut it only allows me to downgrade to 17.6.0.
Thanks in advance.

**Comment by MarkLFT** [comment]
You can only roll back to the last version from what I can see. I had to uninstall and reinstall.

**Comment by sgraphics** [comment]
Same issue here / work halted, very frustrating

**Comment by DinoHad** [comment]
same issue on our side also, we are totally blocked with development due to malfunction of debugger.

**Comment by fnils** [comment]
> > You can only roll back to the last version from what I can see. I had to uninstall and reinstall.
> 
> Ok, thank you. Do you know where I can get an older working version?

So you need to uninstall the old version and the download the boostrapper version you want here.
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history#updating-your-installation-to-a-specific-release

**Comment by EricCornelson** [comment]
We have a fix for this also coming on the debugger side which should be in the next release, but in the mean time, if you want to get things working right away, you can replace the files in C:\Program Files\{Your VS install dir}\Common7\IDE\CommonExtensions\Microsoft\JSDiagnostics\Debugger\DebugAdapter with the files in [dist.zip](https://github.com/dotnet/runtime/files/11776788/dist.zip). That should get you the fix right away

**Comment by MarkLFT** [comment]
@EricCornelson Just wanted to confirm this fixed my immediate issue, thanks.

**Comment by DinoHad** [comment]
@EricCornelson Thank you, will try it, could you please tell us ETA of next release?

**Comment by LongJohnBlackbeard** [comment]
I currently have the same issue.
@EricCornelson  dist.zip file replacement makes debugging breakpoints on my Web Assembly Client project work again. Can this thread be updated when it is fixed in a new release?

**Comment by LongJohnBlackbeard** [comment]
> With Visual Studio 17.6.3 it's working again.

That update did not work for me. 
@EricCornelson dist.zip file replacement got it working again and I can resume development.

**Comment by candritzky** [comment]
@EricCornelson I had the same problem with VS2022 17.6.4 and can confirm that your dist.zip fixed it.

**Comment by Swepps** [comment]
@candritzky Just updated to 17.6.4 and used dist.zip as described by EricCornelson and it appears to fix the issue.

**Comment by buzzluck68** [comment]
I also used dist.zip and while it did fix the debugging breakpoints within C# code files, it caused VS to stop responding for my breakpoint on C# code within a razor file. VS had a popup indicating it was looking for the razor breakpoint, or something to that affect (I already killed that instance of VS to stop it).

**Comment by EricCornelson** [comment]
> @EricCornelson Thank you, will try it, could you please tell us ETA of next release?

Should be around mid-July

**Comment by SimonJWales** [comment]
dist.zip seems to work for me too on VS 17.6.4

**Comment by phantomkingx** [comment]
Issue still on VS 17.6.5, fixed with dist.zip

**Comment by AchilleasTyrnenopoulos** [comment]
Also had same issue in VS 17.6.5 and was solved with the dist.zip

**Comment by benjamin-Keller** [comment]
Still an issue VS 17.6.5, dist.zip solved it

**Comment by 1KimHansen** [comment]
I still have the issue in VS 17.6.5, and "dist.zip" did not solve it

**Comment by badhitman** [comment]
> У нас есть исправление для этого, которое также появится на стороне отладчика, которое должно быть в следующем выпуске, но в то же время, если вы хотите, чтобы все сразу заработало, вы можете заменить файлы в C:\Program Files {Ваш VS установите dir}\Common7\IDE\CommonExtensions\Microsoft\JSDiagnostics\Debugger\DebugAdapter с файлами в [dist.zip](https://github.com/dotnet/runtime/files/11776788/dist.zip) . Это должно дать вам исправление сразу (используйте на свой страх и риск, поскольку это не официальный способ обновления отладчика, хотя он должен работать).


Thanks a lot. this solution helped. VS 17.6.5
there was no end to my suffering and finally the guy fixed the problem that microsoft can't solve.

**Comment by sgreifeneder** [comment]
same here on VS 17.6.5 ... dist.zip fixed the issue

**Comment by badhitman** [comment]
The strangest thing is that the problem is only in one old Blazor project. It used to be ok everywhere, but at some point one project fell into such a problem. The project file is the most common and even trivial. The solution file is also unremarkable. Rolling back to a previous version of VS doesn't help. All Blazor projects except one are fine. It's been a problem for quite some time now.

Eric is a real doctor! My pain is gone - thank you Eric!
