### ISSUE TITLE
[NativeAOT] Test failures in System.Net.Http.Json.Unit.Tests

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#89195]
Example: https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-ac99d648a653499ba7/System.Net.Http.Json.Unit.Tests/3/console.8bd3fbc0.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-ac99d648a653499ba7/System.Net.Http.Json.Unit.Tests/3/console.8bd3fbc0.log?helixlogtype=result)

Failures look like: 
```
Running assembly:System.Net.Http.Json.Unit.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[FAIL] System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest.WriteAsync_Works_WhenOutputIs_WesternEuropeanEncoding(message: "Hello world")
System.NotSupportedException : JsonTypeInfo metadata for type 'System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest+TestModel' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type, IJsonTypeInfoResolver) + 0x78
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean, Nullable`1, Boolean, Boolean) + 0xdc
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type, Boolean) + 0x68
   at System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest.<WriteAsyncTest>d__8.MoveNext() + 0x150
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
[FAIL] System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest.WriteAsync_Works_WhenOutputIs_WesternEuropeanEncoding(message: "ABABABABABABABABABABABABABABABABABABABABABABABABAB"...)
System.NotSupportedException : JsonTypeInfo metadata for type 'System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest+TestModel' was not provided by TypeInfoResolver of type '[]'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type, IJsonTypeInfoResolver) + 0x78
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean, Nullable`1, Boolean, Boolean) + 0xdc
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type, Boolean) + 0x68
   at System.Net.Http.Json.Functional.Tests.TranscodingWriteStreamTest.<WriteAsyncTest>d__8.MoveNext() + 0x150
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xfc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68

```

Steps to repro:
```
build.cmd -s clr.aot+libs -rc checked -c Release
cd src\libraries\System.Net.Http.Json\tests\UnitTests
..\..\..\..\..\dotnet.cmd build /t:Test -c Release /p:TestNativeAot=true /p:CoreCLRConfiguration=checked
```

**Comment by VSadov** [comment]
@MihaZupan @antonfirsov - Do you know of any recent test changes that could have caused this?

**Comment by MihaZupan** [comment]
No, nothing on the networking side. This looks to me like something went wrong with Json.

**Comment by MihaZupan** [comment]
cc: @dotnet/area-system-text-json

**Comment by ericstj** [comment]
I don't see where these tests enable the source generator: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Net.Http.Json/tests/UnitTests

Has this ever worked @VSadov or are you trying something new?

**Comment by VSadov** [comment]
I do not see these failures in https://github.com/dotnet/runtime/pull/84566 , for example, but that was in May. 

I think `runtime-extra-platforms` runs post-merge or at least dayly, so maybe there is a way to get history of failures for `runtime-extra-platforms` and tell more precisely when this failure first occurred.

**Comment by MichalStrehovsky** [comment]
Bunch of System.Text.Json test started failing at the same time. That was tracked in #88982 that was fixed yesterday. Might be worth retrying if your run didn't have the fix.

Cc @eiriktsarpalis

**Comment by VSadov** [comment]
I still see the issue locally - with the provided repro. 
I've restarted testing in https://github.com/dotnet/runtime/pull/85694 to pick the latest bits, but I think good chance the bug is still there (since I see it locally).

**Comment by VSadov** [comment]
The issue is definitely still there. 
See, for example: https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-f1e9e7bcbc4b4a2b8e/System.Net.Http.Json.Unit.Tests/2/console.7847c938.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85694-merge-f1e9e7bcbc4b4a2b8e/System.Net.Http.Json.Unit.Tests/2/console.7847c938.log?helixlogtype=result)

**Comment by MichalStrehovsky** [comment]
@VSadov Could you ActiveIssue them so that we can get extra-platforms clean?

@eiriktsarpalis do you know how the fix for those looks like? It's the same failure mode as S.T.Json tests that started happening around the same time.

**Comment by eiriktsarpalis** [comment]
Root cause is likely https://github.com/dotnet/runtime/pull/88480.

> do you know how the fix for those looks like?

It would involve either explicitly setting the `JsonSerializerIsReflectionEnabled` property to true in the test project or disabling the tests that use reflection in AOT (I'm guessing these happened to be passing until #88480 got merged).
