### ISSUE TITLE
Workingset constantly growing, possible unmanaged memory leak

### ISSUE THREAD

**Issue by westfin** [dotnet/runtime#92490]
We have several asp.net core service which are hosted in kubernetes.
After moving to NET7 we have experienced unexpected memory usage.

Memory is growing until kubernetes got killed container because of memory limit exceeding. But it is seems that there is no managed memory leaks because of based on Prometheus metrics heap stayed stable, and there is no OutOfMemoryException, at the same time working set is constantly growing.

So we have two dumps.
The first `!sos maddress -images` command output shows:

 | Memory Type            |          Count |         Size |   Size (bytes) | 
 |------------------------|----------------|--------------|----------------| 
 | Image                  |            301 |      83,99mb |     88?065?024 | 
 | PAGE_EXECUTE_READ      |          1?418 |      41,16mb |     43?163?648 | 
 | PAGE_EXECUTE_WRITECOPY |          1?317 |      37,27mb |     39?082?496 | 
 | Stack                  |             19 |      25,95mb |     27?213?312 | 
 | GCHeap                 |              6 |      20,45mb |     21?442?560 | 
 |------------------------|----------------|--------------|----------------| 
 | [TOTAL]                |          3?547 |     240,06mb |    251?718?656 | 

The same command on the second dump (after 3 days):
| Memory Type            |          Count |         Size |   Size (bytes) | 
 |------------------------|----------------|--------------|----------------| 
 | Image                  |            454 |     **185,48mb** |    194?494?464 | 
 | PAGE_EXECUTE_WRITECOPY |          1?272 |      46,59mb |     48?853?504 | 
 | PAGE_EXECUTE_READ      |          1?456 |      41,62mb |     43?642?880 | 
 | GCHeap                 |              5 |      29,97mb |     31?428?608 | 
 | Stack                  |             20 |      27,86mb |     29?216?256 | 
 |------------------------|----------------|--------------|----------------| 
 | [TOTAL]                |          3?706 |     363,52mb |    381?177?856 |

The detailed summary shows that a lot of memory used by `doublemapper__deleted_` entry:

For the first dump:
 | Image                                                   |          Count |         Size |   Size (bytes) | 
 |---------------------------------------------------------|----------------|--------------|----------------| 
| doublemapper__deleted_                                  |              1 |     **544,00kb** |        557?056 | 

And for the second dump:
 | Image                                                   |          Count |         Size |   Size (bytes) | 
 |---------------------------------------------------------|----------------|--------------|----------------| 
 | doublemapper__deleted_                                  |            190 |     **106,81mb** |    111?996?928 | 

Does it a memory leak? Is there any way to find out from where it comes from?

I will appreciate for any help, this issue becomes critical for us. Currently we are on pause with our migration to NET7 for other services.

**Environment info:**
_Docker image_: mcr.microsoft.com/dotnet/aspnet:7.0.10-alpine3.18
_Memory limits_: 512MB
_Sdk_: "Microsoft.NET.Sdk.Worker" (seems it is mean Workstation gc mode)

**Comment by mangod9** [comment]
Hello @westfin, are you able to capture some dumps or traces before the memory is hitting its limits? Also if you are able to create a small repro which reproduces the problem that might be useful.

**Comment by westfin** [comment]
> Hello @westfin, are you able to capture some dumps or traces before the memory is hitting its limits? Also if you are able to create a small repro which reproduces the problem that might be useful.

Hello @mangod9 , thank you for response.
You mean as close as possible to limits? Not sure about dumps, because when we are collecting dump, memory is doubled and OOM killed by kubernetes. 
Which traces you are interested? We can try to collect close to limits.

About repro we are trying to localize the problem locally, but without any luck. Currently it is reproduced only on Production.

Any way, is growing of doublemapper__deleted_ entries something abnormal? Should we care about it, is it right direction at all?

**Comment by karakasa** [comment]
possibly related #80580

**Comment by westfin** [comment]
> possibly related #80580

Not sure that this the same. We do not create dynamic assemblies. But may be there are any others code patterns that can cause such issue..

**Comment by MaxRev-Dev** [comment]
Hi everyone, I've got the same issue with the following MREs. 
They can have a different nature, but the memory increase is similar.
1. Heap grows when floating-point types are converted to strings.

```csharp
while (true) {
	var thread = new Thread(() => {
		var _ = 0d.ToString(); // leaks, Double type
                // var __ = 0.ToString(); // no leak, Int32 type
	});
	thread.Start();
	Thread.SpinWait(10);
}
```

2. Running tasks inside the threads

```csharp
while (true) {
	var thread = new Thread(() => {
		Task.Run(() => { }).Wait(); // heap is growing constantly 
	});
	thread.Start();
	Thread.SpinWait(10);
}
```

**Comment by mangod9** [comment]
@kunalspathak, since we have seen a small leak related to ThreadStatics. Not sure whether this is the same issue but worth checking with the fix.

**Comment by kunalspathak** [comment]
> Heap grows when floating-point types are converted to strings.

I ran this with and without the changes in https://github.com/dotnet/runtime/pull/95362. In below screenshot, the 1st entry is without the fix and 2nd entry is after the fix. They were ran for more than 2:34 hours as seen below. I do see marginal reduction in memory consumption with fix, so possibly it was from same reason, but I am not 100% sure. It will be good to verify it on your end as well.


<img width="975" alt="image" src="https://github.com/dotnet/runtime/assets/12488060/ccb7b069-1c4d-483c-9189-0e569f87ecff">

**Comment by SamWilliamsGS** [comment]
We are seeing a very similar issue to you when moving services from .NET 6 to .NET 8 @westfin. .NET services hosted in kubernetes with unmanaged memory growth that lasts until kubernetes gets rid of it, only in production, and so far extremely difficult to reproduce locally. Are you still seeing the issue too?

**Comment by kunalspathak** [comment]
Is it possible to try nightly builds that contains the fix I merged in https://github.com/dotnet/runtime/pull/95362?

**Comment by westfin** [comment]
@SamWilliamsGS Yes we are seeing the issue, but we are on .NET 7

**Comment by westfin** [comment]
Hi, guys, again. We have migrated to .net8.0.10 image. And issue still there.
But now a have several _heaptrack_ dumps. I have collected two dumps with difference 4 days.

I'm not sure but according to comparing result of them seems like an issue is in OpenSSL area. @bartonjs @rzikm I know guys you are experts in this stuff, could you help me please with investigation.

Our application heavily used HttpClient with client certificate.
```cs
serviceCollection.AddHttpClient(clientName)
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        var handler = new HttpClientHandler();
        handler.ClientCertificates.Add(new X509Certificate2("path_to_cert", "some_pwd"));
        return handler;
    });
```

![Image](https://github.com/user-attachments/assets/4e07f144-502c-45c5-b6cb-619fca28d8d4)

**Comment by rzikm** [comment]
Unless you manage to capture a leak in order of hundred(s) of MB, its hard tu tell if those are truly leaked objects or simply the live objects which have not been freed (because they are being used).

Recently, I have encountered a case where the growth of the working set was caused by malloc fragmentation due to native allocations in OpenSSL. One way to limit this fragmentation was to limit the number of malloc arenas used by the process. Can you try running the application with `MALLOC_ARENA_MAX=1`?

**Comment by westfin** [comment]
@rzikm Thank you, we will try and came back with results.

**Comment by rzikm** [comment]
I don't think so. It seems to be specific to glibc implementation of malloc.

Another possible workaround to try could be replacing the allocator by e.g. jemalloc, on Ubuntu, you can do it like this

```
apt-get update && apt-get install -y libjemalloc-dev
LD_PRELOAD=libjemalloc.so.2 <yourApplication>
```

**Comment by westfin** [comment]
Hi @rzikm , I know a lot of time has passed. But we are still with the issue. But I have localized issue. Seems we have leak only in service that http service two service communication. This code 100% reproduce the leakage.
```cs
public sealed class BackgroundWorker(
    IConfiguration configuration,
    ILogger<BackgroundWorker> logger) : BackgroundService
{
    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            DoAsync();
            Thread.Sleep(200);
        }

        return Task.CompletedTask;

        void DoAsync() => ThreadPool.QueueUserWorkItem(async _ =>
        {
            try
            {
                var uri = new Uri(_settings.Endpoint.Url);

                var host = uri.Host;
                var port = uri.Port;

                using var client = new TcpClient(host, port);
                using var stream = new SslStream(client.GetStream(), leaveInnerStreamOpen: false);

                await stream.AuthenticateAsClientAsync(new SslClientAuthenticationOptions
                {
                    TargetHost = host,
                    CertificateRevocationCheckMode = X509RevocationMode.NoCheck
                });

                _logger.LogInformation("Connected to {host}:{port}, ssl protocol version: {SslProtocol}, cipher: {Cipher}", host, port, stream.SslProtocol, stream.NegotiatedCipherSuite);
           }
            catch (Exception e)
            {
                _logger.LogError(e, "Unexpected error occurred in recurring hosted service");
            }
        });
    }

    public override void Dispose() => RemoteCertificate?.Dispose();

    private X509Certificate2 RemoteCertificate { get; set; }

    private readonly ILogger<BackgroundWorker> _logger = logger;
    private readonly ServiceSettings _settings = new(configuration);
```

Not sure about `ThreadPool.QueueUserWorkItem`. Maybe it is not important in that case (will try later).
Issue reproduced on different distro: alpine and noble and on different allocators - I have tried ptmalloc (glibc default), jemalloc and musl mallocng.

version of framework: 10.0.3
**jemalloc** settings: MALLOC_CONF: retain:false,background_thread:true,narenas:2,tcache:false,dirty_decay_ms:0,muzzed_decay_ms:0
**ptmalloc** settings: MALLOC_TRIM_THRESHOLD_: 0, MALLOC_ARENA_MAX: 2
**mallocng**: not tunable

There are some stats that capture from docker containers:
mallinfo from ptmalloc pod:

<img width="1913" height="745" alt="Image" src="https://github.com/user-attachments/assets/b3b05c17-54cf-4f59-9b46-f91c936aa6d5" />

uordblks growing until OOMKilled, keepcost always small something about ~800kb

jemalloc stats from pod:

<img width="1896" height="744" alt="Image" src="https://github.com/user-attachments/assets/36121c93-f64c-4dae-8e00-08c38a97c588" />

general memory usage for all configs: ptmalloc, mallocng, jemalloc

<img width="1836" height="672" alt="Image" src="https://github.com/user-attachments/assets/73e4a63a-cc32-4fb8-acda-4ad19d1f650f" />


Seems like something specific for our end service and tls certificate because with well known github.com issue not reproduced.
Not sure what kind of info I can share more. Please help to continue investigation..

Revocation disabled - so it is not an issue with big CRL

**Comment by rzikm** [comment]
Looking againt at the report, the allocated memory is actually growing, so it might be a leak., the callstack at https://github.com/dotnet/runtime/issues/92490#issuecomment-2456581878 shows CryptoNative_X509StackAddDirectoryStore and ReadNextPublicCert, which should be coming from the in-memory cache of the simulated user cert stores:

https://github.com/dotnet/runtime/blob/6e51f762bc4c98ea90ae6ca21c4e220b4b2e7a5c/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509ChainProcessor.cs#L27-L35

Can you check if you have certs in ~/.dotnet/corefx/cryptography/x509stores/{Root, CA, My} ?

**Comment by rzikm** [comment]
I created a test app that adds a *lot* of certs to the `~/.dotnet/corefx/cryptography/x509stores/{Root, CA, My}` stores, the memory is rising, but `heaptrack` shows no leak. malloc dump shows:

```
Non-mmapped space allocated (bytes):        294,363,136
Number of free chunks:                            5,374
Number of free fastbin blocks:                   33,447
Number of mmapped regions:                            4
Space allocated in mmapped regions (bytes):     704,512
usmblks:                                              0
Space in freed fastbin blocks (bytes):        1,254,576
Total allocated space (bytes):               34,707,616
Total free space (bytes):                   259,655,520
Top-most, releasable space (bytes):             100,352
```

So there is no real leak there. it's just the malloc arena fragmentation thing again.

There are couple of interesting points though, your screenshots seem to suggest that the *used* memory grows until about 90 MB and then (I assume) your app gets OOM killed. One hypothesis there is that Server GC mode is more prone to keep the certs around for longer (most of the certs get to the 2nd GC generation), and the app gets OOMd before they get collected and finalized. You could in theory force occasional full GC, but that may not have a net positive effect.....

I would suggest removing all certs from `~/.dotnet/corefx/cryptography/x509stores/{Root, CA, My}` as a workaround for now, if that fixes the issue, then we might consider increasing the refresh interval from 30s so that we don't reload the cert cache as often (we already check for last modification time on disk, so checking less often is an issue only in case we can't get mtime reliably)

**Comment by westfin** [comment]
@rzikm Thanks for so fast answer. Not sure that certs cache is our case, because as I said I have changed host variable to `github.com` and starts polling and memory was not growing. The pod's configuration was the same, with same set of certs in ~/.dotnet/corefx/cryptography/x509stores/My in root and CA we don't have any certificates. about heaptrack. I will update info, because this was dumped ~2years on whole app. I will dump with this small repro and come back.

**Comment by westfin** [comment]
> One hypothesis there is that Server GC mode is more prone to keep the certs around for longer (most of the certs get to the 2nd GC generation)

Does this mean we should see that managed memory growing? Our metrics shows that managed memory stable

**Comment by rzikm** [comment]
It is possible that you wouldn't, the cert handles on the managed side might be the only thing that gets promoted to 2nd gen and they only couple of bytes each, the bulk of the memory is being held in native.

**Comment by westfin** [comment]
There is heaptrack dump after 12h polling our internal endpoint. Not sure why not all symbols of libssl.so and libcrypto.so resolved. Will wait and try to compare with another dump after 12h

<img width="1916" height="1008" alt="Image" src="https://github.com/user-attachments/assets/61295d33-9bdb-429c-a0d2-a2af53f5b547" />

PS: I have checked we have 3 certificates in ~/.dotnet/corefx/cryptography/x509stores/my directory

**Comment by rzikm** [comment]
This does not seem to be a leak at all, 20 MB is indistinguishable from background noise.

> Not sure why not all symbols of libssl.so and libcrypto.so resolved.

Those are likely internal functions, you can try installing debug symbol packages for the distro, but it is not that important, just knowing the first public entrypoint is enough for analysis. 

> PS: I have checked we have 3 certificates in ~/.dotnet/corefx/cryptography/x509stores/my directory

Are these certs necessary? I think it would be worth checking that removing these works around the issue. Also could you also include malloc stats? At least the fordblks and uordblks or equivalent

**Comment by westfin** [comment]
> This does not seem to be a leak at all, 20 MB is indistinguishable from background noise.

Not sure, there is another data after more 12 hours. It is constantly growing

<img width="1913" height="539" alt="Image" src="https://github.com/user-attachments/assets/0b5b5cf6-46d9-4b1e-a875-7696a36f2641" />

 > Are these certs necessary?

No, I have deleted, check trend after 7 hours, I 100% sure it will OOMkilled at the end

<img width="1879" height="443" alt="Image" src="https://github.com/user-attachments/assets/57098a15-ae6f-46bb-a60b-49c1fbbb5f02" />

 > At least the fordblks and uordblks

<img width="1905" height="865" alt="Image" src="https://github.com/user-attachments/assets/852d7608-68b6-4335-8b7e-1f4a4c13f078" />

Here is graph, based on previous data uordblks will grow, fordblks will +- stable (check [prev comment I have provided this info](https://github.com/dotnet/runtime/issues/92490#issuecomment-4716642242))


But anyway let's check fragmentation version. What kind of tool we can use for it? I have read about /proc/buddyinfo, but if i understand correctly it will show host stats, not a docker container itself, not sure how we can differentiate it.

**Comment by westfin** [comment]
after 3 days, uordblks continue growing 

<img width="1898" height="345" alt="Image" src="https://github.com/user-attachments/assets/1a7838be-3e5a-4c07-9450-2a2aa26473b2" />

uordblks - 79.1Mb
fordblks - 4.9Mb

**Comment by rzikm** [comment]
I still don't see anything standing out in the heaptrack report :/, with these low numbers, it's hard to distinguish what is a leak and what is memory currently being used (heaptrack reports live memory as a leak because there is a missing `free` call). Would it be possible to increase the pod memory limit to about 300MB and get a heaptrack capture starting shortly after the app initializes (there is a bunch of allocations at the app start that are never freed and just pollute the report, you can use `heaptrack -p <pid>` to attach to already running processes)?

**Comment by westfin** [comment]
> I still don't see anything standing out in the heaptrack report :/, with these low numbers, it's hard to distinguish what is a leak and what is memory currently being used (heaptrack reports live memory as a leak because there is a missing `free` call). Would it be possible to increase the pod memory limit to about 300MB and get a heaptrack capture starting shortly after the app initializes (there is a bunch of allocations at the app start that are never freed and just pollute the report, you can use `heaptrack -p <pid>` to attach to already running processes)?

Yep. I will do. Also I have compiled openssl from source, so we will see all call stacks

**Comment by westfin** [comment]
> get a heaptrack capture starting shortly after the app initializes

Sorry we can not, it is required to change some systmen seettings in k8s - for security reason we are not allow this. But 

> I still don't see anything standing out in the heaptrack report :/

Looks like you were right. I have tried another tool to check leak `memleak-bpfcc` it showed top memory allocations that not freed in interval of time. And there is only two interested stacks, but absolute numbers of "leaked" memory too low. Here is example:

```shell
        371416 bytes in 17 allocations from stack
                0x00007f930a8da5ab      CRYPTO_malloc+0x75 [libcrypto.so.3]
                0x00007f930a8da669      CRYPTO_realloc+0x69 [libcrypto.so.3]
                0x00007f930a79e9e0      BUF_MEM_grow+0x14d [libcrypto.so.3]
                0x00007f930ac0edb2      state_machine+0x35d [libssl.so.3]
                0x00007f930ac0e9d5      ossl_statem_connect+0x21 [libssl.so.3]
                0x00007f930abcd88d      SSL_do_handshake+0x12f [libssl.so.3]
                0x00007f930ac84152      CryptoNative_SslDoHandshake+0x22 [libSystem.Security.Cryptography.Native.OpenSsl.so]
````

and 
```shell
                0x00007eff942d75ab      CRYPTO_malloc+0x75 [libcrypto.so.3]
                0x00007eff94157c4a      ossl_asn1_enc_save+0x8d [libcrypto.so.3]
                0x00007eff94150cd5      asn1_item_embed_d2i+0x1056 [libcrypto.so.3]
                0x00007eff941516de      asn1_template_noexp_d2i+0x5b6 [libcrypto.so.3]
                0x00007eff941510fc      asn1_template_ex_d2i+0x2fe [libcrypto.so.3]
                0x00007eff94150a79      asn1_item_embed_d2i+0xdfa [libcrypto.so.3]
                0x00007eff9414fb11      asn1_item_ex_d2i_intern+0xaf [libcrypto.so.3]
                0x00007eff9414fc11      ASN1_item_d2i_ex+0x7f [libcrypto.so.3]
                0x00007eff9414fc7d      ASN1_item_d2i+0x40 [libcrypto.so.3]
                0x00007eff943ca839      d2i_X509+0x34 [libcrypto.so.3]
                0x00007eff9430605c      PEM_ASN1_read_bio+0xaf [libcrypto.so.3]
                0x00007eff943086b6      PEM_read_bio_X509+0x51 [libcrypto.so.3]
```

I have tried to find from where comes second one, because we have removed all certs from `corefx`. 
```shell
lldb -p 1
(lldb) b PEM_read_bio_X509
(lldb) frame select 5
frame #5: 0x000055b68f39229a OpenSslCachedSystemStoreProvider.cs:204
(lldb) v dir
(String &) dir = 0x000055b6903ff048: {
  Object = {
    m_pEEType = 0x000055b690533450
  }
  _stringLength = 14
  _firstChar = U+002f u'/'
}

(lldb) print &dir._firstChar
(char16_t *) 0x000055b6903ff054 u"/etc/ssl/certs"
```
Seems this directory comes from static variable `OpenSslCachedSystemStoreProvider.s_rootStoreDirectories`
In my docker env /etc/ssl/certs contains ~600 files and symbollinks
We are reading /etc/ssl/certs each 5 minutes. Not sure can it be the root of high fragmentation and how we can proof it. But does it necessary to read this directory each 5 minute? Today I will try to remove all certs except one that we need to poll endpoint and will check the results

**Comment by rzikm** [comment]
Do you by chance use `X509Store` in your code with "Root" and `StoreLocation.LocalMachine`? It should not be necessary to explicitly provide this store to X509ChainPolicy.

**Comment by westfin** [comment]
> Do you by chance use `X509Store` in your code with "Root" and `StoreLocation.LocalMachine`? It should not be necessary to explicitly provide this store to X509ChainPolicy.

No, we don't use. Currently all my experiments based on code from https://github.com/dotnet/runtime/issues/92490#issuecomment-4716642242. But I have found that we are explicitly setting SSL_CERT_DIR envvar pointing to /etc/ssl/certs

**Comment by rzikm** [comment]
oh, I see, we open this store internally. 600 certs does not seem that much, though it can affect the fragmentation (my machine has about 200 for comparison).

I don't really see anything that we could do here better, besides making the forced refresh interval longer, but that has different tradeoffs.

@bartonjs any thoughts?

**Comment by bartonjs** [comment]
For the general investigation the two things that pop into my head are

1. Add GC.Collect() to the repro.  If it solves the problem then presumably we have a problem where the GC isn't seeing the memory limit correctly so it doesn't feel motivated to run finalizers.
1. We could distinguish X.509 vs TLS by making a repro that just builds chains instead of poking something over HTTPS.

> because with well known github.com issue not reproduced

The top thing in my head, if there's a leak (vs finalization lag-death) is that we're getting something unbalanced between certs present on the wire in the handshake and certs in another format.  If it's AIA, then the first time the chain is fetched (and matched to a trusted anchor) then the AIA result gets cached (assuming the write to the home directory succeeds), so that would just be a startup blip that immediately stabilizes.

I _assume_ that the repro isn't failing... e.g. I assume that the memory-growth path isn't throwing during AuthenticateAsClient.  If AuthenticateAsClient is failing because the root isn't trusted, then that'd be a different path to investigate.

> besides making the forced refresh interval longer,

The graph looks like the growth happens on 10 minute boundaries, not 5... so while it could be things interacting, it doesn't seem like it's only that refresh.  Plus, that doesn't align with the comment that the memory growth doesn't happen when the background loop is talking to github.com

**Comment by westfin** [comment]
> I assume that the repro isn't failing... e.g. I assume that the memory-growth path isn't throwing during AuthenticateAsClient. If AuthenticateAsClient is failing because the root isn't trusted, then that'd be a different path to investigate.

Yes, it isn't failing.

> We could distinguish X.509 vs TLS by making a repro that just builds chains instead of poking something over HTTPS.

Not sure but I think I already trying it (maybe you mean something else). I have store RemoteCertificate after first AuthenticateAsClient, and then just build the chain instead of AuthenticateAsClient on next iterations. And memory was stable.

> Add GC.Collect() to the repro. If it solves the problem then presumably we have a problem where the GC isn't seeing the memory limit correctly so it doesn't feel motivated to run finalizers.

I can try, could you please help me with repro, when and how often should I do GC.Collect()

>  Plus, that doesn't align with the comment that the memory growth doesn't happen when the background loop is talking to github.com

I will try it again to be sure, because it can move us to wrong direction...

**Comment by bartonjs** [comment]
> when and how often should I do GC.Collect()

If the background worker is 100% of the repro, I'd just do it every loop.  So something like

```diff
        while (!stoppingToken.IsCancellationRequested)
        {
+           GC.Collect();
            DoAsync();
            Thread.Sleep(200);
        }
```

Though, while looking at this line of code... is your DoAsync generally finishing in less than 200 ms, or is part of the repro here involving an ever increasing amount of parallel requests?  Something like

```diff
+   private const int MaxWorkers = 10;
+   private static int s_counter;

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
+           if (Interlocked.Increment(ref s_counter) <= MaxWorkers)
+           {
                DoAsync();
+           }

            Thread.Sleep(200);
        }

        return Task.CompletedTask;
        void DoAsync() => ThreadPool.QueueUserWorkItem(async _ =>
        {
            try
            {
                var uri = new Uri(_settings.Endpoint.Url);

                var host = uri.Host;
                var port = uri.Port;

                using var client = new TcpClient(host, port);
                using var stream = new SslStream(client.GetStream(), leaveInnerStreamOpen: false);

                await stream.AuthenticateAsClientAsync(new SslClientAuthenticationOptions
                {
                    TargetHost = host,
                    CertificateRevocationCheckMode = X509RevocationMode.NoCheck
                });

                _logger.LogInformation("Connected to {host}:{port}, ssl protocol version: {SslProtocol}, cipher: {Cipher}", host, port, stream.SslProtocol, stream.NegotiatedCipherSuite);
           }
            catch (Exception e)
            {
                _logger.LogError(e, "Unexpected error occurred in recurring hosted service");
            }

+           Interlocked.Decrement(ref s_counter);
        });
```

would help identify that

**Comment by westfin** [comment]
> Though, while looking at this line of code... is your DoAsync generally finishing in less than 200 ms, or is part of the repro here involving an ever increasing amount of parallel requests?

Not sure that it's matter... I just read some issues here, and thinking that thread context switches + openssl implentation details produce memory fragmentation.
In our real application there are a lot http requests happen on threadpool in parallel. So I just stopped on this variant when trying find minimal repro.

**Comment by westfin** [comment]
> would help identify that

Thanks I will try right now. I don't know how but I suddenly close the issue :) Could you please reopen

**Comment by westfin** [comment]
Interesting results. Not sure about GC.Collect, can not say that it something change, but seems we have deadlock in  AuthenticateAsClientAsync when poll our internal endpoint. At some moment we stop write log `Connected to...`. Seems this happens because we added `MaxWorkers` variables.

Next interesting thing we don't have such problems in container which poll github.com and his memory stable.

**Comment by rzikm** [comment]
The code with Interlocked is wrong, because it will increment even when not starting another work item, if the work takes longer than 200ms then the s_counter will over time get above 10 and then will be incremented indefinitely without scheduling another connection

The code should be using something like SemaphoreSlim, the sample below should limit max parallel connections to 10

```cs
    SemaphoreSlim _semaphore = new SemaphoreSlim(10, 10);

    protected async override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (stoppingToken.IsCancellationRequested == false)
        {
            await _semaphore.WaitAsync(stoppingToken);
            DoAsync();

            // add delay if necessary
            await Task.Delay(200);
        }

        void DoAsync() => ThreadPool.QueueUserWorkItem(async _ =>
        {
            // do work

            _semaphore.Release();
        });
    }
```

**Comment by bartonjs** [comment]
Whoops, yep, I was missing the "else, Decrement" in the while loop.  It's like lock-free code is hard, or something :smile:.

The fact that github continued to work and your alternative jammed says that it's taking over 200ms to connect, and github isn't.

If it jams up with SemaphoreSlim, or some other work limiting strategy, that means your AuthenticateAsClientAsync calls are basically never finishing, and the fact that you keep enqueuing them would be the source of the perceived leak.  You could use a CancellationToken backed by a timeout (e.g. `new CancellationTokenSource(TimeSpan.FromSeconds(3))`) to limit "basically never".

**Comment by bartonjs** [comment]
```csharp
                using (CancellationTokenSource cts = new CancellationTokenSource(TimeSpan.FromSeconds(3))
                {
                    await stream.AuthenticateAsClientAsync(
                        new SslClientAuthenticationOptions
                        {
                            TargetHost = host,
                            CertificateRevocationCheckMode = X509RevocationMode.NoCheck
                        },
                        cts.Token);
                }
```

will hopefully force that to not be a dead state.


I'm not a networking expert, so I'll say "It sounds like the remote side just stopped responding to you, and that means the handshake never completed, but since you never got a FIN nothing ever threw... it's just waiting on data"  It might even be true :smile:

But based off this, my current inclination is to say that the repro wasn't measuring growth in the platform, just an infinite growth of unresolved tasks.

**Comment by westfin** [comment]
@bartonjs @rzikm Hi a week ago I have tried to change the code:

https://github.com/dotnet/runtime/blob/df846d69e1666f9c6060f2487975b568f3ed93bb/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslCachedSystemStoreProvider.cs#L99-L104

to 

```cs
ret ??= LoadMachineStores();
```

Which means to load system store only ones (ok for us in docker env). I recompiled System.Security.Cryptography.dll and rebuild our real application docker image with new dll. And memory becomes stable for weeks

<img width="935" height="228" alt="Image" src="https://github.com/user-attachments/assets/0d6a4dad-207c-494f-9352-ae63fbcecd98" />

Could you please help to find to which direction I can move?

**Comment by westfin** [comment]
Not sure but maybe it is some how related #132350 
Our application has several http clients registered AddHttpClient with ClientCertificates

**Comment by westfin** [comment]
After continuing the research I have found that some our certs have Windows style line endings CRLF, after changing file to LF, memory becomes stable. Sorry for wasting your time, guys. :(

Have no idea how and why memory leaks with CRLF. But _PEM_read_bio_X509_ itself does not leak I have checked it with small native C repro.
Maybe another part of code base some how related to this part. Sorry again...
