### ISSUE TITLE
ConfigurationBinder source generator emits SYSLIB1100 when it shouldn't apply

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#93132]
### Description

I have a public type with an internal constructor in the same assembly as my bind call. 

a. I wouldn't expect the source generator to need to construct the object at all since it's a Bind call.
b. The constructor is internal, which makes it visible to the source generator.

### Reproduction Steps

Repro project: [internalConstructor.zip](https://github.com/dotnet/runtime/files/12833309/internalConstructor.zip)

```c#
using Microsoft.Extensions.Configuration;

var c = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string,string?>()
    {
        ["Value"] = "Hello",
        ["Value2"] = "Hello world"
    })
    .Build();


MyType x = new();
c.Bind(x);
Console.WriteLine(x.Value);
Console.WriteLine(x.Value2);


public class MyType
{
    internal MyType(){ }
    public string? Value { get; set; }
    public string? Value2 { get; set; }
}
```

### Expected behavior

Compiles successfully without warning.

### Actual behavior

> C:\scratch\internalConstructor\Program.cs(13,1): warning SYSLIB1100: Cannot create instance of type 'MyType' because it
 is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib11
00) [C:\scratch\internalConstructor\internalConstructor.csproj]

### Regression?

No

### Known Workarounds

Suppress the warning

**Comment by ericstj** [comment]
I see a lot of folks hitting `SYSLIB1100` and `SYSLIB1101` for non-root level types - these behave similar to a root level type that's being passed to `Bind` -- the binder doesn't always *need* to create a type so the fact that it cannot may not be a worthwhile diagnostic to raise to the user.

This problem is exacerbated by lack of the ability to granularly suppress these warnings - or suppress at all in source due to https://github.com/dotnet/runtime/issues/92509.

I wonder if we should split these diagnostics into two - one set where it's clear that we can't do what the user wanted and another where it's more informational (and not a warning).  @tarekgh @eiriktsarpalis @eerhardt

**Comment by ericstj** [comment]
What I was discussing above is even broader than the original issue.  The internal constructor problem is a plain-old-bug but one that will may be moot if we take the broader look at this behavior.

My point is that binding to types which are not constructable is actually a very common scenario and doesn't warrant raising a warning.

**Comment by ericstj** [comment]
Repro in this issue no longer produces a warning.  We also fixed our behavior for unsupported types in 
https://github.com/dotnet/runtime/commit/27685cf47bf8001e363fd8e599796cfc1f2af871

**Comment by agocke** [comment]
@ericstj Azure SDK/MCP is still seeing this warning (and others) in Microsoft.Identity.Abstractions: https://github.com/[anuchandy/idweb-source-gen-warns](https://github.com/anuchandy/idweb-source-gen-warns). Any idea what could be going on here, and how we could suppress generation/warnings for these members?
